
export const JYOTISH_QUOTES = [
  { en: "The stars impel, they do not compel.", hi: "सितारे प्रेरित करते हैं, मजबूर नहीं करते।", mr: "तारे प्रेरित करतात, सक्ती करत नाहीत.", kn: "ನಕ್ಷತ್ರಗಳು ಪ್ರೇರೇಪಿಸುತ್ತವೆ, ಬಲವಂತ ಮಾಡುವುದಿಲ್ಲ." },
  { en: "Astrology is a language. If you understand this language, the sky speaks to you.", hi: "ज्योतिष एक भाषा है। यदि आप इस भाषा को समझते हैं, तो आकाश आपसे बात करता है।", mr: "ज्योतिष ही एक भाषा आहे. जर तुम्हाला ही भाषा समजली तर आकाश तुमच्याशी बोलते.", kn: "ಜ್ಯೋತಿಷ್ಯವು ಒಂದು ಭಾಷೆ. ನೀವು ಈ ಭಾಷೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಂಡರೆ, ಆಕಾಶವು ನಿಮ್ಮೊಂದಿಗೆ ಮಾತನಾಡುತ್ತದೆ." },
  { en: "The soul is born into the world at a time when the celestial rays are in harmony with individual karma.", hi: "आत्मा दुनिया में उस समय जन्म लेती है जब आकाशीय किरणें व्यक्तिगत कर्म के साथ सद्भाव में होती हैं।", mr: "जेव्हा आकाशीय किरणे वैयक्तिक कर्माशी सुसंगत असतात तेव्हा आत्मा जगात जन्म घेतो.", kn: "ಆಕಾಶದ ಕಿರಣಗಳು ವೈಯಕ್ತಿಕ ಕರ್ಮದೊಂದಿಗೆ ಸಾಮರಸ್ಯ ಹೊಂದಿರುವ ಸಮಯದಲ್ಲಿ ಆತ್ಮವು ಜಗತ್ತಿನಲ್ಲಿ ಜನಿಸುತ್ತದೆ." },
  { en: "Planets are the mirrors of our past actions.", hi: "ग्रह हमारे पिछले कार्यों के दर्पण हैं।", mr: "ग्रह हे आपल्या भूतकाळातील कर्मांचे आरसे आहेत.", kn: "ಗ್ರಹಗಳು ನಮ್ಮ ಹಿಂದಿನ ಕಾರ್ಯಗಳ ಕನ್ನಡಿಗಳಾಗಿವೆ." },
  { en: "Wisdom is the best remedy for all planetary afflictions.", hi: "ज्ञान सभी ग्रहों के कष्टों का सबसे अच्छा उपाय है।", mr: "ज्ञान हे सर्व ग्रहांच्या पीडांवर सर्वोत्तम उपाय आहे.", kn: "ಜ್ಞಾನವು ಎಲ್ಲಾ ಗ್ರಹಗಳ ದೋಷಗಳಿಗೆ ಅತ್ಯುತ್ತಮ ಪರಿಹಾರವಾಗಿದೆ." }
];

export const COLORS = {
  GOLD: '#D4AF37',
  SAFFRON: '#FF9933',
  DEEP_INDIGO: '#312e81',
  NAVY: '#0B1120',
  CELESTIAL_BLUE: '#4F46E5',
  PARCHMENT: '#FDF5E6',
  INDIGO_DARK: '#312e81',
  INDIGO_LIGHT: '#4338ca'
};

export const RASIS = [
  { name: "Mesha", icon: "♈", label_key: "rasi_mesha" },
  { name: "Rishaba", icon: "♉", label_key: "rasi_vrishabha" },
  { name: "Mithuna", icon: "♊", label_key: "rasi_mithuna" },
  { name: "Kataka", icon: "♋", label_key: "rasi_karka" },
  { name: "Simha", icon: "♌", label_key: "rasi_simha" },
  { name: "Kanya", icon: "♍", label_key: "rasi_kanya" },
  { name: "Thula", icon: "♎", label_key: "rasi_tula" },
  { name: "Vrischika", icon: "♏", label_key: "rasi_vrishchika" },
  { name: "Dhanus", icon: "♐", label_key: "rasi_dhanu" },
  { name: "Makara", icon: "♑", label_key: "rasi_makara" },
  { name: "Kumbha", icon: "♒", label_key: "rasi_kumbha" },
  { name: "Meena", icon: "♓", label_key: "rasi_meena" }
];

export const MUHURTA_TYPES = [
  { id: 'vivaha', label: 'Vivaha (Marriage Ceremony)', label_key: 'muhurta_vivaha' },
  { id: 'grihapravesha', label: 'Griha Pravesha (House Warming)', label_key: 'muhurta_grihapravesha' },
  { id: 'bhoomi_pooja', label: 'Bhoomi Pooja (Ground Breaking)', label_key: 'muhurta_bhoomi_pooja' },
  { id: 'upanayana', label: 'Upanayana (Thread Ceremony)', label_key: 'muhurta_upanayana' },
  { id: 'namakarana', label: 'Namakarana (Naming Ceremony)', label_key: 'muhurta_namakarana' },
  { id: 'annaprashana', label: 'Annaprashana (First Feeding)', label_key: 'muhurta_annaprashana' },
  { id: 'aksharabhyasa', label: 'Akshara Abhyasa (Education Start)', label_key: 'muhurta_aksharabhyasa' },
  { id: 'vidyarambha', label: 'Vidya Arambha (Starting School)', label_key: 'muhurta_vidyarambha' },
  { id: 'karnavedha', label: 'Karnavedha (Ear Piercing)', label_key: 'muhurta_karnavedha' },
  { id: 'choodakarana', label: 'Choodakarana (Mundan/Hair Cut)', label_key: 'muhurta_choodakarana' },
  { id: 'seemantham', label: 'Seemantham (Baby Shower)', label_key: 'muhurta_seemantham' },
  { id: 'vahana', label: 'Vahana Kharidi (Vehicle Purchase)', label_key: 'muhurta_vahana' },
  { id: 'vyapaara', label: 'Vyapaara Arambha (New Business)', label_key: 'muhurta_vyapaara' },
  { id: 'shop_opening', label: 'Nootana Vyapaara (Shop Opening)', label_key: 'muhurta_shop_opening' },
  { id: 'udyoga', label: 'Udyoga Pravesha (Joining Job)', label_key: 'muhurta_udyoga' },
  { id: 'swarna', label: 'Swarna Kharidi (Buying Gold/Jewels)', label_key: 'muhurta_swarna' },
  { id: 'investments', label: 'Dhana Nivesha (Investments)', label_key: 'muhurta_investments' },
  { id: 'yaatra', label: 'Yaatra (Significant Travel)', label_key: 'muhurta_yaatra' },
  { id: 'videsha', label: 'Videsha Gamana (Foreign Travel)', label_key: 'muhurta_videsha' },
  { id: 'shastra_kriya', label: 'Shastra Kriya (Surgery)', label_key: 'muhurta_shastra_kriya' },
  { id: 'medical_start', label: 'Chikitsa Arambha (Start Treatment)', label_key: 'muhurta_medical_start' },
  { id: 'abhijit', label: 'Abhijit Muhurta (Daily Auspicious)', label_key: 'muhurta_abhijit' },
  { id: 'brahma', label: 'Brahma Muhurta (Spiritual Window)', label_key: 'muhurta_brahma' },
  { id: 'shilaanyasa', label: 'Shilaanyasa (Foundation Stone)', label_key: 'muhurta_shilaanyasa' },
  { id: 'renting', label: 'New Rental/Moving Home', label_key: 'muhurta_renting' },
  { id: 'contracts', label: 'Signing Agreements', label_key: 'muhurta_contracts' },
  { id: 'legal', label: 'Legal/Court Initiations', label_key: 'muhurta_legal' },
  { id: 'agriculture', label: 'Krishi Karya (Farming/Sowing)', label_key: 'muhurta_agriculture' }
];

export const HOURS = Array.from({ length: 12 }, (_, i) => (i + 1).toString().padStart(2, '0'));
export const MINUTES = Array.from({ length: 60 }, (_, i) => i.toString().padStart(2, '0'));

export const PLANETS = [
  { name: "Sun", label_key: "planet_sun" },
  { name: "Moon", label_key: "planet_moon" },
  { name: "Mars", label_key: "planet_mars" },
  { name: "Mercury", label_key: "planet_mercury" },
  { name: "Jupiter", label_key: "planet_jupiter" },
  { name: "Venus", label_key: "planet_venus" },
  { name: "Saturn", label_key: "planet_saturn" },
  { name: "Rahu", label_key: "planet_rahu" },
  { name: "Ketu", label_key: "planet_ketu" },
  { name: "Lagna", label_key: "planet_lagna" },
  { name: "Mandi", label_key: "planet_mandi" }
];

export const LANGUAGES = [
  { code: 'en', name: 'English', image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=400&auto=format&fit=crop' },
  { code: 'kn', name: 'ಕನ್ನಡ', image: 'https://images.unsplash.com/photo-1600675281904-67490bbad4a6?q=80&w=400&auto=format&fit=crop' },
  { code: 'hi', name: 'हिन्दी', image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=400&auto=format&fit=crop' },
  { code: 'bn', name: 'বাংলা', image: 'https://images.unsplash.com/photo-1581089781785-603411ffdaa1?q=80&w=400&auto=format&fit=crop' },
  { code: 'gu', name: 'ગુજરાતી', image: 'https://images.unsplash.com/photo-1597041066774-9d2752157a92?q=80&w=400&auto=format&fit=crop' },
  { code: 'kok', name: 'कोंकणी', image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=400&auto=format&fit=crop' },
  { code: 'ml', name: 'മലയാളം', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=400&auto=format&fit=crop' },
  { code: 'mr', name: 'मराठी', image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?q=80&w=400&auto=format&fit=crop' },
  { code: 'ta', name: 'தமிழ்', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=400&auto=format&fit=crop' },
  { code: 'tcy', name: 'ತುಳು', image: 'https://images.unsplash.com/photo-1621360841013-c7683c659ec6?q=80&w=400&auto=format&fit=crop' },
  { code: 'te', name: 'తెలుగు', image: 'https://images.unsplash.com/photo-1608976328267-e673d3ec06ce?q=80&w=400&auto=format&fit=crop' },
  { code: 'sa', name: 'संस्कृतम्', image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=400&auto=format&fit=crop' }
];

export const TRANSLATIONS: Record<string, any> = {
  en: {

    brand_name: "ASTRO LOGIC",
    tagline: "The Ancient Science of Light & Time",
    begin_journey: "Begin Journey",
    choose_path: "Choose Your Path",
    disclaimer: "Astrological predictions are based on planetary calculations and indicate possibilities, not guaranteed outcomes.",
    planetary_transit_in: "in",
    horoscope: "Horoscope",
    matching: "Matching",
    life_partner: "Life Partner",
    daily: "Daily Forecast",
    muhurta: "Muhurta",
    numerology: "Numerology",
    chat: "Astro Chat",
    prashna: "Prashna",
    guruji: "Guruji",
    you: "You",
    guruji_welcome: "Ask Guruji about your life path, planetary transits, or any spiritual guidance.",
    guruji_thinking: "Guruji is consulting the stars...",
    error_guruji: "The cosmic connection is weak. Please try again later.",
    ask_guruji_placeholder: "Ask your question to Guruji...",
    switch_mode: "Switch Path",
    menu_details: "Birth Analysis",
    menu_timeline: "Life Timeline (Past, Present, Future)",
    menu_hora: "Classical Hora Analysis",
    menu_sphta: "Planetary Degrees",
    menu_rasi: "Rasi Kundli",
    menu_navamsha: "Navamsha D9",
    menu_bhava: "Bhava Chalit",
    menu_bhava_analysis: "12 Houses (Bhava) Analysis",
    menu_sandhi: "Sandhi Analysis",
    menu_panchangam: "Panchangam",
    menu_dasha: "Vimshottari Dasha",
    menu_shadvarga: "Shadvarga",
    shadvarga_strengths: "Shadvarga",
    shadbala_analysis: "Shadbala",
    energy_strength: "Energy Strength",
    planetary_power: "Planetary Power",
    menu_yogas: "Yoga Analysis",
    menu_maitri: "Panchadha Graha Maitri",
    menu_ashtaka: "Ashtakavarga Points",
    menu_trisputa: "Trisputadi Analysis",
    menu_dhumadi: "Dhumadi Group",
    menu_basic_details: "Basic Birth Details",
    menu_yoga: "Yoga Analysis",
    menu_career: "Career & Success",
    menu_health: "Health & Vitality",
    menu_money: "Wealth & Finance",
    menu_transit: "Planetary Transits",
    menu_dasha_effect: "Dasha Effects",
    menu_sade_sati: "Sade Sati Analysis",
    menu_gemstones: "Gemstones & Rudraksha",
    menu_nakshatra: "Nakshatra Secrets",
    menu_doshas: "Dosha Check (Kalsarp/Pitra)",
    menu_character: "Character & Personality",
    menu_numerology: "Numerology Analysis",
    back: "Back",
    submit: "Create Horoscope",
    quick_profile: "Quick Profile",
    enter_details_wisdom: "Enter details for personalized wisdom",
    save_continue: "Save & Continue",
    skip_for_now: "Skip for now",
    lang_select: "Language",
    save_profile: "Save Profile",
    saved_profiles: "Recent Charts",
    matching_title: "Divine Relationship Synergy",
    conclusion: "Divine Verdict",
    select_rasi: "Select Rasi",
    daily_title: "Celestial Flow for Today",
    muhurta_title: "Auspicious Muhurta Windows",
    muhurta_select: "Select Purpose",
    sacred_intake: "Sacred Intake",
    partner_one: "Partner One",
    partner_two: "Partner Two",
    birth_location: "Birth Location",
    timeframe: "Timeframe",
    location: "Location",
    quick_search: "Quick Search",
    oracle: "Oracle",
    name: "Name",
    date: "Date",
    nakshatra: "Nakshatra",
    ask_guruji: "Ask Guruji",
    deep_inquiry: "Deep Inquiry",
    seek_answer: "Seek Answer",
    name_of_soul: "Name of Soul",
    birth_date: "Birth Date",
    birth_time: "Birth Time",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    search_city_placeholder: "Search City...",
    muhurta_search_placeholder: "Search for a purpose...",
    prashna_placeholder: "What is your deep question for the stars?",
    guruji_listening: "Guruji is listening...",
    connection_interrupted: "Connection Interrupted",
    disconnected: "Disconnected",
    support_guruji: "Support Guruji",
    scan_to_support: "Scan to Support",
    scan_to_donate: "Scan to Donate via GPay / UPI",
    support_mission: "Support Our Mission",
    support_quote: "“You’ve just received a personalized astrology insight. If it resonated with you, you’re welcome to support us with a small contribution.”",
    csr_title: "ASTRO LOGIC Social Impact",
    csr_books_title: "Educational Empowerment for Special Children",
    csr_books_desc: "ASTRO LOGIC is deeply committed to the holistic development of children with special needs. We provide essential educational kits, specialized learning tools, and infrastructure support to special schools across India. By dedicating nearly 90% of our service revenue, we ensure these brilliant young minds have the resources they need to overcome challenges and achieve their full potential.",
    csr_oldage_title: "Dignity in Aging: Holistic Old Age Home Care",
    csr_oldage_desc: "Our 'Dignity in Aging' initiative focuses on providing comprehensive support to abandoned and underprivileged elders. We partner with old age homes to provide quality healthcare, nutritious meals, and a supportive community. Almost the entirety of our platform's revenue is channeled into these services, ensuring our elders live their golden years with the respect, comfort, and care they truly deserve.",
    secure: "Secure",
    spiritual: "Spiritual",
    support: "Support",
    next_page: "Next Page",
    save_info: "Save Info",
    saved_profiles_title: "Saved Profiles",
    celestial_map: "Celestial Map (Rasi)",
    stars_obscured: "The stars are obscured by clouds. Please try again.",
    go_back: "Go Back",
    dismiss: "Dismiss",
    select_city_warning: "⚠️ Please select a city from the list for accurate calculations.",
    search_assistant_placeholder: "e.g., Jupiter transit in 2024 effects on Mesha Rasi",
    enter_full_name: "Enter Full Name",
    feedback: "Feedback and Suggestions",
    feedback_title: "Your Sacred Feedback and Suggestions",
    feedback_placeholder: "Share your experience or suggestions with the stars...",
    submit_feedback: "Submit Feedback",
    feedback_success: "Thank you for your divine feedback!",
    first_name: "First Name",
    second_name: "Second Name",
    timeframe_placeholder: "e.g. Next 3 months",
    select_seeker: "Select Seeker",
    select_scholar: "Select Scholar",
    seeker: "Seeker",
    scholar: "Scholar",
    seeker_desc: "For general people with layman knowledge. Simple life guidance, career flow, and daily energy in clear, accessible language.",
    scholar_desc: "For astrologers and students. Deep knowledge based on Prashna Marga, Brihat Jataka, and Phaladeepika. Includes Sanskrit shlokas and shastriya words.",
    siddhantic_precision: "Scholar Section",
    personal_guidance: "Seeker Section",
    calculating_heavens: "Calculating Heavens...",
    ask_help_guruji: "Ask Guruji for Help",
    sacred_conversation: "A Sacred Conversation",
    shastriya: "Shastriya",
    life_path: "Life Path",
    timeline: "Timeline",
    siddhantic: "Siddhantic",
    life_phase: "Life Phase",
    wealth_health: "Wealth & Health",
    soul_map: "The Soul Map",
    power_score: "Power Score",
    under_construction: "This celestial path is under construction.",
    return_home: "Return Home",
    get_verdict: "Get Verdict",
    latitude: "Lat",
    longitude: "Lon",
    timezone: "TZ",
    suggestion_title: "Suggestions",
    suggestion_desc: "Help Guruji improve your experience",
    suggestion_placeholder: "Share your thoughts or report an issue...",
    suggestion_send: "Send Suggestion",
    suggestion_sent: "Sent to Guruji",
    panchanga_title: "Panchanga",
    custom_panchanga: "Select Date & Place",
    timeline_title: "Life Timeline Dashboard",
    contact_astrologer_title: "Offer Tambula to Daivajna",
    contact_astrologer_desc: "A sacred ritual of seeking guidance through offerings",
    tambula_offering: "Tambula Offering",
    tambula_desc: "In Vedic tradition, a seeker offers Tambula (Betel leaf, Areca nut, and Dakshina) to the Daivajna (Astrologer) to invoke divine clarity.",
    problem_label: "Describe your inquiry",
    problem_placeholder: "e.g. Career growth, Health issues...",
    contact_time_label: "Preferred time to contact",
    contact_time_placeholder: "e.g. Tomorrow 10 AM",
    submit_problem: "Submit Request",
    problem_submitted_msg: "Our astrologers will contact you soon.",
    mangala_dosha: "Mangala Dosha (Mars Affliction)",
    conclusion_title: "One Line Conclusion",
    remedy_options_title: "Choose Your Remedy Path",
    tier1_title: "Upaya Prarambh",
    tier1_price: "₹99",
    tier1_meaning: "Beginning Remedies",
    tier2_title: "Shubha Marg",
    tier2_price: "₹599",
    tier2_meaning: "Path to Planetary Peace",
    tier3_title: "Sarva Karma Vishleshan",
    tier3_price: "₹999",
    tier3_meaning: "Complete Life Analysis",
    pay_now: "Pay & Proceed",
    appointment_date: "Select Date",
    appointment_time: "Select Time Slot",
    contact_astrologer_remedies: "Contact Astrologer for Remedies",
    analysis_tab_title: "Analysis",
    matching_tab_title: "Matching",
    chat_tab_title: "Astro Chat",
    help: "Help",
    footer_text: "Divine Order • Celestial Alignment • Deep Knowledge",
    celestial_insights_title: "Current Celestial Insights",
    search_assistant_desc: "Search for real-time planet transits, upcoming eclipses, or specific astrological events grounded with Google Search.",
    searching: "Searching...",
    ask_stars: "Ask Stars",
    sources: "Sources",
    invoke_guruji: "Invoke Guruji",
    pranama_end: "Pranama (End)",
    career_guidance: "Career Guidance",
    love_marriage: "Love & Marriage",
    health_energy: "Health & Energy",
    spiritual_path: "Spiritual Path",
    seek_wisdom_message: "Seek wisdom and the stars shall answer through Guruji.",
    connecting: "Connecting...",
    dhanyavaada: "Dhanyavaada",
    pranama: "Pranama",
    path: "Path",
    seeker_path: "Seeker Path",
    you_hint: "You (Hint): I want help with ",
    muhurta_vivaha: "Vivaha (Marriage Ceremony)",
    muhurta_grihapravesha: "Griha Pravesha (House Warming)",
    muhurta_bhoomi_pooja: "Bhoomi Pooja (Ground Breaking)",
    muhurta_upanayana: "Upanayana (Thread Ceremony)",
    muhurta_namakarana: "Namakarana (Naming Ceremony)",
    muhurta_annaprashana: "Annaprashana (First Feeding)",
    muhurta_aksharabhyasa: "Akshara Abhyasa (Education Start)",
    muhurta_vidyarambha: "Vidya Arambha (Starting School)",
    muhurta_karnavedha: "Karnavedha (Ear Piercing)",
    muhurta_choodakarana: "Choodakarana (Mundan/Hair Cut)",
    muhurta_seemantham: "Seemantham (Baby Shower)",
    muhurta_vahana: "Vahana Kharidi (Vehicle Purchase)",
    muhurta_vyapaara: "Vyapaara Arambha (New Business)",
    muhurta_shop_opening: "Nootana Vyapaara (Shop Opening)",
    muhurta_udyoga: "Udyoga Pravesha (Joining Job)",
    muhurta_swarna: "Swarna Kharidi (Buying Gold/Jewels)",
    muhurta_investments: "Dhana Nivesha (Investments)",
    muhurta_yaatra: "Yaatra (Significant Travel)",
    muhurta_videsha: "Videsha Gamana (Foreign Travel)",
    muhurta_shastra_kriya: "Shastra Kriya (Surgery)",
    muhurta_medical_start: "Chikitsa Arambha (Start Treatment)",
    muhurta_abhijit: "Abhijit Muhurta (Daily Auspicious)",
    muhurta_brahma: "Brahma Muhurta (Spiritual Window)",
    muhurta_shilaanyasa: "Shilaanyasa (Foundation Stone)",
    muhurta_renting: "New Rental/Moving Home",
    muhurta_contracts: "Signing Agreements",
    muhurta_legal: "Legal/Court Initiations",
    muhurta_agriculture: "Krishi Karya (Farming/Sowing)",
    home: "Home",
    daily_nav: "Daily",
    oracle_nav: "Oracle",
    chat_nav: "Chat",
    donate_support: "Donate & Support",
    next_analysis: "Next: Choose Analysis",
    sacred_geometry: "Sacred Geometry • Ancient Logic",
    birth_analysis: "Birth Analysis",
    my_character: "My Character",
    rasi_kundli: "Rasi Kundli",
    vimshottari: "Vimshottari",
    ashtakavarga: "Ashtakavarga",
    planet_sun: "Sun",
    planet_moon: "Moon",
    planet_mars: "Mars",
    planet_mercury: "Mercury",
    planet_jupiter: "Jupiter",
    planet_venus: "Venus",
    planet_saturn: "Saturn",
    planet_rahu: "Rahu",
    planet_ketu: "Ketu",
    planet_lagna: "Lagna",
    planet_mandi: "Mandi",
    rasi_mesha: "Mesha",
    rasi_vrishabha: "Vrishabha",
    rasi_mithuna: "Mithuna",
    rasi_karka: "Karka",
    rasi_simha: "Simha",
    rasi_kanya: "Kanya",
    rasi_tula: "Tula",
    rasi_vrishchika: "Vrishchika",
    rasi_dhanu: "Dhanu",
    rasi_makara: "Makara",
    rasi_kumbha: "Kumbha",
    rasi_meena: "Meena"
  },
  kn: {

    brand_name: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್",
    brand_tagline: "ಪ್ರಾಚೀನ ಜ್ಞಾನ, ಆಧುನಿಕ ತರ್ಕ",
    horoscope: "ಜಾತಕ",
    matching: "ಗುಣಮೇಲನ",
    daily: "ದಿನ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    numerology: "ಸಂಖ್ಯಾಶಾಸ್ತ್ರ",
    chat: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    prashna: "ಪ್ರಶ್ನೆ",
    guruji: "ಗುರುಜಿ",
    you: "ನೀವು",
    guruji_welcome: "ನಿಮ್ಮ ಜೀವನದ ಹಾದಿ, ಗ್ರಹಗಳ ಸಂಚಾರ ಅಥವಾ ಯಾವುದೇ ಆಧ್ಯಾತ್ಮಿಕ ಮಾರ್ಗದರ್ಶನದ ಬಗ್ಗೆ ಗುರೂಜಿಯನ್ನು ಕೇಳಿ.",
    guruji_thinking: "ಗುರೂಜಿ ನಕ್ಷತ್ರಗಳನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಿದ್ದಾರೆ...",
    error_guruji: "ಬ್ರಹ್ಮಾಂಡದ ಸಂಪರ್ಕವು ದುರ್ಬಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    ask_guruji_placeholder: "ಗುರೂಜಿಗೆ ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",
    switch_mode: "ಹಾದಿ ಬದಲಿಸಿ",
    menu_details: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    menu_timeline: "ಜೀವನ ಕಾಲಕ್ರಮ (ಹಿಂದಿನ, ಈಗಿನ, ಮುಂದಿನ)",
    menu_hora: "ಶಾಸ್ತ್ರೀಯ ಹೋರಾ ವಿಶ್ಲೇಷಣೆ",
    menu_sphta: "ಗ್ರಹಗಳ ಅಂಶಗಳು",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಚಲಿತ",
    menu_bhava_analysis: "೧೨ ಭಾವ ವಿಶ್ಲೇಷಣೆ",
    soul_map: "ಆತ್ಮದ ನಕ್ಷೆ",
    menu_sandhi: "ಸಂಧಿ ವಿಶ್ಲೇಷಣೆ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    life_phase: "ಜೀವನ ಹಂತ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    power_score: "ಶಕ್ತಿ ಸ್ಕೋರ್",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಮಂಗಳ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೇತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    save_continue: "ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
    skip_for_now: "ಸದ್ಯಕ್ಕೆ ಬಿಟ್ಟುಬಿಡಿ",
    lang_select: "ಭಾಷೆ",
    save_profile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    saved_profiles: "ಇತ್ತೀಚಿನ ಜಾತಕಗಳು",
    matching_title: "ಗುಣಮೇಲನ ಮತ್ತು ಹೊಂದಾಣಿಕೆ",
    conclusion: "ದೈವಿಕ ತೀರ್ಪು",
    select_rasi: "ರಾಶಿ ಆರಿಸಿ",
    daily_title: "ಇಂದಿನ ರಾಶಿಫಲ",
    muhurta_title: "ಶುಭ ಮುಹೂರ್ತಗಳು",
    timeline: "ಕಾಲಕ್ರಮ",
    life_path: "ಜೀವನ ಪಥ",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    wealth_health: "ಸಂಪತ್ತು ಮತ್ತು ಆರೋಗ್ಯ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    tagline: "ಬೆಳಕು ಮತ್ತು ಸಮಯದ ಪ್ರಾಚೀನ ವಿಜ್ಞಾನ",
    muhurta_select: "ಉದ್ದೇಶವನ್ನು ಆರಿಸಿ",
    sacred_intake: "ಜನ್ಮ ವಿವರಗಳು",
    partner_one: "ಮೊದಲ ಸಂಗಾತಿ",
    partner_two: "ಎರಡನೇ ಸಂಗಾತಿ",
    birth_location: "ಜನ್ಮ ಸ್ಥಳ",
    timeframe: "ಸಮಯದ ಚೌಕಟ್ಟು",
    location: "ಸ್ಥಳ",
    quick_search: "ತ್ವರಿತ ಹುಡುಕಾಟ",
    oracle: "ದೈವವಾಣಿ",
    name: "ಹೆಸರು",
    date: "ದಿನಾಂಕ",
    nakshatra: "ನಕ್ಷತ್ರ",
    ask_guruji: "ಗುರೂಜಿಯವರನ್ನು ಕೇಳಿ",
    deep_inquiry: "ಆಳವಾದ ವಿಚಾರಣೆ",
    seek_answer: "ಉತ್ತರ ಹುಡುಕಿ",
    name_of_soul: "ಹೆಸರು",
    birth_date: "ಜನ್ಮ ದಿನಾಂಕ",
    birth_time: "ಜನ್ಮ ಸಮಯ",
    gender: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಸ್ತ್ರೀ",
    other: "ಇತರೆ",
    search_city_placeholder: "ನಗರ ಹುಡುಕಿ...",
    muhurta_search_placeholder: "ಉದ್ದೇಶಕ್ಕಾಗಿ ಹುಡುಕಿ...",
    prashna_placeholder: "ನಕ್ಷತ್ರಗಳಿಗಾಗಿ ನಿಮ್ಮ ಆಳವಾದ ಪ್ರಶ್ನೆ ಏನು?",
    guruji_listening: "ಗುರೂಜಿ ಕೇಳುತ್ತಿದ್ದಾರೆ...",
    connection_interrupted: "ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ",
    disconnected: "ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ",
    support_guruji: "ಗುರೂಜಿಯವರಿಗೆ ಬೆಂಬಲ ನೀಡಿ",
    scan_to_support: "ಬೆಂಬಲಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    muhurta_grihapravesha: "ಗೃಹ ಪ್ರವೇಶ",
    muhurta_bhoomi_pooja: "ಭೂಮಿ ಪೂಜೆ",
    muhurta_upanayana: "ಉಪನಯನ",
    muhurta_namakarana: "ನಾಮಕರಣ",
    muhurta_annaprashana: "ಅನ್ನಪ್ರಾಶನ",
    muhurta_aksharabhyasa: "ಅಕ್ಷರಾಭ್ಯಾಸ",
    muhurta_vidyarambha: "ವಿದ್ಯಾರಂಭ",
    muhurta_karnavedha: "ಕರ್ಣವೇಧ",
    muhurta_choodakarana: "ಚೂಡಾಕರಣ",
    muhurta_seemantham: "ಸೀಮಂತ",
    muhurta_vahana: "ವಾಹನ ಖರೀದಿ",
    muhurta_vyapaara: "ವ್ಯಾಪಾರ ಆರಂಭ",
    muhurta_shop_opening: "ಅಂಗಡಿ ಉದ್ಘಾಟನೆ",
    muhurta_udyoga: "ಉದ್ಯೋಗ ಪ್ರವೇಶ",
    muhurta_swarna: "ಚಿನ್ನ ಖರೀದಿ",
    muhurta_investments: "ಹೂಡಿಕೆಗಳು",
    muhurta_yaatra: "ಯಾತ್ರೆ",
    muhurta_videsha: "ವಿದೇಶ ಪ್ರಯಾಣ",
    muhurta_shastra_kriya: "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ",
    muhurta_medical_start: "ವೈದ್ಯಕೀಯ ಚಿಕಿತ್ಸೆ ಆರಂಭ",
    muhurta_abhijit: "ಅಭಿಜಿತ್ ಮುಹೂರ್ತ",
    muhurta_brahma: "ಬ್ರಹ್ಮ ಮುಹೂರ್ತ",
    muhurta_shilaanyasa: "ಶಿಲಾನ್ಯಾಸ",
    muhurta_renting: "ಹೊಸ ಬಾಡಿಗೆ/ಮನೆ ಬದಲಾವಣೆ",
    muhurta_contracts: "ಒಪ್ಪಂದಗಳಿಗೆ ಸಹಿ ಮಾಡುವುದು",
    muhurta_legal: "ಕಾನೂನು/ನ್ಯಾಯಾಲಯದ ಆರಂಭ",
    scan_to_donate: "GPay / UPI ಮೂಲಕ ದೇಣಿಗೆ ನೀಡಿ",
    support_mission: "ನಮ್ಮ ಕಾರ್ಯಕ್ಕೆ ಬೆಂಬಲ ನೀಡಿ",
    support_quote: "“ನೀವು ಈಗಷ್ಟೇ ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ಸಲಹೆಯನ್ನು ಪಡೆದಿದ್ದೀರಿ. ಅದು ನಿಮಗೆ ಇಷ್ಟವಾದಲ್ಲಿ, ಸಣ್ಣ ದೇಣಿಗೆಯ ಮೂಲಕ ನಮಗೆ ಬೆಂಬಲ ನೀಡಬಹುದು.”",
    csr_title: "ಆಸ್ಟ್ರೋಲಾಜಿಕ್ ಸಾಮಾಜಿಕ ಪ್ರಭಾವ",
    csr_books_title: "ವಿಶೇಷ ಮಕ್ಕಳಿಗೆ ಶೈಕ್ಷಣಿಕ ಸಬಲೀಕರಣ",
    csr_books_desc: "ವಿಶೇಷ ಅಗತ್ಯವುಳ್ಳ ಮಕ್ಕಳ ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿಗೆ ಆಸ್ಟ್ರೋಲಾಜಿಕ್ ಆಳವಾಗಿ ಬದ್ಧವಾಗಿದೆ. ನಾವು ಭಾರತದಾದ್ಯಂತದ ವಿಶೇಷ ಶಾಲೆಗಳಿಗೆ ಅಗತ್ಯ ಶೈಕ್ಷಣಿಕ ಕಿಟ್‌ಗಳು, ವಿಶೇಷ ಕಲಿಕಾ ಪರಿಕರಗಳು ಮತ್ತು ಮೂಲಸೌಕರ್ಯ ಬೆಂಬಲವನ್ನು ಒದಗಿಸುತ್ತೇವೆ. ನಮ್ಮ ಸೇವಾ ಆದಾಯದ ಸುಮಾರು 90% ರಷ್ಟನ್ನು ಮೀಸಲಿಡುವ ಮೂಲಕ, ಈ ಪ್ರತಿಭಾವಂತ ಯುವ ಮನಸ್ಸುಗಳು ಸವಾಲುಗಳನ್ನು ಎದುರಿಸಲು ಮತ್ತು ಅವರ ಪೂರ್ಣ ಸಾಮರ್ಥ್ಯವನ್ನು ತಲುಪಲು ಅಗತ್ಯವಿರುವ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಹೊಂದಿವೆ ಎಂದು ನಾವು ಖಚಿತಪಡಿಸುತ್ತೇವೆ.",
    csr_oldage_title: "ವೃದ್ಧಾಪ್ಯದಲ್ಲಿ ಘನತೆ: ಸಮಗ್ರ ವೃದ್ಧಾಶ್ರಮದ ಆರೈಕೆ",
    csr_oldage_desc: "ನಮ್ಮ 'ವೃದ್ಧಾಪ್ಯದಲ್ಲಿ ಘನತೆ' ಉಪಕ್ರಮವು ಪರಿತ್ಯಕ್ತ ಮತ್ತು ಹಿಂದುಳಿದ ಹಿರಿಯರಿಗೆ ಸಮಗ್ರ ಬೆಂಬಲವನ್ನು ನೀಡುವತ್ತ ಗಮನಹರಿಸುತ್ತದೆ. ಗುಣಮಟ್ಟದ ಆರೋಗ್ಯ ರಕ್ಷಣೆ, ಪೌಷ್ಟಿಕ ಆಹಾರ ಮತ್ತು ಪೂರಕ ಸಮುದಾಯವನ್ನು ಒದಗಿಸಲು ನಾವು ವೃದ್ಧಾಶ್ರಮಗಳೊಂದಿಗೆ ಪಾಲುದಾರಿಕೆ ಹೊಂದಿದ್ದೇವೆ. ನಮ್ಮ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನ ಬಹುಪಾಲು ಆದಾಯವನ್ನು ಈ ಸೇವೆಗಳಿಗೆ ವಿನಿಯೋಗಿಸಲಾಗುತ್ತದೆ, ನಮ್ಮ ಹಿರಿಯರು ತಮ್ಮ ಸುವರ್ಣ ವರ್ಷಗಳನ್ನು ಗೌರವ, ಸೌಕರ್ಯ ಮತ್ತು ಕಾಳಜಿಯೊಂದಿಗೆ ಬದುಕುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುತ್ತೇವೆ.",
    secure: "ಸುರಕ್ಷಿತ",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಬೆಂಬಲ",
    next_page: "ಮುಂದಿನ ಪುಟ",
    save_info: "ಮಾಹಿತಿಯನ್ನು ಉಳಿಸಿ",
    saved_profiles_title: "ಉಳಿಸಿದ ಪ್ರೊಫೈಲ್‌ಗಳು",
    celestial_map: "ರಾಶಿ ಕುಂಡಲಿ",
    stars_obscured: "ಮೋಡಗಳಿಂದ ನಕ್ಷತ್ರಗಳು ಕಾಣಿಸುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    go_back: "ಹಿಂದಕ್ಕೆ ಹೋಗಿ",
    dismiss: "ತೆಗೆದುಹಾಕಿ",
    select_city_warning: "⚠️ ನಿಖರವಾದ ಲೆಕ್ಕಾಚಾರಕ್ಕಾಗಿ ದಯವಿಟ್ಟು ಪಟ್ಟಿಯಿಂದ ನಗರವನ್ನು ಆರಿಸಿ.",
    search_assistant_placeholder: "ಉದಾ: 2024 ರಲ್ಲಿ ಮೇಷ ರಾಶಿಯ ಮೇಲೆ ಗುರು ಗೋಚಾರದ ಪ್ರಭಾವ",
    enter_full_name: "ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    feedback: "ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸಲಹೆಗಳು",
    feedback_title: "ನಿಮ್ಮ ಪವಿತ್ರ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸಲಹೆಗಳು",
    feedback_placeholder: "ನಕ್ಷತ್ರಗಳೊಂದಿಗಿನ ನಿಮ್ಮ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...",
    submit_feedback: "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಸಲ್ಲಿಸಿ",
    feedback_success: "ನಿಮ್ಮ ದೈವಿಕ ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ ಧನ್ಯವಾದಗಳು!",
    first_name: "ಮೊದಲ ಹೆಸರು",
    second_name: "ಎರಡನೇ ಹೆಸರು",
    timeframe_placeholder: "ಉದಾ: ಮುಂದಿನ 3 ತಿಂಗಳುಗಳು",
    select_seeker: "ಸೀಕರ್ ಆರಿಸಿ",
    select_scholar: "ಸ್ಕಾಲರ್ ಆರಿಸಿ",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    suggestion_title: "ಸಲಹೆ",
    suggestion_desc: "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಸುಧಾರಿಸಲು ಗುರೂಜಿಯವರಿಗೆ ಸಹಾಯ ಮಾಡಿ",
    suggestion_placeholder: "ನಿಮ್ಮ ಅನಿಸಿಕೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಅಥವಾ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ...",
    suggestion_send: "ಸಲಹೆ ಕಳುಹಿಸಿ",
    suggestion_sent: "ಗುರೂಜಿಯವರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
    panchanga_title: "ಪಂಚಾಂಗ",
    custom_panchanga: "ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆರಿಸಿ",
    timeline_title: "ಜೀವನ ಕಾಲರೇಖೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    contact_time_placeholder: "ಉದಾ: ನಾಳೆ ಬೆಳಿಗ್ಗೆ 10 ಗಂಟೆಗೆ",
    submit_problem: "ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಿ",
    analysis_tab_title: "ವಿಶ್ಲೇಷಣೆ",
    matching_tab_title: "ಹೊಂದಾಣಿಕೆ",
    menu_basic_details: "ಮೂಲ ಜನ್ಮ ವಿವರಗಳು",
    menu_yoga: "ಯೋಗ ವಿಶ್ಲೇಷಣೆ",
    menu_career: "ವೃತ್ತಿ ಮತ್ತು ಯಶಸ್ಸು",
    menu_health: "ಆರೋಗ್ಯ ಮತ್ತು ಚೈತನ್ಯ",
    menu_money: "ಸಂಪತ್ತು ಮತ್ತು ಹಣಕಾಸು",
    menu_transit: "ಗ್ರಹಗಳ ಗೋಚಾರ",
    menu_dasha_effect: "ದಶಾ ಫಲಗಳು",
    menu_sade_sati: "ಸಾಡೇ ಸಾತಿ ವಿಶ್ಲೇಷಣೆ",
    menu_gemstones: "ರತ್ನ ಮತ್ತು ರುದ್ರಾಕ್ಷಿ",
    menu_nakshatra: "ನಕ್ಷತ್ರ ರಹಸ್ಯಗಳು",
    menu_doshas: "ದೋಷ ತಪಾಸಣೆ (ಕಾಲಸರ್ಪ/ಪಿತೃ)",
    menu_character: "ವ್ಯಕ್ತಿತ್ವ ಮತ್ತು ಗುಣಲಕ್ಷಣ",
    menu_numerology: "ಸಂಖ್ಯಾಶಾಸ್ತ್ರ ವಿಶ್ಲೇಷಣೆ",
    chat_tab_title: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    calculating_heavens: "ಆಕಾಶದ ಲೆಕ್ಕಾಚಾರ ನಡೆಯುತ್ತಿದೆ...",
    help: "ಸಹಾಯ",
    ask_help_guruji: "ಗುರೂಜಿಯವರ ಸಹಾಯ ಪಡೆಯಿರಿ",
    sacred_conversation: "ಪವಿತ್ರ ಸಂವಾದ",
    return_home: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    under_construction: "ಈ ದೈವಿಕ ಮಾರ್ಗವು ನಿರ್ಮಾಣ ಹಂತದಲ್ಲಿದೆ.",
    footer_text: "ದೈವಿಕ ಆದೇಶ • ಆಕಾಶದ ಜೋಡಣೆ • ಆಳವಾದ ಜ್ಞಾನ",
    celestial_insights_title: "सध्याचे आकाशीय अंतर्दृष्टी",
    search_assistant_desc: "रिअल-टाइम ग्रह गोचर, आगामी ग्रहणे किंवा Google शोध द्वारे विशिष्ट ज्योतिषशास्त्रीय घटना शोधा.",
    searching: "शोधत आहे...",
    ask_stars: "ताऱ्यांना विचारा",
    sources: "स्रोत",
    seeker_desc: "स्पष्ट आणि सुलभ भाषेत साधे जीवन मार्गदर्शन, करिअर प्रवाह आणि दैनंदिन ऊर्जा मिळवा.",
    scholar_desc: "गणितीय अचूकता. रेखांश, शास्त्रीय श्लोक आणि सखोल सिद्धांत नियम.",
    siddhantic_precision: "सिद्धांत अचूकता",
    personal_guidance: "वैयक्तिक मार्गदर्शन",
    invoke_guruji: "गुरुजींना आवाहन करा",
    pranama_end: "प्रणाम (समाप्त)",
    career_guidance: "करिअर मार्गदर्शन",
    love_marriage: "प्रेम आणि विवाह",
    health_energy: "आरोग्य आणि ऊर्जा",
    spiritual_path: "आध्यात्मिक मार्ग",
    seek_wisdom_message: "ज्ञान मिळवा आणि गुरुजींच्या माध्यमातून तारे उत्तर देतील.",
    connecting: "कनेक्ट होत आहे...",
    dhanyavaada: "धन्यवाद",
    pranama: "प्रणाम",
    path: "मार्ग",
    siddhantic: "सिद्धांत",
    seeker_path: "सीकर मार्ग",
    you_hint: "तुम्ही (इशारा): मला मदत हवी आहे ",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    timezone: "वेळ क्षेत्र",
    get_verdict: "निर्णय मिळवा",
    muhurta_vivaha: "विवाह (लग्न समारंभ)",
    contact_time_label: "ಸಂಪರ್ಕ ಸಾಧಿಸಲು ಆದ್ಯತೆಯ ಸಮಯ",
    muhurta_agriculture: "ಕೃಷಿ ಕಾರ್ಯ (ಬೇಸಾಯ/ಬಿತ್ತನೆ)",
    today_panchanga: "ಇಂದಿನ ಪಂಚಾಂಗ",
    contact_astrologer_title: "ದೈವಜ್ಞರಿಗೆ ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    contact_astrologer_desc: "ತಾಂಬೂಲ ಸಮರ್ಪಣೆಯ ಮೂಲಕ ದೈವಿಕ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯುವ ಪವಿತ್ರ ವಿಧಿ",
    tambula_offering: "ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    tambula_desc: "ವೈದಿಕ ಸಂಪ್ರದಾಯದಲ್ಲಿ, ಒಬ್ಬ ಸಾಧಕನು ದೈವಜ್ಞರಿಗೆ (ಜ್ಯೋತಿಷಿಗಳಿಗೆ) ತಾಂಬೂಲವನ್ನು (ವೀಳ್ಯದೆಲೆ, ಅಡಿಕೆ ಮತ್ತು ದಕ್ಷಿಣೆ) ಅರ್ಪಿಸಿ ದೈವಿಕ ಸ್ಪಷ್ಟತೆಯನ್ನು ಪಡೆಯುತ್ತಾನೆ.",
    problem_label: "ನಿಮ್ಮ ವಿಚಾರವನ್ನು ವಿವರಿಸಿ",
    problem_placeholder: "ಉದಾ: ವೃತ್ತಿಜೀವನ, ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳು...",
    problem_submitted_msg: "ನಮ್ಮ ಜ್ಯೋತಿಷಿಗಳು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    remedy_options_title: "ನಿಮ್ಮ ಪರಿಹಾರ ಮಾರ್ಗವನ್ನು ಆರಿಸಿ",
    home: "ಮನೆ",
    daily_nav: "ದೈನಂದಿನ",
    oracle_nav: "ದೈವವಾಣಿ",
    chat_nav: "ಸಂವಾದ",
    donate_support: "ದೇಣಿಗೆ ಮತ್ತು ಬೆಂಬಲ",
    next_analysis: "ಮುಂದೆ: ವಿಶ್ಲೇಷಣೆ ಆರಿಸಿ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪ್ರಾಚೀನ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    my_character: "ನನ್ನ ವ್ಯಕ್ತಿತ್ವ",
    tier1_title: "ಉಪಾಯ ಪ್ರಾರಂಭ",
    tier1_price: "₹99",
    tier1_meaning: "ಪರಿಹಾರಗಳ ಆರಂಭ",
    tier2_title: "ಶುಭ ಮಾರ್ಗ",
    tier2_price: "₹599",
    tier2_meaning: "ಗ್ರಹ ಶಾಂತಿಯ ಹಾದಿ",
    tier3_title: "ಸರ್ವ ಕರ್ಮ ವಿಶ್ಲೇಷಣ",
    tier3_price: "₹999",
    tier3_meaning: "ಸಂಪೂರ್ಣ ಜೀವನ ವಿಶ್ಲೇಷಣೆ",
    pay_now: "ಪಾವತಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
    appointment_date: "ದಿನಾಂಕವನ್ನು ಆರಿಸಿ",
    appointment_time: "ಸಮಯವನ್ನು ಆರಿಸಿ",
    contact_astrologer_remedies: "ಪರಿಹಾರಗಳಿಗಾಗಿ ಜ್ಯೋತಿಷಿಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ",
    disclaimer: "ನಿಮ್ಮ ಸಮಾಲೋಚನೆಯನ್ನು ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ದಿನಾಂಕ ಮತ್ತು ಸಮಯದ ಪ್ರಕಾರ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ. ಯಾವುದೇ ಅನಿವಾರ್ಯ ಬದಲಾವಣೆಗಳ ಸಂದರ್ಭದಲ್ಲಿ, ನಮ್ಮ ಜ್ಯೋತಿಷಿಗಳು ನಿಮ್ಮ ಬುಕಿಂಗ್‌ನ 24 ಗಂಟೆಗಳ ಒಳಗೆ ನಿಮ್ಮನ್ನು ವೈಯಕ್ತಿಕವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತಾರೆ."
  },
  mr: {

    brand_name: "अ‍ॅस्ट्रो लॉजिक",
    brand_tagline: "प्राचीन ज्ञान, आधुनिक तर्क",
    tagline: "जिथे ज्योतिषशास्त्राचा तर्काशी मेळ बसतो",
    horoscope: "कुंडली",
    matching: "गुणमेलन",
    daily: "दैनंदिन राशिभविष्य",
    muhurta: "मुहूर्त",
    numerology: "अंकशास्त्र",
    chat: "अ‍ॅस्ट्रो चॅट",
    prashna: "प्रश्न",
    menu_details: "कुंडली विश्लेषण",
    menu_timeline: "जीवन कालक्रम (भूत, वर्तमान, भविष्य)",
    menu_hora: "शास्त्रीय होरा विश्लेषण",
    menu_sphta: "ग्रहांचे अंश",
    menu_rasi: "राशी कुंडली",
    menu_navamsha: "नवांश कुंडली",
    menu_bhava: "भाव चलित",
    menu_bhava_analysis: "१२ भाव विश्लेषण",
    menu_sandhi: "संधी विश्लेषण",
    menu_panchangam: "पंचांग",
    menu_dasha: "विंशोत्तरी दशा",
    menu_shadvarga: "षड्वर्ग",
    shadvarga_strengths: "षड्वर्ग",
    shadbala_analysis: "षडबल",
    energy_strength: "ऊर्जा शक्ती",
    planetary_power: "ग्रहीय शक्ती",
    menu_yogas: "योग विश्लेषण",
    menu_maitri: "पंचधा ग्रह मैत्री",
    menu_ashtaka: "अष्टकवर्ग",
    menu_trisputa: "त्रिसफुट विश्लेषण",
    menu_dhumadi: "धूमादि समूह",
    menu_basic_details: "मूल जन्म विवरण",
    menu_yoga: "योग विश्लेषण",
    menu_career: "करियर और सफलता",
    menu_health: "स्वास्थ्य और ऊर्जा",
    menu_money: "धन और संपत्ति",
    menu_transit: "ग्रह गोचर",
    menu_dasha_effect: "दशा प्रभाव",
    menu_sade_sati: "साढ़े साती विश्लेषण",
    menu_gemstones: "रत्न और रुद्राक्ष",
    menu_nakshatra: "नक्षत्र रहस्य",
    menu_doshas: "दोष जाँच (कालसर्प/पितृ)",
    menu_character: "व्यक्तित्व और चरित्र",
    menu_numerology: "अंकशास्त्र विश्लेषण",
    back: "मागे",
    submit: "कुंडली तयार करा",
    quick_profile: "त्वरित प्रोफाइल",
    enter_details_wisdom: "वैयक्तिक ज्ञानासाठी तपशील प्रविष्ट करा",
    save_continue: "जतन करा आणि पुढे जा",
    skip_for_now: "आत्तासाठी सोडा",
    lang_select: "भाषा",
    save_profile: "प्रोफाइल जतन करा",
    saved_profiles: "अलीकडील कुंडली",
    matching_title: "गुणमेलन आणि सुसंगतता",
    conclusion: "दैवी निर्णय",
    select_rasi: "राशी निवडा",
    daily_title: "आजचे राशिभविष्य",
    muhurta_title: "शुभ मुहूर्त",
    muhurta_select: "उद्देश निवडा",
    sacred_intake: "जन्म तपशील",
    partner_one: "पहिला जोडीदार",
    partner_two: "दुसरा जोडीदार",
    timeframe: "वेळ मर्यादा",
    location: "स्थान",
    quick_search: "त्वरित शोध",
    oracle: "देववाणी",
    ask_guruji: "गुरुजींना विचारा",
    deep_inquiry: "गहन प्रश्न",
    seek_answer: "उत्तर मिळवा",
    name_of_soul: "नाव",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    search_city_placeholder: "शहर शोधा...",
    muhurta_search_placeholder: "उद्देश शोधा...",
    prashna_placeholder: "ताऱ्यांसाठी तुमचा गहन प्रश्न काय आहे?",
    guruji_listening: "गुरुजी ऐकत आहेत...",
    connection_interrupted: "संपर्क तुटला",
    disconnected: "संपर्क तुटला",
    support_guruji: "गुरुजींना पाठिंबा द्या",
    scan_to_support: "पाठिंबा देण्यासाठी स्कॅन करा",
    scan_to_donate: "GPay / UPI द्वारे दान करा",
    support_mission: "आमच्या कार्याला पाठिंबा द्या",
    enter_full_name: "पूर्ण नाव प्रविष्ट करा",
    birth_date: "जन्म तारीख",
    birth_time: "जन्म वेळ",
    birth_location: "जन्म स्थान",
    suggestion_title: "सुझाव",
    suggestion_desc: "तुमचा अनुभव सुधारण्यासाठी गुरुजींना मदत करा",
    suggestion_placeholder: "तुमचे विचार सामायिक करा किंवा समस्येची तक्रार करा...",
    suggestion_send: "सुझाव पाठवा",
    suggestion_sent: "गुरुजींना पाठवले",
    panchanga_title: "पंचांग",
    custom_panchanga: "दिनांक आणि ठिकाण निवडा",
    timeline_title: "जीवन कालरेखा डॅशबोर्ड",
    contact_astrologer_title: "ज्योतिषांशी संपर्क साधा",
    contact_astrologer_desc: "आमच्या तज्ञांकडून वैयक्तिक उपाय मिळवा",
    problem_label: "तुमच्या समस्येचे वर्णन करा",
    problem_placeholder: "उदा: करिअरची वाढ, आरोग्य समस्या...",
    contact_time_label: "संपर्क साधण्यासाठी पसंतीची वेळ",
    contact_time_placeholder: "उदा: उद्या सकाळी 10 वाजता",
    submit_problem: "विनंती सबमिट करा",
    problem_submitted_msg: "आमचे ज्योतिषी लवकरच तुमच्याशी संपर्क साधतील.",
    analysis_tab_title: "विश्लेषण",
    matching_tab_title: "जुळवणी",
    chat_tab_title: "अ‍ॅस्ट्रो चॅट",
    calculating_heavens: "आकाशाची गणना चालू आहे...",
    help: "मदत",
    ask_help_guruji: "गुरुजींची मदत घ्या",
    sacred_conversation: "पवित्र संवाद",
    return_home: "मुख्यपृष्ठावर परत जा",
    under_construction: "हा दैवी मार्ग निर्माणाधीन आहे.",
    footer_text: "दैवी आदेश • आकाशीय संरेखन • सखोल ज्ञान",
    celestial_insights_title: "सध्याचे आकाशीय अंतर्दृष्टी",
    search_assistant_desc: "रिअल-टाइम ग्रह गोचर, आगामी ग्रहणे किंवा Google शोध द्वारे विशिष्ट ज्योतिषशास्त्रीय घटना शोधा.",
    searching: "शोधत आहे...",
    ask_stars: "ताऱ्यांना विचारा",
    sources: "स्रोत",
    seeker_desc: "स्पष्ट आणि सुलभ भाषेत साधे जीवन मार्गदर्शन, करिअर प्रवाह आणि दैनंदिन ऊर्जा मिळवा.",
    scholar_desc: "गणितीय अचूकता. रेखांश, शास्त्रीय श्लोक आणि सखोल सिद्धांत नियम.",
    siddhantic_precision: "सिद्धांत अचूकता",
    personal_guidance: "वैयक्तिक मार्गदर्शन",
    invoke_guruji: "गुरुजींना आवाहन करा",
    pranama_end: "प्रणाम (समाप्त)",
    career_guidance: "करिअर मार्गदर्शन",
    love_marriage: "प्रेम आणि विवाह",
    health_energy: "आरोग्य आणि ऊर्जा",
    spiritual_path: "आध्यात्मिक मार्ग",
    seek_wisdom_message: "ज्ञान मिळवा आणि गुरुजींच्या माध्यमातून तारे उत्तर देतील.",
    connecting: "कनेक्ट होत आहे...",
    dhanyavaada: "धन्यवाद",
    pranama: "प्रणाम",
    path: "मार्ग",
    siddhantic: "सिद्धांत",
    seeker_path: "सीकर मार्ग",
    you_hint: "तुम्ही (इशारा): मला मदत हवी आहे ",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    timezone: "वेळ क्षेत्र",
    get_verdict: "निर्णय मिळवा",
    muhurta_vivaha: "विवाह (लग्न समारंभ)",
    muhurta_grihapravesha: "गृहप्रवेश",
    muhurta_bhoomi_pooja: "भूमीपूजन",
    muhurta_upanayana: "मुंज (उपनयन)",
    muhurta_namakarana: "नामकरण",
    muhurta_annaprashana: "अन्नप्राशन",
    muhurta_aksharabhyasa: "अक्षराभ्यास",
    muhurta_vidyarambha: "विद्यारंभ",
    muhurta_karnavedha: "कर्णवेध",
    muhurta_choodakarana: "चूडाकरण (जावळ)",
    muhurta_seemantham: "डोहाळे जेवण (सीमंत)",
    muhurta_vahana: "वाहन खरेदी",
    muhurta_vyapaara: "नवीन व्यवसाय आरंभ",
    muhurta_shop_opening: "दुकान उद्घाटन",
    muhurta_udyoga: "नोकरीत रुजू होणे",
    muhurta_swarna: "सुवर्ण खरेदी",
    muhurta_investments: "गुंतवणूक",
    muhurta_yaatra: "यात्रा",
    muhurta_videsha: "परदेश प्रवास",
    muhurta_shastra_kriya: "शस्त्रक्रिया",
    muhurta_medical_start: "वैद्यकीय उपचार आरंभ",
    muhurta_abhijit: "अभिजित मुहूर्त",
    muhurta_brahma: "ब्रह्म मुहूर्त",
    muhurta_shilaanyasa: "शिलांन्यास",
    muhurta_renting: "नवीन भाडे/घर बदलणे",
    muhurta_contracts: "करारावर स्वाक्षरी करणे",
    muhurta_legal: "कायदेशीर/न्यायालयीन सुरुवात",
    muhurta_agriculture: "कृषी कार्य (शेती/पेरणी)",
    guruji: "गुरुजी",
    home: "मुख्यपृष्ठ",
    daily_nav: "दैनंदिन",
    oracle_nav: "देववाणी",
    chat_nav: "संवाद",
    donate_support: "देणगी आणि पाठिंबा",
    next_analysis: "पुढील: विश्लेषण निवडा",
    sacred_geometry: "पवित्र भूमिती • प्राचीन तर्क",
    birth_analysis: "जन्म विश्लेषण",
    my_character: "माझे व्यक्तिमत्व",
    timeline: "कालक्रम",
    life_path: "जीवन मार्ग",
    shastriya: "शास्त्रीय",
    wealth_health: "संपत्ती आणि आरोग्य",
    rasi_kundli: "राशी कुंडली",
    soul_map: "आत्म्याचा नकाशा",
    vimshottari: "विंशोत्तरी",
    life_phase: "जीवन टप्पा",
    ashtakavarga: "अष्टकवर्ग",
    power_score: "शक्ती स्कोअर",
    planet_sun: "सूर्य",
    planet_moon: "चंद्र",
    planet_mars: "मंगळ",
    planet_mercury: "बुध",
    planet_jupiter: "गुरु",
    planet_venus: "शुक्र",
    planet_saturn: "शनी",
    planet_rahu: "राहू",
    planet_ketu: "केतू",
    planet_lagna: "लग्न",
    planet_mandi: "मांदी",
    rasi_mesha: "मेष",
    rasi_vrishabha: "वृषभ",
    rasi_mithuna: "मिथुन",
    rasi_karka: "कर्क",
    rasi_simha: "सिंह",
    rasi_kanya: "कन्या",
    rasi_tula: "तूळ",
    rasi_vrishchika: "वृश्चिक",
    rasi_dhanu: "धनु",
    rasi_makara: "मकर",
    rasi_kumbha: "कुंभ",
    rasi_meena: "मीन"
  },
  hi: {

    brand_name: "एस्ट्रोलॉजिक",
    tagline: "प्रकाश और समय का प्राचीन विज्ञान",
    begin_journey: "यात्रा शुरू करें",
    choose_path: "अपना मार्ग चुनें",
    disclaimer: "ज्योतिषीय भविष्यवाणियां ग्रहों की गणना पर आधारित होती हैं और संभावनाओं को दर्शाती हैं, न कि निश्चित परिणामों को।",
    planetary_transit_in: "में",
    horoscope: "कुंडली",
    matching: "गुण मिलान",
    life_partner: "जीवन साथी",
    daily: "दैनिक राशिफल",
    muhurta: "मुहूर्त",
    chat: "एस्ट्रो चैट",
    prashna: "प्रश्न",
    guruji: "गुरुजी",
    you: "आप",
    guruji_welcome: "गुरुजी से अपने जीवन पथ, ग्रहों के गोचर या किसी भी आध्यात्मिक मार्गदर्शन के बारे में पूछें।",
    guruji_thinking: "गुरुजी सितारों से परामर्श कर रहे हैं...",
    error_guruji: "ब्रह्मांडीय संबंध कमजोर है। कृपया बाद में पुनः प्रयास करें।",
    ask_guruji_placeholder: "गुरुजी से अपना प्रश्न पूछें...",
    switch_mode: "पथ बदलें",
    menu_details: "जन्म विश्लेषण",
    menu_timeline: "जीवन कालक्रम (भूत, वर्तमान, भविष्य)",
    menu_hora: "शास्त्रीय होरा विश्लेषण",
    menu_sphta: "ग्रहों के अंश",
    menu_rasi: "राशि कुंडली",
    menu_navamsha: "नवांश कुंडली",
    menu_bhava: "भाव चलित",
    menu_bhava_analysis: "१२ भाव विश्लेषण",
    menu_sandhi: "संधि विश्लेषण",
    menu_panchangam: "पंचांग",
    menu_dasha: "विंशोत्तरी दशा",
    menu_shadvarga: "षड्वर्ग",
    shadvarga_strengths: "षड्वर्ग",
    shadbala_analysis: "षडबल",
    energy_strength: "ऊर्जा शक्ति",
    planetary_power: "ग्रहीय शक्ति",
    menu_yogas: "योग विश्लेषण",
    menu_maitri: "पंचधा ग्रह मैत्री",
    menu_ashtaka: "अष्टकवर्ग",
    menu_trisputa: "त्रिसफुट विश्लेषण",
    menu_dhumadi: "धूमादि समूह",
    menu_basic_details: "मूल जन्म विवरण",
    menu_yoga: "योग विश्लेषण",
    menu_career: "करियर और सफलता",
    menu_health: "स्वास्थ्य और ऊर्जा",
    menu_money: "धन और संपत्ति",
    menu_transit: "ग्रह गोचर",
    menu_dasha_effect: "दशा प्रभाव",
    menu_sade_sati: "साढ़े साती विश्लेषण",
    menu_gemstones: "रत्न और रुद्राक्ष",
    menu_nakshatra: "नक्षत्र रहस्य",
    menu_doshas: "दोष जाँच (कालसर्प/पितृ)",
    menu_character: "व्यक्तित्व और चरित्र",
    back: "पीछे",
    submit: "कुंडली बनाएं",
    quick_profile: "त्वरित प्रोफ़ाइल",
    enter_details_wisdom: "व्यक्तिगत ज्ञान के लिए विवरण दर्ज करें",
    save_continue: "सहेजें और जारी रखें",
    skip_for_now: "अभी के लिए छोड़ें",
    lang_select: "भाषा",
    save_profile: "प्रोफ़ाइल सहेजें",
    saved_profiles: "हाल की कुंडली",
    matching_title: "गुण मिलान और सुसंगतता",
    conclusion: "दैवीय निर्णय",
    select_rasi: "राशि चुनें",
    daily_title: "आज का राशिफल",
    muhurta_title: "शुभ मुहूर्त",
    muhurta_select: "उद्देश्य चुनें",
    sacred_intake: "जन्म विवरण",
    partner_one: "पहला साथी",
    partner_two: "दूसरा साथी",
    timeframe: "समय सीमा",
    location: "स्थान",
    quick_search: "त्वरित खोज",
    oracle: "देववाणी",
    name: "नाम",
    date: "दिनांक",
    nakshatra: "नक्षत्र",
    ask_guruji: "गुरुजी से पूछें",
    deep_inquiry: "गहन प्रश्न",
    seek_answer: "उत्तर प्राप्त करें",
    name_of_soul: "नाम",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "अन्य",
    search_city_placeholder: "शहर खोजें...",
    muhurta_search_placeholder: "उद्देश्य खोजें...",
    prashna_placeholder: "सितारों के लिए आपका गहरा प्रश्न क्या है?",
    guruji_listening: "गुरुजी सुन रहे हैं...",
    connection_interrupted: "संपर्क टूट गया",
    disconnected: "संपर्क टूट गया",
    support_guruji: "गुरुजी का समर्थन करें",
    scan_to_support: "समर्थन के लिए स्कैन करें",
    scan_to_donate: "GPay / UPI के माध्यम से दान करें",
    support_mission: "हमारे मिशन का समर्थन करें",
    support_quote: "“आपको अभी-अभी एक व्यक्तिगत ज्योतिष अंतर्दृष्टि प्राप्त हुई है। यदि यह आपको पसंद आई, तो आप एक छोटे से योगदान के साथ हमारा समर्थन कर सकते हैं।”",
    csr_title: "एस्ट्रोलॉजिक सामाजिक प्रभाव",
    csr_books_title: "विशेष बच्चों के लिए शैक्षिक सशक्तिकरण",
    csr_books_desc: "एस्ट्रोलॉजिक विशेष आवश्यकता वाले बच्चों के समग्र विकास के लिए गहराई से प्रतिबद्ध है। हम पूरे भारत में विशेष स्कूलों को आवश्यक शैक्षिक किट, विशेष शिक्षण उपकरण और बुनियादी ढांचा सहायता प्रदान करते हैं। अपने सेवा राजस्व का लगभग 90% समर्पित करके, हम यह सुनिश्चित करते हैं कि इन प्रतिभाशाली युवा दिमागों के पास चुनौतियों से उबरने और अपनी पूरी क्षमता हासिल करने के लिए आवश्यक संसाधन हों।",
    csr_oldage_title: "वृद्धावस्था में गरिमा: समग्र वृद्धाश्रम देखभाल",
    csr_oldage_desc: "हमारी 'वृद्धावस्था में गरिमा' पहल परित्यक्त और वंचित बुजुर्गों को व्यापक सहायता प्रदान करने पर केंद्रित है। हम गुणवत्तापूर्ण स्वास्थ्य सेवा, पौष्टिक भोजन और एक सहायक समुदाय प्रदान करने के लिए वृद्धाश्रमों के साथ साझेदारी करते हैं। हमारे प्लेटफॉर्म का लगभग पूरा राजस्व इन सेवाओं में लगाया जाता है, जिससे यह सुनिश्चित होता है कि हमारे बुजुर्ग अपने सुनहरे वर्षों को सम्मान, आराम और देखभाल के साथ जिएं।",
    secure: "सुरक्षित",
    spiritual: "आध्यात्मिक",
    support: "समर्थन",
    next_page: "अगला पृष्ठ",
    save_info: "जानकारी सहेजें",
    saved_profiles_title: "सहेजे गए प्रोफाइल",
    celestial_map: "राशि कुंडली",
    stars_obscured: "बादलों की वजह से सितारे दिखाई नहीं दे रहे हैं। कृपया पुनः प्रयास करें।",
    go_back: "पीछे जाएं",
    dismiss: "हटाएं",
    select_city_warning: "⚠️ सटीक गणना के लिए कृपया सूची से शहर चुनें।",
    search_assistant_placeholder: "जैसे: 2024 में मेष राशि पर गुरु गोचर का प्रभाव",
    first_name: "पहला नाम",
    second_name: "दूसरा नाम",
    timeframe_placeholder: "जैसे: अगले 3 महीने",
    select_seeker: "सीकर चुनें",
    select_scholar: "स्कॉलर चुनें",
    seeker: "सीकर",
    scholar: "स्कॉलर",
    enter_full_name: "पूरा नाम दर्ज करें",
    feedback: "प्रतिक्रिया और सुझाव",
    feedback_title: "आपकी पवित्र प्रतिक्रिया और सुझाव",
    feedback_placeholder: "सितारों के साथ अपना अनुभव साझा करें...",
    submit_feedback: "प्रतिक्रिया भेजें",
    feedback_success: "आपकी दिव्य प्रतिक्रिया के लिए धन्यवाद!",
    birth_date: "जन्म तिथि",
    birth_time: "जन्म समय",
    birth_location: "जन्म स्थान",
    suggestion_title: "सुझाव",
    suggestion_desc: "गुरुजी को आपके अनुभव को बेहतर बनाने में मदद करें",
    suggestion_placeholder: "अपने विचार साझा करें या किसी समस्या की रिपोर्ट करें...",
    suggestion_send: "सुझाव भेजें",
    suggestion_sent: "गुरुजी को भेजा गया",
    panchanga_title: "पंचांग",
    custom_panchanga: "दिनांक और स्थान चुनें",
    timeline_title: "जीवन समयरेखा डैशबोर्ड",
    contact_astrologer_title: "ज्योतिषियों से संपर्क करें",
    contact_astrologer_desc: "हमारे विशेषज्ञों से व्यक्तिगत उपचार प्राप्त करें",
    problem_label: "अपनी समस्या का वर्णन करें",
    problem_placeholder: "जैसे: करियर विकास, स्वास्थ्य समस्याएं...",
    contact_time_label: "संपर्क करने का पसंदीदा समय",
    contact_time_placeholder: "जैसे: कल सुबह 10 बजे",
    submit_problem: "अनुरोध सबमिट करें",
    problem_submitted_msg: "हमारे ज्योतिषी जल्द ही आपसे संपर्क करेंगे।",
    analysis_tab_title: "विश्लेषण",
    matching_tab_title: "मिलान",
    chat_tab_title: "एस्ट्रो चैट",
    calculating_heavens: "आकाश की गणना हो रही है...",
    help: "सहायता",
    ask_help_guruji: "गुरुजी से सहायता मांगें",
    sacred_conversation: "पवित्र संवाद",
    return_home: "होम पर वापस जाएं",
    under_construction: "यह दिव्य पथ निर्माणाधीन है।",
    footer_text: "दिव्य आदेश • आकाशीय संरेखण • गहरा ज्ञान",
    celestial_insights_title: "वर्तमान आकाशीय अंतर्दृष्टि",
    search_assistant_desc: "गूगल सर्च के माध्यम से वास्तविक समय के ग्रह गोचर, आगामी ग्रहण या विशिष्ट ज्योतिषीय घटनाओं की खोज करें।",
    searching: "खोज रहे हैं...",
    ask_stars: "सितारों से पूछें",
    sources: "स्रोत",
    seeker_desc: "स्पष्ट और सुलभ भाषा में सरल जीवन मार्गदर्शन, करियर प्रवाह और दैनिक ऊर्जा प्राप्त करें।",
    scholar_desc: "गणितीय सटीकता। देशांतर, शास्त्रीय श्लोक और गहरे सिद्धांत नियम।",
    siddhantic_precision: "सिद्धांत सटीकता",
    personal_guidance: "व्यक्तिगत मार्गदर्शन",
    invoke_guruji: "गुरुजी का आह्वान करें",
    pranama_end: "प्रणाम (समाप्त)",
    career_guidance: "करियर मार्गदर्शन",
    love_marriage: "प्रेम और विवाह",
    health_energy: "स्वास्थ्य और ऊर्जा",
    spiritual_path: "आध्यात्मिक पथ",
    seek_wisdom_message: "ज्ञान प्राप्त करें और सितारे गुरुजी के माध्यम से उत्तर देंगे।",
    connecting: "जुड़ रहा है...",
    dhanyavaada: "धन्यवाद",
    pranama: "प्रणाम",
    path: "पथ",
    siddhantic: "सिद्धांत",
    seeker_path: "सीकर पथ",
    you_hint: "आप (संकेत): मुझे सहायता चाहिए ",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    timezone: "समय क्षेत्र",
    get_verdict: "निर्णय प्राप्त करें",
    muhurta_vivaha: "विवाह (शादी समारोह)",
    muhurta_grihapravesha: "गृह प्रवेश",
    muhurta_bhoomi_pooja: "भूमि पूजन",
    muhurta_upanayana: "उपनयन (जनेऊ)",
    muhurta_namakarana: "नामकरण",
    muhurta_annaprashana: "अन्नप्राशन",
    muhurta_aksharabhyasa: "अक्षराभ्यास",
    muhurta_vidyarambha: "विद्यारंभ",
    muhurta_karnavedha: "कर्णवेध",
    muhurta_choodakarana: "चूड़ाकरण (मुंडन)",
    muhurta_seemantham: "सीमंत (गोद भराई)",
    muhurta_vahana: "वाहन खरीद",
    muhurta_vyapaara: "व्यापार आरंभ",
    muhurta_shop_opening: "दुकान उद्घाटन",
    muhurta_udyoga: "नौकरी में शामिल होना",
    muhurta_swarna: "स्वर्ण खरीद",
    muhurta_investments: "निवेश",
    muhurta_yaatra: "यात्रा",
    muhurta_videsha: "विदेश यात्रा",
    muhurta_shastra_kriya: "शल्य चिकित्सा",
    muhurta_medical_start: "चिकित्सा उपचार आरंभ",
    muhurta_abhijit: "अभिजित मुहूर्त",
    muhurta_brahma: "ब्रह्म मुहूर्त",
    muhurta_shilaanyasa: "शिलान्यास",
    muhurta_renting: "नया किराया/घर बदलना",
    muhurta_contracts: "अनुबंधों पर हस्ताक्षर",
    muhurta_legal: "कानूनी/न्यायालय की शुरुआत",
    muhurta_agriculture: "कृषि कार्य (खेती/बुवाई)",
    home: "मुख्यपृष्ठ",
    daily_nav: "दैनिक",
    oracle_nav: "देववाणी",
    chat_nav: "संवाद",
    donate_support: "दान और समर्थन",
    next_analysis: "अगला: विश्लेषण चुनें",
    sacred_geometry: "पवित्र ज्यामिति • प्राचीन तर्क",
    birth_analysis: "जन्म विश्लेषण",
    my_character: "मेरा व्यक्तित्व",
    timeline: "कालक्रम",
    life_path: "जीवन पथ",
    shastriya: "शास्त्रीय",
    wealth_health: "धन और स्वास्थ्य",
    rasi_kundli: "राशि कुंडली",
    soul_map: "आत्मा का नक्शा",
    vimshottari: "विंशोत्तरी",
    life_phase: "जीवन चरण",
    ashtakavarga: "अष्टकवर्ग",
    power_score: "शक्ति स्कोर",
    planet_sun: "सूर्य",
    planet_moon: "चंद्र",
    planet_mars: "मंगल",
    planet_mercury: "बुध",
    planet_jupiter: "गुरु",
    planet_venus: "शुक्र",
    planet_saturn: "शनि",
    planet_rahu: "राहु",
    planet_ketu: "केतु",
    planet_lagna: "लग्न",
    planet_mandi: "मांदी",
    rasi_mesha: "मेष",
    rasi_vrishabha: "वृषभ",
    rasi_mithuna: "मिथुन",
    rasi_karka: "कर्क",
    rasi_simha: "सिंह",
    rasi_kanya: "कन्या",
    rasi_tula: "तुला",
    rasi_vrishchika: "वृश्चिक",
    rasi_dhanu: "धनु",
    rasi_makara: "मकर",
    rasi_kumbha: "कुंभ",
    rasi_meena: "मीन"
  },
  sa: {

    brand_name: "अस्ट्रोलॉजिक",
    tagline: "प्रकाशस्य समयस्य च प्राचीनं विज्ञानम्",
    begin_journey: "प्रारम्भः",
    choose_path: "मार्गं चिनोतु",
    disclaimer: "ज्योतिषीय भविष्यवाणियां ग्रहों की गणना पर आधारित होती हैं और संभावनाओं को दर्शाती हैं, न कि निश्चित परिणामों को।",
    planetary_transit_in: "मध्ये",
    horoscope: "कुण्डली",
    matching: "गुणमेलनम्",
    life_partner: "जीवनसङ्गी",
    daily: "दैनिकराशिफलम्",
    muhurta: "मुहूर्तः",
    chat: "ज्योतिष-सम्भाषणम्",
    prashna: "प्रश्नः",
    menu_details: "जन्मविश्लेषणम्",
    menu_timeline: "जीवनकालक्रमः (भूतं, वर्तमानं, भविष्यत्)",
    menu_hora: "शास्त्रीयहोराविश्लेषणम्",
    menu_sphta: "ग्रहस्फुटाः",
    menu_rasi: "राशिकुण्डली",
    menu_navamsha: "नवांशकुण्डली",
    menu_bhava: "भावचलितम्",
    menu_bhava_analysis: "१२ भावविश्लेषणम्",
    menu_sandhi: "सन्धिविश्लेषणम्",
    menu_panchangam: "पञ्चाङ्गम्",
    menu_dasha: "विंशोत्तरीदशा",
    menu_shadvarga: "षड्वर्गः",
    shadvarga_strengths: "षड्वर्गबलम्",
    shadbala_analysis: "षड्बलम्",
    energy_strength: "ऊर्जाशक्तिः",
    planetary_power: "ग्रहीयशक्तिः",
    menu_yogas: "योगविश्लेषणम्",
    menu_maitri: "पञ्चधाग्रहमैत्री",
    menu_ashtaka: "अष्टकवर्गः",
    menu_trisputa: "त्रिसफुटविश्लेषणम्",
    menu_dhumadi: "धूमादिसमूहः",
    back: "पृष्ठतः",
    submit: "कुण्डलीं रचयतु",
    quick_profile: "शीघ्रविवरणम्",
    enter_details_wisdom: "व्यक्तिगतज्ञानाय विवरणं लिखतु",
    save_continue: "रक्षतु अनुवर्ततु च",
    skip_for_now: "इदानीं त्यजतु",
    lang_select: "भाषा",
    save_profile: "विवरणं रक्षतु",
    saved_profiles: "अद्यतनाः कुण्डल्यः",
    matching_title: "गुणमेलनं सुसङ्गतिश्च",
    conclusion: "दैवीयनिर्णयः",
    select_rasi: "राशिं चिनोतु",
    daily_title: "अद्यतनं राशिफलम्",
    muhurta_title: "शुभमुहूर्ताः",
    muhurta_select: "उद्देश्यं चिनोतु",
    sacred_intake: "जन्मविवरणम्",
    partner_one: "प्रथमः सङ्गी",
    partner_two: "द्वितीयः सङ्गी",
    timeframe: "समयसीमा",
    location: "स्थानम्",
    quick_search: "शीघ्रावेषणम्",
    oracle: "देववाणी",
    ask_guruji: "गुरुदेवं पृच्छतु",
    deep_inquiry: "गहनप्रश्नः",
    seek_answer: "उत्तरं प्राप्नोतु",
    name_of_soul: "नाम",
    gender: "लिङ्गम्",
    male: "पुरुषः",
    female: "स्त्री",
    other: "अन्यत्",
    search_city_placeholder: "नगरम् अन्वेषयतु...",
    muhurta_search_placeholder: "उद्देश्यम् अन्वेषयतु...",
    prashna_placeholder: "नक्षत्राणां कृते भवतः गहनप्रश्नः कः?",
    guruji: "गुरुदेवः",
    guruji_listening: "गुरुदेवः शृणोति...",
    connection_interrupted: "सम्पर्कः त्रुटितः",
    disconnected: "सम्पर्कः त्रुटितः",
    support_guruji: "गुरुदेवस्य समर्थनं करोतु",
    scan_to_support: "समर्थनाय स्क्यान् करोतु",
    scan_to_donate: "GPay / UPI माध्यमेन दानं करोतु",
    support_mission: "अस्माकं लक्ष्यस्य समर्थनं करोतु",
    support_quote: "“भवता इदानीमेव व्यक्तिगतज्योतिषज्ञानं प्राप्तम्। यदि एतत् रोचते, तर्हि अल्पयोगदानेन अस्माकं समर्थनं करोतु।”",
    secure: "सुरक्षितम्",
    spiritual: "आध्यात्मिकम्",
    support: "समर्थनम्",
    next_page: "अग्रिमं पृष्ठम्",
    save_info: "सूचनां रक्षतु",
    saved_profiles_title: "रक्षितानि विवरणानि",
    celestial_map: "राशिकुण्डली",
    stars_obscured: "मेघैः नक्षत्राणि न दृश्यन्ते। कृपया पुनः प्रयतस्व।",
    go_back: "पृष्ठतः गच्छतु",
    dismiss: "अपासरतु",
    select_city_warning: "⚠️ शुद्धगणनाय कृपया सूच्याः नगरं चिनोतु।",
    search_assistant_placeholder: "यथा: २०२४ वर्षे मेषराशौ गुरुगोचरस्य प्रभावः",
    first_name: "प्रथमं नाम",
    second_name: "द्वितीयं नाम",
    timeframe_placeholder: "यथा: आगामिनः ३ मासाः",
    select_seeker: "जिज्ञासुं चिनोतु",
    select_scholar: "विद्वांसं चिनोतु",
    seeker: "जिज्ञासुः",
    scholar: "विद्वान्",
    enter_full_name: "पूर्णं नाम लिखतु",
    birth_date: "जन्मतिथिः",
    birth_time: "जन्मसमयः",
    birth_location: "जन्मस्थानम्",
    suggestion_title: "परामर्शः",
    suggestion_desc: "गुरुदेवस्य अनुभवं श्रेष्ठं कर्तुं साहाय्यं करोतु",
    suggestion_placeholder: "स्वविचारान् लिखतु अथवा समस्यां सूचयतु...",
    suggestion_send: "परामर्शं प्रेषयतु",
    suggestion_sent: "गुरुदेवाय प्रेषितम्",
    panchanga_title: "पञ्चाङ्गम्",
    custom_panchanga: "तिथिं स्थानं च चिनोतु",
    timeline_title: "जीवनकालಕ್ರಮ-फलಕಮ್",
    contact_astrologer_title: "ज्योतिर्विद्भिः सह सम्पर्कं करोतु",
    contact_astrologer_desc: "अस्माकं विशेषज्ञेभ्यः व्यक्तिगतोपचारं प्राप्नोतु",
    problem_label: "स्वसमस्यां वर्णयतु",
    problem_placeholder: "यथा: वृत्तिविकासः, स्वास्थ्यसमस्याः...",
    contact_time_label: "सम्पर्कस्य प्रियसमयः",
    contact_time_placeholder: "यथा: श्वः प्रातः १० वादने",
    submit_problem: "निवेदनं प्रेषयतु",
    problem_submitted_msg: "अस्माकं ज्योतिर्विदः शीघ्रमेव भवता सह सम्पर्कं करिष्यन्ति।",
    analysis_tab_title: "विश्लेषणम्",
    matching_tab_title: "मेलनम्",
    chat_tab_title: "ज्योतिष-सम्भाषणम्",
    calculating_heavens: "आकाशस्य गणना भवति...",
    help: "साहाय्यम्",
    ask_help_guruji: "गुरुदेवाय साहाय्यं प्रार्थयतु",
    sacred_conversation: "पवित्रः संवादः",
    return_home: "मुख्यपृष्ठं प्रति गच्छतु",
    under_construction: "एषः दिव्यमार्गः निर्माणाधीनः अस्ति।",
    footer_text: "दिव्यादेशः • आकाशीयसङ्गतिः • गभीरं ज्ञानम्",
    celestial_insights_title: "वर्तमानाः आकाशीयदृष्टयः",
    search_assistant_desc: "गूगल-अन्वेषणमाध्यमेन वास्तविकसमयस्य ग्रहगोचरं, आगामिग्रहणं वा विशिष्टज्योतिषघटनावलिं अन्वेषयतु।",
    searching: "अन्वेषणं भवति...",
    ask_stars: "नक्षत्राणि पृच्छतु",
    sources: "स्रोतांसि",
    seeker_desc: "स्पष्टसरलभाषया सरलजीवनमार्गदर्शनं, वृत्तिप्रवाहं, दैनिकोर्जां च प्राप्नोतु।",
    scholar_desc: "गणितीयशुद्धता। देशान्तरं, शास्त्रीयश्लोकाः, गभीरसिद्धान्तनियमाश्च।",
    siddhantic_precision: "सिद्धान्तशुद्धता",
    personal_guidance: "व्यक्तिगतमार्गदर्शनम्",
    invoke_guruji: "गुरुदेवम् आह्वयतु",
    pranama_end: "प्रणामः (समाप्तः)",
    career_guidance: "वृत्तिमार्गदर्शनम्",
    love_marriage: "प्रेम विवाहश्च",
    health_energy: "स्वास्थ्यम् ऊर्जा च",
    spiritual_path: "आध्यात्मिकमार्गः",
    seek_wisdom_message: "ज्ञानं प्राप्नोतु, नक्षत्राणि गुरुदेवमाध्यमेन उत्तरं दास्यन्ति।",
    connecting: "सम्पर्कः भवति...",
    dhanyavaada: "धन्यवादः",
    pranama: "प्रणामः",
    path: "मार्गः",
    siddhantic: "सिद्धान्तः",
    seeker_path: "जिज्ञासुमार्गः",
    you_hint: "भवान् (सङ्केतः): मम साहाय्यम् आवश्यकम् ",
    latitude: "अक्षांशः",
    longitude: "देशान्तरम्",
    timezone: "समयक्षेत्रम्",
    get_verdict: "निर्णयं प्राप्नोतु",
    muhurta_vivaha: "विवाहः",
    muhurta_grihapravesha: "गृहप्रवेशः",
    muhurta_bhoomi_pooja: "भूमिपूजनम्",
    muhurta_upanayana: "उपनयनम्",
    muhurta_namakarana: "नामकरणम्",
    muhurta_annaprashana: "अन्नप्राशनम्",
    muhurta_aksharabhyasa: "अक्षराभ्यासः",
    muhurta_vidyarambha: "विद्यारम्भः",
    muhurta_karnavedha: "कर्णवेधः",
    muhurta_choodakarana: "चूडाकरणम्",
    muhurta_seemantham: "सीमन्तोन्नयनम्",
    muhurta_vahana: "वाहनक्रयः",
    muhurta_vyapaara: "व्यापारारम्भः",
    muhurta_shop_opening: "आपणोद्घाटनम्",
    muhurta_udyoga: "वृत्तिप्रवेशः",
    muhurta_swarna: "स्वर्णक्रयः",
    muhurta_investments: "निवेशः",
    muhurta_yaatra: "यात्रा",
    muhurta_videsha: "विदेशयात्रा",
    muhurta_shastra_kriya: "शल्यचिकित्सा",
    muhurta_medical_start: "चिकित्सारम्भः",
    muhurta_abhijit: "अभिजित् मुहूर्तः",
    muhurta_brahma: "ब्रह्म मुहूर्तः",
    muhurta_shilaanyasa: "शिलान्यासः",
    muhurta_renting: "नूतनभाटकं/गृहपरिवर्तनम्",
    muhurta_contracts: "अनुबन्धहस्ताक्षरम्",
    muhurta_legal: "न्यायालयप्रक्रियारम्भः",
    muhurta_agriculture: "कृषिकार्यम्",
    home: "मुख्यपृष्ठम्",
    daily_nav: "दैनिकम्",
    oracle_nav: "देववाणी",
    chat_nav: "सम्भाषणम्",
    donate_support: "दानं समर्थनं च",
    next_analysis: "अग्रिमम्: विश्लेषणं चिनोतु",
    sacred_geometry: "पवित्रा ज्यामितिः • प्राचीनः तर्कः",
    birth_analysis: "जन्मविश्लेषणम्",
    my_character: "मम व्यक्तित्वम्",
    timeline: "कालक्रमः",
    life_path: "जीवनमार्गः",
    shastriya: "शास्त्रीयम्",
    wealth_health: "धनं स्वास्थ्यं च",
    rasi_kundli: "राशिकुण्डली",
    soul_map: "आत्मनः मानचित्रम्",
    vimshottari: "विंशोत्तरी",
    life_phase: "जीवनचरणम्",
    ashtakavarga: "अष्टकवर्गः",
    power_score: "शक्ति-अङ्कः",
    planet_sun: "सूर्यः",
    planet_moon: "चन्द्रः",
    planet_mars: "मङ्गलः",
    planet_mercury: "बुधः",
    planet_jupiter: "गुरुः",
    planet_venus: "शुक्रः",
    planet_saturn: "शनिः",
    planet_rahu: "राहुः",
    planet_ketu: "केतुः",
    planet_lagna: "लग्नम्",
    planet_mandi: "मान्दिः",
    rasi_mesha: "मेषः",
    rasi_vrishabha: "वृषभः",
    rasi_mithuna: "मिथुनः",
    rasi_karka: "कर्कः",
    rasi_simha: "सिंहः",
    rasi_kanya: "कन्या",
    rasi_tula: "तुला",
    rasi_vrishchika: "वृश्चिकः",
    rasi_dhanu: "धनुः",
    rasi_makara: "मकरः",
    rasi_kumbha: "कुम्भः",
    rasi_meena: "मीनः"
  },
  te: {

    tagline: "జ్యోతిష్యం మరియు తర్కం కలిసే చోటు",
    horoscope: "జాతకం",
    matching: "గుణమేళనం",
    daily: "దినఫలాలు",
    muhurta: "ముహూర్తం",
    chat: "ఆస్ట్రో చాట్",
    prashna: "ప్రశ్న",
    menu_details: "జన్మ విశ్లేషణ",
    menu_timeline: "జీవిత కాలక్రమం (గతం, వర్తమానం, భవిష్యత్తు)",
    menu_hora: "శాస్త్రీయ హోరా విశ్లేషణ",
    menu_sphta: "గ్రహాల అంశాలు",
    menu_rasi: "రాశి చక్రం",
    menu_navamsha: "నవాంశ చక్రం",
    menu_bhava: "భావ చక్రం",
    menu_sandhi: "సంధి విశ్లేషణ",
    menu_panchangam: "పంచాంగం",
    menu_dasha: "వింశోత్తరి దశ",
    menu_shadvarga: "షడ్వర్గ బలం",
    menu_ashtaka: "అష్టకవర్గం",
    menu_trisputa: "త్రిస్ఫుట విశ్లేషణ",
    menu_dhumadi: "ధూమాది సమూహం",
    back: "వెనుకకు",
    submit: "జాతకం తయారు చేయండి",
    quick_profile: "త్వరిత ప్రొఫైల్",
    enter_details_wisdom: "వ్యక్తిగతీకరించిన జ్ఞానం కోసం వివరాలను నమోదు చేయండి",
    save_continue: "సేవ్ చేసి కొనసాగించండి",
    skip_for_now: "ప్రస్తుతానికి వదిలివేయండి",
    lang_select: "భాష",
    save_profile: "ప్రొఫైల్ సేవ్ చేయండి",
    saved_profiles: "ఇటీవలి జాతకాలు",
    matching_title: "గుణమేళనం మరియు పొంతన",
    conclusion: "దైవిక తీర్పు",
    select_rasi: "రాశిని ఎంచుకోండి",
    daily_title: "నేటి రాశిఫలాలు",
    muhurta_title: "శుభ ముహూర్తాలు",
    muhurta_select: "ఉద్దేశ్యాన్ని ఎంచుకోండి",
    search_city_placeholder: "నగరాన్ని వెతకండి...",
    muhurta_search_placeholder: "ఉద్దేశ్యాన్ని వెతకండి...",
    prashna_placeholder: "నక్షత్రాల కోసం మీ లోతైన ప్రశ్న ఏమిటి?",
    guruji_listening: "గురూజీ వింటున్నారు...",
    connection_interrupted: "కనెక్షన్ అంతరాయం కలిగింది",
    disconnected: "డిస్కనెక్ట్ చేయబడింది",
    support_guruji: "గురూజీకి మద్దతు ఇవ్వండి",
    scan_to_support: "మద్దతు ఇవ్వడానికి స్కాన్ చేయండి",
    scan_to_donate: "GPay / UPI ద్వారా విరాళం ఇవ్వండి",
    support_mission: "మా మిషన్‌కు మద్దతు ఇవ్వండి",
    support_quote: "“మీరు ఇప్పుడే వ్యక్తిగత జ్యోతిష్య అంతర్దృష్టిని పొందారు. ఇది మీకు నచ్చినట్లయితే, చిన్న విరాళంతో మాకు మద్దతు ఇవ్వవచ్చు.”",
    secure: "సురక్షితం",
    spiritual: "ఆధ్యాత్మికం",
    support: "మద్దతు",
    next_page: "తదుపరి పేజీ",
    save_info: "సమాచారాన్ని సేవ్ చేయండి",
    saved_profiles_title: "సేవ్ చేసిన ప్రొఫైల్స్",
    celestial_map: "రాశి చక్రం",
    stars_obscured: "మేఘాల వల్ల నక్షత్రాలు కనిపించడం లేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    go_back: "వెనుకకు వెళ్ళండి",
    dismiss: "తీసివేయండి",
    select_city_warning: "⚠️ ఖచ్చితమైన గణన కోసం దయచేసి జాబితా నుండి నగరాన్ని ఎంచుకోండి.",
    guruji: "గురూజీ",
    home: "హోమ్",
    daily_nav: "దినచర్య",
    oracle_nav: "దైవవాణి",
    chat_nav: "సంభాషణ",
    donate_support: "విరాళం & మద్దతు",
    next_analysis: "తదుపరి: విశ్లేషణను ఎంచుకోండి",
    sacred_geometry: "పవిత్ర జ్యామితి • పురాతన తర్కం",
    birth_analysis: "జనన విశ్లేషణ",
    my_character: "నా వ్యక్తిత్వం",
    timeline: "కాలక్రమం",
    life_path: "జీవన మార్గం",
    shastriya: "శాస్త్రీయ",
    wealth_health: "సంపద & ఆరోగ్యం",
    rasi_kundli: "రాశి కుండలి",
    soul_map: "ఆత్మ పటం",
    vimshottari: "వింశోత్తరి",
    life_phase: "జీవన దశ",
    ashtakavarga: "అష్టకవర్గ",
    power_score: "పవర్ స్కోర్",
    brand_name: "ఆస్ట్రో లాజిక్",
    siddhantic_precision: "సిద్ధాంతిక ఖచ్చితత్వం",
    personal_guidance: "వ్యక్తిగత మార్గదర్శకత్వం",
    planet_sun: "సూర్యుడు",
    planet_moon: "చంద్రుడు",
    planet_mars: "కుజుడు",
    planet_mercury: "బుధుడు",
    planet_jupiter: "గురుడు",
    planet_venus: "శుక్రుడు",
    planet_saturn: "శని",
    planet_rahu: "రాహువు",
    planet_ketu: "కేతువు",
    planet_lagna: "లగ్నం",
    planet_mandi: "మాంది",
    rasi_mesha: "మేషం",
    rasi_vrishabha: "వృషభం",
    rasi_mithuna: "మిథునం",
    rasi_karka: "కర్కాటకం",
    rasi_simha: "సింహం",
    rasi_kanya: "కన్య",
    rasi_tula: "తుల",
    rasi_vrishchika: "వృశ్చికం",
    rasi_dhanu: "ధనుస్సు",
    rasi_makara: "మకరం",
    rasi_kumbha: "కుంభం",
    rasi_meena: "మీనం",
    seeker: "సీకర్",
    scholar: "స్కాలర్",
    suggestion_title: "సూచనలు",
    suggestion_desc: "మీ అనుభవాన్ని మెరుగుపరచడంలో గురూజీకి సహాయపడండి",
    suggestion_placeholder: "మీ ఆలోచనలను పంచుకోండి లేదా సమస్యను నివేదించండి...",
    suggestion_send: "సూచన పంపండి",
    suggestion_sent: "గురూజీకి పంపబడింది",
    panchanga_title: "పంచాంగం",
    today_panchanga: "నేటి పంచాంగం",
    custom_panchanga: "తేదీ మరియు స్థలాన్ని ఎంచుకోండి",
    timeline_title: "జీవిత కాలక్రమ డాష్‌బోర్డ్",
    contact_astrologer_title: "జ్యోతిష్కులను సంప్రదించండి",
    contact_astrologer_desc: "మా నిపుణుల నుండి వ్యక్తిగత పరిష్కారాలను పొందండి",
    problem_label: "మీ సమస్యను వివరించండి",
    problem_placeholder: "ఉదా: కెరీర్ వృద్ధి, ఆరోగ్య సమస్యలు...",
    contact_time_label: "సంప్రదించడానికి ఇష్టపడే సమయం",
    contact_time_placeholder: "ఉదా: రేపు ఉదయం 10 గంటలకు",
    submit_problem: "అభ్యర్థనను సమర్పించండి",
    problem_submitted_msg: "మా జ్యోతిష్కులు త్వరలో మిమ్మల్ని సంప్రదిస్తారు."
  },
  ta: {

    tagline: "ஜோதிடமும் பகுத்தறிவும் இணையும் இடம்",
    horoscope: "ஜாதகம்",
    matching: "திருமண பொருத்தம்",
    daily: "தினசரி ராசிபலன்",
    muhurta: "முஹூர்த்தம்",
    chat: "ஆஸ்ட்ரோ சாட்",
    prashna: "பிரசன்னம்",
    menu_details: "பிறப்பு ஆய்வு",
    menu_timeline: "வாழ்க்கை காலவரிசை (கடந்த, நிகழ், எதிர்காலம்)",
    menu_hora: "சாஸ்திர ஹோரா ஆய்வு",
    menu_sphta: "கிரக பாகைகள்",
    menu_rasi: "ராசி கட்டம்",
    menu_navamsha: "நவாம்ச கட்டம்",
    menu_bhava: "பாவ சக்கரம்",
    menu_sandhi: "சந்தி ஆய்வு",
    menu_panchangam: "பஞ்சாங்கம்",
    menu_dasha: "விம்சோத்தரி தசை",
    menu_shadvarga: "ஷட்வர்க பலம்",
    menu_ashtaka: "அஷ்டகவர்க்கம்",
    menu_trisputa: "திரிஸ்புட ஆய்வு",
    menu_dhumadi: "தூமாதி குழு",
    back: "பின்னால்",
    submit: "ஜாதகம் உருவாக்கு",
    quick_profile: "விரைவான சுயவிவரம்",
    enter_details_wisdom: "தனிப்பயனாக்கப்பட்ட ஞானத்திற்காக விவரங்களை உள்ளிடவும்",
    save_continue: "சேமித்து தொடரவும்",
    skip_for_now: "இப்போதைக்குத் தவிர்க்கவும்",
    lang_select: "மொழி",
    save_profile: "சுயவிவரத்தைச் சேமி",
    saved_profiles: "சமீபத்திய ஜாதகங்கள்",
    matching_title: "திருமண பொருத்தம் மற்றும் இணக்கம்",
    conclusion: "தெய்வீக தீர்ப்பு",
    select_rasi: "ராசியைத் தேர்ந்தெடுக்கவும்",
    daily_title: "இன்றைய ராசிபலன்",
    muhurta_title: "சுப முஹூர்த்தங்கள்",
    muhurta_select: "நோக்கத்தைத் தேர்ந்தெடுக்கவும்",
    search_city_placeholder: "நகரத்தைத் தேடுங்கள்...",
    muhurta_search_placeholder: "நோக்கத்தைத் தேடுங்கள்...",
    prashna_placeholder: "நட்சத்திரங்களிடம் உங்கள் ஆழமான கேள்வி என்ன?",
    guruji_listening: "குருஜி கேட்டுக்கொண்டிருக்கிறார்...",
    connection_interrupted: "இணைப்பு துண்டிக்கப்பட்டது",
    disconnected: "துண்டிக்கப்பட்டது",
    support_guruji: "குருஜிக்கு ஆதரவு அளிக்கவும்",
    scan_to_support: "ஆதரவு அளிக்க ஸ்கேன் செய்யவும்",
    scan_to_donate: "GPay / UPI மூலம் நன்கொடை அளிக்கவும்",
    support_mission: "எங்கள் பணிக்கு ஆதரவு அளிக்கவும்",
    support_quote: "“நீங்கள் இப்போது தனிப்பட்ட ஜோதிட ஆலோசனையைப் பெற்றுள்ளீர்கள். இது உங்களுக்குப் பிடித்திருந்தால், சிறிய பங்களிப்புடன் எங்களை ஆதரிக்கலாம்.”",
    secure: "பாதுகாப்பானது",
    spiritual: "ஆன்மீகம்",
    support: "ஆதரவு",
    next_page: "அடுத்த பக்கம்",
    save_info: "தகவலைச் சேமிக்கவும்",
    saved_profiles_title: "சேமிக்கப்பட்ட சுயவிவரங்கள்",
    celestial_map: "ராசி கட்டம்",
    stars_obscured: "மேகங்களால் நட்சத்திரங்கள் மறைக்கப்பட்டுள்ளன. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    go_back: "பின்னால் செல்லவும்",
    dismiss: "நீக்கவும்",
    select_city_warning: "⚠️ துல்லியமான கணக்கீட்டிற்கு தயவுசெய்து பட்டியலிலிருந்து நகரத்தைத் தேர்ந்தெடுக்கவும்.",
    guruji: "குருஜி",
    home: "முகப்பு",
    daily_nav: "தினசரி",
    oracle_nav: "தெய்வீக வாக்கு",
    chat_nav: "உரையாடல்",
    donate_support: "நன்கொடை & ஆதரவு",
    next_analysis: "அடுத்து: பகுப்பாய்வைத் தேர்ந்தெடுக்கவும்",
    sacred_geometry: "புனித வடிவியல் • பண்டைய தர்க்கம்",
    birth_analysis: "பிறப்பு பகுப்பாய்வு",
    my_character: "எனது ஆளுமை",
    timeline: "காலவரிசை",
    life_path: "வாழ்க்கை பாதை",
    shastriya: "சாஸ்திரீய",
    wealth_health: "செல்வம் & ஆரோக்கியம்",
    rasi_kundli: "ராசி குண்டலி",
    soul_map: "ஆன்ம வரைபடம்",
    vimshottari: "விம்ஷோத்தரி",
    life_phase: "வாழ்க்கை நிலை",
    ashtakavarga: "அஷ்டகவர்க்கம்",
    power_score: "சக்தி மதிப்பெண்",
    brand_name: "ஆஸ்ட்ரோ லாஜிக்",
    siddhantic_precision: "சாஸ்திரீய துல்லியம்",
    personal_guidance: "தனிப்பட்ட வழிகாட்டுதல்",
    planet_sun: "சூரியன்",
    planet_moon: "சந்திரன்",
    planet_mars: "செவ்வாய்",
    planet_mercury: "புதன்",
    planet_jupiter: "குரு",
    planet_venus: "சுக்கிரன்",
    planet_saturn: "சனி",
    planet_rahu: "ராகு",
    planet_ketu: "கேது",
    planet_lagna: "லக்னம்",
    planet_mandi: "மாந்தி",
    rasi_mesha: "மேஷம்",
    rasi_vrishabha: "ரிஷபம்",
    rasi_mithuna: "மிதுனம்",
    rasi_karka: "கடகம்",
    rasi_simha: "சிம்மம்",
    rasi_kanya: "கன்னி",
    rasi_tula: "துலாம்",
    rasi_vrishchika: "விருச்சிகம்",
    rasi_dhanu: "தனுசு",
    rasi_makara: "மகரம்",
    rasi_kumbha: "கும்பம்",
    rasi_meena: "மீனம்",
    seeker: "சீக்கர்",
    scholar: "ஸ்காலர்",
    suggestion_title: "பரிந்துரைகள்",
    suggestion_desc: "உங்கள் அனுபவத்தை மேம்படுத்த குருஜிக்கு உதவுங்கள்",
    suggestion_placeholder: "உங்கள் கருத்துக்களைப் பகிரவும் அல்லது சிக்கலைப் புகாரளிக்கவும்...",
    suggestion_send: "பரிந்துரையை அனுப்பு",
    suggestion_sent: "குருஜிக்கு அனுப்பப்பட்டது",
    panchanga_title: "பஞ்சாங்கம்",
    today_panchanga: "இன்றைய பஞ்சாங்கம்",
    custom_panchanga: "தேதி மற்றும் இடத்தைத் தேர்ந்தெடுக்கவும்",
    timeline_title: "வாழ்க்கை காலவரிசை டாஷ்போர்டு",
    contact_astrologer_title: "ஜோதிடர்களைத் தொடர்பு கொள்ளுங்கள்",
    contact_astrologer_desc: "எங்கள் நிபுணர்களிடமிருந்து தனிப்பட்ட தீர்வுகளைப் பெறுங்கள்",
    problem_label: "உங்கள் சிக்கலை விவரிக்கவும்",
    problem_placeholder: "எ.கா. தொழில் வளர்ச்சி, சுகாதார பிரச்சினைகள்...",
    contact_time_label: "தொடர்பு கொள்ள விருப்பமான நேரம்",
    contact_time_placeholder: "எ.கா. நாளை காலை 10 மணி",
    submit_problem: "கோரிக்கையைச் சமர்ப்பிக்கவும்",
    problem_submitted_msg: "எங்கள் ஜோதிடர்கள் விரைவில் உங்களைத் தொடர்புகொள்வார்கள்."
  },
  ml: {

    tagline: "ജ്യോതിഷവും യുക്തിയും ഒന്നിക്കുന്ന ഇടം",
    horoscope: "ജാതകം",
    matching: "പൊരുത്തം",
    daily: "ദിവസഫലം",
    muhurta: "മുഹൂർത്തം",
    chat: "ആസ്ട്രോ ചാറ്റ്",
    prashna: "പ്രശ്നം",
    menu_details: "ജനന വിശകലനം",
    menu_timeline: "ജീവിത കാലക്രമം (കഴിഞ്ഞത്, ഇപ്പോൾ, ഭാവി)",
    menu_hora: "ശാസ്ത്രീയ ഹോര വിശകലനം",
    menu_sphta: "ഗ്രഹ സ്ഫുടം",
    menu_rasi: "രാശി ചക്രം",
    menu_navamsha: "നവാംശ ചക്രം",
    menu_bhava: "ഭാവ ചക്രം",
    menu_sandhi: "സന്ധി വിശകലനം",
    menu_panchangam: "പഞ്ചാംഗം",
    menu_dasha: "വിംശോത്തരി ദശ",
    menu_shadvarga: "ഷഡ്വർഗ ബലം",
    menu_ashtaka: "അഷ്ടകവർഗ്ഗം",
    menu_trisputa: "ത്രിസ്ഫുട വിശകലനം",
    menu_dhumadi: "ധൂമാദി ഗ്രൂപ്പ്",
    back: "പിന്നിലേക്ക്",
    submit: "ജാതകം ഉണ്ടാക്കുക",
    quick_profile: "ദ്രുത പ്രൊഫൈൽ",
    enter_details_wisdom: "വ്യക്തിഗതമാക്കിയ അറിവിനായി വിശദാംശങ്ങൾ നൽകുക",
    save_continue: "സേവ് ചെയ്ത് തുടരുക",
    skip_for_now: "ഇപ്പോഴത്തേക്ക് ഒഴിവാക്കുക",
    lang_select: "ഭാഷ",
    save_profile: "പ്രൊഫൈൽ സംരക്ഷിക്കുക",
    saved_profiles: "സമീപകാല ജാതകങ്ങൾ",
    matching_title: "വിവാഹ പൊരുത്തം",
    conclusion: "ദൈവിക വിധി",
    select_rasi: "രാശി തിരഞ്ഞെടുക്കുക",
    daily_title: "ഇന്നത്തെ രാശിഫലം",
    muhurta_title: "ശുഭ മുഹൂർത്തങ്ങൾ",
    muhurta_select: "ഉദ്ദേശ്യം തിരഞ്ഞെടുക്കുക",
    search_city_placeholder: "നഗരം തിരയുക...",
    muhurta_search_placeholder: "ഉദ്ദേശ്യം തിരയുക...",
    prashna_placeholder: "നക്ഷത്രങ്ങളോടുള്ള നിങ്ങളുടെ ആഴത്തിലുള്ള ചോദ്യം എന്താണ്?",
    guruji_listening: "ഗുരുജി കേൾക്കുന്നു...",
    connection_interrupted: "ബന്ധം തടസ്സപ്പെട്ടു",
    disconnected: "ബന്ധം വേർപെട്ടു",
    support_guruji: "ഗുരുജിയെ പിന്തുണയ്ക്കുക",
    scan_to_support: "പിന്തുണയ്ക്കാൻ സ്കാൻ ചെയ്യുക",
    scan_to_donate: "GPay / UPI വഴി സംഭാവന ചെയ്യുക",
    support_mission: "ഞങ്ങളുടെ ദൗത്യത്തെ പിന്തുണയ്ക്കുക",
    support_quote: "“നിങ്ങൾക്ക് ഇപ്പോൾ വ്യക്തിഗത ജ്യോതിഷ ഉപദേശം ലഭിച്ചു. ഇത് നിങ്ങൾക്ക് ഇഷ്ടപ്പെട്ടെങ്കിൽ, ചെറിയൊരു സംഭാവനയിലൂടെ ഞങ്ങളെ പിന്തുണയ്ക്കാം.”",
    secure: "സുരക്ഷിതം",
    spiritual: "ആത്മീയം",
    support: "പിന്തുണ",
    next_page: "അടുത്ത പേജ്",
    save_info: "വിവരങ്ങൾ സംരക്ഷിക്കുക",
    saved_profiles_title: "സംരക്ഷിച്ച പ്രൊഫൈലുകൾ",
    celestial_map: "രാശി ചക്രം",
    stars_obscured: "മേഘങ്ങൾ കാരണം നക്ഷത്രങ്ങൾ കാണുന്നില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    go_back: "പിന്നിലേക്ക് പോകുക",
    dismiss: "ഒഴിവാക്കുക",
    select_city_warning: "⚠️ കൃത്യമായ കണക്കുകൂട്ടലിനായി ദയവായി പട്ടികയിൽ നിന്ന് നഗരം തിരഞ്ഞെടുക്കുക.",
    guruji: "ഗുരുജി",
    home: "ഹോം",
    daily_nav: "ദൈനംദിനം",
    oracle_nav: "ദൈവവാണി",
    chat_nav: "സംവാദം",
    donate_support: "സംഭാവനയും പിന്തുണയും",
    next_analysis: "അടുത്തത്: വിശകലനം തിരഞ്ഞെടുക്കുക",
    sacred_geometry: "വിശുദ്ധ ജ്യാമിതി • പുരാതന യുക്തി",
    birth_analysis: "ജനന വിശകലനം",
    my_character: "എന്റെ വ്യക്തിത്വം",
    timeline: "കാലക്രമം",
    life_path: "ജീവിത പാത",
    shastriya: "ശാസ്ത്രീയം",
    wealth_health: "സമ്പത്തും ആരോഗ്യവും",
    rasi_kundli: "രാശി കുണ്ഡലി",
    soul_map: "ആത്മാവിന്റെ ഭൂപടം",
    vimshottari: "വിംശോത്തരി",
    life_phase: "ജീവിത ഘട്ടം",
    ashtakavarga: "അഷ്ടകവർഗ്ഗം",
    power_score: "പവർ സ്കോർ",
    brand_name: "ആസ്ട്രോ ലോജിക്",
    siddhantic_precision: "സിദ്ധാന്തിക കൃത്യത",
    personal_guidance: "വ്യക്തിഗത മാർഗ്ഗനിർദ്ദേശം",
    planet_sun: "സൂര്യൻ",
    planet_moon: "ചന്ദ്രൻ",
    planet_mars: "ചൊവ്വ",
    planet_mercury: "ബുധൻ",
    planet_jupiter: "വ്യാഴം",
    planet_venus: "ശുക്രൻ",
    planet_saturn: "ശനി",
    planet_rahu: "രാഹു",
    planet_ketu: "കേതു",
    planet_lagna: "ലഗ്നം",
    planet_mandi: "മാന്തി",
    rasi_mesha: "മേടം",
    rasi_vrishabha: "ഇടവം",
    rasi_mithuna: "മിഥുനം",
    rasi_karka: "കർക്കടകം",
    rasi_simha: "ചിങ്ങം",
    rasi_kanya: "കന്നി",
    rasi_tula: "തുലാം",
    rasi_vrishchika: "വൃശ്ചികം",
    rasi_dhanu: "ധനു",
    rasi_makara: "മകരം",
    rasi_kumbha: "കുംഭം",
    rasi_meena: "മീനം",
    seeker: "സീക്കർ",
    scholar: "സ്കോളർ",
    suggestion_title: "നിർദ്ദേശങ്ങൾ",
    suggestion_desc: "നിങ്ങളുടെ അനുഭവം മെച്ചപ്പെടുത്താൻ ഗുരുജിയെ സഹായിക്കുക",
    suggestion_placeholder: "നിങ്ങളുടെ ചിന്തകൾ പങ്കിടുക അല്ലെങ്കിൽ ഒരു പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക...",
    suggestion_send: "നിർദ്ദേശം അയയ്ക്കുക",
    suggestion_sent: "ഗുരുജിക്ക് അയച്ചു",
    panchanga_title: "പഞ്ചാംഗം",
    today_panchanga: "ഇന്നത്തെ പഞ്ചാംഗം",
    custom_panchanga: "തീയതിയും സ്ഥലവും തിരഞ്ഞെടുക്കുക",
    timeline_title: "ജീവിത കാലക്രമ ഡാഷ്‌ബോർഡ്",
    contact_astrologer_title: "ജ്യോതിഷികളെ ബന്ധപ്പെടുക",
    contact_astrologer_desc: "ഞങ്ങളുടെ വിദഗ്ധരിൽ നിന്ന് വ്യക്തിഗത പരിഹാരങ്ങൾ നേടുക",
    problem_label: "നിങ്ങളുടെ പ്രശ്നം വിവരിക്കുക",
    problem_placeholder: "ഉദാ: കരിയർ വളർച്ച, ആരോഗ്യ പ്രശ്നങ്ങൾ...",
    contact_time_label: "ബന്ധപ്പെടാൻ താൽപ്പര്യമുള്ള സമയം",
    contact_time_placeholder: "ഉദാ: നാളെ രാവിലെ 10 മണിക്ക്",
    submit_problem: "അഭ്യർത്ഥന സമർപ്പിക്കുക",
    problem_submitted_msg: "ഞങ്ങളുടെ ജ്യോതിഷികൾ ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും."
  },
  tcy: {

    brand_name: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್",
    brand_tagline: "ಪ್ರಾಚೀನ ಜ್ಞಾನ, ಆಧುನಿಕ ತರ್ಕ",
    tagline: "ಜ್ಯೋತಿಷ್ಯ ಬೊಕ್ಕ ತರ್ಕದ ಸಂಗಮ",
    horoscope: "ಜಾತಕ",
    matching: "ಪೊಂದಾಣಿಕೆ",
    daily: "ದಿನ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    chat: "ಚರ್ಚೆ",
    prashna: "ಪ್ರಶ್ನೆ",
    menu_details: "ಜಾತಕ ವಿವರ",
    menu_timeline: "ಜೀವನ ಕಾಲಕ್ರಮ (ಪಿರವುದ, ಇತ್ತೆದ, ಬರ್ಪಿನ)",
    menu_hora: "ಹೋರಾ ವಿಶ್ಲೇಷಣೆ",
    menu_sphta: "ಗ್ರಹಸ್ಫುಟ",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಕುಂಡಲಿ",
    menu_sandhi: "ಭಾವ-ಸಂಧಿ",
    menu_panchangam: "ಪಂಚಾಂಗ",
    menu_dasha: "ದಶಾ-ಭುಕ್ತಿ",
    menu_shadvarga: "ಷಡ್ವರ್ಗ",
    menu_ashtaka: "ಅಷ್ಟಕವರ್ಗ",
    menu_trisputa: "ತ್ರಿಸ್ಫುಟಾದಿ",
    menu_dhumadi: "ಧೂಮಾದಿ",
    back: "ಪಿರ",
    submit: "ಜಾತಕ ಮಲ್ಪುಲೆ",
    quick_profile: "ತ್ವರಿತ ಪ್ರೊಫೈಲ್",
    enter_details_wisdom: "ವೈಯಕ್ತಿಕ ಜ್ಞಾನಗಾದ್ ವಿವರಲೆನ್ ಕೊರ್ಲೆ",
    save_continue: "ಒರಿಪಾಲೆ ಬೊಕ್ಕ ದುಂಬು ಪೋಲೆ",
    skip_for_now: "ಇತ್ತೆಗ್ ಬುಡ್ಲೆ",
    lang_select: "ಬಾಸೆ",
    save_profile: "ಪ್ರೊಫೈಲ್ ಒರಿಪಾಲೆ",
    saved_profiles: "ಇತ್ತೀಚಿನ ಜಾತಕಲು",
    matching_title: "ಜಾತಕ ಪೊಂದಾಣಿಕೆ",
    conclusion: "ದೈವಿಕ ತೀರ್ಪು",
    select_rasi: "ರಾಶಿ ಆಯ್ದುಕೊಳೆ",
    daily_title: "ಇತ್ತೆದ ಭವಿಷ್ಯ",
    muhurta_title: "ಎಡ್ಡೆ ಮುಹೂರ್ತಲು",
    muhurta_select: "ಉದ್ದೇಶ ಆಯ್ದುಕೊಳೆ",
    search_city_placeholder: "ಊರು ನಾಡ್ಲೆ...",
    muhurta_search_placeholder: "ಉದ್ದೇಶ ನಾಡ್ಲೆ...",
    prashna_placeholder: "ನಕ್ಷತ್ರಲೆಗ್ ನಿಮ್ಮ ಗಹನವಾಯಿನ ಪ್ರಶ್ನೆ ದಾದ?",
    guruji_listening: "ಗುರೂಜಿ ಕೇನೊಂದುಲ್ಲೆರ್...",
    connection_interrupted: "ಸಂಪರ್ಕ ಕಡಿತ ಆಂಡ್",
    disconnected: "ಸಂಪರ್ಕ ಕಡಿತ ಆಂಡ್",
    support_guruji: "ಗುರೂಜಿಗ್ ಬೆಂಬಲ ಕೊರ್ಲೆ",
    scan_to_support: "ಬೆಂಬಲ ಕೊರಿಯೆರೆ ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ",
    scan_to_donate: "GPay / UPI ಮುಖಾಂತರ ದೇಣಿಗೆ ಕೊರ್ಲೆ",
    support_mission: "ನಮ್ಮ ಧ್ಯೇಯಗ್ ಬೆಂಬಲ ಕೊರ್ಲೆ",
    support_quote: "“ಈರ್ ಇತ್ತೆ ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ಒಳನೋಟನ್ ಪಡೆದರ್. ಉಂದು ಇರೆಗ್ ಇಷ್ಟ ಆಂಡ, ಎಲ್ಯ ಕೊಡುಗೆದೊಟ್ಟುಗು ನಮ್ಮನ್ ಬೆಂಬಲಿಸವೊಲಿ.”",
    secure: "ಸುರಕ್ಷಿತ",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಬೆಂಬಲ",
    next_page: "ಮುಂದಿನ ಪುಟ",
    save_info: "ಮಾಹಿತಿ ಒರಿಪಾಲೆ",
    saved_profiles_title: "ಒರಿಪಾಯಿನ ಪ್ರೊಫೈಲ್ಲು",
    celestial_map: "ರಾಶಿ ಕುಂಡಲಿ",
    stars_obscured: "ನಕ್ಷತ್ರಲು ಮೋಡೊಡು ಮರೆಯಾತುಂಡು. ದಯವಿಟ್ಟು ಪಿರ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ.",
    go_back: "ಪಿರ ಪೋಲೆ",
    dismiss: "ದೂರ ಮಲ್ಪುಲೆ",
    select_city_warning: "⚠️ ನಿಖರವಾಯಿನ ಲೆಕ್ಕಾಚಾರಗಾದ್ ದಯವಿಟ್ಟು ಪಟ್ಟಿಡ್ದ್ ಪೇಂಟೆನ್ ಆಯ್ದುಕೊಳೆ.",
    guruji: "ಗುರೂಜಿ",
    home: "ಇಲ್ಲ",
    daily_nav: "ದಿನೋಲದ",
    oracle_nav: "ದೈವವಾಣಿ",
    chat_nav: "ಪದಿನೆ",
    donate_support: "ಸಹಾಯ ಬೊಕ್ಕ ಬೆಂಬಲ",
    next_analysis: "ದುಂಬು: ವಿಶ್ಲೇಷಣೆ ಆಯ್ದುಕೊಳೆ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪರತ್ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    my_character: "ಎನ್ನ ವ್ಯಕ್ತಿತ್ವ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    siddhantic_precision: "ಸಿದ್ಧಾಂತಿಕ ನಿಖರತೆ",
    personal_guidance: "ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನ",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಅಂಗಾರಕ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೇತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    calculating_heavens: "ಆಕಾಶದ ಲೆಕ್ಕಾಚಾರ ನಡತೊಂದುಂಡು...",
    ask_help_guruji: "ಗುರೂಜಿನ ಸಹಾಯ ಕೇನ್ಲೆ",
    sacred_conversation: "ಒಂಜಿ ಪವಿತ್ರ ಸಂಭಾಷಣೆ",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    life_path: "ಜೀವನ ಸಾದಿ",
    timeline: "ಕಾಲಕ್ರಮ",
    siddhantic: "ಸಿದ್ಧಾಂತ",
    today_panchanga: "ಇತ್ತೆದ ಪಂಚಾಂಗ",
    life_phase: "ಜೀವನ ಹಂತ",
    wealth_health: "ಸಂಪತ್ತು ಬೊಕ್ಕ ಆರೋಗ್ಯ",
    soul_map: "ಆತ್ಮದ ನಕ್ಷೆ",
    planetary_power: "ಗ್ರಹಲೆನ ಶಕ್ತಿ",
    energy_strength: "ಶಕ್ತಿದ ಸಾಮರ್ಥ್ಯ",
    power_score: "ಶಕ್ತಿದ ಅಂಕ",
    under_construction: "ಈ ದೈವಿಕ ಸಾದಿ ನಿರ್ಮಾಣ ಹಂತಡುಂಡು.",
    return_home: "ಇಲ್ಲಗ್ ಪಿರ ಪೋಲೆ",
    get_verdict: "ತೀರ್ಪು ಪಡೆಲೆ",
    latitude: "ಅಕ್ಷಾಂಶ",
    longitude: "ರೇಖಾಂಶ",
    timezone: "ಸಮಯ ವಲಯ",
    enter_full_name: "ಪೂರ್ಣ ಪುದರ್ ಬರೆಲೆ",
    birth_date: "ಪುಟ್ಟಿನ ದಿನಾಂಕ",
    birth_time: "ಪುಟ್ಟಿನ ಸಮಯ",
    birth_location: "ಪುಟ್ಟಿನ ಜಾಗೆ",
    suggestion_title: "ಸಲಹೆಲು",
    suggestion_desc: "ನಿಮ್ಮ ಅನುಭವನ್ ಸುಧಾರಿಸಯೆರೆ ಗುರೂಜಿಗ್ ಸಹಾಯ ಮಲ್ಪುಲೆ",
    suggestion_placeholder: "ನಿಮ್ಮ ಅನಿಸಿಕೆಲೆನ್ ಅಥವಾ समस्याಲೆನ್ ಮುಲ್ಪ ಪಟ್ಟೊಳೆ...",
    suggestion_send: "ಸಲಹೆ ಕಡಪುಡ್ಲೆ",
    suggestion_sent: "ಗುರೂಜಿಗ್ ಕಡಪುಡ್ದುಂಡು",
    panchanga_title: "ಪಂಚಾಂಗ",
    custom_panchanga: "ದಿನಾಂಕ ಬೊಕ್ಕ ಜಾಗೆ ಆಯ್ದುಕೊಳೆ",
    timeline_title: "ಜೀವನ ಕಾಲಕ್ರಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    contact_astrologer_title: "ದೈವಜ್ಞೆರೆಗ್ ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    contact_astrologer_desc: "ತಾಂಬೂಲ ಸಮರ್ಪಣೆದ ಮುಖಾಂತರ ದೈವಿಕ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯುನ ಪವಿತ್ರ ವಿಧಿ",
    problem_label: "ನಿಮ್ಮ ಸಮಸ್ಯೆನ್ ವಿವರಿಸಲೆ",
    problem_placeholder: "ಉದಾ: ಉದ್ಯೋಗದ ಏಳಿಗೆ, ಆರೋಗ್ಯದ ಸಮಸ್ಯೆಲು...",
    contact_time_label: "ಸಂಪರ್ಕ ಮಲ್ಪೆರೆ ಎಡ್ಡೆ ಸಮಯ",
    contact_time_placeholder: "ಉದಾ: ಎಲ್ಲೆ ಕಾಂಡೆ 10 ಗಂಟೆಗ್",
    submit_problem: "ವಿನಂತಿನ್ ಸಲ್ಲಿಸಲೆ",
    problem_submitted_msg: "ನಮ್ಮ ಜ್ಯೋತಿಷಿಲು ಬೇಗನೆ ನಿಮ್ಮನ್ ಸಂಪರ್ಕ ಮಲ್ಪುವೆರ್.",
    mangala_dosha: "ಮಂಗಳ ದೋಷ",
    conclusion_title: "ಒಂಜಿ ಸಾಲಿದ ತೀರ್ಮಾನ",
    remedy_options_title: "ಪರಿಹಾರದ ಸಾದಿನ್ ಆಯ್ದುಕೊಳೆ"
  },
  kok: {

    tagline: "ಜಂಯ್ ಜ್ಯೋತಿಷ್ಯ ಆನಿ ತರ್ಕ ಮೆಳ್ತಾ",
    horoscope: "ಜಾತಕ",
    matching: "ಗುಣಮೇಲನ",
    daily: "ದಿನಾಚೆಂ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    chat: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    prashna: "ಪ್ರಶ್ನ",
    menu_details: "ಜನ್ಮ ವಿಶ್ಲೇಷಣ",
    menu_timeline: "ಜೀವನ ಕಾಲಕ್ರಮ (ಫಾಟ್ಲೊ, ಆತಾಂಚೊ, ಫುಡಾರಾಂಚೊ)",
    menu_hora: "ಹೋರಾ ವಿಶ್ಲೇಷಣ",
    menu_sphta: "ಗ್ರಹಾಂಚೆ ಅಂಶ",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಚಲಿತ",
    menu_sandhi: "ಸಂಧಿ ವಿಶ್ಲೇಷಣ",
    menu_panchangam: "ಪಂಚಾಂಗ",
    menu_dasha: "ವಿಂಶೋತ್ತರಿ ದಶಾ",
    menu_shadvarga: "ಷಡ್ವರ್ಗ ಬಲ",
    menu_ashtaka: "ಅಷ್ಟಕವರ್ಗ",
    menu_trisputa: "ತ್ರಿಸ್ಫುಟ ವಿಶ್ಲೇಷಣ",
    menu_dhumadi: "ಧೂಮಾದಿ ಪಂಗಡ",
    back: "ಪಿರ",
    submit: "ಜಾತಕ ತಯಾರ್ ಕರಾ",
    quick_profile: "ತ್ವರಿತ ಪ್ರೊಫೈಲ್",
    enter_details_wisdom: "ವೈಯಕ್ತಿಕ ಜ್ಞಾನಾ ಖಾತಿರ್ ವಿವರ ನಮೂದ ಕರಾ",
    save_continue: "ಸಾಂಬಾಳಾ ಆನಿ ಮುಖಾರ್ ವಚಾ",
    skip_for_now: "ಆತಾಂಚ್ಯಾಕ್ ಸೊಡಾ",
    lang_select: "ಭಾಸ್",
    save_profile: "ಪ್ರೊಫೈಲ್ ಸಾಂಬಾಳಾ",
    saved_profiles: "ಹಾಲಿಂಚಿಂ ಜಾತಕಾಂ",
    matching_title: "ಗುಣಮೇಲನ ಆನಿ ಸುಸಂಗತತಾ",
    conclusion: "ದೈವಿ ನಿರ್ಣಯ",
    select_rasi: "ರಾಶಿ ವಿಂಚಾ",
    daily_title: "ಆಯಿಚೆಂ ರಾಶಿಭವಿಷ್ಯ",
    muhurta_title: "ಬರೆ ಮುಹೂರ್ತ",
    muhurta_select: "ಉದ್ದೇಶ ವಿಂಚಾ",
    search_city_placeholder: "ಶಹರ್ ಸೊಧಾ...",
    muhurta_search_placeholder: "ಉದ್ದೇಶ ಸೊಧಾ...",
    prashna_placeholder: "ನಕ್ಷತ್ರಾಂ ಖಾತಿರ್ ತುಜೊ ಗಹನ್ ಪ್ರಶ್ನ್ ಕಿತೆಂ?",
    guruji_listening: "ಗುರೂಜಿ ಆಯ್ಕೊನ್ ಆಸಾತ್...",
    connection_interrupted: "ಸಂಪರ್ಕ್ ತುಟ್ಲೊ",
    disconnected: "ಸಂಪರ್ಕ್ ತುಟ್ಲೊ",
    support_guruji: "ಗುರೂಜಿಕ್ ಪಾಟಿಂಬೊ ದಿಯಾ",
    scan_to_support: "ಪಾಟಿಂಬೊ ದೀಂವ್ಕ್ ಸ್ಕ್ಯಾನ್ ಕರಾ",
    scan_to_donate: "GPay / UPI ದ್ವಾರಿಂ ದಾನ್ ಕರಾ",
    support_mission: "ಆಮ್ಚ್ಯಾ ಕಾರ್ಯಾಕ್ ಪಾಟಿಂಬೊ ದಿಯಾ",
    support_quote: "“ತುಕಾ ಆತಾಂಚ್ ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ಸಲೊ ಮೆಳ್ಳಾ. ಜರ್ ತೊ ತುಕಾ ಆವಡ್ಲೊ ಜಾಲ್ಯಾರ್, ತುಂ ಆಮ್ಕಾಂ ಎಕಾ ಲ್ಹಾನ್ ದೇಣಿಗೆ ದ್ವಾರಿಂ ಪಾಟಿಂಬೊ ದೀಂವ್ಕ್ ಶಕ್ತಾಯ್.”",
    secure: "ಸುರಕ್ಷಿತ್",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಪಾಟಿಂಬೊ",
    next_page: "ಮುಕ್ಲೆಂ ಪಾನ್",
    save_info: "ಮಾಹಿತಿ ಸಾಂಬಾಳಾ",
    saved_profiles_title: "ಸಾಂಬಾಳ್ಳೆಲೆ ಪ್ರೊಫೈಲ್",
    celestial_map: "ರಾಶಿ ಕುಂಡಲಿ",
    stars_obscured: "ಕುಪಾಂಕ್ ಲಾಗೊನ್ ನಕ್ಷತ್ರಾಂ ದಿಸನಾಂತ್. ದಯಾ ಕರುನ್ ಪರತ್ ಪ್ರಯತ್ನ ಕರಾ.",
    go_back: "ಪಾಟಿಂ ವಚಾ",
    dismiss: "ಕಾಡ್ನ್ ಉಡಯಾ",
    select_city_warning: "⚠️ ಸಾರ್ಕ್ಯಾ ಗಣನೆ ಖಾತಿರ್ ದಯಾ ಕರುನ್ ಪಟ್ಟಿಂತ್ಲೆಂ ಶಹರ್ ವಿಂಚಾ.",
    guruji: "ಗುರೂಜಿ",
    home: "ಘರ್",
    daily_nav: "ದಿಸ್ಪಟ್ಟೆ",
    oracle_nav: "ದೇವವಾಣಿ",
    chat_nav: "ಸಂವಾದ",
    donate_support: "ದಾಣಿ ಆನಿ ಆಧಾರ",
    next_analysis: "ಫುಡೆಂ: ವಿಶ್ಲೇಷಣ ವಿಂಚಾ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪುರಾತನ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣ",
    my_character: "ಮ್ಹಜೆಂ ವ್ಯಕ್ತಿತ್ವ",
    timeline: "ಕಾಲಕ್ರಮ",
    life_path: "ಜೀವನ ವಾಟ್",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    wealth_health: "ಸಂಪತ್ತಿ ಆನಿ ಭಲಾಯ್ಕಿ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    soul_map: "ಆತ್ಮ್ಯಾಚೊ ನಕಾಶೊ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    life_phase: "ಜೀವನ ಹಂತ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    power_score: "ಶಕ್ತಿ ಸ್ಕೋರ್",
    siddhantic_precision: "ಸಿದ್ಧಾಂತಿಕ ನಿಖರತೆ",
    personal_guidance: "ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನ",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಮಂಗಳ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೇತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    suggestion_title: "ಸೂಚನಾ",
    suggestion_desc: "ತುಜೊ ಅನ್ಭವ್ ಸುಧಾರಂವ್ಕ್ ಗುರೂಜಿಕ್ ಮಜತ್ ಕರ್",
    suggestion_placeholder: "ತುಜೆ ವಿಚಾರಾಂ ವಾಂಟುನ್ ಘೆ ಅಥವಾ ಏಕಾದಿ ಸಮಸ್ಯೆ ವರದಿ ಕರ್...",
    suggestion_send: "ಸೂಚನಾ ಧಾಡ್",
    suggestion_sent: "ಗುರೂಜಿಕ್ ಧಾಡ್ಲಾಂ",
    panchanga_title: "ಪಂಚಾಂಗ",
    today_panchanga: "ಆಜ್ಚೆಂ ಪಂಚಾಂಗ",
    custom_panchanga: "ದಿನಾಂಕ್ ಆನಿ ಜಾಗೊ ವಿಂಚಾ",
    timeline_title: "ಜೀವನ ಕಾಲಕ್ರಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    contact_astrologer_title: "ಜ್ಯೋತಿಷಿಂಕ್ ಸಂಪರ್ಕ್ ಕರ್",
    contact_astrologer_desc: "ಆಮ್ಚ್ಯಾ ತಜ್ಞಾಂಕಡ್ಲ್ಯಾನ್ ವೈಯಕ್ತಿಕ ಪರಿಹಾರ್ ಘೆ",
    problem_label: "ತುಜಿ ಸಮಸ್ಯೆ ವಿವರುನ್ ಸಾಂಗ್",
    problem_placeholder: "ಉದಾ: ವೃತ್ತಿ ವಾಡಾವಳ್, ಭಲಾಯ್ಕಿ ಸಮಸ್ಯೆ...",
    contact_time_label: "ಸಂಪರ್ಕ್ ಕರುಂಕ್ ಬರಿ ವೇಳ್",
    contact_time_placeholder: "ಉದಾ: ಫಾಲ್ಯಾಂ ಸಕಾಳಿಂ 10 ವರಾರ್",
    submit_problem: "ವಿನಂತಿ ಸಾದರ್ ಕರ್",
    problem_submitted_msg: "ಆಮ್ಚೆ ಜ್ಯೋತಿಷಿ ವೆಗಿಂಚ್ ತುಕಾ ಸಂಪರ್ಕ್ ಕರ್ತಲೆ."
  },
  gu: {

    tagline: "જ્યાં જ્યોતિષ અને તર્કનો મેળાપ થાય છે",
    horoscope: "કુંડળી",
    matching: "ગુણ મિલન",
    daily: "દૈનિક રાશિફળ",
    muhurta: "મુહૂર્ત",
    chat: "એસ્ટ્રો ચેટ",
    prashna: "પ્રશ્ન",
    menu_details: "જન્મ વિશ્લેષણ",
    menu_timeline: "જીવન કાલક્રમ (ભૂત, વર્તમાન, ભવિષ્ય)",
    menu_hora: "શાસ્ત્રીય હોરા વિશ્લેષણ",
    menu_sphta: "ગ્રહોના અંશ",
    menu_rasi: "રાશિ કુંડળી",
    menu_navamsha: "નવાંશ કુંડળી",
    menu_bhava: "ભાવ ચલિત",
    menu_sandhi: "સંધિ વિશ્લેષણ",
    menu_panchangam: "પંચાંગ",
    menu_dasha: "વિંશોત્તરી દશા",
    menu_shadvarga: "ષડ્વર્ગ બળ",
    menu_ashtaka: "અષ્ટકવર્ગ",
    menu_trisputa: "ત્રિસ્ફુટ વિશ્લેષણ",
    menu_dhumadi: "ધૂમાદિ સમૂહ",
    back: "પાછા",
    submit: "કુંડળી બનાવો",
    quick_profile: "ઝડપી પ્રોફાઇલ",
    enter_details_wisdom: "વ્યક્તિગત જ્ઞાન માટે વિગતો દાખલ કરો",
    save_continue: "સાચવો અને ચાલુ રાખો",
    skip_for_now: "હમણાં માટે છોડી દો",
    lang_select: "ભાષા",
    save_profile: "પ્રોફાઇલ સાચવો",
    saved_profiles: "તાજેતરની કુંડળી",
    matching_title: "ગુણ મિલન અને સુસંગતતા",
    conclusion: "દૈવી નિર્ણય",
    select_rasi: "રાશિ પસંદ કરો",
    daily_title: "આજનું રાશિફળ",
    muhurta_title: "શુભ મુહૂર્ત",
    muhurta_select: "ઉદ્દેશ્ય પસંદ કરો",
    search_city_placeholder: "શહેર શોધો...",
    muhurta_search_placeholder: "ઉદ્દેશ્ય શોધો...",
    prashna_placeholder: "તારાઓ માટે તમારો ગહન પ્રશ્ન શું છે?",
    guruji_listening: "ગુરુજી સાંભળી રહ્યા છે...",
    connection_interrupted: "સંપર્ક તૂટી ગયો",
    disconnected: "સંપર્ક તૂટી ગયો",
    support_guruji: "ગુરુજીને ટેકો આપો",
    scan_to_support: "ટેકો આપવા માટે સ્કેન કરો",
    scan_to_donate: "GPay / UPI દ્વારા દાન કરો",
    support_mission: "અમારા મિશનને ટેકો આપો",
    support_quote: "“તમને હમણાં જ વ્યક્તિગત જ્યોતિષીય આંતરદૃષ્ટિ મળી છે. જો તમને તે ગમી હોય, તો તમે નાના યોગદાન સાથે અમને ટેકો આપી શકો છો.”",
    secure: "સુરક્ષિત",
    spiritual: "આધ્યાત્મિક",
    support: "ટેકો",
    next_page: "આગળનું પૃષ્ઠ",
    save_info: "માહિતી સાચવો",
    saved_profiles_title: "સાચવેલ પ્રોફાઇલ્સ",
    celestial_map: "રાશિ કુંડળી",
    stars_obscured: "વાદળોને કારણે તારાઓ દેખાતા નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
    go_back: "પાછા જાઓ",
    dismiss: "દૂર કરો",
    select_city_warning: "⚠️ ચોક્કસ ગણતરી માટે કૃપા કરીને સૂચિમાંથી શહેર પસંદ કરો.",
    guruji: "ગુરુજી",
    home: "હોમ",
    daily_nav: "દૈનિક",
    oracle_nav: "દેવવાણી",
    chat_nav: "સંવાદ",
    donate_support: "દાન અને સમર્થન",
    next_analysis: "આગળ: વિશ્લેષણ પસંદ કરો",
    sacred_geometry: "પવિત્ર ભૂમિતિ • પ્રાચીન તર્ક",
    birth_analysis: "જન્મ વિશ્લેષણ",
    my_character: "મારું વ્યક્તિત્વ",
    timeline: "કાલક્રમ",
    life_path: "જીવન પથ",
    shastriya: "શાસ્ત્રીય",
    wealth_health: "ધન અને સ્વાસ્થ્ય",
    rasi_kundli: "રાશિ કુંડળી",
    soul_map: "આત્માનો નકશો",
    vimshottari: "વિંશોત્તરી",
    life_phase: "જીવન તબક્કો",
    ashtakavarga: "અષ્ટકવર્ગ",
    power_score: "શક્તિ સ્કોર",
    brand_name: "એસ્ટ્રો લોજિક",
    siddhantic_precision: "સિદ્ધાંતિક ચોકસાઈ",
    personal_guidance: "વ્યક્તિગત માર્ગદર્શન",
    planet_sun: "સૂર્ય",
    planet_moon: "ચંદ્ર",
    planet_mars: "મંગળ",
    planet_mercury: "બુધ",
    planet_jupiter: "ગુરુ",
    planet_venus: "શુક્ર",
    planet_saturn: "શનિ",
    planet_rahu: "રાહુ",
    planet_ketu: "કેતુ",
    planet_lagna: "લગ્ન",
    planet_mandi: "માંદી",
    rasi_mesha: "મેષ",
    rasi_vrishabha: "વૃષભ",
    rasi_mithuna: "મિથુન",
    rasi_karka: "કર્ક",
    rasi_simha: "સિંહ",
    rasi_kanya: "કન્યા",
    rasi_tula: "તુલા",
    rasi_vrishchika: "વૃશ્ચિક",
    rasi_dhanu: "ધનુ",
    rasi_makara: "મકર",
    rasi_kumbha: "કુંભ",
    rasi_meena: "મીન",
    seeker: "સીકર",
    scholar: "સ્કોલર",
    suggestion_title: "સૂચનો",
    suggestion_desc: "તમારા અનુભવને સુધારવામાં ગુરુજીને મદદ કરો",
    suggestion_placeholder: "તમારા વિચારો શેર કરો અથવા સમસ્યાની જાણ કરો...",
    suggestion_send: "સૂચન મોકલો",
    suggestion_sent: "ગુરુજીને મોકલવામાં આવ્યું",
    panchanga_title: "પંચાંગ",
    today_panchanga: "આજનું પંચાંગ",
    custom_panchanga: "તારીખ અને સ્થળ પસંદ કરો",
    timeline_title: "જીવન સમયરેખા ડેશબોર્ડ",
    contact_astrologer_title: "જ્યોતિષીઓનો સંપર્ક કરો",
    contact_astrologer_desc: "અમારા નિષ્ણાતો પાસેથી વ્યક્તિગત ઉપાયો મેળવો",
    problem_label: "તમારી સમસ્યાનું વર્ણન કરો",
    problem_placeholder: "દા.ત. કારકિર્દી વૃદ્ધિ, આરોગ્ય સમસ્યાઓ...",
    contact_time_label: "સંપર્ક કરવા માટેનો પસંદગીનો સમય",
    contact_time_placeholder: "દા.ત. આવતીકાલે સવારે 10 વાગ્યે",
    submit_problem: "વિનંતી સબમિટ કરો",
    problem_submitted_msg: "અમારા જ્યોતિષીઓ ટૂંક સમયમાં તમારો સંપર્ક કરશે."
  },
};