import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const ta_full = {
    brand_name: "ஆஸ்ட்ரோ லாஜிக்",
    tagline: "பண்டைய அறிவியலும் நவீன தர்க்கமும் இணையும் இடம்",
    begin_journey: "பயணத்தைத் தொடங்குங்கள்",
    choose_path: "உங்கள் பாதையைத் தேர்ந்தெடுக்கவும்",
    disclaimer: "ஜோதிட கணிப்புகள் கிரக நிலைகளை அடிப்படையாகக் கொண்டவை. இவை ஒரு வழிகாட்டுதலே தவிர, உறுதிப்படுத்தப்பட்ட முடிவுகள் அல்ல.",
    planetary_transit_in: "ல்",
    horoscope: "ஜாதகம்",
    matching: "பொருத்தம்",
    life_partner: "வாழ்க்கைத் துணை",
    daily: "தினசரி ராசிபலன்",
    muhurta: "முகூர்த்தம்",
    numerology: "எண்கணிதம்",
    chat: "ஆஸ்ட்ரோ சாட்",
    prashna: "பிரசன்னம்",
    guruji: "குருஜி",
    you: "நீங்கள்",
    guruji_welcome: "உங்கள் வாழ்க்கை பாதை, கிரக பெயர்ச்சிகள் அல்லது ஆன்மீக வழிகாட்டுதல் பற்றி குருஜியிடம் கேளுங்கள்.",
    guruji_thinking: "குருஜி கிரகங்களை கணித்துக்கொண்டிருக்கிறார்...",
    error_guruji: "தொடர்பு துண்டிக்கப்பட்டது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
    ask_guruji_placeholder: "குருஜியிடம் உங்கள் கேள்வியைக் கேளுங்கள்...",
    switch_mode: "பயன்முறையை மாற்றவும்",
    menu_details: "பிறப்பு விவரங்கள்",
    menu_timeline: "வாழ்க்கை காலவரிசை (கடந்த காலம், நிகழ் காலம், எதிர்காலம்)",
    menu_hora: "சாஸ்திரிய ஹோரா பகுப்பாய்வு",
    menu_sphta: "கிரக நிலைகள்",
    menu_rasi: "ராசி கட்டம்",
    menu_navamsha: "நவாம்சம் (D9)",
    menu_bhava: "பாவ சலிதம்",
    menu_bhava_analysis: "12 பாவங்களின் பகுப்பாய்வு",
    menu_sandhi: "சந்தி பகுப்பாய்வு",
    menu_panchangam: "பஞ்சாங்கம்",
    menu_dasha: "விம்சோத்தரி தசை",
    menu_shadvarga: "ஷட்வர்கம்",
    shadvarga_strengths: "ஷட்வர்க பலம்",
    shadbala_analysis: "ஷட்பல பகுப்பாய்வு",
    energy_strength: "ஆற்றல் பலம்",
    planetary_power: "கிரக பலம்",
    menu_yogas: "யோக பகுப்பாய்வு",
    menu_maitri: "பஞ்சதா கிரக மைத்ரி",
    menu_ashtaka: "அஷ்டகவர்க்கம்",
    menu_trisputa: "திரிஸ்புட பகுப்பாய்வு",
    menu_dhumadi: "தூமாதி கிரகங்கள்",
    menu_basic_details: "அடிப்படை பிறப்பு விவரங்கள்",
    menu_yoga: "யோகங்கள்",
    menu_career: "தொழில் மற்றும் வெற்றி",
    menu_health: "ஆரோக்கியம் மற்றும் ஆற்றல்",
    menu_money: "செல்வம் மற்றும் நிதி",
    menu_transit: "கிரக பெயர்ச்சிகள்",
    menu_dasha_effect: "தசா பலன்கள்",
    menu_sade_sati: "ஏழரை சனி பகுப்பாய்வு",
    menu_gemstones: "ராசிக்கற்கள் மற்றும் ருத்ராட்சம்",
    menu_nakshatra: "நட்சத்திர ரகசியங்கள்",
    menu_doshas: "தோஷ பரிசோதனை (காலசர்ப்பம்/பித்ரு)",
    menu_character: "குணம் மற்றும் ஆளுமை",
    menu_numerology: "எண்கணித பகுப்பாய்வு",
    back: "பின்புறம்",
    submit: "ஜாதகத்தை உருவாக்கு",
    quick_profile: "விரைவான சுயவிவரம்",
    enter_details_wisdom: "விவரங்களை உள்ளிடவும்",
    save_continue: "சேமித்து தொடரவும்",
    continue: "தொடரவும் ➔",
    next_choose_analysis: "அடுத்து: பகுப்பாய்வைத் தேர்ந்தெடுக்கவும் ➔",
    skip_for_now: "இப்போது தவிர்க்கவும்",
    lang_select: "மொழி",
    loshu_grid: "லோஷு கிரிட்",
    full_name: "முழு பெயர்",
    classical_predictions: "சாஸ்திரிய கணிப்புகள்",
    sacred_guide: "புனித வழிகாட்டி",
    seeker_scholar_desc: "எளிய வாழ்க்கை வழிகாட்டுதலுக்கு 'சீக்கர்' என்பதைத் தேர்ந்தெடுக்கவும். ஆழமான ஜோதிட விவரங்களுக்கு 'ஸ்காலர்' என்பதைத் தேர்ந்தெடுக்கவும்.",
    save_profile: "சுயவிவரத்தைச் சேமி",
    saved_profiles: "சமீபத்திய ஜாதகங்கள்",
    matching_title: "திருமண பொருத்த பலன்கள்",
    conclusion: "முடிவு",
    select_rasi: "ராசியைத் தேர்ந்தெடுக்கவும்",
    daily_title: "இன்றைய கிரக ஓட்டம்",
    muhurta_title: "சுப முகூர்த்த நேரங்கள்",
    muhurta_select: "நோக்கத்தைத் தேர்ந்தெடுக்கவும்",
    sacred_intake: "தகவல் உள்ளீடு",
    partner_one: "முதல் நபர்",
    partner_two: "இரண்டாம் நபர்",
    birth_location: "பிறந்த இடம்",
    timeframe: "கால அளவு",
    location: "இடம்",
    quick_search: "விரைவான தேடல்",
    oracle: "ஆரக்கிள்",
    name: "பெயர்",
    date: "தேதி",
    nakshatra: "நட்சத்திரம்",
    ask_guruji: "குருஜியிடம் கேளுங்கள்",
    deep_inquiry: "ஆழ்ந்த விசாரணை",
    seek_answer: "பதிலைத் தேடுங்கள்",
    name_of_soul: "பெயர்",
    birth_date: "பிறந்த தேதி",
    birth_time: "பிறந்த நேரம்",
    gender: "பாலினம்",
    male: "ஆண்",
    female: "பெண்",
    other: "இதர",
    search_city_placeholder: "நகரத்தைத் தேடுங்கள்...",
    muhurta_search_placeholder: "தேவையைத் தேடுங்கள்...",
    prashna_placeholder: "உங்கள் ஆழ்ந்த கேள்வி என்ன?",
    guruji_listening: "குருஜி கவனித்துக் கொண்டிருக்கிறார்...",
    connection_interrupted: "தொடர்பு துண்டிக்கப்பட்டது",
    disconnected: "துண்டிக்கப்பட்டது",
    support_guruji: "குருஜிக்கு ஆதரவு அளிக்கவும்",
    scan_to_support: "ஆதரவு அளிக்க ஸ்கேன் செய்யவும்",
    scan_to_donate: "GPay / UPI மூலம் நன்கொடை அளிக்க ஸ்கேன் செய்யவும்",
    support_mission: "எங்கள் பணிக்கு ஆதரவு அளிக்கவும்",
    support_quote: "உங்கள் வாழ்க்கைக்கான ஜோதிட வழிகாட்டுதலைப் பெற்றுள்ளீர்கள். இது உங்களுக்குப் பயனுள்ளதாக இருந்தால், எங்களை ஆதரிக்கலாம்.",
    csr_title: "ஆஸ்ட்ரோ லாஜிக் சமூக பாதிப்பு",
    csr_books_title: "சிறப்பு குழந்தைகளுக்கான கல்வி அதிகாரமளித்தல்",
    csr_books_desc: "எங்கள் வருமானத்தில் 90% சிறப்பு குழந்தைகளின் கல்விக்காகச் செலவிடப்படுகிறது.",
    csr_oldage_title: "முதியோருக்கான கண்ணியமான பராமரிப்பு",
    csr_oldage_desc: "ஆதரவற்ற முதியோர்களுக்குத் தரமான உணவு மற்றும் மருத்துவ வசதிகளை வழங்குகிறோம்.",
    secure: "பாதுகாப்பானது",
    spiritual: "ஆன்மீகம்",
    support: "ஆதரவு",
    next_page: "அடுத்த பக்கம்",
    save_info: "தகவலைச் சேமி",
    saved_profiles_title: "சேமிக்கப்பட்ட சுயவிவரங்கள்",
    celestial_map: "வான வரைபடம் (ராசி)",
    stars_obscured: "மேகங்களால் கிரகங்கள் மறைக்கப்பட்டுள்ளன. மீண்டும் முயற்சிக்கவும்.",
    go_back: "பின்புறம் செல்லவும்",
    dismiss: "நீக்கவும்",
    select_city_warning: "⚠️ துல்லியமான கணிப்புக்கு நகரத்தைத் தேர்ந்தெடுக்கவும்.",
    search_assistant_placeholder: "உதாரணம்: 2024 குரு பெயர்ச்சி பலன்கள்",
    enter_full_name: "முழு பெயரை உள்ளிடவும்",
    feedback: "கருத்து மற்றும் பரிந்துரைகள்",
    feedback_title: "உங்கள் கருத்துக்கள் மற்றும் பரிந்துரைகள்",
    feedback_placeholder: "உங்கள் அனுபவத்தைப் பகிரவும்...",
    submit_feedback: "அனுப்புக",
    feedback_success: "உங்கள் கருத்துக்கு நன்றி!",
    first_name: "முதல் பெயர்",
    second_name: "இரண்டாம் பெயர்",
    timeframe_placeholder: "உதாரணம்: அடுத்த 3 மாதங்கள்",
    select_seeker: "சீக்கர்",
    select_scholar: "ஸ்காலர்",
    seeker: "சீக்கர்",
    scholar: "ஸ்காலர்",
    seeker_desc: "எளிமையான வழிகாட்டுதல், தொழில் மற்றும் அன்றாட வாழ்க்கைக்கான எளிய மொழியில் பலன்கள்.",
    scholar_desc: "ஜோதிடர்கள் மற்றும் மாணவர்களுக்காக. ஆழ்ந்த தொழில்நுட்ப விவரங்கள் மற்றும் சமஸ்கிருத ஸ்லோகங்கள்.",
    siddhantic_precision: "ஸ்காலர் பகுதி",
    personal_guidance: "சீக்கர் பகுதி",
    calculating_heavens: "கணிப்புகள் நடைபெறுகின்றன...",
    ask_help_guruji: "குருஜியின் உதவியைக் கேளுங்கள்",
    sacred_conversation: "ஒரு புனித உரையாடல்",
    shastriya: "சாஸ்திரிய",
    life_path: "வாழ்க்கை பாதை",
    timeline: "காலவரிசை",
    siddhantic: "சித்தாந்தம்",
    life_phase: "வாழ்க்கை கட்டம்",
    wealth_health: "செல்வம் மற்றும் ஆரோக்கியம்",
    soul_map: "ஆன்ம வரைபடம்",
    power_score: "பலத்தின் மதிப்பெண்",
    under_construction: "இந்தப் பகுதி இன்னும் தயாரிப்பில் உள்ளது.",
    return_home: "முகப்பு பக்கத்திற்குச் செல்லவும்",
    get_verdict: "முடிவைப் பெறுங்கள்",
    latitude: "அட்சரேகை",
    longitude: "தீர்க்கரேகை",
    timezone: "நேர மண்டலம்",
    suggestion_title: "பரிந்துரைகள்",
    suggestion_desc: "உங்கள் அனுபவத்தை மேம்படுத்த குருஜிக்கு உதவுங்கள்",
    suggestion_placeholder: "உங்கள் எண்ணங்களைப் பகிரவும்...",
    suggestion_send: "அனுப்புக",
    suggestion_sent: "குருஜிக்கு அனுப்பப்பட்டது",
    panchanga_title: "பஞ்சாங்கம்",
    custom_panchanga: "தேதி மற்றும் இடத்தை மாற்றவும்",
    timeline_title: "வாழ்க்கை காலவரிசை டாஷ்போர்டு",
    contact_astrologer_title: "ஜோதிடரை அணுகவும்",
    contact_astrologer_desc: "தாம்பூலம் சமர்ப்பித்தல்",
    tambula_offering: "தாம்பூல காணிக்கை",
    tambula_desc: "ஜோதிடரை அணுகி வழிகாட்டுதல் பெற தாம்பூலம் மற்றும் தட்சணை சமர்ப்பிக்கவும்.",
    problem_label: "உங்கள் தேவையை விவரிக்கவும்",
    problem_placeholder: "உதாரணம்: தொழில் வளர்ச்சி, ஆரோக்கியம்...",
    contact_time_label: "தொடர்பு கொள்ள வேண்டிய நேரம்",
    contact_time_placeholder: "உதாரணம்: நாளை காலை 10 மணி",
    submit_problem: "அனுப்புக",
    problem_submitted_msg: "எங்கள் ஜோதிடர் விரைவில் உங்களைத் தொடர்புகொள்வார்.",
    mangala_dosha: "செவ்வாய் தோஷம்",
    conclusion_title: "சுருக்கமான முடிவு",
    remedy_options_title: "பரிகார முறையைத் தேர்ந்தெடுக்கவும்",
    tier1_title: "உபாய ஆரம்பம்",
    tier1_price: "₹99",
    tier1_meaning: "தொடக்க பரிகாரங்கள்",
    tier2_title: "சுப மார்க்கம்",
    tier2_price: "₹599",
    tier2_meaning: "திருப்பம் தரும் வழி",
    tier3_title: "சர்வ கர்ம பகுப்பாய்வு",
    tier3_price: "₹999",
    tier3_meaning: "முழுமையான வாழ்க்கை பகுப்பாய்வு",
    pay_now: "பணம் செலுத்தித் தொடரவும்",
    appointment_date: "தேதியைத் தேர்ந்தெடுக்கவும்",
    appointment_time: "நேரத்தைத் தேர்ந்தெடுக்கவும்",
    contact_astrologer_remedies: "பரிகாரங்களுக்கு ஜோதிடரை அணுகவும்",
    analysis_tab_title: "பகுப்பாய்வு",
    matching_tab_title: "பொருத்தம்",
    chat_tab_title: "ஆஸ்ட்ரோ சாட்",
    help: "உதவி",
    footer_text: "தெய்வீக ஆணை • கிரக அமைப்புகள் • ஆழ்ந்த அறிவு",
    celestial_insights_title: "தற்போதைய கிரக நிலைகள்",
    search_assistant_desc: "கிரக பெயர்ச்சிகள் அல்லது ஜோதிட நிகழ்வுகளைத் தேடுங்கள்.",
    searching: "தேடுகிறது...",
    ask_stars: "கிரகங்களிடம் கேளுங்கள்",
    sources: "ஆதாரங்கள்",
    invoke_guruji: "குருஜியை அழையுங்கள்",
    pranama_end: "பிரணாமம் (முடிவு)",
    career_guidance: "தொழில் வழிகாட்டுதல்",
    love_marriage: "காதல் மற்றும் திருமணம்",
    health_energy: "ஆரோக்கியம் மற்றும் ஆற்றல்",
    spiritual_path: "ஆன்மீக பாதை",
    seek_wisdom_message: "ஞானத்தைத் தேடுங்கள், நட்சத்திரங்கள் பதிலளிக்கும்.",
    connecting: "இணைகிறது...",
    dhanyavaada: "தன்யவாதா",
    pranama: "பிரணாமம்",
    path: "பாதை",
    seeker_path: "சீக்கர் பாதை",
    you_hint: "எனக்கு உதவி தேவை ",
    muhurta_vivaha: "திருமணம்",
    muhurta_grihapravesha: "கிருகப்பிரவேசம்",
    muhurta_bhoomi_pooja: "பூமி பூஜை",
    muhurta_upanayana: "உபநயனம் (பூணூல் அணிவித்தல்)",
    muhurta_namakarana: "பெயர் சூட்டுதல்",
    muhurta_annaprashana: "அன்னப்பிராசனம் (முதல் உணவு)",
    muhurta_aksharabhyasa: "அட்சராபியாசம்",
    muhurta_vidyarambha: "பள்ளியில் சேர்த்தல்",
    muhurta_karnavedha: "காது குத்துதல்",
    muhurta_choodakarana: "முடி எடுத்தல்",
    muhurta_seemantham: "சீமந்தம்",
    muhurta_vahana: "வாகனம் வாங்குதல்",
    muhurta_vyapaara: "வியாபாரம் தொடங்குதல்",
    muhurta_shop_opening: "கடை திறப்பு விழா",
    muhurta_udyoga: "வேலையில் சேர",
    muhurta_swarna: "தங்கம் வாங்குதல்",
    muhurta_investments: "முதலீடுகள்",
    muhurta_yaatra: "பயணம்",
    muhurta_videsha: "வெளிநாட்டு பயணம்",
    muhurta_shastra_kriya: "அறுவை சிகிச்சை",
    muhurta_medical_start: "மருத்துவ சிகிச்சை தொடங்க",
    muhurta_abhijit: "அபிஜித் முகூர்த்தம்",
    muhurta_brahma: "பிரம்மா முகூர்த்தம்",
    muhurta_shilaanyasa: "அடிக்கல் நாட்டுதல்",
    muhurta_renting: "வாடகை வீடு மாற",
    muhurta_contracts: "ஒப்பந்தம் கையெழுத்திட",
    muhurta_legal: "நீதிமன்ற விவகாரங்கள்",
    muhurta_agriculture: "விவசாயப் பணிகள்",
    home: "முகப்பு",
    daily_nav: "தினசரி",
    oracle_nav: "ஆரக்கிள்",
    chat_nav: "சாட்",
    donate_support: "நன்கொடை அளிக்கவும்",
    next_analysis: "அடுத்து: பகுப்பாய்வைத் தேர்ந்தெடுக்கவும்",
    sacred_geometry: "புனித வடிவியல்",
    birth_analysis: "பிறப்பு பகுப்பாய்வு",
    my_character: "என் ஆளுமை",
    rasi_kundli: "ராசி கட்டம்",
    vimshottari: "விம்சோத்தரி",
    ashtakavarga: "அஷ்டகவர்க்கம்",
    planet_sun: "சூரியன்",
    planet_moon: "சந்திரன்",
    planet_mars: "செவ்வாய்",
    planet_mercury: "புதன்",
    planet_jupiter: "குரு",
    planet_venus: "சுக்கிரன்",
    planet_saturn: "சனி",
    planet_rahu: "ராகு",
    planet_ketu: "கேது",
    planet_lagna: "லக்னம்",
    planet_mandi: "மாந்தி",
    rasi_mesha: "மேஷம்",
    rasi_vrishabha: "ரிஷபம்",
    rasi_mithuna: "மிதுனம்",
    rasi_karka: "கடகம்",
    rasi_simha: "சிம்மம்",
    rasi_kanya: "கன்னி",
    rasi_tula: "துலாம்",
    rasi_vrishchika: "விருச்சிகம்",
    rasi_dhanu: "தனுசு",
    rasi_makara: "மகரம்",
    rasi_kumbha: "கும்பம்",
    rasi_meena: "மீனம்",
    muhurta_analysis: "முகூர்த்த பகுப்பாய்வு",
    auspicious_time: "சுப நேரம்",
    verdict: "தீர்ப்பு",
    planetary_positions: "கிரக நிலைகள்",
    classical_references: "சாஸ்திரிய மேற்கோள்கள்",
    panchanga_breakdown: "பஞ்சாங்க விவரங்கள்",
    technical_summary: "தொழில்நுட்ப சுருக்கம்",
    saved_readings: "சேமிக்கப்பட்டவை",
    no_readings: "பட்டியல் காலியாக உள்ளது",
    no_readings_desc: "தகவல்களைச் சேமிக்கத் தொடங்குங்கள்.",
    clear_history_confirm: "அனைத்து தகவல்களையும் அழிக்க வேண்டுமா?",
    vastu_title: "வாஸ்து சாஸ்திரம்",
    vastu_desc: "ஆற்றல் மற்றும் வாஸ்து",
    vastu_analysis: "வாஸ்து பகுப்பாய்வு",
    home_harmony: "வீட்டு அமைதி",
    palm_reading_title: "கைரேகை சாஸ்திரம்",
    palm_reading_desc: "கைரேகை கணிப்பு",
    upload_palm: "கைரேகை புகைப்படத்தைப் பதிவேற்றவும்",
    palm_instructions: "கையைச் சமமாக வைத்து புகைப்படம் எடுக்கவும்.",
    analyzing_palm: "கைரேகைகள் ஆராயப்படுகின்றன...",
    palm_analysis_res: "கைரேகை பகுப்பாய்வு",
    camera_access: "கேமரா",
    gallery_access: "கேலரி",
    invalid_palm_error: "புகைப்படம் தெளிவாக இல்லை. மீண்டும் பதிவேற்றவும்.",
    classical_source_authority: "சாஸ்திரிய ஆதாரம்",
    welcome_tour: "வரவேற்கிறோம்",
    welcome_tour_desc: "ஜோதிட உலகிற்கு உங்களை வரவேற்கிறோம்.",
    seeker_mode_active: "சீக்கர் முறை",
    scholar_mode_active: "ஸ்காலர் முறை",
    seeker_tour_desc: "எளிமையான பாதை",
    scholar_tour_desc: "ஆழ்ந்த ஆராய்ச்சி",
    sacred_dashboard: "டாஷ்போர்டு",
    dashboard_tour_desc: "அனைத்தும் ஓரிடத்தில்.",
    guruji_tour: "குருஜியை அணுகவும்",
    guruji_tour_desc: "உங்கள் உதவியாளர்.",
    navigation_tour: "பயணம் தொடரும்",
    nav_tour_desc: "எளிமையான வடிவமைப்பு.",
    save_profile_error: "பெயரை உள்ளிடவும்.",
    profile_saved: "சேமிக்கப்பட்டது.",
    profile_saved_for: "{name} சுயவிவரம் சேமிக்கப்பட்டது.",
    life_partner_analysis: "வாழ்க்கைத்துணை பகுப்பாய்வு",
    prashna_analysis: "பிரசன்ன பகுப்பாய்வு",
    stars_silent: "மீண்டும் முயற்சிக்கவும்.",
    celestial_connection_failed: "தொடர்பு துண்டிக்கப்பட்டது.",
    switch_to_dark: "டார்க் மோட்",
    switch_to_light: "லைட் மோட்",
    blog: "வலைப்பதிவு",
    blog_desc: "கட்டுரைகள்",
    enter_details_warning: "பிறந்த நேரம் மற்றும் தேதியை உள்ளிடவும்.",
    sending: "அனுப்பப்படுகிறது...",
    offline: "ஆஃப்லைன்",
    csr_tagline: "தர்மம் மற்றும் கருணை",
    csr_revenue_committed: "வருவாய் அர்ப்பணிப்பு",
    csr_souls_nourished: "பயனடைந்தவர்கள்",
    csr_verified_integrity: "நேர்மை",
    csr_schools_supported: "பள்ளிகள்",
    csr_kits_distributed: "கிட்கள்",
    csr_volunteer_hours: "நேரம்",
    csr_homes_adopted: "வீடுகள்",
    csr_elders_assisted: "முதியவர்கள்",
    csr_medical_camps: "மருத்துவ முகாம்கள்",
    csr_special_children_initiative: "குழந்தைகளுக்கான திட்டம்",
    csr_elder_care_program: "முதியோர் பராமரிப்பு",
    csr_revenue_committed_90: "90% வருமானம் சமூக சேவைக்காக",
    csr_holistic_care_100: "100% சேவை",
    seeker_mode_desc_short: "சீக்கர் பயன்முறை",
    scholar_mode_desc_short: "ஸ்காலர் பயன்முறை",
    saved_profiles_desc: "சமீபத்தியவை",
    today_panchanga: "இன்றைய பஞ்சாங்கம்"
};

const te_full = {
    brand_name: "ఆస్ట్రో లాజిక్",
    tagline: "పురాతన విజ్ఞానం మరియు ఆధునిక తర్కం",
    begin_journey: "ప్రయాణాన్ని ప్రారంభించండి",
    choose_path: "మీ మార్గాన్ని ఎంచుకోండి",
    disclaimer: "జ్యోతిష్య అంచనాలు గ్రహాల గణనల ఆధారంగా ఉంటాయి. ఇవి ఒక సూచన మాత్రమే, ఖచ్చితమైన ఫలితాలు కాదు.",
    planetary_transit_in: "లో",
    horoscope: "జాతకం",
    matching: "గుణ మేళనం",
    life_partner: "జీవిత భాగస్వామి",
    daily: "దినఫలం",
    muhurta: "ముహూర్తం",
    numerology: "సంఖ్యాశాస్త్రం",
    chat: "ఆస్ట్రో చాట్",
    prashna: "ప్రశ్న",
    guruji: "గురూజీ",
    you: "మీరు",
    guruji_welcome: "మీ జీవిత పథం, గ్రహ సంచారాలు లేదా ఆధ్యాత్మిక మార్గదర్శకత్వం గురించి గురూజీని అడగండి.",
    guruji_thinking: "గురూజీ గ్రహాలను లెక్కిస్తున్నారు...",
    error_guruji: "సంప్రదింపు విచ్ఛిన్నమైంది. కాసేపు ఆగి మళ్ళీ ప్రయత్నించండి.",
    ask_guruji_placeholder: "గురూజీని ప్రశ్నించండి...",
    switch_mode: "మార్గాన్ని మార్చండి",
    menu_details: "జన్మ విశ్లేషణ",
    menu_timeline: "జీవిత కాలక్రమం (గతం, వర్తమానం, భవిష్యత్తు)",
    menu_hora: "శాస్త్రీయ హోరా విశ్లేషణ",
    menu_sphta: "గ్రహ స్థితులు",
    menu_rasi: "రాశి చక్రం",
    menu_navamsha: "నవాంశం (D9)",
    menu_bhava: "భావ చలితం",
    menu_bhava_analysis: "12 భావాల విశ్లేషణ",
    menu_sandhi: "సంధి విశ్లేషణ",
    menu_panchangam: "పంచాంగం",
    menu_dasha: "వింశోత్తరి దశ",
    menu_shadvarga: "షడ్వర్గం",
    shadvarga_strengths: "షడ్వర్గ బలం",
    shadbala_analysis: "షడ్బల విశ్లేషణ",
    energy_strength: "శక్తి బలం",
    planetary_power: "గ్రహ బలం",
    menu_yogas: "యోగ విశ్లేషణ",
    menu_maitri: "పంచధా గ్రహ మైత్రి",
    menu_ashtaka: "అష్టకవర్గం",
    menu_trisputa: "త్రిస్ఫుట విశ్లేషణ",
    menu_dhumadi: "ధూమాది గ్రహాలు",
    menu_basic_details: "ప్రాథమిక జన్మ వివరాలు",
    menu_yoga: "యోగాలు",
    menu_career: "వృత్తి మరియు విజయం",
    menu_health: "ఆరోగ్యం మరియు శక్తి",
    menu_money: "సంపద మరియు ఆర్థికం",
    menu_transit: "గ్రహ సంచారం",
    menu_dasha_effect: "దశా ఫలితాలు",
    menu_sade_sati: "ఏలిననాటి శని విశ్లేషణ",
    menu_gemstones: "రత్నాలు & రుద్రాక్షలు",
    menu_nakshatra: "నక్షత్ర రహస్యాలు",
    menu_doshas: "దోష తనిఖీ (కాలసర్ప/పితృ)",
    menu_character: "గణ మరియు వ్యక్తిత్వం",
    menu_numerology: "సంఖ్యాశాస్త్ర విశ్లేషణ",
    back: "వెనుకకు",
    submit: "జాతకాన్ని తయారు చేయండి",
    quick_profile: "త్వరిత ప్రొఫైల్",
    enter_details_wisdom: "వివరాలను నమోదు చేయండి",
    save_continue: "సేవ్ చేసి కొనసాగండి",
    continue: "కొనసాగండి ➔",
    next_choose_analysis: "తర్వాత: విశ్లేషణను ఎంచుకోండి ➔",
    skip_for_now: "ప్రస్తుతానికి వద్దు",
    lang_select: "భాష",
    loshu_grid: "లోషూ గ్రిడ్",
    full_name: "పూర్తి పేరు",
    classical_predictions: "శాస్త్రీయ అంచనాలు",
    sacred_guide: "పవిత్ర మార్గదర్శి",
    seeker_scholar_desc: "సరళమైన మార్గదర్శకత్వం కోసం 'సీకర్' ఎంచుకోండి. లోతైన జ్యోతిష్య వివరాల కోసం 'స్కాలర్' ఎంచుకోండి.",
    save_profile: "ప్రొఫైల్ సేవ్ చేయండి",
    saved_profiles: "ఇటీవలి జాతకాలు",
    matching_title: "వివాహ పొంతన ఫలితాలు",
    conclusion: "తీర్పు",
    select_rasi: "రాశిని ఎంచుకోండి",
    daily_title: "నేటి గ్రహగతి",
    muhurta_title: "శుభ ముహూర్త సమయాలు",
    muhurta_select: "ప్రయోజనాన్ని ఎంచుకోండి",
    sacred_intake: "సమాచార నమోదు",
    partner_one: "మొదటి వ్యక్తి",
    partner_two: "రెండవ వ్యక్తి",
    birth_location: "జన్మస్థలం",
    timeframe: "సమయం",
    location: "స్థలం",
    quick_search: "త్వరిత వెతుకులాట",
    oracle: "ఒరాకిల్",
    name: "పేరు",
    date: "తేదీ",
    nakshatra: "నక్షత్రం",
    ask_guruji: "గురూజీని అడగండి",
    deep_inquiry: "లోతైన విచారణ",
    seek_answer: "సమాధానం వెతకండి",
    name_of_soul: "పేరు",
    birth_date: "జన్మ తేదీ",
    birth_time: "జన్మ సమయం",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    search_city_placeholder: "నగరాన్ని వెతకండి...",
    muhurta_search_placeholder: "లక్ష్యాన్ని వెతకండి...",
    prashna_placeholder: "మీ లోతైన ప్రశ్న ఏమిటి?",
    guruji_listening: "గురూజీ వింటున్నారు...",
    connection_interrupted: "సంప్రదింపు విచ్ఛిన్నమైంది",
    disconnected: "విచ్ఛిన్నమైంది",
    support_guruji: "గురూజీకి మద్దతు ఇవ్వండి",
    scan_to_support: "మద్దతు కోసం స్కాన్ చేయండి",
    scan_to_donate: "GPay / UPI ద్వారా విరాళం ఇవ్వండి",
    support_mission: "మా మిషన్ కు మద్దతు ఇవ్వండి",
    support_quote: "మీరు ఇప్పుడే వ్యక్తిగత జ్యోతిష్య మార్గదర్శకత్వం పొందారు. మీకు నచ్చితే, మమ్మల్ని మద్దతు ఇవ్వవచ్చు.",
    csr_title: "ఆస్ట్రో లాజిక్ సామాజిక ప్రభావం",
    csr_books_title: "ప్రత్యేక పిల్లల కోసం విద్యా సాధికారత",
    csr_books_desc: "మా ఆదాయంలో 90% ప్రత్యేక పిల్లల విద్య కోసం ఖర్చు చేయబడుతుంది.",
    csr_oldage_title: "వృద్ధులకు గౌరవప్రదమైన సంరక్షణ",
    csr_oldage_desc: "అనాథ వృద్ధులకు నాణ్యమైన ఆహారం మరియు వైద్య సదుపాయాలను అందిస్తాము.",
    secure: "సురక్షితం",
    spiritual: "ఆధ్యాత్మికం",
    support: "మద్దతు",
    next_page: "తదుపరి పేజీ",
    save_info: "సమాచారాన్ని సేవ్ చేయండి",
    saved_profiles_title: "సేవ్ చేసిన ప్రొఫైల్స్",
    celestial_map: "ఖగోళ చిత్రం (రాశి)",
    stars_obscured: "మేఘాల వల్ల గ్రహాలు కనిపించడం లేదు. మళ్ళీ ప్రయత్నించండి.",
    go_back: "వెనుకకు వెళ్ళండి",
    dismiss: "రద్దు చేయండి",
    select_city_warning: "⚠️ ఖచ్చితమైన గణన కోసం నగరాన్ని ఎంచుకోండి.",
    search_assistant_placeholder: "ఉదాహరణ: 2024 గురు సంచార ఫలితాలు",
    enter_full_name: "పూర్తి పేరు నమోదు చేయండి",
    feedback: "అభిప్రాయాలు",
    feedback_title: "మీ అభిప్రాయాలు మరియు సూచనలు",
    feedback_placeholder: "మీ అనుభవాన్ని భాగస్వామ్యం చేయండి...",
    submit_feedback: "పంపండి",
    feedback_success: "మీ అభిప్రాయానికి ధన్యవాదాలు!",
    first_name: "మొదటి పేరు",
    second_name: "రెండవ పేరు",
    timeframe_placeholder: "ఉదాహరణ: వచ్చే 3 నెలలు",
    select_seeker: "సీకర్",
    select_scholar: "స్కాలర్",
    seeker: "సీకర్",
    scholar: "స్కాలర్",
    seeker_desc: "సామాన్యుల కోసం సరళమైన మార్గదర్శకత్వం, కెరీర్ మరియు రోజువారీ జీవితం కోసం విశ్లేషణ.",
    scholar_desc: "జ్యోతిష్కులు మరియు విద్యార్థుల కోసం. లోతైన సాంకేతిక వివరాలు మరియు సంస్కృత శ్లోకాలు.",
    siddhantic_precision: "స్కాలర్ విభాగం",
    personal_guidance: "సీకర్ విభాగం",
    calculating_heavens: "గణనలు జరుగుతున్నాయి...",
    ask_help_guruji: "గురూజీ సహాయం కోరండి",
    sacred_conversation: "ఒక పవిత్ర సంభాషణ",
    shastriya: "శాస్త్రీయ",
    life_path: "జీవన మార్గం",
    timeline: "కాలక్రమం",
    siddhantic: "సిద్ధాంతం",
    life_phase: "జీవన దశ",
    wealth_health: "సంపద మరియు ఆరోగ్యం",
    soul_map: "ఆత్మ మానచిత్రం",
    power_score: "శక్తి మార్కులు",
    under_construction: "ఈ విభాగం ఇంకా తయారీలో ఉంది.",
    return_home: "హోమ్ పేజీకి వెళ్ళండి",
    get_verdict: "తీర్పు పొందండి",
    latitude: "అక్షాంశం",
    longitude: "రేఖాంశం",
    timezone: "సమయ మండలి",
    suggestion_title: "సూచనలు",
    suggestion_desc: "మీ అనుభవాన్ని మెరుగుపరచడంలో గురూజీకి సహాయపడండి",
    suggestion_placeholder: "మీ ఆలోచనలను పంచుకోండి...",
    suggestion_send: "పంపండి",
    suggestion_sent: "గురూజీకి పంపబడింది",
    panchanga_title: "పంచాంగం",
    custom_panchanga: "తేదీ మరియు స్థలాన్ని మార్చండి",
    timeline_title: "జీవన కాలక్రమ డాష్ బోర్డు",
    contact_astrologer_title: "జ్యోతిష్కుని సంప్రదించండి",
    contact_astrologer_desc: "తాంబూల సమర్పణం",
    tambula_offering: "తాంబూల సమర్పణం",
    tambula_desc: "జ్యోతిష్కుని సంప్రదించి మార్గదర్శకత్వం పొందడానికి తాంబూలం మరియు దక్షిణ సమర్పించండి.",
    problem_label: "మీ అవసరాన్ని వివరించండి",
    problem_placeholder: "ఉదాహరణ: కెరీర్ వృద్ధి, ఆరోగ్యం...",
    contact_time_label: "సంప్రదించాల్సిన సమయం",
    contact_time_placeholder: "ఉదాహరణ: రేపు ఉదయం 10 గంటలకు",
    submit_problem: "పంపండి",
    problem_submitted_msg: "మా జ్యోతిష్కుడు త్వరలో మిమ్మల్ని సంప్రదిస్తారు.",
    mangala_dosha: "కుజ దోషం",
    conclusion_title: "సంక్షిప్త ముగింపు",
    remedy_options_title: "పరిహార మార్గాన్ని ఎంచుకోండి",
    tier1_title: "ఉపాయ ప్రారంభం",
    tier1_price: "₹99",
    tier1_meaning: "ప్రారంభ పరిహారాలు",
    tier2_title: "శుభ మార్గం",
    tier2_price: "₹599",
    tier2_meaning: "మలుపు తిప్పే దారి",
    tier3_title: "సర్వ కర్మ విశ్లేషణ",
    tier3_price: "₹999",
    tier3_meaning: "పూర్తి జీవిత విశ్లేషణ",
    pay_now: "డబ్బు చెల్లించి కొనసాగండి",
    appointment_date: "తేదీని ఎంచుకోండి",
    appointment_time: "సమయాన్ని ఎంచుకోండి",
    contact_astrologer_remedies: "పరిహారాల కోసం జ్యోతిష్కుని సంప్రదించండి",
    analysis_tab_title: "విశ్లేషణ",
    matching_tab_title: "పొంతన",
    chat_tab_title: "ఆస్ట్రో చాట్",
    help: "సహాయం",
    footer_text: "దైవ నిర్ణయం • గ్రహాల అమరిక • లోతైన జ్ఞానం",
    celestial_insights_title: "ప్రస్తుత గ్రహ స్థితులు",
    search_assistant_desc: "గ్రహ సంచారాలు లేదా జ్యోతిష్య సంఘటనల కోసం వెతకండి.",
    searching: "వెతుకుతోంది...",
    ask_stars: "గ్రహాలను అడగండి",
    sources: "ఆధారాలు",
    invoke_guruji: "గురూజీని ఆహ్వానించండి",
    pranama_end: "ప్రణామం (ముగింపు)",
    career_guidance: "కెరీర్ మార్గదర్శకత్వం",
    love_marriage: "ప్రేమ మరియు వివాహం",
    health_energy: "ఆరోగ్యం మరియు శక్తి",
    spiritual_path: "ఆధ్యాత్మిక మార్గం",
    seek_wisdom_message: "జ్ఞానాన్ని వెతకండి, నక్షత్రాలు సమాధానమిస్తాయి.",
    connecting: "కనెక్ట్ అవుతోంది...",
    dhanyavaada: "ధన్యవాదాలు",
    pranama: "ప్రణామం",
    path: "మార్గం",
    seeker_path: "సీకర్ మార్గం",
    you_hint: "నాకు సహాయం కావాలి ",
    muhurta_vivaha: "వివాహం",
    muhurta_grihapravesha: "గృహప్రవేశం",
    muhurta_bhoomi_pooja: "భూమి పూజ",
    muhurta_upanayana: "ఉపనయనం (ఒడుగు)",
    muhurta_namakarana: "నామకరణం",
    muhurta_annaprashana: "అన్నప్రాశన (మొదటి ఆహారం)",
    muhurta_aksharabhyasa: "అక్షరాభ్యాసం",
    muhurta_vidyarambha: "పాఠశాలలో చేర్పించడం",
    muhurta_karnavedha: "చెవి పోగులు పెట్టడం",
    muhurta_choodakarana: "పుట్టు వెంట్రుకలు తీయిండం",
    muhurta_seemantham: "సీమంతం",
    muhurta_vahana: "వాహనం కొనుగోలు",
    muhurta_vyapaara: "వ్యాపారం ప్రారంభం",
    muhurta_shop_opening: "దుకాణం ప్రారంభోత్సవం",
    muhurta_udyoga: "ఉద్యోగంలో చేరడానికి",
    muhurta_swarna: "బంగారం కొనుగోలు",
    muhurta_investments: "పెట్టుబడులు",
    muhurta_yaatra: "ప్రయాణం",
    muhurta_videsha: "విదేశీ ప్రయాణం",
    muhurta_shastra_kriya: "శస్త్రచికిత్స",
    muhurta_medical_start: "వైద్య చికిత్స ప్రారంభం",
    muhurta_abhijit: "అభిజీత్ ముహూర్తం",
    muhurta_brahma: "బ్రహ్మ ముహూర్తం",
    muhurta_shilaanyasa: "శంకుస్థాపన",
    muhurta_renting: "అద్దె ఇల్లు మారడానికి",
    muhurta_contracts: "ఒప్పందాలపై సంతకం",
    muhurta_legal: "కోర్టు వ్యవహారాలు",
    muhurta_agriculture: "వ్యవసాయ పనులు",
    home: "హోమ్",
    daily_nav: "దినసరి",
    oracle_nav: "ఒరాకిల్",
    chat_nav: "చాట్",
    donate_support: "విరాళం ఇవ్వండి",
    next_analysis: "తర్వాత: విశ్లేషణను ఎంచుకోండి",
    sacred_geometry: "పవిత్ర జ్యామితి",
    birth_analysis: "జన్మ విశ్లేషణ",
    my_character: "నా వ్యక్తిత్వం",
    rasi_kundli: "రాశి చక్రం",
    vimshottari: "వింశోత్తరి",
    ashtakavarga: "అష్టకవర్గం",
    planet_sun: "సూర్యుడు",
    planet_moon: "చంద్రుడు",
    planet_mars: "కుజుడు",
    planet_mercury: "బుధుడు",
    planet_jupiter: "గురుడు",
    planet_venus: "శుక్రుడు",
    planet_saturn: "శని",
    planet_rahu: "రాహువు",
    planet_ketu: "కేతువు",
    planet_lagna: "లగ్నం",
    planet_mandi: "మాంది",
    rasi_mesha: "మేషం",
    rasi_vrishabha: "వృషభం",
    rasi_mithuna: "మిథునం",
    rasi_karka: "కర్కాటకం",
    rasi_simha: "సింహం",
    rasi_kanya: "కన్య",
    rasi_tula: "తుల",
    rasi_vrishchika: "వృశ్చికం",
    rasi_dhanu: "ధనుస్సు",
    rasi_makara: "మకరం",
    rasi_kumbha: "కుంభం",
    rasi_meena: "మీనం",
    muhurta_analysis: "ముహూర్త విశ్લેషణ",
    auspicious_time: "శుభ సమయం",
    verdict: "తీర్పు",
    planetary_positions: "గ్రహ స్థితులు",
    classical_references: "శాస్త్రీయ ప్రస్తావనలు",
    panchanga_breakdown: "పంచాంగ వివరాలు",
    technical_summary: "సాంకేతిక సారాంశం",
    saved_readings: "సేవ్ చేసినవి",
    no_readings: "జాబితా ఖాళీగా ఉంది",
    no_readings_desc: "వివరాలను సేవ్ చేయడం ప్రారంభించండి.",
    clear_history_confirm: "అన్ని వివరాలను తొలగించాలా?",
    vastu_title: "వాస్తు శాస్త్రం",
    vastu_desc: "శక్తి మరియు వాస్తు",
    vastu_analysis: "వాస్తు విశ్లేషణ",
    home_harmony: "ఇంట్లో ప్రశాంతత",
    palm_reading_title: "హస్త సాముద్రికం",
    palm_reading_desc: "చేతి రేఖల విశ్లేషణ",
    upload_palm: "అరచేతి ఫోటోను అప్లోడ్ చేయండి",
    palm_instructions: "చేతిని సమానంగా ఉంచి ఫోటో తీయండి.",
    analyzing_palm: "చేతి రేఖలు విశ్లేషించబడుతున్నాయి...",
    palm_analysis_res: "హస్త రేఖల విశ్లేషణ",
    camera_access: "కెమెరా",
    gallery_access: "గ్యాలరీ",
    invalid_palm_error: "ఫోటో స్పష్టంగా లేదు. మళ్ళీ అప్లోడ్ చేయండి.",
    classical_source_authority: "శాస్త్రీయ ఆధారం",
    welcome_tour: "స్వాగతం",
    welcome_tour_desc: "జ్యోతిష్య ప్రపంచానికి మీకు స్వాగతం.",
    seeker_mode_active: "సీకర్ మోడ్",
    scholar_mode_active: "స్కాలర్ మోడ్",
    seeker_tour_desc: "సరళమైన మార్గం",
    scholar_tour_desc: "లోతైన పరిశోధన",
    sacred_dashboard: "డాష్ బోర్డు",
    dashboard_tour_desc: "అన్నీ ఒకే చోట.",
    guruji_tour: "గురూజీని సంప్రదించండి",
    guruji_tour_desc: "మీ సహాయకుడు.",
    navigation_tour: "ప్రయాణం కొనసాగుతుంది",
    nav_tour_desc: "సరళమైన డిజైన్.",
    save_profile_error: "పేరును నమోదు చేయండి.",
    profile_saved: "సేవ్ చేయబడింది.",
    profile_saved_for: "{name} ప్రొఫైల్ సేవ్ చేయబడింది.",
    life_partner_analysis: "భాగస్వామి విશ્લેషణ",
    prashna_analysis: "ప్రశ్న విశ్લેషణ",
    stars_silent: "మళ్ళీ ప్రయత్నించండి.",
    celestial_connection_failed: "సంప్రదింపు విచ్ఛిన్నమైంది.",
    switch_to_dark: "డార్క్ మోడ్",
    switch_to_light: "లైట్ మోడ్",
    blog: "బ్లాగ్",
    blog_desc: "వ్యాసాలు",
    enter_details_warning: "జన్మ సమయం మరియు తేదీని నమోదు చేయండి.",
    sending: "పంపబడుతోంది...",
    offline: "ఆఫ్ లైన్",
    csr_tagline: "ధర్మం మరియు కరుణ",
    csr_revenue_committed: "ఆదాయం అంకితం",
    csr_souls_nourished: "ప్రయోజనం పొందినవారు",
    csr_verified_integrity: "నిజాయితీ",
    csr_schools_supported: "పాఠశాలలు",
    csr_kits_distributed: "కిట్లు",
    csr_volunteer_hours: "సమయం",
    csr_homes_adopted: "నివాసాలు",
    csr_elders_assisted: "వృద్ధులు",
    csr_medical_camps: "వైద్య శిబిరాలు",
    csr_special_children_initiative: "పిల్లల కోసం పథకం",
    csr_elder_care_program: "వృద్ధుల సంరక్షణ",
    csr_revenue_committed_90: "90% ఆదాయం సామాజిక సేవ కోసం",
    csr_holistic_care_100: "100% సేవ",
    seeker_mode_desc_short: "సీకర్ మోడ్",
    scholar_mode_desc_short: "స్కాలర్ మోడ్",
    saved_profiles_desc: "ఇటీవలివి",
    today_panchanga: "నేటి పంచాంగం"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    // Find matching closing brace
    const endMarker = '  },';
    const endIndex = content.indexOf(endMarker, startIndex + startMarker.length);
    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 4);
}

let newContent = content;
newContent = updateLanguage(newContent, 'ta', ta_full);
newContent = updateLanguage(newContent, 'te', te_full);

fs.writeFileSync(filePath, newContent);
console.log("Updated Tamil and Telugu translations.");
