import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const tcy_full = {
    brand_name: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್",
    tagline: "ಪರತ್ ಜ್ಞಾನ ಬೊಕ್ಕ ಆಧುನಿಕ ತರ್ಕದ ಸಂಗಮ",
    begin_journey: "ಪ್ರಯಾಣ ಸುರು ಮಲ್ಪುಲೆ",
    choose_path: "ನಿಮ್ಮ ಸಾದಿನ್ ಆಯ್ದುಕೊಳೆ",
    disclaimer: "ಜೋತಿಷ್ಯ ಮಾರ್ಗದರ್ಶನ ಗ್ರಹಲೆನ ಲೆಕ್ಕಾಚಾರದ ಮೇಲೆ ಆಧಾರಿತವಾದುಂಡು, ಪಲಿತಾಂಶದ ಭರವಸೆ ಕೊರ್ಪುಜಿ.",
    planetary_transit_in: "ಡು",
    horoscope: "ಜಾತಕ",
    matching: "ಗುಣ ಮೇಲನ",
    life_partner: "ಜೀವನ ಸಂಗಾತಿ",
    daily: "ದೈನಂದಿನ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    numerology: "ಅಂಕಶಾಸ್ತ್ರ",
    chat: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    prashna: "ಪ್ರಶ್ನೆ",
    guruji: "ಗುರೂಜಿ",
    you: "ಈರ್",
    guruji_welcome: "ನಿಮ್ಮ ಜೀವನದ ಸಾದಿ, ಗ್ರಹಲೆನ ಗೋಚಾರ ಅಥವಾ ಮಾರ್ಗದರ್ಶನ ಬೋಡಾಂಡ ಗುರೂಜಿಗ್ ಕೇನ್ಲೆ.",
    guruji_thinking: "ಗುರೂಜಿ ತಾರೆಲೆನ್ ಲೆಕ್ಕ ಮಲ್ತೊಂದುಲ್ಲೆರ್...",
    error_guruji: "ಸಂಪರ್ಕ ಸರಿಯಿಲ್ಲೆ. ದಯವಿಟ್ಟು ಪಿರ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ.",
    ask_guruji_placeholder: "ಗುರೂಜಿಗ್ ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇನ್ಲೆ...",
    switch_mode: "ಪಹಾದಿ ಬದಲಾವಣೆ",
    menu_details: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    menu_timeline: "ಜೀವನ ಕಾಲಕ್ರಮ",
    menu_hora: "ಹೋರಾ ವಿಶ್ಲೇಷಣೆ",
    menu_sphta: "ಗ್ರಹ ಸ್ಪಷ್ಟತೆ",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಚಲಿತ",
    menu_bhava_analysis: "ಭಾವ ವಿಶ್ಲೇಷಣೆ",
    menu_sandhi: "ಸಂಧಿ ವಿಶ್ಲೇಷಣೆ",
    menu_panchangam: "ಪಂಚಾಂಗ",
    menu_dasha: "ದಶಾ ಭವಿಷ್ಯ",
    menu_shadvarga: "ಷಡ್ವರ್ಗ",
    shadvarga_strengths: "ಷಡ್ವರ್ಗ ಬಲ",
    shadbala_analysis: "ಷಡ್ಬಲ",
    energy_strength: "ಶಕ್ತಿ",
    planetary_power: "ಗ್ರಹ ಬಲ",
    menu_yogas: "ಯೋಗ ವಿಶ್ಲೇಷಣೆ",
    menu_maitri: "ಗ್ರಹ ಮೈತ್ರಿ",
    menu_ashtaka: "ಅಷ್ಟಕವರ್ಗ",
    menu_trisputa: "ತ್ರಿಸ್ಫುಟ",
    menu_dhumadi: "ಧೂಮಾದಿ",
    menu_basic_details: "ಜನ್ಮ ವಿವರ",
    menu_yoga: "ಯೋಗ",
    menu_career: "ಉದ್ಯೋಗ ಬೊಕ್ಕ ಯಶಸ್ಸು",
    menu_health: "ಆರೋಗ್ಯ",
    menu_money: "ಸಂಪತ್ತು",
    menu_transit: "ಗ್ರಹ ಗೋಚಾರ",
    menu_dasha_effect: "ದಶೆ ಫಲ",
    menu_sade_sati: "ಸಾಡೆ ಸಾತಿ",
    menu_gemstones: "ರತ್ನ ಬೊಕ್ಕ ರುದ್ರಾಕ್ಷ",
    menu_nakshatra: "ನಕ್ಷತ್ರ ರಹಸ್ಯ",
    menu_doshas: "ದೋಷ ತಪಾಸಣೆ",
    menu_character: "ಸ್ವಭಾವ",
    menu_numerology: "ಅಂಕಿ ಸಂಖ್ಯೆ",
    back: "ಪಿರ",
    submit: "ಜಾತಕ ತಯಾರ್ ಮಲ್ಪುಲೆ",
    quick_profile: "ತ್ವರಿತ ಪ್ರೊಫೈಲ್",
    enter_details_wisdom: "ವಿವರ ಕೊರ್ಲೆ",
    save_continue: "ಉಳಿತಾಯ ಬೊಕ್ಕ ದುಂಬು ಪೋಲೆ",
    continue: "ದುಂಬು ಪೋಲೆ ➔",
    next_choose_analysis: "ದುಂಬು: ವಿಶ್ಲೇಷಣೆ ➔",
    skip_for_now: "ಇತ್ತೆಗ್ ಬೊಡ್ಚಿ",
    lang_select: "ಭಾಷೆ",
    loshu_grid: "ಲೋಶು ಗ್ರಿಡ್",
    full_name: "ಪೂರ್ಣ ಪುದರ್",
    classical_predictions: "ಶಾಸ್ತ್ರೀಯ ಭವಿಷ್ಯ",
    sacred_guide: "ಪವಿತ್ರ ಮಾರ್ಗದರ್ಶಿ",
    seeker_scholar_desc: "ಸರಳ ಮಾರ್ಗದರ್ಶನಗಾದ್ ಸೀಕರ್, ವಿವರವಾಯಿನ ಮಾಹಿತಿ ಗಾದ್ ಸ್ಕಾಲರ್ ಆಯ್ದುಕೊಳೆ.",
    save_profile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    saved_profiles: "ಇತ್ತೀಚಿನ ಜಾತಕಲು",
    matching_title: "ಸಂಬಂಧ ಹೊಂದಾಣಿಕೆ",
    conclusion: "ತೀರ್ಪು",
    select_rasi: "ರಾಶಿ ಆಯ್ದುಕೊಳೆ",
    daily_title: "ಇತ್ತೆದಯ ಫ್ಲೋ",
    muhurta_title: "ಶುಭ ಮುಹೂರ್ತ",
    muhurta_select: "ಉದ್ದೇಶ ಆಯ್ದುಕೊಳೆ",
    sacred_intake: "ವಿವರ ದಾಖಲೆ",
    partner_one: "ಪಾತ್ರ 1",
    partner_two: "ಪಾತ್ರ 2",
    birth_location: "ಪುಟ್ಟಿನ ಜಾಗೆ",
    timeframe: "ಸಮಯ",
    location: "ಜಾಗೆ",
    quick_search: "ಬೇಗನೆ ನಾಡ್ಲೆ",
    oracle: "ಒರಾಕಲ್",
    name: "ಪುದರ್",
    date: "ದಿನಾಂಕ",
    nakshatra: "ನಕ್ಷತ್ರ",
    ask_guruji: "ಗುರೂಜಿಗ್ ಕೇನ್ಲೆ",
    deep_inquiry: "ವಿವರ ವಿಚಾರಣೆ",
    seek_answer: "ಪರಿಹಾರ ನಾಡ್ಲೆ",
    name_of_soul: "ಅಭ್ಯರ್ಥಿ ಪುದರ್",
    birth_date: "ಪುಟ್ಟಿನ ದಿನಾಂಕ",
    birth_time: "ಪುಟ್ಟಿನ ಸಮಯ",
    gender: "ಲಿಂಗ",
    male: "ಆಣ್",
    female: "ಪೊಣ್ಣು",
    other: "ಇತರ",
    search_city_placeholder: "ನಗರ ನಾಡ್ಲೆ...",
    muhurta_search_placeholder: "ಉದ್ದೇಶ ನಾಡ್ಲೆ...",
    prashna_placeholder: "ನಿಮ್ಮ ವಿಶೇಷ ಪ್ರಶ್ನೆ ದಾದ?",
    guruji_listening: "ಗುರೂಜಿ ಕೇಣೊಂದುಲ್ಲೆರ್...",
    connection_interrupted: "ಸಂಪರ್ಕ ಕಡಿತ",
    disconnected: "ಡಿಸ್ಕನೆಕ್ಟ್",
    support_guruji: "ಗುರೂಜಿಗ್ ಬೆಂಬಲ ಕೊರ್ಲೆ",
    scan_to_support: "ಬೆಂಬಲಗಾದ್ ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ",
    scan_to_donate: "GPay / UPI ಗಾದ್ ಸ್ಕ್ಯಾನ್ ಮಲ್ಪುಲೆ",
    support_mission: "ನಮ್ಮ ಮಿಷನ್ಗ್ ಸಹಾಯ ಮಲ್ಪುಲೆ",
    support_quote: "ನಿಮ್ಮ ಜಾತಕ ಮಾರ್ಗದರ್ಶನ ಗಾದ್ ನಾ ಮುಲ್ಪ ಉಲ್ಲೆ. ಸಹಾಯ ಮಲ್ಪೆರೆ ಮನಸ್ಸಾಂಡ ಮಲ್ಪುಲೆ.",
    csr_title: "ಸಾಮಾಜಿಕ ಕಳಕಳಿ",
    csr_books_title: "ವಿಶೇಷ ಜೋಕುಲೆಗ್ ಶಿಕ್ಷಣ",
    csr_books_desc: "ವಿಶೇಷ ಚೇತನ ಜೋಕುಲೆಗ್ ಅಕಲೆನ ಶಿಕ್ಷಣ ಗಾದ್ ನಾವು ನಮ್ಮ ಆದಾಯದ 90% ಭಾಗವನ್ನು ಮೀಸಲಿರಿಸಿದ್ದೇವೆ.",
    csr_oldage_title: "ವೃದ್ಧಾಪ್ಯಡ್ ಗೌರವ",
    csr_oldage_desc: "ಅಶಕ್ತ ವೃದ್ಧರೆಗ್ ಆಶ್ರಯ ಬೊಕ್ಕ ಆಹಾರದ ಸಹಾಯ ಮಲ್ಪುನ ಯೋಜನೆ.",
    secure: "ಸುರಕ್ಷಿತ",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಬೆಂಬಲ",
    next_page: "ಮುಂದಿನ ಪುಟ",
    save_info: "ಮಾಹಿತಿ ಉಳಿಸಿ",
    saved_profiles_title: "ಉಳಿಸಿದ ಪ್ರೊಫೈಲ್",
    celestial_map: "ಆಕಾಶ ನಕ್ಷೆ",
    stars_obscured: "ಮೋಡ ಮುಚ್ಚಿದುಂಡು. ಪಿರ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ.",
    go_back: "ಪಿರ ಪೋಲೆ",
    dismiss: "ಬಿಡಿ",
    select_city_warning: "⚠️ ಸರಿಯಾಯಿನ ಲೆಕ್ಕಾಚಾರಗಾದ್ ನಗರ ಆಯ್ದುಕೊಳೆ.",
    search_assistant_placeholder: "ಉದಾ: 2024 ಮೆಷ ರಾಶಿ ಫಲ",
    enter_full_name: "ಪೂರ್ಣ ಪುದರ್ ಬರೆಲೆ",
    feedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    feedback_title: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಬೊಕ್ಕ ಸಲಹೆಗಳು",
    feedback_placeholder: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ...",
    submit_feedback: "ಸಲ್ಲಿಸಿ",
    feedback_success: "ಧನ್ಯವಾದಗಳು!",
    first_name: "ಸುರುತ ಪುದರ್",
    second_name: "ಎರಡನೇ ಪುದರ್",
    timeframe_placeholder: "ಉದಾ: ಬರ್ಪಿನ 3 ತಿಂಗಳಲ್ಲಿ",
    select_seeker: "ಸೀಕರ್ ಆಯ್ದುಕೊಳೆ",
    select_scholar: "ಸ್ಕಾಲರ್ ಆಯ್ದುಕೊಳೆ",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    seeker_desc: "ಸಾಮಾನ್ಯ ಜನಕಲೆಗಾದ್ ಸರಳ ಸಾದಿ.",
    scholar_desc: "ಜ್ಯೋತಿಷಿಲೆಗಾದ್ ಆಳವಾಯಿನ ಮಾಹಿತಿ.",
    siddhantic_precision: "ಸ್ಕಾಲರ್ ವಿಭಾಗ",
    personal_guidance: "ಸೀಕರ್ ವಿಭಾಗ",
    calculating_heavens: "ಲೆಕ್ಕಾಚಾರ ನಡತೊಂದುಂಡು...",
    ask_help_guruji: "ಗುರೂಜಿನ ಸಹಾಯ ಕೇನ್ಲೆ",
    sacred_conversation: "ಪವಿತ್ರ ಸಂಭಾಷಣೆ",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    life_path: "ಜೀವನ ಸಾದಿ",
    timeline: "ಸಮಯ",
    siddhantic: "ಸಿದ್ದಾಂತಿಕ್",
    life_phase: "ಜೀವನ ಹಂತ",
    wealth_health: "ಸಂಪತ್ತು ಬೊಕ್ಕ ಆರೋಗ್ಯ",
    soul_map: "ಆತ್ಮದ ನಕ್ಷೆ",
    power_score: "ಶಕ್ತಿ",
    under_construction: "ನಿರ್ಮಾಣ ಹಂತಡುಂಡು.",
    return_home: "ಇಲ್ಲಗ್ ಪಿರ ಪೋಲೆ",
    get_verdict: "ವೀರ್ಡಿಕ್ಟ್ ಪಡೆಲೆ",
    latitude: "ಅಕ್ಷಾಂಶ",
    longitude: "ರೇಖಾಂಶ",
    timezone: "ಸಮಯ ವಲಯ",
    suggestion_title: "ಸಲಹೆ",
    suggestion_desc: "ಅನುಭವ ಸುಧಾರಿಸಯೆರೆ ಸಹಾಯ ಮಲ್ಪುಲೆ",
    suggestion_placeholder: "ನಿಮ್ಮ ವಿಷಯ ಬರೆಲೆ...",
    suggestion_send: "ಕಡಪುಡ್ಲೆ",
    suggestion_sent: "ಗುತ್ತುಜಿಗ್ ಮುಟ್ಟಿದುಂಡು",
    panchanga_title: "ಪಂಚಾಂಗ",
    custom_panchanga: "ದಿನಾಂಕ ಬೊಕ್ಕ ಜಾಗೆ",
    timeline_title: "ಕಾಲಕ್ರಮ",
    contact_astrologer_title: "ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    contact_astrologer_desc: "ದೈವಜ್ಞೆರೆಗ್ ತಾಂಬೂಲ ಕೊರ್ಲೆ",
    tambula_offering: "ತಾಂಬೂಲ",
    tambula_desc: "ತಾಂಬೂಲ ಕೊರ್ದು ದಕ್ಷಿಣೆ ಬುಡ್ಲೆ.",
    problem_label: "ಸಮಸ್ಯೆ ಪಂಡಿಲೆ",
    problem_placeholder: "ದಾದ ಸಮಸ್ಯೆ ಉಂಡು?",
    contact_time_label: "ಸಂಪರ್ಕ ಕಾಲ",
    contact_time_placeholder: "ಯಾವಾಗ?",
    submit_problem: "ಸಲ್ಲಿಕೆ",
    problem_submitted_msg: "ಸಂಪರ್ಕ ಮಲ್ಪುವೆರ್.",
    mangala_dosha: "ಕುಜ ದೋಷ",
    conclusion_title: "ತೀರ್ಮಾನ",
    remedy_options_title: "ಪರಿಹಾರ ಮಾರ್ಗ",
    tier1_title: "ಉಪಾಯ ಪ್ರಾರಂಭ",
    tier1_price: "₹99",
    tier1_meaning: "ಸುರುತ ಪರಿಹಾರ",
    tier2_title: "ಶುಭ ಮಾರ್ಗ",
    tier2_price: "₹599",
    tier2_meaning: "ಗ್ರಹ ಶಾಂತಿ ಸಾದಿ",
    tier3_title: "ಸರ್ವ ಕರ್ಮ",
    tier3_price: "₹999",
    tier3_meaning: "ಪೂರ್ಣ ಮಾಹಿತಿ",
    pay_now: "ಹಣ ಪಾವತಿಸಿ",
    appointment_date: "ದಿನಾಂಕ",
    appointment_time: "ಸಮಯ",
    contact_astrologer_remedies: "ಜ್ಯೋತಿಷಿ ಸಂಪರ್ಕ",
    analysis_tab_title: "ವಿಶ್ಲೇಷಣೆ",
    matching_tab_title: "ಹೊಂದಾಣಿಕೆ",
    chat_tab_title: "ಚಾಟ್",
    help: "ಸಹಾಯ",
    footer_text: "ದೈವಿಕ ಆಜ್ಞೆ • ಆಧ್ಯಾತ್ಮಿಕ ಸಾದಿ",
    celestial_insights_title: "ಇತ್ತೆದ ಗ್ರಹಗತಿ",
    search_assistant_desc: "ಪಂಚಾಂಗ ಬೊಕ್ಕ ಗೋಚಾರ ಫಲ ನಾಡ್ಲೆ.",
    searching: "ನಾಡ್ತೊಂದುಂಡು...",
    ask_stars: "ತಾರೆಲೆನ್ ಕೇನ್ಲೆ",
    sources: "ಆಧಾರ",
    invoke_guruji: "ಗುರೂಜಿ ಬರ್ಲೆ",
    pranama_end: "ಪ್ರಣಾಮ",
    career_guidance: "ಉದ್ಯೋಗ ಮಾರ್ಗದರ್ಶನ",
    love_marriage: "ಮದಿಮೆ ಬೊಕ್ಕ ಪ್ರೀತಿ",
    health_energy: "ಆರೋಗ್ಯ ಬೊಕ್ಕ ಶಕ್ತಿ",
    spiritual_path: "ಆಧ್ಯಾತ್ಮಿಕ ಸಾದಿ",
    seek_wisdom_message: "ಗುರೂಜಿನ ಮೂಲಕ ತಾರೆಲೆನ ಉತ್ತರ ಪಡೆಲೆ.",
    connecting: "ಸಂಪರ್ಕ ಆವೊಂದುಂಡು...",
    dhanyavaada: "ಧನ್ಯವಾದ",
    pranama: "ಪ್ರಣಾಮ",
    path: "ಸಾದಿ",
    seeker_path: "ಸೀಕರ್ ಸಾದಿ",
    you_hint: "ನಂಕು ಸಹಾಯ ಬೋಡು ",
    muhurta_vivaha: "ಮದಿಮೆ",
    muhurta_grihapravesha: "ಗೃಹ ಪ್ರವೇಶ",
    muhurta_bhoomi_pooja: "ಭೂಮಿ ಪೂಜೆ",
    muhurta_upanayana: "ಉಪನಯನ",
    muhurta_namakarana: "ನಾಮಕರಣ",
    muhurta_annaprashana: "ಅನ್ನಪ್ರಾಶನ",
    muhurta_aksharabhyasa: "ಅಕ್ಷರಾಭ್ಯಾಸ",
    muhurta_vidyarambha: "ವಿದ್ಯಾರಂಭ",
    muhurta_karnavedha: "ಕರ್ಣವೇದ",
    muhurta_choodakarana: "ಮಂಡನ",
    muhurta_seemantham: "ಸೀಮಂತ",
    muhurta_vahana: "ವಾಹನ ಖರೀದಿ",
    muhurta_vyapaara: "ವ್ಯಾಪಾರ ಸುರು",
    muhurta_shop_opening: "ಅಂಗಡಿ ಉದ್ಘಾಟನೆ",
    muhurta_udyoga: "ಕೆಲಸಕ್ಕೆ ಸೇರುವುದು",
    muhurta_swarna: "ಬಂಗಾರ ಖರೀದಿ",
    muhurta_investments: "ಹೂಡಿಕೆ",
    muhurta_yaatra: "ಪ್ರಯಾಣ",
    muhurta_videsha: "ವಿದೇಶ ಪ್ರಯಾಣ",
    muhurta_shastra_kriya: "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ",
    muhurta_medical_start: "ಚಿಕಿತ್ಸೆ ಸುರು",
    muhurta_abhijit: "ಅಭಿಜಿತ್ ಮುಹೂರ್ತ",
    muhurta_brahma: "ಬ್ರಹ್ಮ ಮುಹೂರ್ತ",
    muhurta_shilaanyasa: "ಗುದ್ದಲಿ ಪೂಜೆ",
    muhurta_renting: "ಬಾಡಿಗೆ ಇಲ್ಲ್",
    muhurta_contracts: "ಒಪ್ಪಂದ",
    muhurta_legal: "ಕೋರ್ಟ್ ಕೆಲಸ",
    muhurta_agriculture: "ಕೃಷಿ ಕೆಲಸ",
    home: "ಇಲ್ಲ್",
    daily_nav: "ದಿನಚರಿ",
    oracle_nav: "ಒರಾಕಲ್",
    chat_nav: "ಚಾಟ್",
    donate_support: "ಸಹಾಯ ಬೊಕ್ಕ ಬೆಂಬಲ",
    next_analysis: "ದುಂಬು: ವಿಶ್ಲೇಷಣೆ ಆಯ್ದುಕೊಳೆ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪರತ್ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    my_character: "ಎನ್ನ ವ್ಯಕ್ತಿತ್ವ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಅಂಗಾರಕ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೇತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    muhurta_analysis: "ಸಿದ್ಧಾಂತಿಕ ಸಾದಿ",
    auspicious_time: "ಶುಭ ಸಮಯ",
    verdict: "ವೈದಿಕ ತೀರ್ಪು",
    planetary_positions: "ಗ್ರಹಗಳ ಸ್ಥಿತಿ",
    classical_references: "ಶಾಸ್ತ್ರೀಯ ಆಧಾರ",
    panchanga_breakdown: "ಪಂಚಾಂಗ ವಿವರ",
    technical_summary: "ತಾಂತ್ರಿಕ ಸಾರಾಂಶ",
    saved_readings: "ಆರ್ಕೈವ್",
    no_readings: "ಆರ್ಕೈವ್ ಖಾಲಿ ಉಂಡು",
    no_readings_desc: "ಜಾತಕ ವಿಶ್ಲೇಷಣೆ ಮಲ್ಪುಲೆ.",
    clear_history_confirm: "ಮಾಹಿತಿ ಅಜಪೊಡೆ?",
    vastu_title: "ವಾಸ್ತು ಶಾಸ್ತ್ರ",
    vastu_desc: "ಶಕ್ತಿ ಬೊಕ್ಕ ವಾಸ್ತು",
    vastu_analysis: "ವಾಸ್ತು ವಿಶ್ಲೇಷಣೆ",
    home_harmony: "ಇಲ್ಲದ ನೆಮ್ಮದಿ",
    palm_reading_title: "ಹಸ್ತ ಸಾಮುದ್ರಿಕ",
    palm_reading_desc: "ಹಸ್ತ ರೇಖಾ ಶಾಸ್ತ್ರ",
    upload_palm: "ಹಂಗೈ ಫೋಟೋ ಕೊರ್ಲೆ",
    palm_instructions: "ಕೈಯನ್ನು ಸಮತಲವಾಗಿ ಇಡಿ.",
    analyzing_palm: "ರೇಖೆ ತಪಾಸಣೆ...",
    palm_analysis_res: "ಹಸ್ತ ವಿಶ್ಲೇಷಣೆ",
    camera_access: "ಕ್ಯಾಮೆರಾ",
    gallery_access: "ಗ್ಯಾಲರಿ",
    invalid_palm_error: "ಫೋಟೋ ಸರಿಯಿಲ್ಲೆ. ದಯವಿಟ್ಟು ಪಿರ ಕೊರ್ಲೆ.",
    classical_source_authority: "ಮೂಲ ಶಾಸ್ತ್ರ",
    welcome_tour: "ಸ್ವಾಗತ",
    welcome_tour_desc: "ಜೋತಿಷ್ಯ ಲೋಕಗ್ ಸ್ವಾಗತ.",
    seeker_mode_active: "ಸೀಕರ್",
    scholar_mode_active: "ಸ್ಕಾಲರ್",
    seeker_tour_desc: "ಸರಳ ಮಾರ್ಗ",
    scholar_tour_desc: "ಆಳವಾದ ಜ್ಞಾನ",
    sacred_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dashboard_tour_desc: "ಪಂಚಾಂಗ ಅಪ್ಡೇಟ್",
    guruji_tour: "ಗುರೂಜಿ ಮಾರ್ಗದರ್ಶನ",
    guruji_tour_desc: "ಗುರೂಜಿ ಬಟನ್",
    navigation_tour: "ನ್ಯಾವಿಗೇಷನ್",
    nav_tour_desc: "ಬಳಸುವುದು ಸುಲಭ.",
    save_profile_error: "ಪುದರ್ ಬರೆಲೆ.",
    profile_saved: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ.",
    profile_saved_for: "{name} ಗಾಗಿ ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ.",
    life_partner_analysis: "ಜೀವನ ಸಂಗಾತಿ ವಿಶ್ಲೇಷಣೆ",
    prashna_analysis: "ಪ್ರಶ್ನೆ ವಿಶ್ಲೇಷಣೆ",
    stars_silent: "ತಾರೆಲು ಮೌನವಾಗಿವೆ. ಪಿರ ಪ್ರಯತ್ನ ಮಲ್ಪುಲೆ.",
    celestial_connection_failed: "ಸಂಪರ್ಕ ಸೋತಿದೆ.",
    switch_to_dark: "ಡಾರ್ಕ್ ಮೋಡ್",
    switch_to_light: "ಲೈಟ್ ಮೋಡ್",
    blog: "ಬ್ಲಾಗ್",
    blog_desc: "ಸಿದ್ದಾಂತ ಬೊಕ್ಕ ಹೋರ",
    enter_details_warning: "ವಿವರ ಕೊರ್ಲೆ.",
    sending: "ಕಡಪುಡೊಂದುಂಡು...",
    offline: "ಆಫ್‌ಲೈನ್",
    csr_tagline: "ಧರ್ಮ ಬೊಕ್ಕ ಸಾಮಾಜಿಕ ಸೇವೆ",
    csr_revenue_committed: "ಆದಾಯ ಕೊಡುಗೆ",
    csr_souls_nourished: "ಸಹಾಯ ಪಡೆದವರು",
    csr_verified_integrity: "ನಂಬಿಕೆ ದ್ರೋಹವಿಲ್ಲೆ",
    csr_schools_supported: "ಶೋಲೆ ಸಹಾಯ",
    csr_kits_distributed: "ಕಿಟ್ ವಿತರಣೆ",
    csr_volunteer_hours: "ಸೇವಾ ಸಮಯ",
    csr_homes_adopted: "ಆಶ್ರಯ ಒದಗಿಸಿದವರು",
    csr_elders_assisted: "ವೃದ್ಧರ ಸೇವೆ",
    csr_medical_camps: "ವೈದ್ಯಕೀಯ ಶಿಬಿರ",
    csr_special_children_initiative: "ವಿಶೇಷ ಚೇತನ ಸೇವೆ",
    csr_elder_care_program: "ವೃದ್ಧರ ಸೇವೆ ಯೋಜನೆ",
    csr_revenue_committed_90: "90% ಆದಾಯ ಸಮಾಜ ಸೇವೆಗೆ",
    csr_holistic_care_100: "100% ಸೇವೆ",
    seeker_mode_desc_short: "ಸೀಕರ್ ಮೋಡ್",
    scholar_mode_desc_short: "ಸ್ಕಾಲರ್ ಮೋಡ್",
    saved_profiles_desc: "ಇತ್ತೀಚಿನ ಚಿತ್ರ",
    brand_tagline: "ಪರತ್ ಜ್ಞಾನ, ಆಧುನಿಕ ತರ್ಕ",
    today_panchanga: "ಇತ್ತೆದ ಪಂಚಾಂಗ"
};

const bn_fix = {
    chat_nav: "চ্যাট"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    // Find matching closing brace
    const endMarker = '  },';
    const endIndex = content.indexOf(endMarker, startIndex + startMarker.length);
    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 4);
}

function patchKeys(content: string, lang: string, patch: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    let newContent = content;
    Object.entries(patch).forEach(([key, value]) => {
        const keyPattern = new RegExp(`(${key}:\\s*)"[^"]*"`);
        const blockEndIndex = newContent.indexOf('  },', startIndex);
        const block = newContent.substring(startIndex, blockEndIndex);
        if (block.includes(key + ':')) {
            const newBlock = block.replace(keyPattern, `$1"${value}"`);
            newContent = newContent.substring(0, startIndex) + newBlock + newContent.substring(blockEndIndex);
        }
    });
    return newContent;
}

let newContent = content;
newContent = updateLanguage(newContent, 'tcy', tcy_full);
newContent = patchKeys(newContent, 'bn', bn_fix);

fs.writeFileSync(filePath, newContent);
console.log("Updated Tulu translations and fixed Bengali.");
