import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const gu_full = {
    brand_name: "એસ્ટ્રો લોજિક",
    tagline: "જિજ્ઞાસા અને તર્કનો સંગમ",
    begin_journey: "યાત્રા શરૂ કરો",
    choose_path: "તમારો માર્ગ પસંદ કરો",
    disclaimer: "જ્યોતિષીય આગાહીઓ ગ્રહોની ગણતરીઓ પર આધારિત છે અને માત્ર સંભવિતતાઓ સૂચવે છે, નિશ્ચિત પરિણામો નહીં.",
    planetary_transit_in: "માં",
    horoscope: "કુંડળી",
    matching: "ગુણ મિલન",
    life_partner: "જીવન સાથી",
    daily: "દૈનિક રાશિફળ",
    muhurta: "મુહૂર્ત",
    numerology: "અંકશાસ્ત્ર",
    chat: "એસ્ટ્રો ચેટ",
    prashna: "પ્રશ્ન",
    guruji: "ગુરુજી",
    you: "તમે",
    guruji_welcome: "તમારા જીવનના માર્ગ, ગ્રહોના ગોચર અથવા અન્ય આધ્યાત્મિક માર્ગદર્શન વિશે ગુરુજીને પૂછો.",
    guruji_thinking: "ગુરુજી તારાઓની ગણતરી કરી રહ્યા છે...",
    error_guruji: "તારાઓ સાથેનો સંપર્ક નબળો છે. કૃપા કરીને થોડી વાર પછી પ્રયત્ન કરો.",
    ask_guruji_placeholder: "ગુરુજીને તમારો પ્રશ્ન પૂછો...",
    switch_mode: "માર્ગ બદલો",
    menu_details: "જન્મ વિશ્લેષણ",
    menu_timeline: "જીવન કાલક્રમ (ભૂતકાળ, વર્તમાન, ભવિષ્ય)",
    menu_hora: "શાસ્ત્રીય હોરા વિશ્લેષણ",
    menu_sphta: "ગ્રહોના અંશ",
    menu_rasi: "રાશિ કુંડળી",
    menu_navamsha: "નવાંશ કુંડળી",
    menu_bhava: "ભાવ ચલિત",
    menu_bhava_analysis: "૧૨ ભાવોનું વિશ્લેષણ",
    menu_sandhi: "સંધિ વિશ્લેષણ",
    menu_panchangam: "પંચાંગ",
    menu_dasha: "વિંશોત્તરી દશા",
    menu_shadvarga: "ષડ્વર્ગ",
    shadvarga_strengths: "ષડ્વર્ગ બળ",
    shadbala_analysis: "ષડ્બલ",
    energy_strength: "ઊર્જા શક્તિ",
    planetary_power: "ગ્રહોનું બળ",
    menu_yogas: "યોગ વિશ્લેષણ",
    menu_maitri: "પંચધા ગ્રહ મૈત્રી",
    menu_ashtaka: "અષ્ટકવર્ગ બિંદુઓ",
    menu_trisputa: "ત્રિસ્ફુટાદિ વિશ્લેષણ",
    menu_dhumadi: "ધૂમાદિ ગ્રહ સમૂહ",
    menu_basic_details: "મૂળભૂત જન્મ વિગતો",
    menu_yoga: "યોગ વિશ્લેષણ",
    menu_career: "કારકિર્દી અને સફળતા",
    menu_health: "સ્વાસ્થ્ય અને ઊર્જા",
    menu_money: "ધન અને સંપત્તિ",
    menu_transit: "ગ્રહોનું ગોચર",
    menu_dasha_effect: "દશાની અસરો",
    menu_sade_sati: "સાડાસાતી વિશ્લેષણ",
    menu_gemstones: "રત્ન અને રુદ્રાક્ષ",
    menu_nakshatra: "નક્ષત્ર રહસ્યો",
    menu_doshas: "દોષ તપાસ (કાલસર્પ/પિતૃ)",
    menu_character: "સ્વભાવ અને વ્યક્તિત્વ",
    menu_numerology: "અંકશાસ્ત્ર વિશ્લેષણ",
    back: "પાછા",
    submit: "કુંડળી બનાવો",
    quick_profile: "ઝડપી પ્રોફાઇલ",
    enter_details_wisdom: "વ્યક્તિગત માર્ગદર્શન માટે વિગતો દાખલ કરો",
    save_continue: "સાચવો અને આગળ વધો",
    continue: "આગળ વધો ➔",
    next_choose_analysis: "આગળ: વિશ્લેષણ પસંદ કરો ➔",
    skip_for_now: "હમણાં માટે છોડી દો",
    lang_select: "ભાષા",
    loshu_grid: "લોશુ ગ્રીડ",
    full_name: "પૂરું નામ",
    classical_predictions: "શાસ્ત્રીય આગાહીઓ",
    sacred_guide: "પવિત્ર માર્ગદર્શક",
    seeker_scholar_desc: "સરળ માર્ગદર્શન માટે 'સિકર' પસંદ કરો. ઊંડાણપૂર્વકની તકનીકી વિગતો અને સંસ્કૃત શ્લોકો માટે 'સ્કોલર' પસંદ કરો.",
    save_profile: "પ્રોફાઇલ સાચવો",
    saved_profiles: "તાજેતરના ચાર્ટ્સ",
    matching_title: "દૈવી સંબંધ સુમેળ",
    conclusion: "દૈવી નિર્ણય",
    select_rasi: "રાશિ પસંદ કરો",
    daily_title: "આજનું આકાશી પ્રવાહ",
    muhurta_title: "શુભ મુહૂર્ત સમયગાળો",
    muhurta_select: "હેતુ પસંદ કરો",
    sacred_intake: "માહિતી દાખલ કરો",
    partner_one: "પ્રથમ પાત્ર",
    partner_two: "દ્વિતીય પાત્ર",
    birth_location: "જન્મ સ્થળ",
    timeframe: "સમયગાળો",
    location: "સ્થળ",
    quick_search: "ઝડપી શોધ",
    oracle: "ઓરેકલ",
    name: "નામ",
    date: "તારીખ",
    nakshatra: "નક્ષત્ર",
    ask_guruji: "ગુરુજીને પૂછો",
    deep_inquiry: "ઊંડી તપાસ",
    seek_answer: "જવાબ શોધો",
    name_of_soul: "વ્યક્તિનું નામ",
    birth_date: "જન્મ તારીખ",
    birth_time: "જન્મ સમય",
    gender: "જાતિ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    search_city_placeholder: "શહેર શોધો...",
    muhurta_search_placeholder: "હેતુ શોધો...",
    prashna_placeholder: "તારોઓને તમારો ઊંડો પ્રશ્ન શું છે?",
    guruji_listening: "ગુરુજી સાંભળી રહ્યા છે...",
    connection_interrupted: "જોડાણ કપાઈ ગયું",
    disconnected: "સંપર્ક તૂટી ગયો",
    support_guruji: "ગુરુજીને સહયોગ આપો",
    scan_to_support: "સહયોગ આપવા માટે સ્કેન કરો",
    scan_to_donate: "GPay / UPI દ્વારા દાન કરવા સ્કેન કરો",
    support_mission: "અમારા મિશનને સહયોગ આપો",
    support_quote: "તમને હમણાં જ જ્યોતિષીય માર્ગદર્શન મળ્યું છે. જો તે તમને ઉપયોગી લાગ્યું હોય, તો તમે નાના યોગદાન દ્વારા અમને સહયોગ કરી શકો છો.",
    csr_title: "એસ્ટ્રો લોજિક સામાજિક પ્રભાવ",
    csr_books_title: "વિશેષ બાળકો માટે શૈક્ષણિક સશક્તિકરણ",
    csr_books_desc: "એસ્ટ્રો લોજિક વિશેષ જરૂરિયાતો ધરાવતા બાળકોના સર્વાંગી વિકાસ માટે પ્રતિબદ્ધ છે. અમે શાળાઓને શૈક્ષણિક કિટ્સ અને સાધનો પૂરા પાડીએ છીએ. અમારી આવકનો ૯૦% હિસ્સો આ બાળકોના ભવિષ્ય માટે ફાળવવામાં આવે છે.",
    csr_oldage_title: "વૃદ્ધાવસ્થામાં સન્માન: વૃદ્ધાશ્રમની સંભાળ",
    csr_oldage_desc: "અમારી 'ડિગ્નિટી ઇન એજિંગ' પહેલ નિરાધાર વૃદ્ધોને વ્યાપક સહાય પૂરી પાડવા પર ધ્યાન કેન્દ્રિત કરે છે. અમે તેમને ગુણવત્તાયુક્ત આરોગ્ય સંભાળ અને પૌષ્ટિક ભોજન મળે તેની ખાતરી કરીએ છીએ.",
    secure: "સુરક્ષિત",
    spiritual: "આધ્યાત્મિક",
    support: "સહયોગ",
    next_page: "આગળનું પાનું",
    save_info: "માહિતી સાચવો",
    saved_profiles_title: "સાચવેલી પ્રોફાઇલ્સ",
    celestial_map: "આકાશી નકશો (રાશિ)",
    stars_obscured: "વાદળોને કારણે તારાઓ દેખાતા નથી. ફરી પ્રયાસ કરો.",
    go_back: "પાછા જાઓ",
    dismiss: "બંધ કરો",
    select_city_warning: "⚠️ ચોક્કસ ગણતરી માટે કૃપા કરીને સૂચિમાંથી શહેર પસંદ કરો.",
    search_assistant_placeholder: "દા.ત., ૨૦૨૪ માં ગુરુ ગોચરની મેષ રાશિ પર અસર",
    enter_full_name: "પૂરું નામ દાખલ કરો",
    feedback: "પ્રતિસાદ અને સૂચનો",
    feedback_title: "તમારા પવિત્ર પ્રતિસાદ અને સૂચનો",
    feedback_placeholder: "તમારો અનુભવ અથવા સૂચનો શેર કરો...",
    submit_feedback: "પ્રતિસાદ સબમિટ કરો",
    feedback_success: "તમારા પ્રતિસાદ બદલ આભાર!",
    first_name: "પ્રથમ નામ",
    second_name: "બીજું નામ",
    timeframe_placeholder: "દા.ત. આગામી ૩ મહિના",
    select_seeker: "સિકર પસંદ કરો",
    select_scholar: "સ્કોલર પસંદ કરો",
    seeker: "સિકર",
    scholar: "સ્કોલર",
    seeker_desc: "સામાન્ય લોકો માટે. સરળ ભાષામાં જીવન માર્ગદર્શન, કારકિર્દી અને દૈનિક ઉર્જા.",
    scholar_desc: "જ્યોતિષીઓ અને વિદ્યાર્થીઓ માટે. પ્રશ્ન માર્ગ અને ફળદીપિકા પર આધારિત ઊંડું જ્ઞાન અને સંસ્કૃત શ્લોકો.",
    siddhantic_precision: "સ્કોલર વિભાગ",
    personal_guidance: "સિકર વિભાગ",
    calculating_heavens: "ગણતરી થઈ રહી છે...",
    ask_help_guruji: "મદદ માટે ગુરુજીને પૂછો",
    sacred_conversation: "એક પવિત્ર સંવાદ",
    shastriya: "શાસ્ત્રીય",
    life_path: "જીવન માર્ગ",
    timeline: "સમયરેખા",
    siddhantic: "સદ્ધાંતિક",
    life_phase: "જીવનનો તબક્કો",
    wealth_health: "સંપત્તિ અને સ્વાસ્થ્ય",
    soul_map: "આત્માનો નકશો",
    power_score: "શક્તિ ગુણાંક",
    under_construction: "આ માર્ગ અત્યારે નિર્માણ હેઠળ છે.",
    return_home: "હોમ પર પાછા ફરો",
    get_verdict: "નિર્ણય મેળવો",
    latitude: "અક્ષાંશ",
    longitude: "રેખાંશ",
    timezone: "સમય ક્ષેત્ર",
    suggestion_title: "સૂચનો",
    suggestion_desc: "તમારા અનુભવને સુધારવામાં ગુરુજીને મદદ કરો",
    suggestion_placeholder: "તમારા વિચારો જણાવો અથવા સમસ્યાની જાણ કરો...",
    suggestion_send: "સૂચન મોકલો",
    suggestion_sent: "ગુરુજીને મોકલાયું",
    panchanga_title: "પંચાંગ",
    custom_panchanga: "તારીખ અને સ્થળ પસંદ કરો",
    timeline_title: "જીવન સમયરેખા ડેશબોર્ડ",
    contact_astrologer_title: "દૈવજ્ઞને તાંબુલ અર્પણ કરો",
    contact_astrologer_desc: "માર્ગદર્શન મેળવવાની એક પવિત્ર વિધિ",
    tambula_offering: "તાંબુલ અર્પણ",
    tambula_desc: "વૈદિક પરંપરામાં, જિજ્ઞાસુ દૈવજ્ઞને તાંબુલ અને દક્ષિણા અર્પણ કરે છે.",
    problem_label: "તમારી સમસ્યાનું વર્ણન કરો",
    problem_placeholder: "દા.ત. કારકિર્દીમાં વૃદ્ધિ, સ્વાસ્થ્ય સમસ્યાઓ...",
    contact_time_label: "સંપર્ક કરવા માટેનો પસંદગીનો સમય",
    contact_time_placeholder: "દા.ત. આવતીકાલે સવારે ૧૦ વાગ્યે",
    submit_problem: "વિનંતી સબમિટ કરો",
    problem_submitted_msg: "અમારા જ્યોતિષીઓ ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
    mangala_dosha: "મંગળ દોષ",
    conclusion_title: "એક લીટીમાં નિષ્કર્ષ",
    remedy_options_title: "તમારો ઉપાય માર્ગ પસંદ કરો",
    tier1_title: "ઉપાય પ્રારંભ",
    tier1_price: "₹99",
    tier1_meaning: "પ્રારંભિક ઉપાયો",
    tier2_title: "શુભ માર્ગ",
    tier2_price: "₹599",
    tier2_meaning: "ગ્રહોની શાંતિનો માર્ગ",
    tier3_title: "સર્વ કર્મ વિશ્લેષણ",
    tier3_price: "₹999",
    tier3_meaning: "સંપૂર્ણ જીવન વિશ્લેષણ",
    pay_now: "ચુકવણી કરો અને આગળ વધો",
    appointment_date: "તારીખ પસંદ કરો",
    appointment_time: "સમય પસંદ કરો",
    contact_astrologer_remedies: "ઉપાયો માટે જ્યોતિષીનો સંપર્ક કરો",
    analysis_tab_title: "વિશ્લેષણ",
    matching_tab_title: "મિલન",
    chat_tab_title: "એસ્ટ્રો ચેટ",
    help: "મદદ",
    footer_text: "દૈવી આદેશ • આકાશી ગોઠવણી • ઊંડું જ્ઞાન",
    celestial_insights_title: "વર્તમાન આકાશી આંતરદૃષ્ટિ",
    search_assistant_desc: "ગ્રહોના ગોચર અથવા ચોક્કસ જ્યોતિષીય ઘટનાઓ માટે શોધો.",
    searching: "શોધાઈ રહ્યું છે...",
    ask_stars: "તારાઓને પૂછો",
    sources: "સ્રોતો",
    invoke_guruji: "ગુરુજીનું આવાહન કરો",
    pranama_end: "પ્રણામ (સમાપ્ત)",
    career_guidance: "કારકિર્દી માર્ગદર્શન",
    love_marriage: "પ્રેમ અને લગ્ન",
    health_energy: "સ્વાસ્થ્ય અને ઊર્જા",
    spiritual_path: "આધ્યાત્મિક માર્ગ",
    seek_wisdom_message: "જ્ઞાન શોધો અને તારાઓ ગુરુજી દ્વારા જવાબ આપશે.",
    connecting: "જોડાઈ રહ્યું છે...",
    dhanyavaada: "ધન્યવાદ",
    pranama: "પ્રણામ",
    path: "માર્ગ",
    seeker_path: "સિકર માર્ગ",
    you_hint: "તમે (સંકેત): મારે મદદ જોઈએ છે ",
    muhurta_vivaha: "વિવાહ મુહૂર્ત",
    muhurta_grihapravesha: "ગૃહ પ્રવેશ",
    muhurta_bhoomi_pooja: "ભૂમિ પૂજન",
    muhurta_upanayana: "ઉપનયન (જનોઈ)",
    muhurta_namakarana: "નામકરણ",
    muhurta_annaprashana: "અન્નપ્રાશન",
    muhurta_aksharabhyasa: "અક્ષરાભ્યાસ",
    muhurta_vidyarambha: "વિદ્યારંભ",
    muhurta_karnavedha: "કર્ણવેધ",
    muhurta_choodakarana: "ચૌલ કર્મ (મુંડન)",
    muhurta_seemantham: "સીમંતોન્નયન",
    muhurta_vahana: "વાહન ખરીદી",
    muhurta_vyapaara: "વ્યાપાર આરંભ",
    muhurta_shop_opening: "દુકાન ઉદ્ઘાટન",
    muhurta_udyoga: "નોકરીમાં જોડાવા માટે",
    muhurta_swarna: "સોનું/ઝવેરાતની ખરીદી",
    muhurta_investments: "રોકાણ માટે",
    muhurta_yaatra: "મહત્વપૂર્ણ યાત્રા",
    muhurta_videsha: "વિદેશ ગમન",
    muhurta_shastra_kriya: "શસ્ત્રક્રિયા (સર્જરી)",
    muhurta_medical_start: "ચિકિત્સા આરંભ",
    muhurta_abhijit: "અભિજિત મુહૂર્ત",
    muhurta_brahma: "બ્રહ્મ મુહૂર્ત",
    muhurta_shilaanyasa: "શિલાન્યાસ",
    muhurta_renting: "નવું ભાડું/સ્થળાંતર",
    muhurta_contracts: "કરાર પર હસ્તાક્ષર",
    muhurta_legal: "કાનૂની કાર્યવાહી",
    muhurta_agriculture: "કૃષિ કાર્ય",
    home: "હોમ",
    daily_nav: "દૈનિક",
    oracle_nav: "ઓરેકલ",
    chat_nav: "ચેટ",
    donate_support: "દાન અને સહયોગ",
    next_analysis: "આગળ: વિશ્લેષણ પસંદ કરો",
    sacred_geometry: "પવિત્ર ભૂમિતિ • પ્રાચીન તર્ક",
    birth_analysis: "જન્મ વિશ્લેષણ",
    my_character: "મારો સ્વભાવ",
    rasi_kundli: "રાશિ કુંડળી",
    vimshottari: "વિંશોત્તરી",
    ashtakavarga: "અષ્ટકવર્ગ",
    planet_sun: "સૂર્ય",
    planet_moon: "ચંદ્ર",
    planet_mars: "મંગળ",
    planet_mercury: "બુધ",
    planet_jupiter: "ગુરુ",
    planet_venus: "શુક્ર",
    planet_saturn: "શનિ",
    planet_rahu: "રાહુ",
    planet_ketu: "કેતુ",
    planet_lagna: "લગ્ન",
    planet_mandi: "માંદી",
    rasi_mesha: "મેષ",
    rasi_vrishabha: "વૃષભ",
    rasi_mithuna: "મિથુન",
    rasi_karka: "કર્ક",
    rasi_simha: "સિંહ",
    rasi_kanya: "કન્યા",
    rasi_tula: "તુલા",
    rasi_vrishchika: "વૃશ્ચિક",
    rasi_dhanu: "ધનુ",
    rasi_makara: "મકર",
    rasi_kumbha: "કુંભ",
    rasi_meena: "મીન",
    muhurta_analysis: "સિદ્ધાંતિક સંરેખણ",
    auspicious_time: "શુભ સમયગાળો",
    verdict: "વૈદિક નિર્ણય",
    planetary_positions: "ગ્રહોની સ્થિતિ",
    classical_references: "શાસ્ત્રીય પ્રમાણ",
    panchanga_breakdown: "પંચાંગ વિશ્લેષણ",
    technical_summary: "તકનીકી સારાંશ",
    saved_readings: "આર્કાઇવ",
    no_readings: "આર્કાઇવ ખાલી છે",
    no_readings_desc: "તમારા આકાશી જ્ઞાનને સાચવવા માટે કુંડળી વિશ્લેષણ કરો.",
    clear_history_confirm: "બધા સાચવેલા રીડિંગ્સ ભૂંસી નાખવા છે?",
    vastu_title: "વાસ્તુ શાસ્ત્ર",
    vastu_desc: "તમારી જગ્યાને આકાશી ઉર્જા સાથે જોડો",
    vastu_analysis: "સ્થાપત્ય વેદ વિશ્લેષણ",
    home_harmony: "ગૃહ સુમેળ",
    palm_reading_title: "હસ્તરેખા વિજ્ઞાન",
    palm_reading_desc: "હસ્ત રેખા શાસ્ત્રનું પ્રાચીન વિજ્ઞાન",
    upload_palm: "હથેળીનો ફોટો અપલોડ કરો",
    palm_instructions: "સૂચનાઓ: તમારી હથેળીને સપાટ રાખો. પૂરતો પ્રકાશ હોવો જોઈએ.",
    analyzing_palm: "ભાગ્યની રેખાઓ વંચાઈ રહી છે...",
    palm_analysis_res: "હસ્ત રેખા વિશ્લેષણ",
    camera_access: "કેમેરા ખોલો",
    gallery_access: "ગેલેરીમાંથી પસંદ કરો",
    invalid_palm_error: "દૈવી દૃષ્ટિ અહીં હથેળીને સ્પષ્ટ રીતે જોઈ શકતી નથી. કૃપા કરીને સ્પષ્ટ ફોટો અપલોડ કરો.",
    classical_source_authority: "શાસ્ત્રીય સ્રોત અધિકાર",
    welcome_tour: "એસ્ટ્રો લોજિકમાં સ્વાગત છે",
    welcome_tour_desc: "તમારી પવિત્ર યાત્રાનું અન્વેષણ કરીએ.",
    seeker_mode_active: "સિકર માર્ગ સક્રિય",
    scholar_mode_active: "સ્કોલર માર્ગ સક્રિય",
    seeker_tour_desc: "તમે સિકર મોડમાં છો. અમે સરળ અને વ્યવહારુ માર્ગદર્શન આપીએ છીએ.",
    scholar_tour_desc: "તમે સ્કોલર મોડમાં છો. ઊંડી તકનીકી વિગતો અને શ્લોકોની અપેક્ષા રાખો.",
    sacred_dashboard: "સેલેસ્ટિયલ ડેશબોર્ડ",
    dashboard_tour_desc: "ઝડપી રીડિંગ્સ અને પંચાંગ અપડેટ્સ માટે તમારું મુખ્ય કેન્દ્ર.",
    guruji_tour: "ગુરુજીની સલાહ લો",
    guruji_tour_desc: "ગુરુજી બટન દ્વારા તમે સીધા પ્રશ્નો પૂછી શકો છો.",
    navigation_tour: "સરળ નેવિગેશન",
    nav_tour_desc: "વિવિધ સાધનો વચ્ચે સ્વિચ કરવા માટે નીચેના ટેબ બારનો ઉપયોગ કરો.",
    save_profile_error: "કૃપા કરીને સાચવવા માટે નામ દાખલ કરો.",
    profile_saved: "પ્રોફાઇલ સાચવી લેવામાં આવી છે.",
    profile_saved_for: "{name} ની પ્રોફાઇલ સાચવી.",
    life_partner_analysis: "જીવન સાથી વિશ્લેષણ",
    prashna_analysis: "પ્રશ્ન વિશ્લેષણ",
    stars_silent: "તારો શાંત છે. ફરી પ્રયાસ કરો.",
    celestial_connection_failed: "આકાશી જોડાણ નિષ્ફળ થયું.",
    switch_to_dark: "ડાર્ક મોડ પર સ્વિચ કરો",
    switch_to_light: "લાઇટ મોડ પર સ્વિચ કરો",
    blog: "બ્લોગ",
    blog_desc: "સિદ્ધાંત અને હોરા",
    enter_details_warning: "ચોક્કસ ગણતરી માટે કૃપા કરીને જન્મ તારીખ અને સમય દાખલ કરો.",
    sending: "મોકલી રહ્યું છે...",
    offline: "ઓફલાઇન",
    csr_tagline: "ધર્મ અને કરુણા",
    csr_revenue_committed: "આવક પ્રતિબદ્ધતા",
    csr_souls_nourished: "તૃપ્ત આત્માઓ",
    csr_verified_integrity: "ચકાસાયેલ અખંડિતતા",
    csr_schools_supported: "સહાયિત શાળાઓ",
    csr_kits_distributed: "વિતરિત કિટ્સ",
    csr_volunteer_hours: "સ્વયંસેવક કલાકો",
    csr_homes_adopted: "દત્તક લીધેલા ઘરો",
    csr_elders_assisted: "સહાયિત વૃદ્ધો",
    csr_medical_camps: "મેડિકલ કેમ્પ",
    csr_special_children_initiative: "વિશેષ બાળકો માટેની પહેલ",
    csr_elder_care_program: "વૃદ્ધ સંભાળ કાર્યક્રમ",
    csr_revenue_committed_90: "૯૦% આવક પ્રતિબદ્ધતા",
    csr_holistic_care_100: "૧૦૦% સર્વાંગી સંભાળ",
    seeker_mode_desc_short: "સિકર મોડ • પવિત્ર માર્ગદર્શન",
    scholar_mode_desc_short: "સ્કોલર મોડ • સિદ્ધાંતિક નિખાલસતા",
    saved_profiles_desc: "તાજેતરના ચાર્ટ્સ",
    today_panchanga: "આજનું પંચાંગ",
    brand_tagline: "પ્રાચીન જ્ઞાન, આધુનિક તર્ક"
};

const bn_full = {
    brand_name: "অ্যাস্ট্রো লজিক",
    tagline: "প্রাচীন বিজ্ঞান ও আধুনিক যুক্তির মেলবন্ধন",
    begin_journey: "যাত্রা শুরু করুন",
    choose_path: "আপনার পথ বেছে নিন",
    disclaimer: "জ্যোতিষীয় গণনাগুলি গ্রহের অবস্থানের উপর ভিত্তি করে রচিত এবং এগুলি কেবলমাত্র সম্ভাবনা নির্দেশ করে, কোনো সুনিশ্চিত ফলাফল নয়।",
    planetary_transit_in: "তে",
    horoscope: "রাশিফল",
    matching: "যোটক বিচার",
    life_partner: "জীবন সঙ্গী",
    daily: "দৈনিক রাশিফল",
    muhurta: "শুভ মুহূর্ত",
    numerology: "সংখ্যাতত্ত্ব",
    chat: "অ্যাস্ট্রো চ্যাট",
    prashna: "প্রশ্ন",
    guruji: "গুরুজি",
    you: "আপনি",
    guruji_welcome: "আপনার জীবন পথ, গ্রহের ট্রানজিট বা যেকোনো আধ্যাত্মিক দিকনির্দেশনা সম্পর্কে গুরুজিকে জিজ্ঞাসা করুন।",
    guruji_thinking: "গুরুজি তারাদের গণনা করছেন...",
    error_guruji: "মহাজাগতিক সংযোগ বিচ্ছিন্ন। দয়া করে পরে চেষ্টা করুন।",
    ask_guruji_placeholder: "গুরুজিকে প্রশ্ন জিজ্ঞাসা করুন...",
    switch_mode: "পথ পরিবর্তন করুন",
    menu_details: "জন্ম বিশ্লেষণ",
    menu_timeline: "জীবন বিবর্তন (অতীত, বর্তমান, ভবিষ্যৎ)",
    menu_hora: "শাস্ত্রীয় হোরা বিশ্লেষণ",
    menu_sphta: "গ্রহের স্পষ্ট স্থিতি",
    menu_rasi: "রাশি কুণ্ডলী",
    menu_navamsha: "নবাংশ কুণ্ডলী",
    menu_bhava: "ভাব চলিত",
    menu_bhava_analysis: "দ্বাদশ ভাব বিশ্লেষণ",
    menu_sandhi: "সন্ধি বিশ্লেষণ",
    menu_panchangam: "পঞ্চাঙ্গ",
    menu_dasha: "বিংশোত্তরী দশা",
    menu_shadvarga: "ষড়বর্গ",
    shadvarga_strengths: "ষড়বর্গ শক্তি",
    shadbala_analysis: "ষড়বল বিশ্লেষণ",
    energy_strength: "শক্তি সামর্থ্য",
    planetary_power: "গ্রহের ক্ষমতা",
    menu_yogas: "যোগ বিশ্লেষণ",
    menu_maitri: "পঞ্চধা মৈত্রী",
    menu_ashtaka: "অষ্টকবর্গ",
    menu_trisputa: "ত্রিস্ফুট বিশ্লেষণ",
    menu_dhumadi: "ধূমাদি গ্রহ",
    menu_basic_details: "সাধারণ জন্ম বিবরণ",
    menu_yoga: "যোগ বিচার",
    menu_career: "কেরিয়ার ও সাফল্য",
    menu_health: "স্বাস্থ্য ও শক্তি",
    menu_money: "সম্পদ ও অর্থ",
    menu_transit: "গ্রহের গোচর",
    menu_dasha_effect: "দশার প্রভাব",
    menu_sade_sati: "সাড়ে সাতি বিশ্লেষণ",
    menu_gemstones: "রত্ন ও রুদ্রাক্ষ",
    menu_nakshatra: "নক্ষত্র রহস্য",
    menu_doshas: "দোষ বিচার (কালসর্প/পিতৃ)",
    menu_character: "চরিত্র ও ব্যক্তিত্ব",
    menu_numerology: "সংখ্যাতত্ত্ব বিশ্লেষণ",
    back: "পিছনে",
    submit: "কুণ্ডলী তৈরি করুন",
    quick_profile: "দ্রুত প্রোফাইল",
    enter_details_wisdom: "ব্যক্তিগত দিকনির্দেশনার জন্য বিশদ বিবরণ দিন",
    save_continue: "সংরক্ষণ ও এগিয়ে যান",
    continue: "এগিয়ে যান ➔",
    next_choose_analysis: "পরবর্তী: বিশ্লেষণ বেছে নিন ➔",
    skip_for_now: "এখনকার জন্য থাক",
    lang_select: "ভাষা",
    loshu_grid: "লোশু গ্রিড",
    full_name: "পুরো নাম",
    classical_predictions: "শাস্ত্রীয় ভবিষ্যৎবাণী",
    sacred_guide: "পবিত্র নির্দেশক",
    seeker_scholar_desc: "সহজ জীবন নির্দেশনার জন্য 'সিকার' বাছুন। গভীর কারিগরি বা শাস্ত্রীয় আলোচনার জন্য 'স্কলার' বাছুন।",
    save_profile: "প্রোফাইল সংরক্ষণ করুন",
    saved_profiles: "সাম্প্রতিক কুণ্ডলী",
    matching_title: "দিব্য সম্পর্ক সমন্বয়",
    conclusion: "দিব্য রায়",
    select_rasi: "রাশি বেছে নিন",
    daily_title: "আজকের গ্রহ সংযোগ",
    muhurta_title: "শুভ মুহূর্ত সময়াংশ",
    muhurta_select: "উদ্দেশ্য বেছে নিন",
    sacred_intake: "উপাত্ত সংগ্রহ",
    partner_one: "প্রথম সাথী",
    partner_two: "দ্বিতীয় সাথী",
    birth_location: "জন্মস্থান",
    timeframe: "সময়সীমা",
    location: "অবস্থান",
    quick_search: "দ্রুত অনুসন্ধান",
    oracle: "ওরাকল",
    name: "নাম",
    date: "তারিখ",
    nakshatra: "নক্ষত্র",
    ask_guruji: "গুরুজিকে জিজ্ঞাসা করুন",
    deep_inquiry: "গভীর অনুসন্ধান",
    seek_answer: "উত্তর খুঁজুন",
    name_of_soul: "নাম",
    birth_date: "জন্ম তারিখ",
    birth_time: "জন্ম সময়",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    search_city_placeholder: "শহর খুঁজুন...",
    muhurta_search_placeholder: "উদ্দেশ্য খুঁজুন...",
    prashna_placeholder: "তারাদের কাছে আপনার কি প্রশ্ন আছে?",
    guruji_listening: "গুরুজি শুনছেন...",
    connection_interrupted: "সংযোগ বিচ্ছিন্ন হয়েছে",
    disconnected: "বিচ্ছিন্ন",
    support_guruji: "গুরুজিকে সমর্থন করুন",
    scan_to_support: "সমর্থন করতে স্ক্যান করুন",
    scan_to_donate: "GPay / UPI-এর মাধ্যমে অনুদান দিতে স্ক্যান করুন",
    support_mission: "আমাদের মিশনে পাশে দাঁড়ান",
    support_quote: "আপনি এইমাত্র একটি ব্যক্তিগত জ্যোতিষ পরামর্শ পেলেন। যদি এটি আপনার ভালো লেগে থাকে, তবে আমাদের এগিয়ে যেতে সাহায্য করতে পারেন।",
    csr_title: "অ্যাস্ট্রো লজিক সামাজিক প্রভাব",
    csr_books_title: "বিশেষ শিশুদের জন্য শিক্ষা সহায়তা",
    csr_books_desc: "অ্যাস্ট্রো লজিক বিশেষ শিশুদের সামগ্রিক উন্নয়নে প্রতিশ্রুতিবদ্ধ। আমরা ভারতের বিভিন্ন স্কুলে শিক্ষা সামগ্রী সরবরাহ করি। আমাদের আয়ের ৯০% এই মহৎ উদ্দেশ্যে ব্যয় হয়।",
    csr_oldage_title: "বৃদ্ধ বয়সে মর্যাদা: বৃদ্ধাশ্রমের যত্ন",
    csr_oldage_desc: "আমাদের এই উদ্যোগ পরিত্যক্ত প্রবীণদের স্বাস্থ্য ও পুষ্টির যত্ন নেওয়ার জন্য নিবেদিত।",
    secure: "সুরক্ষিত",
    spiritual: "আধ্যাত্মিক",
    support: "সমর্থন",
    next_page: "পরবর্তী পাতা",
    save_info: "তথ্য সংরক্ষণ করুন",
    saved_profiles_title: "সংরক্ষিত প্রোফাইল",
    celestial_map: "মহাজাগতিক মানচিত্র (রাশি)",
    stars_obscured: "মেঘের কারণে তারা দেখা যাচ্ছে না। আবার চেষ্টা করুন।",
    go_back: "পিছনে যান",
    dismiss: "বাতিল",
    select_city_warning: "⚠️ সঠিক গণনার জন্য তালিকা থেকে একটি শহর বাছুন।",
    search_assistant_placeholder: "উদা: ২০২৪ সালে মেষ রাশির উপর বৃহস্পতির প্রভাব",
    enter_full_name: "পুরো নাম লিখুন",
    feedback: "মতামত ও পরামর্শ",
    feedback_title: "আপনার মতামত ও পরামর্শ",
    feedback_placeholder: "আপনার অভিজ্ঞতা বা পরামর্শ তারাদের সাথে ভাগ করুন...",
    submit_feedback: "মতামত পাঠান",
    feedback_success: "মতামত পাঠানোর জন্য আপনাকে ধন্যবাদ!",
    first_name: "প্রথম নাম",
    second_name: "দ্বিতীয় নাম",
    timeframe_placeholder: "উদা: আগামী ৩ মাস",
    select_seeker: "সিকার বাছুন",
    select_scholar: "স্কলার বাছুন",
    seeker: "সিকার",
    scholar: "স্কলার",
    seeker_desc: "সাধারণ মানুষের জন্য সহজ জীবন নির্দেশনা, কেরিয়ার এবং প্রতিদিনের শক্তির পূর্বাভাস।",
    scholar_desc: "জ্যোতিষী ও শিক্ষার্থীদের জন্য গভীর কারিগরি জ্ঞান, শাস্ত্রীয় শ্লোক ও সূক্ষ্ম গাণিতিক বিশ্লেষণ।",
    siddhantic_precision: "স্কলার বিভাগ",
    personal_guidance: "সিকার বিভাগ",
    calculating_heavens: "স্বর্গীয় গণনা চলছে...",
    ask_help_guruji: "সাহায্যের জন্য গুরুজিকে বলুন",
    sacred_conversation: "একটি পবিত্র সংলাপ",
    shastriya: "ধর্মীয়",
    life_path: "জীবন পথ",
    timeline: "ঘটনাক্রম",
    siddhantic: "সিদ্ধান্ত",
    life_phase: "জীবনের পর্যায়",
    wealth_health: "সম্পদ ও স্বাস্থ্য",
    soul_map: "আত্মার মানচিত্র",
    power_score: "শক্তি সংখ্যা",
    under_construction: "এই পথটি বর্তমানে নির্মাণাধীন।",
    return_home: "হোমে ফিরে যান",
    get_verdict: "বিচার পান",
    latitude: "অক্ষাংশ",
    longitude: "দ্রাঘিমাংশ",
    timezone: "সময় অঞ্চল",
    suggestion_title: "পরামর্শ",
    suggestion_desc: "অভিজ্ঞতা উন্নত করতে গুরুজিকে সাহায্য করুন",
    suggestion_placeholder: "পরামর্শ লিখুন বা সমস্যা জানান...",
    suggestion_send: "পরামর্শ পাঠান",
    suggestion_sent: "গুরুজিকে পাঠানো হয়েছে",
    panchanga_title: "পঞ্জিকা",
    custom_panchanga: "তারিখ ও স্থান বাছুন",
    timeline_title: "জীবনরেখা ড্যাশবোর্ড",
    contact_astrologer_title: "দৈবজ্ঞকে তাম্বুল অর্পণ",
    contact_astrologer_desc: "পরামর্শ চাওয়ার একটি পবিত্র আচার",
    tambula_offering: "তাম্বুল অর্পণ",
    tambula_desc: "বৈদিক রীতি অনুযায়ী, একজন অনুসন্ধানী গুরুকে পান, সুপারি ও দক্ষিণা অর্পণ করেন।",
    problem_label: "আপনার সমস্যা বর্ণনা করুন",
    problem_placeholder: "উদা: কেরিয়ার উন্নতি, স্বাস্থ্য সমস্যা...",
    contact_time_label: "যোগাযোগ করার পছন্দের সময়",
    contact_time_placeholder: "উদা: আগামীকাল সকাল ১০টা",
    submit_problem: "অনুরোধ পাঠান",
    problem_submitted_msg: "আমাদের জ্যোতিষীরা শীঘ্রই আপনার সাথে যোগাযোগ করবেন।",
    mangala_dosha: "মঙ্গল দোষ",
    conclusion_title: "এক লাইনে সংক্ষেপ",
    remedy_options_title: "আপনার প্রতিকার পথ বেছে নিন",
    tier1_title: "উপায় প্রারম্ভ",
    tier1_price: "₹৯৯",
    tier1_meaning: "প্রাথমিক প্রতিকার",
    tier2_title: "শুভ মার্গ",
    tier2_price: "₹৫৯৯",
    tier2_meaning: "শান্তির পথ",
    tier3_title: "সর্ব কর্ম বিশ্লেষণ",
    tier3_price: "₹৯৯৯",
    tier3_meaning: "সম্পূর্ণ জীবন বিশ্লেষণ",
    pay_now: "প্রদান করুন ও এগিয়ে যান",
    appointment_date: "তারিখ বাছুন",
    appointment_time: "সময় বাছুন",
    contact_astrologer_remedies: "প্রতিকারের জন্য জ্যোতিষীর সাথে কথা বলুন",
    analysis_tab_title: "বিশ্লেষণ",
    matching_tab_title: "মিলন",
    chat_tab_title: "অ্যাস্ট্রো চ্যাট",
    help: "সাহায্য",
    footer_text: "ঐশ্বরিক নিয়ম • মহাজাগতিক সারিবদ্ধতা • গভীর জ্ঞান",
    celestial_insights_title: "বর্তমান মহাজাগতিক অন্তর্দৃষ্টি",
    search_assistant_desc: "গ্রহের গোচর বা নির্দিষ্ট জ্যোতিষীয় ঘটনা সম্পর্কে অনুসন্ধান করুন।",
    searching: "অনুসন্ধান চলছে...",
    ask_stars: "তারাদের জিজ্ঞাসা করুন",
    sources: "সূত্র",
    invoke_guruji: "গুরুজিকে আহ্বান করুন",
    pranama_end: "প্রণাম (শেষ)",
    career_guidance: "কেরিয়ার পরামর্শ",
    love_marriage: "প্রেম ও বিবাহ",
    health_energy: "স্বাস্থ্য ও শক্তি",
    spiritual_path: "আধ্যাত্মিক পথ",
    seek_wisdom_message: "জ্ঞান সন্ধান করুন এবং গুরুজির মাধ্যমে তারারা উত্তর দেবেন।",
    connecting: "সংযোগ করা হচ্ছে...",
    dhanyavaada: "ধন্যবাদ",
    pranama: "প্রণাম",
    path: "পথ",
    seeker_path: "সিকার পথ",
    you_hint: "আপনি (ইঙ্গিত): আমি জানতে চাই ",
    muhurta_vivaha: "বিবাহ মুহূর্ত",
    muhurta_grihapravesha: "গৃহপ্রবেশ",
    muhurta_bhoomi_pooja: "ভূমি পূজা",
    muhurta_upanayana: "উপনয়ন",
    muhurta_namakarana: "নামকরণ",
    muhurta_annaprashana: "অন্নপ্রাশন",
    muhurta_aksharabhyasa: "হাতেখড়ি",
    muhurta_vidyarambha: "বিদ্যারম্ভ",
    muhurta_karnavedha: "কর্ণভেদ",
    muhurta_choodakarana: "চূড়াকরণ (মুণ্ডন)",
    muhurta_seemantham: "সাধভক্ষণ (সীমন্তোন্নয়ন)",
    muhurta_vahana: "যানবাহন ক্রয়",
    muhurta_vyapaara: "ব্যবসা আরম্ভ",
    muhurta_shop_opening: "দোকান উদ্বোধন",
    muhurta_udyoga: "কাজে যোগদান",
    muhurta_swarna: "স্বর্ণ ক্রয়",
    muhurta_investments: "বিনিয়োগ",
    muhurta_yaatra: "গুরুত্বপূর্ণ যাত্রা",
    muhurta_videsha: "বিদেশ যাত্রা",
    muhurta_shastra_kriya: "অস্ত্রোপচার (সার্জারি)",
    muhurta_medical_start: "চিকিৎসা আরম্ভ",
    muhurta_abhijit: "অভিজিৎ মুহূর্ত",
    muhurta_brahma: "ব্রহ્ম মুহূর্ত",
    muhurta_shilaanyasa: "ভিত্তিপ্রস্তর স্থাপন",
    muhurta_renting: "বাড়ি পরিবর্তন/ভাড়া নেওয়া",
    muhurta_contracts: "চুক্তি স্বাক্ষর",
    muhurta_legal: "আইনি কার্যক্রম",
    muhurta_agriculture: "কৃষি কাজ",
    home: "হোম",
    daily_nav: "দৈনিক",
    oracle_nav: "ওরাকল",
    chat_nav: "চેટ",
    donate_support: "অনুদান ও সমর্থন",
    next_analysis: "পরবর্তী: বিশ্লেষণ বাছুন",
    sacred_geometry: "পবিত্র জ্যামিতি • প্রাচীন যুক্তি",
    birth_analysis: "জন্ম বিশ্লেষণ",
    my_character: "আমার চরিত্র",
    rasi_kundli: "রাশি কুণ্ডলী",
    vimshottari: "বিংশোত্তরী",
    ashtakavarga: "অষ্টকবর্গ",
    planet_sun: "সূর্য",
    planet_moon: "চন্দ্র",
    planet_mars: "মঙ্গল",
    planet_mercury: "বুধ",
    planet_jupiter: "বৃহস্পতি",
    planet_venus: "শুক্র",
    planet_saturn: "শনি",
    planet_rahu: "রাহু",
    planet_ketu: "কেতু",
    planet_lagna: "লগ্ন",
    planet_mandi: "মান্দি",
    rasi_mesha: "মেষ",
    rasi_vrishabha: "বৃষ",
    rasi_mithuna: "মিথুন",
    rasi_karka: "কর্কট",
    rasi_simha: "সিংহ",
    rasi_kanya: "কন্যা",
    rasi_tula: "তুলা",
    rasi_vrishchika: "বৃশ্চিক",
    rasi_dhanu: "ধনু",
    rasi_makara: "মকর",
    rasi_kumbha: "কুম্ভ",
    rasi_meena: "মীন",
    muhurta_analysis: "সূক্ষ্ম সংযোগ",
    auspicious_time: "শুভ সময়",
    verdict: "বৈদিক বিচার",
    planetary_positions: "গ্রহের অবস্থান",
    classical_references: "শাস্ত্রীয় প্রমাণ",
    panchanga_breakdown: "পঞ্জিকা বিশ্লেষণ",
    technical_summary: "কারিগরি সারসংক্ষেপ",
    saved_readings: "আর্কাইভ",
    no_readings: "আর্কাইভ খালি",
    no_readings_desc: "আপনার বিশদ জানতে কুণ্ডলী বা প্রশ্ন বিশ্লেষণ করুন।",
    clear_history_confirm: "সব সংরক্ষিত তথ্য মুছে ফেলবেন?",
    vastu_title: "বাস্তু শাস্ত্র",
    vastu_desc: "আপনার স্থানকে স্বর্গীয় শক্তির সাথে মিলিয়ে নিন",
    vastu_analysis: "স্থাপত্য বেদ বিশ্লেষণ",
    home_harmony: "গৃহ সুখ",
    palm_reading_title: "হস্তরেখা বিচার",
    palm_reading_desc: "প্রাচীন হস্তরেখা শাস্ত্র",
    upload_palm: "হাতের করতল ছবি আপলোড করুন",
    palm_instructions: "নির্দেশিকা: হাতের তালু একটি সমতল স্থানে রেখে সরাসরি উপর থেকে ছবি তুলুন।",
    analyzing_palm: "ভাগ্যের রেখা পড়া হচ্ছে...",
    palm_analysis_res: "হস্তরেখা বিশ্লেষণ",
    camera_access: "ক্যামেরা খুলুন",
    gallery_access: "গ্যালারি থেকে বাছুন",
    invalid_palm_error: "দিব্য দৃষ্টি এখানে করতল স্পষ্ট দেখতে পাচ্ছে না। দয়া করে একটি পরিষ্কার ছবি দিন।",
    classical_source_authority: "শাস্ত্রীয় উৎস কর্তৃপক্ষ",
    welcome_tour: "অ্যাস্ট্রো লজিকে স্বাগতম",
    welcome_tour_desc: "আপনার মহাজাগতিক যাত্রা শুরু করি।",
    seeker_mode_active: "সিকার পথ সক্রিয়",
    scholar_mode_active: "স্কলার পথ সক্রিয়",
    seeker_tour_desc: "আপনি এখন সিকার মোডে আছেন। আমরা সহজ এবং ব্যবহারিক পরামর্শ দেব।",
    scholar_tour_desc: "আপনি এখন স্কলার মোডে আছেন। গভীর গাণিতিক ও শাস্ত্রীয় বিশ্লেষণ আশা করুন।",
    sacred_dashboard: "মহাজাগতিক ড্যাশবোর্ড",
    dashboard_tour_desc: "পঞ্জিকা এবং বিভিন্ন জ্যোতিষীয় সরঞ্জামের সহজ মাধ্যম।",
    guruji_tour: "গুরুজির পরামর্শ নিন",
    guruji_tour_desc: "নিচের ভাসমান 'গুরুজি' বাটনটি ক্লিক করে সরাসরি প্রশ্ন করতে পারেন।",
    navigation_tour: "সহজ নেভিগেশন",
    nav_tour_desc: "বিভিন্ন মেনু ও ফিচারের মধ্যে পরিবর্তন করতে নিচের বারটি ব্যবহার করুন।",
    save_profile_error: "সংরক্ষণ করার জন্য একটি নাম লিখুন।",
    profile_saved: "প্রোফাইল সংরক্ষিত হয়েছে।",
    profile_saved_for: "{name} এর প্রোফাইল সংরক্ষিত।",
    life_partner_analysis: "জীবনসঙ্গী বিশ্লেষণ",
    prashna_analysis: "প্রশ্ন বিশ্লেষণ",
    stars_silent: "তারাদের সাড়া পাওয়া যাচ্ছে না। আবার চেষ্টা করুন।",
    celestial_connection_failed: "দিব্য সংযোগ স্থাপন করা যায়নি।",
    switch_to_dark: "ডার্ক মোড",
    switch_to_light: "লাইট মোড",
    blog: "ব্লগ",
    blog_desc: "সিদ্ধান্ত ও হোরা",
    enter_details_warning: "সঠিক গণনার জন্য জন্ম তারিখ ও সময় দিন।",
    sending: "পাঠানো হচ্ছে...",
    offline: "অফলাইন",
    csr_tagline: "ধর্ম ও সেবা",
    csr_revenue_committed: "রাজস্ব প্রতিশ্রুতি",
    csr_souls_nourished: "উপকারভোগী",
    csr_verified_integrity: "যাচাইকৃত সততা",
    csr_schools_supported: "সমর্থিত বিদ্যালয়",
    csr_kits_distributed: "বিতরণকৃত কিট",
    csr_volunteer_hours: "সেবা সময়",
    csr_homes_adopted: "গৃহীত আবাস",
    csr_elders_assisted: "সহায়তা প্রাপ্ত প্রবীণ",
    csr_medical_camps: "মেডিক্যাল ক্যাম্প",
    csr_special_children_initiative: "বিশেষ শিশুদের উদ্যোগ",
    csr_elder_care_program: "বৃদ্ধাশ্রম সেবা কর্মসূচি",
    csr_revenue_committed_90: "৯০% রাজস্ব প্রতিশ্রুতি",
    csr_holistic_care_100: "১০০% সামগ্রিক সেবা",
    seeker_mode_desc_short: "সিকার মোড • পবিত্র নির্দেশ",
    scholar_mode_desc_short: "স্কলার মোড • সূক্ষ্ম বিশ্লেষণ",
    saved_profiles_desc: "সাম্প্রতিক কুণ্ডলী",
    today_panchanga: "আজকের পঞ্জিকা",
    brand_tagline: "প্রাচীন ঐতিহ্য, আধুনিক বিচার"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    const nextBlockStart = content.indexOf(': {', startIndex + startMarker.length);
    let endIndex = content.lastIndexOf('},', nextBlockStart === -1 ? content.length : nextBlockStart);
    
    // Fallback search for end
    if (endIndex === -1 || endIndex < startIndex) {
        endIndex = content.indexOf('  },', startIndex);
    }

    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 3);
}

let newContent = content;
newContent = updateLanguage(newContent, 'gu', gu_full);
newContent = updateLanguage(newContent, 'bn', bn_full);

fs.writeFileSync(filePath, newContent);
console.log("Updated Gujarati and Bengali translations.");
