import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const kok_full = {
    brand_name: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್",
    tagline: "ದೈವಿಕ್ ಜ್ಞಾನ್ ಆನಿ ತರ್ಕಾಚೊ ಸಂಗ್ಮ್",
    begin_journey: "ಪ್ರಯಾಣ ಸುರು ಕರ್",
    choose_path: "ತುಜಿ ವಾಟ್ ವಿಂಚಿ",
    disclaimer: "ಜ್ಯೋತಿಷ್ಯ ಮಾರ್ಗದರ್ಶನ್ ಗ್ರಹಾಂಚ್ಯಾ ಗಣಿತಾಚೆರ್ ಆದಾರಿತ್ ಆಸಾ, ಫಲಿತಾಂಶಚಿ ಭರವಸೊ ದೀನಾ.",
    planetary_transit_in: "ಕಡೆ",
    horoscope: "ಜಾತಕ್",
    matching: "ಗುಣಮೇಲನ್",
    life_partner: "ಜೀವನ್ ಸಂಗಾತಿ",
    daily: "ದಿನಾಚೆಂ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    numerology: "ಅಂಕಶಾಸ್ತ್ರ",
    chat: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    prashna: "ಪ್ರಶ್ನ",
    guruji: "ಗುರೂಜಿ",
    you: "ತುಂ",
    guruji_welcome: "ತುಜ್ಯಾ ಜೀವನ ಶೈಲಿ, ಗ್ರಹಾಂಚೆ ಬದಲಾವಣೆ ವಾ ಮಾರ್ಗದರ್ಶನಾ ಖಾತಿರ್ ಗುರೂಜಿಕ್ ವಿಚಾರ್.",
    guruji_thinking: "ಗುರೂಜಿ ತಾರಾಂಚೆ ಗಣನ್ ಕರ್ತಾ...",
    error_guruji: "ಸಂಪರ್ಕ್ ಸಾರ್ಕೊ ನಾ. ಪರ್ತ್ಯಾನ್ ಪ್ರಯತ್ನ ಕರ್.",
    ask_guruji_placeholder: "ಗುರೂಜಿಕ್ ತುಜೊ ಪ್ರಶ್ನ ವಿಚಾರ್...",
    switch_mode: "ಪಹಾದಿ ಬದಲಾವಣೆ",
    menu_details: "ಜನ್ಮ ವಿಶ್ಲೇಷಣ",
    menu_timeline: "ಜೀವನ್ ಕಾಲಕ್ರಮ",
    menu_hora: "ಹೋರಾ ವಿಶ್ಲೇಷಣ",
    menu_sphta: "ಗ್ರಹ ಸ್ಪಷ್ಟ್",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಚಲಿತ",
    menu_bhava_analysis: "ಭಾವ ವಿಶ್ಲೇಷಣ",
    menu_sandhi: "ಸಂಧಿ ವಿಶ್ಲೇಷಣ",
    menu_panchangam: "ಪಂಚಾಂಗ",
    menu_dasha: "ದಶಾ ಫಲ",
    menu_shadvarga: "ಷಡ್ವರ್ಗ",
    shadvarga_strengths: "ಷಡ್ವರ್ಗ ಬರ್ರಿ",
    shadbala_analysis: "ಷಡ್ಬಲ",
    energy_strength: "ಶಕ್ತಿ",
    planetary_power: "ಗ್ರಹ ಸಕತ್",
    menu_yogas: "ಯೋಗ ವಿಶ್ಲೇಷಣ",
    menu_maitri: "ಗ್ರಹ ಮೈತ್ರಿ",
    menu_ashtaka: "ಅಷ್ಟಕವರ್ಗ",
    menu_trisputa: "ತ್ರಿಸ್ಫುಟ",
    menu_dhumadi: "ಧೂಮಾದಿ",
    menu_basic_details: "ಜನ್ಮ ವಿವರ",
    menu_yoga: "ಯೋಗ",
    menu_career: "ವೃತ್ತಿ ಆನಿ ಯಶಸ್",
    menu_health: "ಭಲಾಯ್ಕಿ",
    menu_money: "ಆಸ್ತಿ",
    menu_transit: "ಗ್ರಹ ಗೋಚಾರ್",
    menu_dasha_effect: "ದಶಾ ಫಲ",
    menu_sade_sati: "ಸಾಡೆ ಸಾತಿ",
    menu_gemstones: "ರತ್ನ ಆನಿ ರುದ್ರಾಕ್ಷ",
    menu_nakshatra: "ನಕ್ಷತ್ರ ರಹಸ್ಯ",
    menu_doshas: "ದೋಷ ತಪಾಸಣ",
    menu_character: "ಸ್ವಭಾವ",
    menu_numerology: "ಅಂಕ ಗಣಿತ",
    back: "ಪಾಟಿ",
    submit: "ಜಾತಕ್ ತಯಾರಾ ಕರ್",
    quick_profile: "ವೆಗಿಂ ಪ್ರೊಫೈಲ್",
    enter_details_wisdom: "ವಿವರ ಸಾದರ್ ಕರ್",
    save_continue: "ಉರಯ್ ಆನಿ ಮುಖಾರ್ ಚಲ್",
    continue: "ಮುಖಾರ್ ಚಲ್ ➔",
    next_choose_analysis: "ಮುಖಾರ್: ವಿಶ್ಲೇಷಣ ➔",
    skip_for_now: "ಆತಾಂ ನಾಕಾ",
    lang_select: "ಭಾಷಾ",
    loshu_grid: "ಲೋಶು ಗ್ರಿಡ್",
    full_name: "ಪುರ್ತೆಂ ನಾಂವ್",
    classical_predictions: "ಶಾಸ್ತ್ರೀಯ ಭವಿಷ್ಯ",
    sacred_guide: "ದೈವಿಕ್ ಮಾರ್ಗದರ್ಶಿ",
    seeker_scholar_desc: "ಸರಳ ಮಾರ್ಗದರ್ಶನಾ ಖಾತಿರ್ ಸೀಕರ್, ವಿವರುನ್ ಮಾಹಿತಿ ಖಾತಿರ್ ಸ್ಕಾಲರ್ ವಿಂಚಿ.",
    save_profile: "ಪ್ರೊಫೈಲ್ ಉರಯ್",
    saved_profiles: "ಹಾಲಾಚಿಂ ಜಾತಕಾಂ",
    matching_title: "ಸಂಬಂಧ ಮೇಳವಣೆ",
    conclusion: "ನಿರ್ಣಯ್",
    select_rasi: "ರಾಶಿ ವಿಂಚಿ",
    daily_title: "ಆಜ್ಚೆಂ ನಕ್ಷತ್ರ ಸುರ್ವೆ",
    muhurta_title: "ಶುಭ ಮುಹೂರ್ತ ವೇಳ್",
    muhurta_select: "ಉದ್ದೇಶ ವಿಂಚಿ",
    sacred_intake: "ವಿವರ ದಾಕಲ್ ಕರ್",
    partner_one: "ಸಂಗಾತಿ 1",
    partner_two: "ಸಂಗಾತಿ 2",
    birth_location: "ಜನ್ಮ ಸ್ಥಳ್",
    timeframe: "ಸಮಯ್",
    location: "ಜಾಗೊ",
    quick_search: "ವೆಗಿಂ ಸೊಧ್",
    oracle: "ದೈವ ಪರೀಕ್ಷಾ",
    name: "ನಾಂವ್",
    date: "ತಾರೀಕ್",
    nakshatra: "ನಕ್ಷತ್ರ",
    ask_guruji: "ಗುರೂಜಿಕ್ ವಿಚಾರ್",
    deep_inquiry: "ವಿವರ ವಿಚಾರಣ",
    seek_answer: "ಪರಿಹಾರ್ ಸೊಧ್",
    name_of_soul: "ಅಭ್ಯರ್ಥಿ ನಾಂವ್",
    birth_date: "ಜನ್ಮ ತಾರೀಕ್",
    birth_time: "ಜನ್ಮ ವೇಳ್",
    gender: "ಲಿಂಗ್",
    male: "ದಾದ್ಲೊ",
    female: "ಸ್ತ್ರೀ",
    other: "ಇತರ",
    search_city_placeholder: "ಶಹರ ಸೊಧ್...",
    muhurta_search_placeholder: "ಉದ್ದೇಶ ಸೊಧ್...",
    prashna_placeholder: "ತುಜೊ ಮುಖಾರ ಪ್ರಶ್ನ ಕಿತೆಂ?",
    guruji_listening: "ಗುರೂಜಿ ಆಯ್ಕತಾ...",
    connection_interrupted: "ಸಂಪರ್ಕ್ ಕಟ್",
    disconnected: "ಡಿಸ್ಕನೆಕ್ಟ್",
    support_guruji: "ಗುರೂಜಿಕ್ ಕುಮಕ್ ಕರ್",
    scan_to_support: "ಕುಮಕ್ ಖಾತಿರ್ ಸ್ಕ್ಯಾನ್ ಕರ್",
    scan_to_donate: "GPay / UPI ಮುಕಾಂತ್ ದಾನ ಕರ್",
    support_mission: "ಆಮ್ಚಾ ಮಿಸಾಂವಾ ಖಾತಿರ್ ಮಜತ್ ಕರ್",
    support_quote: "ತುಕಾ ತುಜೆ ಜಾತಕ ಮಾರ್ಗದರ್ಶನ ಫಾವೊ ಜಾಲ್ಯಾ. ಮಜತ್ ಕರುಂಕ್ ಖುಷಿ ಆಸಾಂಡಾ ಕರ್.",
    csr_title: "ಸಾಮಾಜಿಕ್ ಕಳವಳ",
    csr_books_title: "ವಿಶೇಷ ಭುರ್ಗ್ಯಾಂಕ್ ಶಿಕ್ಷಣ",
    csr_books_desc: "ವಿಶೇಷ ಚೇತನ ಭುರ್ಗ್ಯಾಂಕ್ ತಾಂಚ್ಯಾ ಶಿಕ್ಷಣ ಖಾತಿರ್ ಆಾಮ್ಚ್ಯಾ ಆದಾಯಾಚೊ 90% ವಾಟೊ ಆಮಿ ದಿತಾಂವ್.",
    csr_oldage_title: "ಪಿರ್ಾಯೆರ್ ಗೌರವ",
    csr_oldage_desc: "ಗರಬಿವಂತ ಪ್ರಾಯೆಚ್ಚಾ ಲೊಕಾಂಕ್ ಆಶ್ರಯ ಆನಿ ಜೆವಣಾಚಿ ವ್ಯವಸ್ಥಾ.",
    secure: "ಸುರಕ್ಷಿತ",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಸರ್ಪೋಟ್",
    next_page: "ಮುಖ್ಲೆಂ ಪಾನ್",
    save_info: "ಮಾಹಿತಿ ಉರಯ್",
    saved_profiles_title: "ಉರಯಿಲ್ಲಿ ಪ್ರೊಫೈಲ್",
    celestial_map: "ಆಕಾಶ ನಕ್ಷೆ",
    stars_obscured: "ಕುಪಾಂ ಮುಚ್ಚಿಲಿಂ. ಪರ್ತ್ಯಾನ್ ಪ್ರಯತ್ನ ಕರ್.",
    go_back: "ಪಾಟಿ ವಚ್",
    dismiss: "ಸೋಡ್",
    select_city_warning: "⚠️ ಸಾರ್ಕ್ ಗಣಾಂ ಖಾತಿರ್ ಶಹರ ವಿಂಚಿ.",
    search_assistant_placeholder: "ಉದಾ: 2024 ಮೆಷ ರಾಶಿ ಫಲ",
    enter_full_name: "ಪುರ್ತೆಂ ನಾಂವ್ ಬರಯ್",
    feedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    feedback_title: "ತುಜಿ ಪ್ರತಿಕ್ರಿಯೆ ಆನಿ ಸೂಚನಾ",
    feedback_placeholder: "ತುಜೊ ಅನ್ಭವ್ ಸಾಂಗ್...",
    submit_feedback: "ಸಾದರ್ ಕರ್",
    feedback_success: "ಧನ್ಯವಾದ್!",
    first_name: "ಸುರ್ವೆ ನಾಂವ್",
    second_name: "ದುಸ್ರೆಂ ನಾಂವ್",
    timeframe_placeholder: "ಉದಾ: ಯೆಂವ್ಚ್ಯಾ 3 ಮ್ಹೈನಾಲಾಂತ್",
    select_seeker: "ಸೀಕರ್ ವಿಂಚಿ",
    select_scholar: "ಸ್ಕಾಲರ್ ವಿಂಚಿ",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    seeker_desc: "ಸಾಮಾನ್ಯ ಲೊಕಾ ಖಾತಿರ್ ಸರಳ ವಾಟ್.",
    scholar_desc: "ಜ್ಯೋತಿಷಿಂಕ್ ಗೂಂಡ್ ಜ್ಞಾನ್.",
    siddhantic_precision: "ಸ್ಕಾಲರ್ ಸೆಕ್ಷನ್",
    personal_guidance: "ಸೀಕರ್ ಸೆಕ್ಷನ್",
    calculating_heavens: "ಲೆಕ್ಕಾಚಾರ ಚಲ್ತಾ...",
    ask_help_guruji: "ಗುರೂಜಿಚಿ ಮಜತ್ ಘೆ",
    sacred_conversation: "ದೈವಿಕ್ ಸಂಭಾಷಣ",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    life_path: "ಜೀವನ್ ವಾಟ್",
    timeline: "ಸಮಯ್",
    siddhantic: "ಸಿದ್ದಾಂತಿಕ್",
    life_phase: "ಜೀವನ ಚಕ್ರ",
    wealth_health: "ಆಸ್ತಿ ಆನಿ ಭಲಾಯ್ಕಿ",
    soul_map: "ಆತ್ಮ್ಯಾಚೊ ನಕಾಶೊ",
    power_score: "ಶಕ್ತಿ",
    under_construction: "ಕಾಮ್ ಚಲ್ತಾ.",
    return_home: "ಘರಾ ಪಾಟಿ ವಚ್",
    get_verdict: "ನಿರ್ಣಯ್ ಘೆ",
    latitude: "ಅಕ್ಷಾಂಶ",
    longitude: "ರೇಖಾಂಶ",
    timezone: "ಸಮಯ ವಲಯ",
    suggestion_title: "ಸೂಚನಾ",
    suggestion_desc: "ಅನ್ಭವ್ ಸುಧಾರಂವ್ಕ್ ಮಜತ್ ಕರ್",
    suggestion_placeholder: "ತುಜೆ ವಿಷಯ ಬರಯ್...",
    suggestion_send: "ಧಾಡ್",
    suggestion_sent: "ಗುತ್ತುಜಿಕ್ ಪಾವಲೆಂ",
    panchanga_title: "ಪಂಚಾಂಗ",
    today_panchanga: "ಆಜ್ಚೆಂ ಪಂಚಾಂಗ",
    custom_panchanga: "ತಾರೀಕ್ ಆನಿ ಜಾಗೊ",
    timeline_title: "ಕಾಲಕ್ರಮ",
    contact_astrologer_title: "ತಾಂಬೂಲ ಸಮರ್ಪಣ",
    contact_astrologer_desc: "ದೈವಜ್ಞಾಂಕ್ ತಾಂಬೂಲ ದೀ",
    tambula_offering: "ತಾಂಬೂಲ",
    tambula_desc: "ತಾಂಬೂಲ ಆನಿ ದಕ್ಷಿಣೆ ದೀ.",
    problem_label: "ಸಮಸ್ಯೆ ಸಾಂಗ್",
    problem_placeholder: "ಕಿತೆಂ ಸಮಸ್ಯೆ ಆಸಾ?",
    contact_time_label: "ಸಂಪರ್ಕ್ ವೇಳ್",
    contact_time_placeholder: "ಯೆದೊಳ್?",
    submit_problem: "ಸಲ್ಲಿಕೆ",
    problem_submitted_msg: "ಸಂಪರ್ಕ್ ಕರ್ತಾಲೆ.",
    mangala_dosha: "ಮಂಗಳ ದೋಷ",
    conclusion_title: "ನಿರ್ಣಯ್",
    remedy_options_title: "ಪರಿಹಾರ್ ಮಾರ್ಗ್",
    tier1_title: "ಉಪಾಯ ಸುರು",
    tier1_price: "₹99",
    tier1_meaning: "ಸುರ್ವೆಚೆ ಪರಿಹಾರ್",
    tier2_title: "ಶುಭ ಮಾರ್ಗ್",
    tier2_price: "₹599",
    tier2_meaning: "ಗ್ರಹ ಶಾಂತಿ ವಾಟ್",
    tier3_title: "ಸರ್ವ ಕರ್ಮ",
    tier3_price: "₹999",
    tier3_meaning: "ಪುರ್ತಿ ಮಾಹಿತಿ",
    pay_now: "ಹಣ್ ಪಾವತಿಸಿ",
    appointment_date: "ತಾರೀಕ್",
    appointment_time: "ವೇಳ್",
    contact_astrologer_remedies: "ಜ್ಯೋತಿಷಿ ಸಂಪರ್ಕ್",
    analysis_tab_title: "ವಿಶ್ಲೇಷಣ",
    matching_tab_title: "ಹೊಂದಾಣಿಕೆ",
    chat_tab_title: "ಚಾಟ್",
    help: "ಮಜತ್",
    footer_text: "ದೈವಿಕ್ ಆಜ್ಞಾ • ಆಧ್ಯಾತ್ಮಿಕ ವಾಟ್",
    celestial_insights_title: "ಆತಾಂಚಾ ಗ್ರಹಗತಿ",
    search_assistant_desc: "ಪಂಚಾಂಗ ಆನಿ ಫಲ ಸೊಧ್.",
    searching: "ಸೊಧ್ತಾ...",
    ask_stars: "ತಾರಾಂಕ್ ವಿಚಾರ್",
    sources: "ಆದಾರ್",
    invoke_guruji: "ಗುರೂಜಿ ಯೆ",
    pranama_end: "ಪ್ರಣಾಮ",
    career_guidance: "ವೃತ್ತಿ ಮಾರ್ಗದರ್ಶನ",
    love_marriage: "ಕಲಿಬೆ ಆಾ ಆನಿ ಪ್ರೀತಿ",
    health_energy: "ಭಲಾಯ್ಕಿ ಆನಿ ಶಕ್ತಿ",
    spiritual_path: "ಆಧ್ಯಾತ್ಮಿಕ ವಾಟ್",
    seek_wisdom_message: "ಗುರೂಜಿ ಮುಕಾಂತ್ ತಾರಾಂಚೆ ಉತ್ತರ ಘೆ.",
    connecting: "ಸಂಪರ್ಕ್ ಜತಾ...",
    dhanyavaada: "ಧನ್ಯವಾದ್",
    pranama: "ಪ್ರಣಾಮ",
    path: "ವಾಟ್",
    seeker_path: "ಸೀಕರ್ ವಾಟ್",
    you_hint: "ಮಕಾ ಕುಮಕ್ ಬೋಡು ",
    muhurta_vivaha: "ಕಾಜಾರ್",
    muhurta_grihapravesha: "ಘುರಾ ಪ್ರವೇಶ",
    muhurta_bhoomi_pooja: "ಭೂಮಿ ಪೂಜಾ",
    muhurta_upanayana: "ಮುಂಜ",
    muhurta_namakarana: "ನಾಂವ್ ದವರ್ಚೆಂ",
    muhurta_annaprashana: "ಜೆವಣ ಉಬಾರ್ಚೆಂ",
    muhurta_aksharabhyasa: "ಅಕ್ಷರಾಭ್ಯಾಸ",
    muhurta_vidyarambha: "ವಿದ್ಯಾರಂಭ",
    muhurta_karnavedha: "ಕಾನ್ ಹುಳ್ಚೆಂ",
    muhurta_choodakarana: "ಕೇಂಸ್ ಕಾಡ್ಚೆಂ",
    muhurta_seemantham: "ಬಾಳಂತಿ",
    muhurta_vahana: "ಗಾಡಿ ಖರೀದಿ",
    muhurta_vyapaara: "ಬ್ಯುಸಿನೆಸ್ ಸುರು",
    muhurta_shop_opening: "ದುಕಾನ ಉದ್ಘಾಟನ",
    muhurta_udyoga: "ಕಾಮಾರ್ ಮೆಳಾವ್ಣೆ",
    muhurta_swarna: "ಭಂಗಾರ ಖರೀದಿ",
    muhurta_investments: "ಇನ್ವೆಸ್ಟ್ಮೆಂಟ್",
    muhurta_yaatra: "ಪಯಣ",
    muhurta_videsha: "ವಿದೇಶ ಪಯಣ",
    muhurta_shastra_kriya: "ಆಪರೇಶನ್",
    muhurta_medical_start: "ಮೆಡಿಕಲ್ ಸುರು",
    muhurta_abhijit: "ಅಭಿಜಿತ್ ಮುಹೂರ್ತ",
    muhurta_brahma: "ಬ್ರಹ್ಮ ಮುಹೂರ್ತ",
    muhurta_shilaanyasa: "ಬುನಾದಿ ಫಾತ್ರೊ",
    muhurta_renting: "ಬಾಡಿಗೆ ಘರ",
    muhurta_contracts: "ಪತ್ರ",
    muhurta_legal: "ಕೋರ್ಟು ಕಾಮ್",
    muhurta_agriculture: "ಶೆತ ಕಾಮ್",
    home: "ಘರಾ",
    daily_nav: "ದಿನಚರಿ",
    oracle_nav: "ಒರಾಕಲ್",
    chat_nav: "ಚಾಟ್",
    donate_support: "ಮಜತ್ ಆನಿ ಸರ್ಪೋಟ್",
    next_analysis: "ಮುಖಾರ್: ವಿಶ್ಲೇಷಣ ವಿಂಚಿ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪುರಾತನ್ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣ",
    my_character: "ಮ್ಹಜೆಂ ವ್ಯಕ್ತಿತ್ವ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಮಂಗಳ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೆತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    muhurta_analysis: "ಸಿದ್ಧಾಂತಿಕ ವಾಟ್",
    auspicious_time: "ಶುಭ ವೇಳ್",
    verdict: "ದೈವಿಕ್ ತೀರ್ಪು",
    planetary_positions: "ಗ್ರಹಾಂಚೆ ಸ್ಥಿತಿ",
    classical_references: "ಶಾಸ್ತ್ರೀಯ ಆಧಾರ",
    panchanga_breakdown: "ಪಂಚಾಂಗ ವಿವರ",
    technical_summary: "ತಾಂತ್ರಿಕ ಸಾರಾಂಶ",
    saved_readings: "ಆರ್ಕೈವ್",
    no_readings: "ಆರ್ಕೈವ್ ರಿತ್ತೆಂ ಆಸಾ",
    no_readings_desc: "ಜಾತಕ ವಿಶ್ಲೇಷಣಾ ಕರ್.",
    clear_history_confirm: "ಮಾಹಿತಿ ಕಾಡ್ಚೆಂ?",
    vastu_title: "ವಾಸ್ತು ಶಾಸ್ತ್ರ",
    vastu_desc: "ಸಕತ್ ಆನಿ ವಾಸ್ತು",
    vastu_analysis: "ವಾಸ್ತು ವಿಶ್ಲೇಷಣ",
    home_harmony: "ಘರಾ ಶಾಂತಿ",
    palm_reading_title: "ಹಸ್ತ ಸಾಮುದ್ರಿಕ",
    palm_reading_desc: "ಹಸ್ತ ರೇಖಾ ಶಾಸ್ತ್ರ",
    upload_palm: "ಹಾತಾಚೊ ಫೋಟೋ ದೀವ್",
    palm_instructions: "ಹಾತ್ ಸಮತಟ್ಟಾ ದವರ್.",
    analyzing_palm: "ರೇಖೆ ತಪಾಸಣಾ...",
    palm_analysis_res: "ಹಸ್ತ ವಿಶ್ಲೇಷಣ",
    camera_access: "ಕ್ಯಾಮೆರಾ",
    gallery_access: "ಗ್ಯಾಲರಿ",
    invalid_palm_error: "ಫೋಟೋ ಸಾರ್ಕೊ ನಾ. ಪರ್ತ್ಯಾನ್ ದೀವ್.",
    classical_source_authority: "ಮೂಲ ಶಾಸ್ತ್ರ",
    welcome_tour: "ಸ್ವಾಗತ್",
    welcome_tour_desc: "ಜೋತ್ಯಿಷ್ಯ ಲೋಕ ಖಾತಿರ್ ಸ್ವಾಗತ್.",
    seeker_mode_active: "ಸೀಕರ್",
    scholar_mode_active: "ಸ್ಕಾಲರ್",
    seeker_tour_desc: "ಸರಳ ವಾಟ್",
    scholar_tour_desc: "ಗೂಂಡ್ ಜ್ಞಾನ್",
    sacred_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dashboard_tour_desc: "ಪಂಚಾಂಗ ಅಪ್ಡೇಟ್",
    guruji_tour: "ಗುರೂಜಿ ಮಾರ್ಗದರ್ಶನ",
    guruji_tour_desc: "ಗುರೂಜಿ ಬಟನ್",
    navigation_tour: "ನ್ಯಾವಿಗೇಷನ್",
    nav_tour_desc: "ವಾಪರ್ ಕರುಂಕ್ ಸುಲಭ.",
    save_profile_error: "ನಾಂವ್ ಬರಯ್.",
    profile_saved: "ಪ್ರೊಫೈಲ್ ಉರಯ್ಲ್ಯಾಂ.",
    profile_saved_for: "{name} ಖಾತಿರ್ ಪ್ರೊಫೈಲ್ ಉರಯ್ಲ್ಯಾಂ.",
    life_partner_analysis: "ಜೀವನ್ ಸಂಗಾತಿ ವಿಶ್ಲೇಷಣ",
    prashna_analysis: "ಪ್ರಶ್ನ ವಿಶ್ಲೇಷಣ",
    stars_silent: "ತಾರಾಂ ಮೌನ್ ಆಸಾತ್. ಪರ್ತ್ಯಾನ್ ಪ್ರಯತ್ನ ಕರ್.",
    celestial_connection_failed: "ಸಂಪರ್ಕ್ ಪಾವೊಂಕ್ ನಾ.",
    switch_to_dark: "ಡಾರ್ಕ್ ಮೋಡ್",
    switch_to_light: "ಲೈಟ್ ಮೋಡ್",
    blog: "ಬ್ಲಾಗ್",
    blog_desc: "ಸಿದ್ದಾಂತ ಆನಿ ಹೋರ",
    enter_details_warning: "ವಿವರ ಸಾದರ್ ಕರ್.",
    sending: "ಧಾಡ್ತಾ...",
    offline: "ಆಫ್‌ಲೈನ್",
    csr_tagline: "ಧರ್ಮ್ ಆನಿ ಸಾಮಾಜಿಕ್ ಸೇವಾ",
    csr_revenue_committed: "ಯೆಣಿಗೆ ಕೊಡುಗೆ",
    csr_souls_nourished: "ಸಹಾಯ್ ಮೆಳ್ಳಿಂ",
    csr_verified_integrity: "ನಂಬಿಕೆ ಆಸಾ",
    csr_schools_supported: "ಶೋಲೆ ಕುಮಕ್",
    csr_kits_distributed: "ಕಿಟ್ ವಾಂಟ್ಲೆ",
    csr_volunteer_hours: "ಸೇವಾ ವೇಳ್",
    csr_homes_adopted: "ಆಶ್ರಯ ದಿಲ್ಲೆ",
    csr_elders_assisted: "ಪ್ರಾಯ್ಕಾಂಚಿ ಸೇವಾ",
    csr_medical_camps: "ವೈದ್ಯಕೀಯ ಶಿಬಿರ",
    csr_special_children_initiative: "ವಿಶೇಷ ಭುರ್ಗ್ಯಾಂ ಸೇವಾ",
    csr_elder_care_program: "ಪ್ರಾಯ್ಕಾಂ ಸೇವಾ ಯೋಜನೆ",
    csr_revenue_committed_90: "90% ಆದಾಯ ಸಮಾಜ ಸೇವಕ್",
    csr_holistic_care_100: "100% ಸೇವಾ",
    seeker_mode_desc_short: "ಸೀಕರ್ ಮೋಡ್",
    scholar_mode_desc_short: "ಸ್ಕಾಲರ್ ಮೋಡ್",
    saved_profiles_desc: "ಹಾಲಾಚೆಂ ಚಿತ್ರ",
    brand_tagline: "ದೈವಿಕ್ ಜ್ಞಾನ್, ಆಧುನಿಕ ತರ್ಕ",
    brand_logo: "ASTRO LOGIC"
};

const ml_full = {
    brand_name: "ആസ്ട്രോ ലോജിക്",
    tagline: "പുരാതന ജ്ഞാനവും ആധുനിക യുക്തിയും",
    begin_journey: "യാത്ര തുടങ്ങുക",
    choose_path: "നിങ്ങളുടെ വഴി തിരഞ്ഞെടുക്കുക",
    disclaimer: "ജ്യോതിഷ പ്രവചനങ്ങൾ ഗ്രഹങ്ങളുടെ കണക്കുകൂട്ടലുകളെ അടിസ്ഥാനമാക്കിയുള്ളതാണ്. ഇതൊരു സാധ്യത മാത്രമാണ്.",
    planetary_transit_in: "ൽ",
    horoscope: "ജാതകം",
    matching: "പൊരുത്തം",
    life_partner: "ജീവിത പങ്കാളി",
    daily: "ദിവസഫലം",
    muhurta: "മുഹൂർത്തം",
    numerology: "സംഖ്യാശാസ്ത്രം",
    chat: "ആസ്ട്രോ ചാറ്റ്",
    prashna: "പ്രശ്നം",
    guruji: "ഗുരുജി",
    you: "നിങ്ങൾ",
    guruji_welcome: "ജീവിത പാതയെക്കുറിച്ചോ ഗ്രഹമാറ്റങ്ങളെക്കുറിച്ചോ ഗുരുജിയോട് ചോദിക്കുക.",
    guruji_thinking: "ഗുരുജി ചിന്തിക്കുന്നു...",
    error_guruji: "ബന്ധം നഷ്ടമായിരിക്കുന്നു. കുറച്ചു കഴിഞ്ഞ് ശ്രമിക്കുക.",
    ask_guruji_placeholder: "ഗുരുജിയോട് ചോദിക്കുക...",
    switch_mode: "വഴി മാറ്റുക",
    menu_details: "ജനന വിശകലനം",
    menu_timeline: "ജീവിതരേഖ (അতীতം, വർത്തമാനം, ഭാവി)",
    menu_hora: "ഹോരാ വിശകലനം",
    menu_sphta: "ഗ്രഹ സ്ഥിതി",
    menu_rasi: "രാശി ചക്രം",
    menu_navamsha: "നവാംശം (D9)",
    menu_bhava: "ഭാവ ചലിതം",
    menu_bhava_analysis: "12 ഭാവങ്ങളുടെ വിശകലനം",
    menu_sandhi: "സന്ധി വിശകലനം",
    menu_panchangam: "പഞ്ചാംഗം",
    menu_dasha: "വിംശോത്തരി ദശ",
    menu_shadvarga: "ഷഡ്വർഗ്ഗം",
    shadvarga_strengths: "ഷഡ്വർഗ്ഗ ബലം",
    shadbala_analysis: "ഷഡ്ബല വിശകലനം",
    energy_strength: "ഊർജ്ജം",
    planetary_power: "ഗ്രഹ ബലം",
    menu_yogas: "യോഗ വിശകലനം",
    menu_maitri: "പഞ്ചധാ മൈത്രി",
    menu_ashtaka: "അഷ്ടകവർഗ്ഗം",
    menu_trisputa: "ത്രിസ്ഫുട വിശകലനം",
    menu_dhumadi: "ധൂമാദി ഗ്രഹങ്ങൾ",
    menu_basic_details: "അടിസ്ഥാന വിവരങ്ങൾ",
    menu_yoga: "യോഗങ്ങൾ",
    menu_career: "കരിയറും വിജയവും",
    menu_health: "ആരോഗ്യവും ഊർജ്ജവും",
    menu_money: "ധനവും സമ്പത്തും",
    menu_transit: "ഗ്രഹമാറ്റങ്ങൾ",
    menu_dasha_effect: "ദശകളുടെ സ്വാധീനം",
    menu_sade_sati: "ഏഴര ശനി വിശകലനം",
    menu_gemstones: "രത്നങ്ങൾ & രുദ്രാക്ഷം",
    menu_nakshatra: "നക്ഷത്ര രഹസ്യങ്ങൾ",
    menu_doshas: "ദോഷപ്പൊരുത്തം (കാൽസർപ്പം/പിതൃ)",
    menu_character: "സ്വഭാവവും വ്യക്തിത്വവും",
    menu_numerology: "സംഖ്യാശാസ്ത്ര വിശകലനം",
    back: "പിന്നിലേക്ക്",
    submit: "ജാതകം തയ്യാറാക്കുക",
    quick_profile: "ക്വിക്ക് പ്രൊഫൈൽ",
    enter_details_wisdom: "വിവരങ്ങൾ നൽകുക",
    save_continue: "സംരക്ഷിച്ചു മുന്നോട്ട് പോവുക",
    continue: "തുടരുക ➔",
    next_choose_analysis: "അടുത്തത്: വിശകലനം ➔",
    skip_for_now: "ഇപ്പോൾ വേണ്ട",
    lang_select: "ഭാഷ",
    loshu_grid: "ലോഷു ഗ്രിഡ്",
    full_name: "മുഴുനാമം",
    classical_predictions: "ജ്യോതിഷ പ്രവചനങ്ങൾ",
    sacred_guide: "പവിത്ര വഴികാട്ടി",
    seeker_scholar_desc: "ലളിതമായ ഉപദേശങ്ങൾക്ക് 'സീകർ' തിരഞ്ഞെടുക്കുക. ആഴത്തിലുള്ള വിശകലനങ്ങൾക്ക് 'സ്കോളർ' തിരഞ്ഞെടുക്കുക.",
    save_profile: "പ്രൊഫൈൽ സംരക്ഷിക്കുക",
    saved_profiles: "നേരത്തെ ചെയ്തവ",
    matching_title: "വിവാഹ പൊരുത്തം",
    conclusion: "വിധി",
    select_rasi: "രാശി തിരഞ്ഞെടുക്കുക",
    daily_title: "ഇന്നത്തെ ഗ്രഹഗതി",
    muhurta_title: "ശുഭ മുഹൂർത്തങ്ങൾ",
    muhurta_select: "ആവശ്യം തിരഞ്ഞെടുക്കുക",
    sacred_intake: "വിവരശേഖരണം",
    partner_one: "ഒന്നാമത്തെയാൾ",
    partner_two: "രണ്ടാമത്തെയാൾ",
    birth_location: "ജനനസ്ഥലം",
    timeframe: "സമയം",
    location: "സ്ഥലം",
    quick_search: "വേഗത്തിൽ തിരയുക",
    oracle: "ഒറാക്കിൾ",
    name: "പേര്",
    date: "തിയതി",
    nakshatra: "നക്ഷത്രം",
    ask_guruji: "ഗുരുജിയോട് ചോദിക്കുക",
    deep_inquiry: "വിശദമായ അന്വേഷണം",
    seek_answer: "ഉത്തരം തേടുക",
    name_of_soul: "പേര്",
    birth_date: "ജനന തിയതി",
    birth_time: "ജനന സമയം",
    gender: "ലിംഗം",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    other: "മറ്റുള്ളവ",
    search_city_placeholder: "നഗരം തിരയുക...",
    muhurta_search_placeholder: "ആവശ്യം തിരയുക...",
    prashna_placeholder: "നിങ്ങൾ അറിയാൻ ആഗ്രഹിക്കുന്നതെന്താണ്?",
    guruji_listening: "ഗുരുജി കേൾക്കുന്നു...",
    connection_interrupted: "ബന്ധം വിച്ഛേദിക്കപ്പെട്ടു",
    disconnected: "ഡിസ്കണക്റ്റഡ്",
    support_guruji: "ഗുരുജിയെ പിന്തുണയ്ക്കുക",
    scan_to_support: "പിന്തുണയ്ക്കാൻ സ്കാൻ ചെയ്യുക",
    scan_to_donate: "GPay / UPI വഴി പിന്തുണയ്ക്കാം",
    support_mission: "ഞങ്ങളുടെ ലക്ഷ്യത്തിൽ പങ്കാളിയാവുക",
    support_quote: "നിങ്ങളുടെ ജീവിത പാതയെക്കുറിച്ച് ഒരു ഉപദേശം ലഭിച്ചു. ഇഷ്ടപ്പെട്ടെങ്കിൽ പിന്തുണയ്ക്കാം.",
    csr_title: "ആസ്ട്രോ ലോജിക് സാമൂഹിക പ്രതിബദ്ധത",
    csr_books_title: "ഭിന്നശേഷിയുള്ള കുട്ടികൾക്ക് വിദ്യാഭ്യാസം",
    csr_books_desc: "ഞങ്ങളുടെ വരുമാനത്തിന്റെ 90% ഭിന്നശേഷിയുള്ള കുട്ടികളുടെ വിദ്യാഭ്യാസത്തിനായി മാറ്റിവെക്കുന്നു.",
    csr_oldage_title: "വൃദ്ധജനങ്ങൾക്ക് താങ്ങായി",
    csr_oldage_desc: "ആരും നോക്കാനില്ലാത്ത വൃദ്ധജനങ്ങൾക്ക് ഭക്ഷണവും മരുന്നും ഉറപ്പാക്കുന്നു.",
    secure: "സുരക്ഷിതം",
    spiritual: "ആത്മീയത",
    support: "പിന്തുണ",
    next_page: "അടുത്ത പേജ്",
    save_info: "വിവരങ്ങൾ സംരക്ഷിക്കുക",
    saved_profiles_title: "സംരക്ഷിച്ച പ്രൊഫൈലുകൾ",
    celestial_map: "രാശി ചക്രം",
    stars_obscured: "ഗ്രഹഗതി അനുകൂലമല്ല. വീണ്ടും ശ്രമിക്കുക.",
    go_back: "പിന്നിലേക്ക്",
    dismiss: "ഒഴിവാക്കുക",
    select_city_warning: "⚠️ നഗരം തിരഞ്ഞെടുക്കുക.",
    search_assistant_placeholder: "ഉദാ: 2024 ലെ വ്യാഴമാറ്റം",
    enter_full_name: "മുഴുനാമം നൽകുക",
    feedback: "അഭിപ്രായങ്ങൾ",
    feedback_title: "നിങ്ങളുടെ അഭിപ്രായങ്ങൾ അറിയിക്കുക",
    feedback_placeholder: "എന്തെങ്കിലും നിർദ്ദേശങ്ങൾ ഉണ്ടോ?",
    submit_feedback: "അയക്കുക",
    feedback_success: "നിങ്ങളുടെ അഭിപ്രായത്തിന് നന്ദി!",
    first_name: "ആദ്യ പേര്",
    second_name: "രണ്ടാം പേര്",
    timeframe_placeholder: "ഉദാ: അടുത്ത 3 മാസം",
    select_seeker: "സീകർ",
    select_scholar: "സ്കോളർ",
    seeker: "സീകർ",
    scholar: "സ്കോളർ",
    seeker_desc: "ലളിതമായ ഉപദേശങ്ങൾക്കും നിത്യജീവിത മാർഗനിർദ്ദേശങ്ങൾക്കും.",
    scholar_desc: "ജ്യോതിഷ ശാസ്ത്രത്തെക്കുറിച്ച് ആഴത്തിൽ അറിയാൻ ആഗ്രഹിക്കുന്നവർക്ക്.",
    siddhantic_precision: "സ്കോളർ സെക്ഷൻ",
    personal_guidance: "സീകർ സെക്ഷൻ",
    calculating_heavens: "കണക്കുകൂട്ടലുകൾ നടക്കുന്നു...",
    ask_help_guruji: "ഗുരുജിയുടെ സഹായം തേടുക",
    sacred_conversation: "സംഭാഷണം",
    shastriya: "ശാസ്ത്രീയം",
    life_path: "ജീവിത പാത",
    timeline: "സമയരേഖ",
    siddhantic: "സിദ്ധാന്തം",
    life_phase: "ജീവിത ഘട്ടം",
    wealth_health: "സമ്പത്തും ആരോഗ്യവും",
    soul_map: "ആത്മാവിന്റെ ഭൂപടം",
    power_score: "ശക്തി",
    under_construction: "പണിപ്പുരയിലാണ്.",
    return_home: "തിരിച്ചു പോവുക",
    get_verdict: "ഫലം അറിയുക",
    latitude: "അക്ഷാംശം",
    longitude: "രേഖാംശം",
    timezone: "സമയ മേഖല",
    suggestion_title: "നിർദ്ദേശങ്ങൾ",
    suggestion_desc: "ഗുരുജിയെ സഹായിക്കുക",
    suggestion_placeholder: "നിങ്ങളുടെ അഭിപ്രായം...",
    suggestion_send: "അയക്കുക",
    suggestion_sent: "ഗുരുജിക്ക് ലഭിച്ചു",
    panchanga_title: "പഞ്ചാംഗം",
    custom_panchanga: "തിയതിയും സ്ഥലവും മാറ്റുക",
    timeline_title: "ജീവിതരേഖ ഡാഷ്ബോർഡ്",
    contact_astrologer_title: "ജ്യോതിഷിയെ സമീപിക്കുക",
    contact_astrologer_desc: "താമ്പൂല സമർപ്പണം",
    tambula_offering: "താമ്പൂല സമർപ്പണം",
    tambula_desc: "ജ്യോതിഷിയെ സമീപിച്ച് മാർഗനിർദ്ദേശം തേടുക.",
    problem_label: "പ്രശ്നം വിശദീകരിക്കുക",
    problem_placeholder: "ഉദാ: ഉദ്യോഗം, ആരോഗ്യം...",
    contact_time_label: "ബന്ധപ്പെടേണ്ട സമയം",
    contact_time_placeholder: "ഉദാ: നാളെ രാവിലെ 10 മണി",
    submit_problem: "അപേക്ഷിക്കുക",
    problem_submitted_msg: "ഞങ്ങളുടെ ജ്യോതിഷി ഉടൻ ബന്ധപ്പെടും.",
    mangala_dosha: "ചൊവ്വാദോഷം",
    conclusion_title: "ചുരുക്കത്തിൽ",
    remedy_options_title: "പരിഹാരങ്ങൾ തിരഞ്ഞെടുക്കുക",
    tier1_title: "ഉപായ പ്രാരംഭം",
    tier1_price: "₹99",
    tier1_meaning: "തുടക്കക്കാർക്കുള്ള പരിഹാരങ്ങൾ",
    tier2_title: "ശുഭമാർഗ്ഗം",
    tier2_price: "₹599",
    tier2_meaning: "ഗ്രഹശാന്തിക്ക്",
    tier3_title: "സർവ്വ കർമ്മ വിശ്ലേഷണം",
    tier3_price: "₹999",
    tier3_meaning: "പൂർണ്ണമായ വിശകലനം",
    pay_now: "പേയ്മെന്റ് ചെയ്യുക",
    appointment_date: "തിയതി തിരഞ്ഞടുക്കുക",
    appointment_time: "സമയം തിരഞ്ഞെടുക്കുക",
    contact_astrologer_remedies: "പരിഹാരങ്ങൾക്കായി ബന്ധപ്പെടുക",
    analysis_tab_title: "വിശകലനം",
    matching_tab_title: "പൊരുത്തം",
    chat_tab_title: "ആസ്ട്രോ ചാറ്റ്",
    help: "സഹായം",
    footer_text: "ദൈവവിധി • ആത്മീയ ജ്ഞാനം",
    celestial_insights_title: "നിലവിലെ അവസ്ഥ",
    search_assistant_desc: "ഗ്രഹങ്ങളുടെ മാറ്റങ്ങളും മറ്റും തിരയാം.",
    searching: "തിരയുന്നു...",
    ask_stars: "താരങ്ങളോട് ചോദിക്കാം",
    sources: "ഉറവിടങ്ങൾ",
    invoke_guruji: "ഗുരുജിയെ വിളിക്കുക",
    pranama_end: "പ്രണാമം",
    career_guidance: "കരിയർ വഴി",
    love_marriage: "പ്രണയവും വിവാഹവും",
    health_energy: "ആരോഗ്യവും ഊർജ്ജവും",
    spiritual_path: "ആത്മീയ പാത",
    seek_wisdom_message: "നക്ഷത്രങ്ങൾ മറുപടി നൽകും.",
    connecting: "ബന്ധപ്പെടുന്നു...",
    dhanyavaada: "നന്ദി",
    pranama: "പ്രണാമം",
    path: "വഴി",
    seeker_path: "സീകർ വഴി",
    you_hint: "എനിക്ക് സഹായം വേണം ",
    muhurta_vivaha: "വിവാഹം",
    muhurta_grihapravesha: "ഗൃഹപ്രവേശം",
    muhurta_bhoomi_pooja: "ഭൂമി പൂജ",
    muhurta_upanayana: "ഉപനയനം",
    muhurta_namakarana: "നാമകരണം",
    muhurta_annaprashana: "ചോറൂണ്",
    muhurta_aksharabhyasa: "വിദ്യാരംഭം",
    muhurta_vidyarambha: "സ്കൂളിൽ ചേർക്കാൻ",
    muhurta_karnavedha: "കാത് കുത്താൻ",
    muhurta_choodakarana: "ചൗളം (മുടി നീക്കം ചെയ്യൽ)",
    muhurta_seemantham: "സീമന്തം",
    muhurta_vahana: "വാഹനം വാങ്ങാൻ",
    muhurta_vyapaara: "ബിസിനസ് തുടങ്ങാൻ",
    muhurta_shop_opening: "കട ഉദ്ഘാടനം",
    muhurta_udyoga: "ജോലിയിൽ പ്രവേശിക്കാൻ",
    muhurta_swarna: "സ്വർണ്ണം വാങ്ങാൻ",
    muhurta_investments: "നിക്ഷേപം",
    muhurta_yaatra: "യാത്ര",
    muhurta_videsha: "വിദേശ യാത്ര",
    muhurta_shastra_kriya: "ശസ്ത്രക്രിയ",
    muhurta_medical_start: "ചികിൽസ തുടങ്ങാൻ",
    muhurta_abhijit: "അഭിജിത്ത് മുഹൂർത്തം",
    muhurta_brahma: "ബ്രഹ്മ മുഹൂർത്തം",
    muhurta_shilaanyasa: "കല്ലിടീൽ",
    muhurta_renting: "വാടക വീട് മാറാൻ",
    muhurta_contracts: "ഒപ്പിടാൻ",
    muhurta_legal: "കോടതി കാര്യങ്ങൾ",
    muhurta_agriculture: "കൃഷി കാര്യങ്ങൾ",
    home: "ഹോം",
    daily_nav: "നിത്യം",
    oracle_nav: "ഒറാക്കിൾ",
    chat_nav: "ചാറ്റ്",
    donate_support: "പിന്തുണയ്ക്കുക",
    next_analysis: "അടുത്ത വിശ്കലനം",
    sacred_geometry: "പവിത്ര ജ്യാമിതി",
    birth_analysis: "ജനന വിശകലനം",
    my_character: "എന്റെ വ്യക്തിത്വം",
    rasi_kundli: "രാശി ചക്രം",
    vimshottari: "വിംശോത്തരി",
    ashtakavarga: "അഷ്ടകവർഗ്ഗം",
    planet_sun: "സൂര്യൻ",
    planet_moon: "ചന്ദ്രൻ",
    planet_mars: "ചൊവ്വ",
    planet_mercury: "ബുധൻ",
    planet_jupiter: "വ്യാഴം",
    planet_venus: "ശുക്രൻ",
    planet_saturn: "ശനി",
    planet_rahu: "രാഹു",
    planet_ketu: "കേതു",
    planet_lagna: "ലഗ്നം",
    planet_mandi: "മാന്തി",
    rasi_mesha: "മേടം",
    rasi_vrishabha: "ഇടവം",
    rasi_mithuna: "മിഥുനം",
    rasi_karka: "കർക്കിടകം",
    rasi_simha: "ചിങ്ങം",
    rasi_kanya: "കന്നി",
    rasi_tula: "തുലാം",
    rasi_vrishchika: "വൃശ്ചികം",
    rasi_dhanu: "ധനു",
    rasi_makara: "മകരം",
    rasi_kumbha: "കുംഭം",
    rasi_meena: "മീനം",
    muhurta_analysis: "മുഹൂർത്ത വിശകലനം",
    auspicious_time: "ശുഭ സമയം",
    verdict: "വിധി",
    planetary_positions: "ഗ്രഹ നില",
    classical_references: "ശാസ്ത്രീയ പരാമർശങ്ങൾ",
    panchanga_breakdown: "പഞ്ചാംഗ വിശ്ലേഷണം",
    technical_summary: "സാങ്കേതിക ചുരുക്കം",
    saved_readings: "സംരക്ഷിച്ചവ",
    no_readings: "ലിസ്റ്റ് കാലിയാണ്",
    no_readings_desc: "വിവരങ്ങൾ സംരക്ഷിക്കാൻ തുടങ്ങുക.",
    clear_history_confirm: "എല്ലാം മായിച്ചു കളയണോ?",
    vastu_title: "വാസ്തു ശാസ്ത്രം",
    vastu_desc: "ഊർജ്ജവും വാസ്തുവും",
    vastu_analysis: "വാസ്തു വിശകലനം",
    home_harmony: "വീട്ടിലെ സമാധാനം",
    palm_reading_title: "ഹസ്തരേഖ",
    palm_reading_desc: "കൈനോട്ടം",
    upload_palm: "ഫോട്ടോ അപ്ലോഡ് ചെയ്യുക",
    palm_instructions: "കൈത്തലം വ്യക്തമായി കാണുന്ന ഫോട്ടോ നൽകുക.",
    analyzing_palm: "വിശകലനം ചെയ്യുന്നു...",
    palm_analysis_res: "ഹസ്തരേഖ വിശകലനം",
    camera_access: "ക്യാമറ",
    gallery_access: "ഗാലറി",
    invalid_palm_error: "ഫോട്ടോ വ്യക്തമല്ല. വീണ്ടും ശ്രമിക്കുക.",
    classical_source_authority: "ശാസ്ത്രീയ ആധാരം",
    welcome_tour: "സ്വാഗതം",
    welcome_tour_desc: "ജ്യോതിഷ ലോകത്തേക്ക് സ്വാഗതം.",
    seeker_mode_active: "സീകർ സജീവം",
    scholar_mode_active: "സ്കോളർ സജീവം",
    seeker_tour_desc: "ലളിതമായ പാത",
    scholar_tour_desc: "ഗഹനമായ പാത",
    sacred_dashboard: "ഡാഷ്ബോർഡ്",
    dashboard_tour_desc: "എല്ലാം ഒരിടത്ത്.",
    guruji_tour: "ഗുരുജിയോട് ചോദിക്കുക",
    guruji_tour_desc: "നിങ്ങളുടെ സഹായി.",
    navigation_tour: "യാത്ര തുടരാം",
    nav_tour_desc: "ലളിതമായ രൂപകൽപ്പന.",
    save_profile_error: "പേര് ദയവായി നൽകുക.",
    profile_saved: "സംരക്ഷിച്ചു.",
    profile_saved_for: "{name} ന്റെ പ്രൊഫൈൽ സംരക്ഷിച്ചു.",
    life_partner_analysis: "പങ്കാളി വിശകലനം",
    prashna_analysis: "പ്രശ്ന വിശകലനം",
    stars_silent: "വീണ്ടും ശ്രമിക്കുക.",
    celestial_connection_failed: "കണക്ഷൻ നഷ്ടപ്പെട്ടു.",
    switch_to_dark: "ഡാർക്ക് മോഡ്",
    switch_to_light: "ലൈറ്റ് മോড",
    blog: "ബ്ലോഗ്",
    blog_desc: "ലേഖനങ്ങൾ",
    enter_details_warning: "ദയവായി സമയം നൽകുക.",
    sending: "അയക്കുന്നു...",
    offline: "ഓഫ്ലൈൻ",
    csr_tagline: "ധർമ്മവും കരുണയും",
    csr_revenue_committed: "സഹായങ്ങൾ",
    csr_souls_nourished: "കുട്ടികൾ",
    csr_verified_integrity: "വിശ്വസ്തത",
    csr_schools_supported: "സ്കൂളുകൾ",
    csr_kits_distributed: "കിറ്റുകൾ",
    csr_volunteer_hours: "മണിക്കൂറുകൾ",
    csr_homes_adopted: "ഭവനങ്ങൾ",
    csr_elders_assisted: "വൃദ്ധജനങ്ങൾ",
    csr_medical_camps: "മെഡിക്കൽ ക്യാമ്പുകൾ",
    csr_special_children_initiative: "കുട്ടികൾക്കായുള്ള പദ്ധതി",
    csr_elder_care_program: "വൃദ്ധജന പരിപാലനം",
    csr_revenue_committed_90: "90% വരുമാനം സേവനത്തിനായി",
    csr_holistic_care_100: "100% സേവനം",
    seeker_mode_desc_short: "സീകർ മോഡ്",
    scholar_mode_desc_short: "സ്കോളർ മോഡ്",
    saved_profiles_desc: "ചാർട്ടുകൾ",
    today_panchanga: "ഇന്നത്തെ പഞ്ചാംഗം"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    // Find matching closing brace
    const endMarker = '  },';
    const endIndex = content.indexOf(endMarker, startIndex + startMarker.length);
    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 4);
}

let newContent = content;
newContent = updateLanguage(newContent, 'kok', kok_full);
newContent = updateLanguage(newContent, 'ml', ml_full);

fs.writeFileSync(filePath, newContent);
console.log("Updated Konkani and Malayalam translations.");
