import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const kn_full = {
    brand_name: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್",
    tagline: "ಪುರಾತನ ಜ್ಞಾನ ಮತ್ತು ಆಧುನಿಕ ತರ್ಕದ ಸಂಗಮ",
    begin_journey: "ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    choose_path: "ನಿಮ್ಮ ಹಾದಿಯನ್ನು ಆಯ್ದುಕೊಳ್ಳಿ",
    disclaimer: "ಜ್ಯೋತಿಷ್ಯ ಮುನ್ಸೂಚನೆಗಳು ಗ್ರಹಗಳ ಲೆಕ್ಕಾಚಾರದ ಮೇಲೆ ಆಧಾರಿತವಾಗಿವೆ. ಇವು ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಮಾತ್ರ.",
    planetary_transit_in: "ರಲ್ಲಿ",
    horoscope: "ಜಾತಕ",
    matching: "ಹೊಂದಾಣಿಕೆ",
    life_partner: "ಜೀವನ ಸಂಗಾತಿ",
    daily: "ದೈನಂದಿನ ಭವಿಷ್ಯ",
    muhurta: "ಮುಹೂರ್ತ",
    numerology: "ಅಂಕಶಾಸ್ತ್ರ",
    chat: "ಆಸ್ಟ್ರೋ ಚಾಟ್",
    prashna: "ಪ್ರಶ್ನೆ",
    guruji: "ಗುರೂಜಿ",
    you: "ನೀವು",
    guruji_welcome: "ನಿಮ್ಮ ಜೀವನದ ಹಾದಿ ಅಥವಾ ಗ್ರಹಗಳ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಗುರೂಜಿಯವರನ್ನು ಕೇಳಿ.",
    guruji_thinking: "ಗುರೂಜಿಯವರು ಗ್ರಹಗಳನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡುತ್ತಿದ್ದಾರೆ...",
    error_guruji: "ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    ask_guruji_placeholder: "ಗುರೂಜಿಯವರನ್ನು ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    switch_mode: "ಪದ್ಧತಿಯನ್ನು ಬದಲಾಯಿಸಿ",
    menu_details: "ಜನ್ಮ ವಿವರಗಳು",
    menu_timeline: "ಜೀವನ ಕಾಲಕ್ರಮ (ಹಿಂದಿನ, ಈಗಿನ, ಮುಂದಿನ)",
    menu_hora: "ಹೋರಾ ವಿಶ್ಲೇಷಣೆ",
    menu_sphta: "ಗ್ರಹ ಸ್ಪಷ್ಟತೆ",
    menu_rasi: "ರಾಶಿ ಕುಂಡಲಿ",
    menu_navamsha: "ನವಾಂಶ ಕುಂಡಲಿ",
    menu_bhava: "ಭಾವ ಚಲಿತ",
    menu_bhava_analysis: "ಭಾವ ವಿಶ್ಲೇಷಣೆ",
    menu_sandhi: "ಸಂಧಿ ವಿಶ್ಲೇಷಣೆ",
    menu_panchangam: "ಪಂಚಾಂಗ",
    menu_dasha: "ದಶಾ ಫಲಗಳು",
    menu_shadvarga: "ಷಡ್ವರ್ಗ",
    shadvarga_strengths: "ಷಡ್ವರ್ಗ ಬಲ",
    shadbala_analysis: "ಷಡ್ಬಲ ವಿಶ್ಲೇಷಣೆ",
    energy_strength: "ಶಕ್ತಿ ಬಲ",
    planetary_power: "ಗ್ರಹ ಬಲ",
    menu_yogas: "ಯೋಗ ವಿಶ್ಲೇಷಣೆ",
    menu_maitri: "ಗ್ರಹ ಮೈತ್ರಿ",
    menu_ashtaka: "ಅಷ್ಟಕವರ್ಗ",
    menu_trisputa: "ತ್ರಿಸ್ಫುಟ ವಿಶ್ಲೇಷಣೆ",
    menu_dhumadi: "ಧೂಮಾದಿ ಗ್ರಹಗಳು",
    menu_basic_details: "ಮೂಲ ಜನ್ಮ ವಿವರಗಳು",
    menu_yoga: "ಯೋಗಗಳು",
    menu_career: "ವೃತ್ತಿ ಮತ್ತು ಯಶಸ್ಸು",
    menu_health: "ಆರೋಗ್ಯ ಮತ್ತು ಶಕ್ತಿ",
    menu_money: "ಸಂಪತ್ತು ಮತ್ತು ಹಣಕಾಸು",
    menu_transit: "ಗ್ರಹ ಗೋಚಾರ",
    menu_dasha_effect: "ದಶೆಗಳ ಪ್ರಭಾವ",
    menu_sade_sati: "ಸಾಡೆ ಸಾತಿ ವಿಶ್ಲೇಷಣೆ",
    menu_gemstones: "ರತ್ನಗಳು ಮತ್ತು ರುದ್ರಾಕ್ಷಿ",
    menu_nakshatra: "ನಕ್ಷತ್ರ ರಹಸ್ಯಗಳು",
    menu_doshas: "ದೋಷ ತಪಾಸಣೆ (ಕಾಲಸರ್ಪ/ಪಿತೃ)",
    menu_character: "ಸ್ವಭಾವ ಮತ್ತು ವ್ಯಕ್ತಿತ್ವ",
    menu_numerology: "ಅಂಕಿಅಂಶ ವಿಶ್ಲೇಷಣೆ",
    back: "ಹಿಂದೆ",
    submit: "ಜಾತಕ ತಯಾರಿಸಿ",
    quick_profile: "ತ್ವರಿತ ಪ್ರೊಫೈಲ್",
    enter_details_wisdom: "ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    save_continue: "ಉಳಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ",
    continue: "ಮುಂದುವರಿಯಿರಿ ➔",
    next_choose_analysis: "ಮುಂದೆ: ವಿಶ್ಲೇಷಣೆ ಆಯ್ದುಕೊಳ್ಳಿ ➔",
    skip_for_now: "ಸದ್ಯಕ್ಕೆ ಬೇಡ",
    lang_select: "ಭಾಷೆ",
    loshu_grid: "ಲೋಶು ಗ್ರಿಡ್",
    full_name: "ಪೂರ್ಣ ಹೆಸರು",
    classical_predictions: "ಶಾಸ್ತ್ರೀಯ ಭವಿಷ್ಯಗಳು",
    sacred_guide: "ಪವಿತ್ರ ಮಾರ್ಗದರ್ಶಿ",
    seeker_scholar_desc: "ಸರಳ ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ 'ಸೀಕರ್', ವಿವರವಾದ ಮಾಹಿತಿಗಾಗಿ 'ಸ್ಕಾಲರ್' ಆಯ್ದುಕೊಳ್ಳಿ.",
    save_profile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    saved_profiles: "ಇತ್ತೀಚಿನ ಜಾತಕಗಳು",
    matching_title: "ಗುಣ ಮೇಲನ ಫಲಿತಾಂಶ",
    conclusion: "ತೀರ್ಪು",
    select_rasi: "ರಾಶಿ ಆಯ್ದುಕೊಳ್ಳಿ",
    daily_title: "ಇಂದಿನ ಗ್ರಹಗಳ ಹರಿವು",
    muhurta_title: "ಶುಭ ಮುಹೂರ್ತ ಸಮಯಗಳು",
    muhurta_select: "ಉದ್ದೇಶ ಆಯ್ದುಕೊಳ್ಳಿ",
    sacred_intake: "ಮಾಹಿತಿ ಸಂಗ್ರಹಣೆ",
    partner_one: "ಮೊದಲ ವ್ಯಕ್ತಿ",
    partner_two: "ಎರಡನೇ ವ್ಯಕ್ತಿ",
    birth_location: "ಜನ್ಮ ಸ್ಥಳ",
    timeframe: "ಸಮಯ",
    location: "ಸ್ಥಳ",
    quick_search: "ತ್ವರಿತ ಹುಡುಕಾಟ",
    oracle: "ಒರಾಕಲ್",
    name: "ಹೆಸರು",
    date: "ದಿನಾಂಕ",
    nakshatra: "ನಕ್ಷತ್ರ",
    ask_guruji: "ಗುರೂಜಿಯವರನ್ನು ಕೇಳಿ",
    deep_inquiry: "ಆಳವಾದ ವಿಚಾರಣೆ",
    seek_answer: "ಉತ್ತರವನ್ನು ಹುಡುಕಿ",
    name_of_soul: "ಹೆಸರು",
    birth_date: "ಜನ್ಮ ದಿನಾಂಕ",
    birth_time: "ಜನ್ಮ ಸಮಯ",
    gender: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    other: "ಇತರ",
    search_city_placeholder: "ನಗರ ಹುಡುಕಿ...",
    muhurta_search_placeholder: "ಗುರಿ ಹುಡುಕಿ...",
    prashna_placeholder: "ನಿಮ್ಮ ಆಳವಾದ ಪ್ರಶ್ನೆ ಏನು?",
    guruji_listening: "ಗುರೂಜಿಯವರು ಕೇಳುತ್ತಿದ್ದಾರೆ...",
    connection_interrupted: "ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ",
    disconnected: "ಡಿಸ್ಕನೆಕ್ಟ್",
    support_guruji: "ಗುರೂಜಿಯವರಿಗೆ ಬೆಂಬಲ ನೀಡಿ",
    scan_to_support: "ಬೆಂಬಲಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scan_to_donate: "GPay / UPI ಮೂಲಕ ದಾನ ಮಾಡಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    support_mission: "ನಮ್ಮ ಮಿಷನ್ ಗೆ ಬೆಂಬಲ ನೀಡಿ",
    support_quote: "ನೀವು ಇದೀಗ ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ಮಾರ್ಗದರ್ಶನ ಪಡೆದಿದ್ದೀರಿ. ಇದು ನಿಮಗೆ ಇಷ್ಟವಾದಲ್ಲಿ, ನಮ್ಮನ್ನು ಬೆಂಬಲಿಸಬಹುದು.",
    csr_title: "ಆಸ್ಟ್ರೋ ಲಾಜಿಕ್ ಸಾಮಾಜಿಕ ಪ್ರಭಾವ",
    csr_books_title: "ವಿಶೇಷ ಮಕ್ಕಳಿಗೆ ಶಿಕ್ಷಣ ನೆರವು",
    csr_books_desc: "ನಮ್ಮ ಆದಾಯದ 90% ಭಾಗವನ್ನು ವಿಶೇಷ ಚೇತನ ಮಕ್ಕಳ ಶಿಕ್ಷಣಕ್ಕಾಗಿ ಧರ್ಮದತ್ತಿಯಾಗಿ ಮೀಸಲಿಟ್ಟಿದ್ದೇವೆ.",
    csr_oldage_title: "ವೃದ್ಧಾಪ್ಯದಲ್ಲಿ ಗೌರವ: ವೃದ್ಧಾಶ್ರಮಗಳ ಸೇವೆ",
    csr_oldage_desc: "ಅಶಕ್ತ ವೃದ್ಧರಿಗೆ ಆಶ್ರಯ ಮತ್ತು ಆಹಾರದ ಸೇವೆ ನೀಡುವ ನಮ್ಮ ಪವಿತ್ರ ಕಾರ್ಯ.",
    secure: "ಸುರಕ್ಷಿತ",
    spiritual: "ಆಧ್ಯಾತ್ಮಿಕ",
    support: "ಬೆಂಬಲ",
    next_page: "ಮುಂದಿನ ಪುಟ",
    save_info: "ಮಾಹಿತಿ ಉಳಿಸಿ",
    saved_profiles_title: "ಉಳಿಸಿದ ಪ್ರೊಫೈಲ್",
    celestial_map: "ಆಕಾಶ ನಕ್ಷೆ (ರಾಶಿ)",
    stars_obscured: "ಮೋಡ ಮುಚ್ಚಿರುವುದರಿಂದ ಗ್ರಹಗಳು ಕಾಣಿಸುತ್ತಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    go_back: "ಹಿಂದೆ ಹೋಗಿ",
    dismiss: "ಬಿಡಿ",
    select_city_warning: "⚠️ ಸರಿಯಾದ ಲೆಕ್ಕಾಚಾರಕ್ಕಾಗಿ ನಗರವನ್ನು ಆಯ್ದುಕೊಳ್ಳಿ.",
    search_assistant_placeholder: "ಉದಾ: 2024 ಗುರು ಗೋಚಾರ ಫಲ",
    enter_full_name: "ಪೂರ್ಣ ಹೆಸರು ಬರೆಯಿರಿ",
    feedback: "ಪ್ರತಿಕ್ರಿಯೆ",
    feedback_title: "ನಿಮ್ಮ ಅನಿಸಿಕೆ ಮತ್ತು ಸಲಹೆಗಳು",
    feedback_placeholder: "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಿ...",
    submit_feedback: "ಸಲ್ಲಿಸಿ",
    feedback_success: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!",
    first_name: "ಮೊದಲ ಹೆಸರು",
    second_name: "ಎರಡನೇ ಹೆಸರು",
    timeframe_placeholder: "ಉದಾ: ಬರುವ 3 ತಿಂಗಳಲ್ಲಿ",
    select_seeker: "ಸೀಕರ್",
    select_scholar: "ಸ್ಕಾಲರ್",
    seeker: "ಸೀಕರ್",
    scholar: "ಸ್ಕಾಲರ್",
    seeker_desc: "ಸಾಮಾನ್ಯ ಜನರಿಗಾಗಿ ಸುಲಭ ಭಾಷೆಯಲ್ಲಿ ಮಾರ್ಗದರ್ಶನ.",
    scholar_desc: "ಜ್ಯೋತಿಷಿಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ ಆಳವಾದ ತಾಂತ್ರಿಕ ಮಾಹಿತಿ ಮತ್ತು ಶ್ಲೋಕಗಳು.",
    siddhantic_precision: "ಸ್ಕಾಲರ್ ವಿಭಾಗ",
    personal_guidance: "ಸೀಕರ್ ವಿಭಾಗ",
    calculating_heavens: "ಲೆಕ್ಕಾಚಾರಗಳು ನಡೆಯುತ್ತಿವೆ...",
    ask_help_guruji: "ಗುರೂಜಿಯವರ ಸಹಾಯ ಪಡೆಯಿರಿ",
    sacred_conversation: "ಪವಿತ್ರ ಸಂಭಾಷಣೆ",
    shastriya: "ಶಾಸ್ತ್ರೀಯ",
    life_path: "ಜೀವನ ದಾರಿ",
    timeline: "ಸಮಯ",
    siddhantic: "ಸಿದ್ಧಾಂತ",
    life_phase: "ಜೀವನದ ಹಂತ",
    wealth_health: "ಸಂಪತ್ತು ಮತ್ತು ಆರೋಗ್ಯ",
    soul_map: "ಆತ್ಮದ ನಕ್ಷೆ",
    power_score: "ಶಕ್ತಿ ಸಂಖ್ಯೆ",
    under_construction: "ಈ ದಾರಿಯು ಇನ್ನೂ ನಿರ್ಮಾಣ ಹಂತದಲ್ಲಿದೆ.",
    return_home: "ಹೋಮ್ ಗೆ ಮರಳಿ",
    get_verdict: "ನಿರ್ಧಾರ ಪಡೆಯಿರಿ",
    latitude: "ಅಕ್ಷಾಂಶ",
    longitude: "ರೇಖಾಂಶ",
    timezone: "ಸಮಯ ವಲಯ",
    suggestion_title: "ಸೂಚನೆಗಳು",
    suggestion_desc: "ಅನುಭವ ಸುಧಾರಿಸಲು ಗುರೂಜಿಗೆ ಸಹಾಯ ಮಾಡಿ",
    suggestion_placeholder: "ನಿಮ್ಮ ಅನಿಸಿಕೆ ಬರೆಯಿರಿ...",
    suggestion_send: "ಕಳುಹಿಸಿ",
    suggestion_sent: "ಗುರೂಜಿಯವರಿಗೆ ಮುಟ್ಟಿದೆ",
    panchanga_title: "ಪಂಚಾಂಗ",
    custom_panchanga: "ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳ ಬದಲಿಸಿ",
    timeline_title: "ಜೀವನ ಕಾಲಕ್ರಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    contact_astrologer_title: "ದೈವಜ್ಞರಿಗೆ ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    contact_astrologer_desc: "ಮಾರ್ಗದರ್ಶನ ಪಡೆಯುವ ಪವಿತ್ರ ವಿಧಾನ",
    tambula_offering: "ತಾಂಬೂಲ ಸಮರ್ಪಣೆ",
    tambula_desc: "ವೈದಿಕ ಪದ್ಧತಿಯಂತೆ ಗುರೂಜಿಯವರಿಗೆ ದಕ್ಷಿಣೆಯೊಂದಿಗೆ ತಾಂಬೂಲ ನೀಡಿ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.",
    problem_label: "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    problem_placeholder: "ಉದಾ: ವೃತ್ತಿ ಅಭಿವೃದ್ಧಿ, ಆರೋಗ್ಯ ಸಮಸ್ಯೆ...",
    contact_time_label: "ಸಂಪರ್ಕಿಸುವ ಸಮಯ",
    contact_time_placeholder: "ಉದಾ: ನಾಳೆ ಬೆಳಿಗ್ಗೆ 10 ಗಂಟೆಗೆ",
    submit_problem: "ಸಲ್ಲಿಸಿ",
    problem_submitted_msg: "ನಮ್ಮ ಜ್ಯೋತಿಷಿಗಳು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    mangala_dosha: "ಮಂಗಳ ದೋಷ",
    conclusion_title: "ತೀರ್ಮಾನ",
    remedy_options_title: "ಪರಿಹಾರ ಮಾರ್ಗವನ್ನು ಆಯ್ದುಕೊಳ್ಳಿ",
    tier1_title: "ಉಪಾಯ ಪ್ರಾರಂಭ",
    tier1_price: "₹99",
    tier1_meaning: "ಪ್ರಾಥಮಿಕ ಪರಿಹಾರಗಳು",
    tier2_title: "ಶುಭ ಮಾರ್ಗ",
    tier2_price: "₹599",
    tier2_meaning: "ತಿರುವು ನೀಡುವ ದಾರಿ",
    tier3_title: "ಸರ್ವ ಕರ್ಮ ಹರಿವು",
    tier3_price: "₹999",
    tier3_meaning: "ಪೂರ್ಣ ಜೀವನ ವಿಶ್ಲೇಷಣೆ",
    pay_now: "ಪಾವತಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    appointment_date: "ದಿನಾಂಕ ಆಯ್ದುಕೊಳ್ಳಿ",
    appointment_time: "ಸಮಯ ಆಯ್ದುಕೊಳ್ಳಿ",
    contact_astrologer_remedies: "ಪರಿಹಾರಗಳಿಗಾಗಿ ಜ್ಯೋತಿಷಿಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ",
    analysis_tab_title: "ವಿಶ್ಲೇಷಣೆ",
    matching_tab_title: "ಹೊಂದಾಣಿಕೆ",
    chat_tab_title: "ಚಾಟ್",
    help: "ಸಹಾಯ",
    footer_text: "ದೈವಿಕ ಆಜ್ಞೆ • ಗ್ರಹಗಳ ಸಾಲು • ಆಳವಾದ ಜ್ಞಾನ",
    celestial_insights_title: "ಪ್ರಸ್ತುತ ಗ್ರಹಗಳ ಸ್ಥಿತಿ",
    search_assistant_desc: "ಗ್ರಹ ಗೋಚಾರ ಅಥವಾ ಜೋತಿಷ್ಯಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಯಾವುದೇ ವಿಚಾರ ಹುಡುಕಿ.",
    searching: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    ask_stars: "ತಾರೆಗಳನ್ನು ಕೇಳಿ",
    sources: "ಆಧಾರ",
    invoke_guruji: "ಗುರೂಜಿಯವರನ್ನು ಆಹ್ವಾನಿಸಿ",
    pranama_end: "ಪ್ರಣಾಮಗಳು (ಕೊನೆ)",
    career_guidance: "ವೃತ್ತಿ ಮಾರ್ಗದರ್ಶನ",
    love_marriage: "ಮದುವೆ ಮತ್ತು ಪ್ರೀತಿ",
    health_energy: "ಆರೋಗ್ಯ ಮತ್ತು ಶಕ್ತಿ",
    spiritual_path: "ಆಧ್ಯಾತ್ಮಿಕ ಹಾದಿ",
    seek_wisdom_message: "ಜ್ಞಾನವನ್ನು ಹುಡುಕಿ, ತಾರೆಗಳು ಗುರೂಜಿಯವರ ಮೂಲಕ ಉತ್ತರಿಸುತ್ತಾರೆ.",
    connecting: "ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
    dhanyavaada: "ಧನ್ಯವಾದಗಳು",
    pranama: "ಪ್ರಣಾಮಗಳು",
    path: "ಹಾದಿ",
    seeker_path: "ಸೀಕರ್ ಹಾದಿ",
    you_hint: "ನನಗೆ ಸಹಾಯ ಬೇಕು ",
    muhurta_vivaha: "ವಿವಾಹ",
    muhurta_grihapravesha: "ಗೃಹ ಪ್ರವೇಶ",
    muhurta_bhoomi_pooja: "ಭೂಮಿ ಪೂಜೆ",
    muhurta_upanayana: "ಉಪನಯನ",
    muhurta_namakarana: "ನಾಮಕರಣ",
    muhurta_annaprashana: "ಅನ್ನಪ್ರಾಶನ",
    muhurta_aksharabhyasa: "ಅಕ್ಷರಾಭ್ಯಾಸ",
    muhurta_vidyarambha: "ವಿದ್ಯಾರಂಭ",
    muhurta_karnavedha: "ಕರ್ಣವೇದ",
    muhurta_choodakarana: "ಕೂದಲು ತೆಗೆಯುವುದು",
    muhurta_seemantham: "ಸೀಮಂತ",
    muhurta_vahana: "ವಾಹನ ಖರೀದಿ",
    muhurta_vyapaara: "ವ್ಯಾಪಾರ ಆರಂಭ",
    muhurta_shop_opening: "ಅಂಗಡಿ ಉದ್ಘಾಟನೆ",
    muhurta_udyoga: "ಕೆಲಸಕ್ಕೆ ಸೇರುವುದು",
    muhurta_swarna: "ಚಿನ್ನ ಖರೀದಿ",
    muhurta_investments: "ಹೂಡಿಕೆ",
    muhurta_yaatra: "ಪ್ರಯಾಣ",
    muhurta_videsha: "ವಿದೇಶ ಪ್ರಯಾಣ",
    muhurta_shastra_kriya: "ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ",
    muhurta_medical_start: "ಚಿಕಿತ್ಸೆ ಸುರು",
    muhurta_abhijit: "ಅಭಿಜಿತ್ ಮುಹೂರ್ತ",
    muhurta_brahma: "ಬ್ರಹ್ಮ ಮುಹೂರ್ತ",
    muhurta_shilaanyasa: "ಗುದ್ದಲಿ ಪೂಜೆ",
    muhurta_renting: "ಬಾಡಿಗೆ ಮನೆ",
    muhurta_contracts: "ಒಪ್ಪಂದ",
    muhurta_legal: "ಕೋರ್ಟ್ ಕೆಲಸ",
    muhurta_agriculture: "ಕೃಷಿ ಕೆಲಸ",
    home: "ಹೋಮ್",
    daily_nav: "ದೈನಂದಿನ",
    oracle_nav: "ಒರಾಕಲ್",
    chat_nav: "ಚಾಟ್",
    donate_support: "ದಾನ ಮತ್ತು ಬೆಂಬಲ",
    next_analysis: "ಮುಂದೆ: ವಿಶ್ಲೇಷಣೆ ಆಯ್ದುಕೊಳ್ಳಿ",
    sacred_geometry: "ಪವಿತ್ರ ಜ್ಯಾಮಿತಿ • ಪುರಾತನ ತರ್ಕ",
    birth_analysis: "ಜನ್ಮ ವಿಶ್ಲೇಷಣೆ",
    my_character: "ನನ್ನ ವ್ಯಕ್ತಿತ್ವ",
    rasi_kundli: "ರಾಶಿ ಕುಂಡಲಿ",
    vimshottari: "ವಿಂಶೋತ್ತರಿ",
    ashtakavarga: "ಅಷ್ಟಕವರ್ಗ",
    planet_sun: "ಸೂರ್ಯ",
    planet_moon: "ಚಂದ್ರ",
    planet_mars: "ಕುಜ",
    planet_mercury: "ಬುಧ",
    planet_jupiter: "ಗುರು",
    planet_venus: "ಶುಕ್ರ",
    planet_saturn: "ಶನಿ",
    planet_rahu: "ರಾಹು",
    planet_ketu: "ಕೇತು",
    planet_lagna: "ಲಗ್ನ",
    planet_mandi: "ಮಾಂದಿ",
    rasi_mesha: "ಮೇಷ",
    rasi_vrishabha: "ವೃಷಭ",
    rasi_mithuna: "ಮಿಥುನ",
    rasi_karka: "ಕರ್ಕ",
    rasi_simha: "ಸಿಂಹ",
    rasi_kanya: "ಕನ್ಯಾ",
    rasi_tula: "ತುಲಾ",
    rasi_vrishchika: "ವೃಶ್ಚಿಕ",
    rasi_dhanu: "ಧನು",
    rasi_makara: "ಮಕರ",
    rasi_kumbha: "ಕುಂಭ",
    rasi_meena: "ಮೀನ",
    muhurta_analysis: "ಮುಹೂರ್ತ ವಿಶ್ಲೇಷಣೆ",
    auspicious_time: "ಶುಭ ಸಮಯ",
    verdict: "ನಿರ್ಣಯ",
    planetary_positions: "ಗ್ರಹಗಳ ಸ್ಥಿತಿ",
    classical_references: "ಶಾಸ್ತ್ರೀಯ ಆಧಾರ",
    panchanga_breakdown: "ಪಂಚಾಂಗ ವಿವರಗಳು",
    technical_summary: "ತಾಂತ್ರಿಕ ಸಾರಾಂಶ",
    saved_readings: "ಉಳಿಸಿದವು",
    no_readings: "ಪಟ್ಟಿ ಖಾಲಿ ಇದೆ",
    no_readings_desc: "ವಿವರಗಳನ್ನು ಉಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ.",
    clear_history_confirm: "ಎಲ್ಲವನ್ನೂ ಅಳಿಸಬೇಕೆ?",
    vastu_title: "ವಾಸ್ತು ಶಾಸ್ತ್ರ",
    vastu_desc: "ಶಕ್ತಿ ಮತ್ತು ವಾಸ್ತು",
    vastu_analysis: "ವಾಸ್ತು ವಿಶ್ಲೇಷಣೆ",
    home_harmony: "ಮನೆಯ ನೆಮ್ಮದಿ",
    palm_reading_title: "ಹಸ್ತ ಸಾಮುದ್ರಿಕ",
    palm_reading_desc: "ರೇಖೆಗಳ ನಡುವಿನ ಭವಿಷ್ಯ",
    upload_palm: "ಹಂಗೈ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    palm_instructions: "ಕೈ ನಕ್ಷೆ: ಕೈಯನ್ನು ಸಮತಟ್ಟಾದ ಜಾಗದಲ್ಲಿಟ್ಟು ಫೋಟೋ ತೆಗೆಯಿರಿ.",
    analyzing_palm: "ರೇಖೆಗಳನ್ನು ಪರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ...",
    palm_analysis_res: "ಹಸ್ತ ವಿಶ್ಲೇಷಣೆ",
    camera_access: "ಕ್ಯಾಮರಾ",
    gallery_access: "ಗ್ಯಾಲರಿ",
    invalid_palm_error: "ಫೋಟೋ ಸರಿಯಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ವಚ್ಛವಾದ ಫೋಟೋ ನೀಡಿ.",
    classical_source_authority: "ಮೂಲ ಶಾಸ್ತ್ರಾಧಾರ",
    welcome_tour: "ಸ್ವಾಗತ",
    welcome_tour_desc: "ಜ್ಯೋತಿಷ್ಯ ಪ್ರಪಂಚಕ್ಕೆ ಸುಸ್ವಾಗತ.",
    seeker_mode_active: "ಸೀಕರ್ ಹಾದಿ ಸಕ್ರಿಯ",
    scholar_mode_active: "ಸ್ಕಾಲರ್ ಹಾದಿ ಸಕ್ರಿಯ",
    seeker_tour_desc: "ಸರಳ ಮತ್ತು ಸುಲಭ ಸಾದಿ.",
    scholar_tour_desc: "ಆಳವಾದ ಜ್ಞಾನದ ಹರಿವು.",
    sacred_dashboard: "ದೈವಿಕ ಡ್ಯಾಶ್ ಬೋರ್ಡ್",
    dashboard_tour_desc: "ಪಂಚಾಂಗ ಅಪ್ಡೇಟ್ ಗಳು.",
    guruji_tour: "ಗುರೂಜಿಯವರ ಮಾರ್ಗದರ್ಶನ",
    guruji_tour_desc: "ನಿಮ್ಮ ಸಹಾಯಕ್ಕೆ ಗುರೂಜಿ ಬಟನ್.",
    navigation_tour: "ಸರಿಯಾದ ಚಲನೆ",
    nav_tour_desc: "ಬಳಸುವುದು ಸುಲಭ.",
    save_profile_error: "ಉಳಿಸಲು ಹೆಸರು ನಮೂದಿಸಿ.",
    profile_saved: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ.",
    profile_saved_for: "{name} ಗಾಗಿ ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ.",
    life_partner_analysis: "ಜೀವನ ಸಂಗಾತಿ ವಿಶ್ಲೇಷಣೆ",
    prashna_analysis: "ಪ್ರಶ್ನೆ ವಿಶ್ಲೇಷಣೆ",
    stars_silent: "ತಾರೆಗಳು ಮೌನವಾಗಿವೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    celestial_connection_failed: "ಸಂಪರ್ಕ ಸೋತಿದೆ.",
    switch_to_dark: "ಡಾರ್ಕ್ ಮೋಡ್",
    switch_to_light: "ಲೈಟ್ ಮೋಡ್",
    blog: "ಬ್ಲಾಗ್",
    blog_desc: "ಸಿದ್ಧಾಂತ ಮತ್ತು ಹೋರಾ",
    enter_details_warning: "ಸಮಯ ಮತ್ತು ದಿನಾಂಕ ನಮೂದಿಸಿ.",
    sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    offline: "ಆಫ್‌ಲೈನ್",
    csr_tagline: "ಧರ್ಮ ಮತ್ತು ಸಾಮಾಜಿಕ ಸೇವೆ",
    csr_revenue_committed: "ಆದಾಯದ ಕೊಡುಗೆ",
    csr_souls_nourished: "ಸಹಾಯ ಪಡೆದವರು",
    csr_verified_integrity: "ಪಾರದರ್ಶಕ ಸೇವೆ",
    csr_schools_supported: "ಶಾಲಾ ನೆರವು",
    csr_kits_distributed: "ಕಿಟ್ ವಿತರಣೆ",
    csr_volunteer_hours: "ಸೇವಾ ಸಮಯ",
    csr_homes_adopted: "ದತ್ತು ಪಡೆದ ಆಶ್ರಮಗಳು",
    csr_elders_assisted: "ವೃದ್ಧರ ಸೇವೆ",
    csr_medical_camps: "ವೈದ್ಯಕೀಯ ಶಿಬಿರಗಳು",
    csr_special_children_initiative: "ವಿಶೇಷ ಚೇತನ ಸೇವೆ",
    csr_elder_care_program: "ವೃದ್ಧರ ಸೇವೆ ಯೋಜನೆ",
    csr_revenue_committed_90: "90% ಆದಾಯ ಸಮಾಜ ಸೇವೆಗೆ",
    csr_holistic_care_100: "100% ಸೇವೆ",
    seeker_mode_desc_short: "ಸೀಕರ್ ಮೋಡ್",
    scholar_mode_desc_short: "ಸ್ಕಾಲರ್ ಮೋಡ್",
    saved_profiles_desc: "ಇತ್ತೀಚಿನ ಚಿತ್ರ",
    today_panchanga: "ಇಂದಿನ ಪಂಚಾಂಗ"
};

const mr_full = {
    brand_name: "अ‍ॅस्ट्रो लॉजिक",
    tagline: "प्राचीन ज्ञान आणि आधुनिक तर्क",
    begin_journey: "प्रवासाला सुरुवात करा",
    choose_path: "तुमचा मार्ग निवडा",
    disclaimer: "ज्योतिषशास्त्रीय भाकिते ग्रहांच्या गणितावर आधारित असतात. ही केवळ मार्गदर्शनासाठी आहेत.",
    planetary_transit_in: "मध्ये",
    horoscope: "कुंडली",
    matching: "गुण मिलन",
    life_partner: "जीवनसाथी",
    daily: "दैनिक राशिभविष्य",
    muhurta: "मुहूर्त",
    numerology: "अंकशास्त्र",
    chat: "अ‍ॅस्ट्रो चॅट",
    prashna: "प्रश्न",
    guruji: "गुरुजी",
    you: "तुम्ही",
    guruji_welcome: "तुमच्या जीवनाबद्दल किंवा ग्रहांच्या स्थितीबद्दल गुरुजींना विचारा.",
    guruji_thinking: "गुरुजी ग्रहांची गणना करत आहेत...",
    error_guruji: "संपर्क तुटला आहे. कृपया थोड्या वेळाने प्रयत्न करा.",
    ask_guruji_placeholder: "गुरुजींना तुमचा प्रश्न विचारा...",
    switch_mode: "पद्धत बदला",
    menu_details: "जन्म तपशील",
    menu_timeline: "जीवन कालरेखा",
    menu_hora: "होरा विश्लेषण",
    menu_sphta: "ग्रह स्पष्टता",
    menu_rasi: "राशी कुंडली",
    menu_navamsha: "नवांश कुंडली",
    menu_bhava: "भाव चलित",
    menu_bhava_analysis: "भाव विश्लेषण",
    menu_sandhi: "संधी विश्लेषण",
    menu_panchangam: "पंचांग",
    menu_dasha: "दशा भविष्य",
    menu_shadvarga: "षड्वर्ग",
    shadvarga_strengths: "षड्वर्ग बल",
    shadbala_analysis: "षड्बल",
    energy_strength: "ऊर्जा",
    planetary_power: "ग्रह बल",
    menu_yogas: "योग विश्लेषण",
    menu_maitri: "ग्रह मैत्री",
    menu_ashtaka: "अष्टकवर्ग",
    menu_trisputa: "त्रिसफुट",
    menu_dhumadi: "धूमादि ग्रह",
    menu_basic_details: "मूळ जन्म तपशील",
    menu_yoga: "योग",
    menu_career: "करिअर आणि यश",
    menu_health: "आरोग्य",
    menu_money: "संपत्ती",
    menu_transit: "ग्रह गोचर",
    menu_dasha_effect: "दशा प्रभाव",
    menu_sade_sati: "साडे साती",
    menu_gemstones: "रत्न आणि रुद्राक्ष",
    menu_nakshatra: "नक्षत्र रहस्य",
    menu_doshas: "दोष तपासणी",
    menu_character: "स्वभाव",
    menu_numerology: "अंक गणित",
    back: "परत",
    submit: "कुंडली तयार करा",
    quick_profile: "त्वरित प्रोफाइल",
    enter_details_wisdom: "तपशील भरा",
    save_continue: "जतन करा आणि पुढे चला",
    continue: "पुढे चला ➔",
    next_choose_analysis: "पुढे: विश्लेषण निवडा ➔",
    skip_for_now: "सध्या नको",
    lang_select: "भाषा",
    loshu_grid: "लोशू ग्रिड",
    full_name: "पूर्ण नाव",
    classical_predictions: "शास्त्रीय भाकिते",
    sacred_guide: "दैवी मार्गदर्शक",
    seeker_scholar_desc: "साध्या मार्गदर्शनासाठी 'सलीकर', सविस्तर माहितीसाठी 'स्कॉलर' निवडा.",
    save_profile: "प्रोफाइल जतन करा",
    saved_profiles: "अलीकडील कुंडल्या",
    matching_title: "गुण मिलन निकाल",
    conclusion: "निर्णय",
    select_rasi: "राशी निवडा",
    daily_title: "आजची ग्रहांची स्थिती",
    muhurta_title: "शुभ मुहूर्त वेळ",
    muhurta_select: "हेतू निवडा",
    sacred_intake: "माहिती भरा",
    partner_one: "भागीदार १",
    partner_two: "भागीदार २",
    birth_location: "जन्म स्थान",
    timeframe: "वेळ",
    location: "ठिकाण",
    quick_search: "त्वरीत शोध",
    oracle: "ओराकल",
    name: "नाव",
    date: "दिनांक",
    nakshatra: "नक्षत्र",
    ask_guruji: "गुरुजींना विचारा",
    deep_inquiry: "सखोल चौकशी",
    seek_answer: "उत्तर शोधा",
    name_of_soul: "नाव",
    birth_date: "जन्म तारीख",
    birth_time: "जन्म वेळ",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    search_city_placeholder: "शहर शोधा...",
    muhurta_search_placeholder: "हेतू शोधा...",
    prashna_placeholder: "तुमचा प्रश्न काय आहे?",
    guruji_listening: "गुरुजी ऐकत आहेत...",
    connection_interrupted: "संपर्क तुटला",
    disconnected: "डिसकनेक्ट",
    support_guruji: "गुरुजींना पाठिंबा द्या",
    scan_to_support: "पाठिंबा देण्यासाठी स्कॅन करा",
    scan_to_donate: "GPay / UPI द्वारे दान करण्यासाठी स्कॅन करा",
    support_mission: "आमच्या कार्याला मदत करा",
    support_quote: "तुम्ही आत्ता व्यक्तिगत ज्योतिष मार्गदर्शन मिळवले आहे. आवडल्यास आम्हाला पाठिंबा देऊ शकता.",
    csr_title: "सामाजिक प्रभाव",
    csr_books_title: "विशेष मुलांसाठी शिक्षण मदत",
    csr_books_desc: "आम्ही विशेष मुलांच्या शिक्षणासाठी आमच्या उत्पन्नाचा ९०% भाग दान करतो.",
    csr_oldage_title: "वृद्धापकाळात सन्मान",
    csr_oldage_desc: "अगतिक वृद्धांना अन्न आणि आश्रय देण्याचे आमचे कार्य.",
    secure: "सुरक्षित",
    spiritual: "आध्यात्मिक",
    support: "पाठिंबा",
    next_page: "पुढील पान",
    save_info: "माहिती जतन करा",
    saved_profiles_title: "जतन केलेले प्रोफाइल",
    celestial_map: "आकाश नकाशा",
    stars_obscured: "ढगांमुळे ग्रह दिसत नाहीत. पुन्हा प्रयत्न करा.",
    go_back: "मागे जा",
    dismiss: "सोडून द्या",
    select_city_warning: "⚠️ अचूक गणना करण्यासाठी शहर निवडा.",
    search_assistant_placeholder: "उदा: २०२४ गुरु गोचर",
    enter_full_name: "पूर्ण नाव लिहा",
    feedback: "प्रतिक्रिया",
    feedback_title: "तुमची प्रतिक्रिया आणि सूचना",
    feedback_placeholder: "तुमचा अनुभव सांगा...",
    submit_feedback: "पाठवा",
    feedback_success: "प्रतिक्रियेबद्दल धन्यवाद!",
    first_name: "पहिले नाव",
    second_name: "दुसरे नाव",
    timeframe_placeholder: "उदा: पुढील ३ महिने",
    select_seeker: "सीकर निवडा",
    select_scholar: "स्कॉलर निवडा",
    seeker: "सीकर",
    scholar: "स्कॉलर",
    seeker_desc: "सामान्य लोकांसाठी साधी भाषा.",
    scholar_desc: "ज्योतिषी आणि विद्यार्थ्यांसाठी तांत्रिक माहिती.",
    siddhantic_precision: "स्कॉलर विभाग",
    personal_guidance: "सीकर विभाग",
    calculating_heavens: "गणना सुरू आहे...",
    ask_help_guruji: "गुरुजींची मदत घ्या",
    sacred_conversation: "दैवी संवाद",
    shastriya: "शास्त्रीय",
    life_path: "जीवन मार्ग",
    timeline: "वेळ",
    siddhantic: "सिद्धांत",
    life_phase: "जीवनाचा टप्पा",
    wealth_health: "संपत्ती आणि आरोग्य",
    soul_map: "आत्म्याचा नकाशा",
    power_score: "शक्ती",
    under_construction: "काम सुरू आहे.",
    return_home: "घरी परत जा",
    get_verdict: "निकाल मिळवा",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    timezone: "वेळ क्षेत्र",
    suggestion_title: "सूचना",
    suggestion_desc: "अनुभव सुधारण्यासाठी मदत करा",
    suggestion_placeholder: "तुमचे मत लिहा...",
    suggestion_send: "पाठवा",
    suggestion_sent: "गुरुजींना मिळाले",
    panchanga_title: "पंचांग",
    today_panchanga: "आजचे पंचांग",
    custom_panchanga: "दिनांक आणि ठिकाण निवडा",
    timeline_title: "कालक्रम",
    contact_astrologer_title: "तांबूल अर्पण",
    contact_astrologer_desc: "दैवज्ञांना तांबूल द्या",
    tambula_offering: "तांबूल",
    tambula_desc: "दक्षिणेसह तांबूल देऊन मार्गदर्शन घ्या.",
    problem_label: "समस्या सांगा",
    problem_placeholder: "काय समस्या आहे?",
    contact_time_label: "संपर्काची वेळ",
    contact_time_placeholder: "कधी?",
    submit_problem: "पाठवा",
    problem_submitted_msg: "लवकरच संपर्क करू.",
    mangala_dosha: "मंगळ दोष",
    conclusion_title: "निष्कर्ष",
    remedy_options_title: "उपाय निवडा",
    tier1_title: "उपाय प्रारंभ",
    tier1_price: "₹९९",
    tier1_meaning: "सुरुवातीचे उपाय",
    tier2_title: "शुभ मार्ग",
    tier2_price: "₹५९९",
    tier2_meaning: "प्रगतीचा मार्ग",
    tier3_title: "सर्व कर्म",
    tier3_price: "₹९९९",
    tier3_meaning: "संपूर्ण माहिती",
    pay_now: "पैसे भरा",
    appointment_date: "तारीख",
    appointment_time: "वेळ",
    contact_astrologer_remedies: "ज्योतिषी संपर्क",
    analysis_tab_title: "विश्लेषण",
    matching_tab_title: "मिळवणी",
    chat_tab_title: "चॅट",
    help: "मदत",
    footer_text: "दैवी संकेत • आध्यात्मिक मार्ग",
    celestial_insights_title: "सध्याची ग्रहांची स्थिती",
    search_assistant_desc: "पंचांग आणि गोचर शोधा.",
    searching: "शोधत आहे...",
    ask_stars: "ताऱ्यांना विचारा",
    sources: "आधार",
    invoke_guruji: "गुरुजींना बोलवा",
    pranama_end: "प्रणाम",
    career_guidance: "करिअर मार्गदर्शन",
    love_marriage: "लग्नाचे योग",
    health_energy: "आरोग्य आणि ऊर्जा",
    spiritual_path: "आध्यात्मिक मार्ग",
    seek_wisdom_message: "गुरुजींच्या माध्यमातून उत्तर मिळवा.",
    connecting: "संपर्क होत आहे...",
    dhanyavaada: "धन्यवाद",
    pranama: "प्रणाम",
    path: "मार्ग",
    seeker_path: "सीकर मार्ग",
    you_hint: "मला मदत हवी आहे ",
    muhurta_vivaha: "विवाह",
    muhurta_grihapravesha: "गृह प्रवेश",
    muhurta_bhoomi_pooja: "भूमी पूजन",
    muhurta_upanayana: "मुंज",
    muhurta_namakarana: "नामकरण",
    muhurta_annaprashana: "अन्नप्राशन",
    muhurta_aksharabhyasa: "अक्षराभ्यास",
    muhurta_vidyarambha: "विद्यारंभ",
    muhurta_karnavedha: "कान टोचणे",
    muhurta_choodakarana: "जावळ",
    muhurta_seemantham: "डोहाळे जेवण",
    muhurta_vahana: "वाहन खरेदी",
    muhurta_vyapaara: "व्यवसाय प्रारंभ",
    muhurta_shop_opening: "दुकान उद्घाटन",
    muhurta_udyoga: "नोकरीवर रुजू होणे",
    muhurta_swarna: "सोने खरेदी",
    muhurta_investments: "गुंतवणूक",
    muhurta_yaatra: "प्रवास",
    muhurta_videsha: "परदेश प्रवास",
    muhurta_shastra_kriya: "ऑपरेशन",
    muhurta_medical_start: "उपचार सुरू करणे",
    muhurta_abhijit: "अभिजित मुहूर्त",
    muhurta_brahma: "ब्रह्म मुहूर्त",
    muhurta_shilaanyasa: "पायाभरणी",
    muhurta_renting: "भाड्याचे घर",
    muhurta_contracts: "करार",
    muhurta_legal: "कोर्ट काम",
    muhurta_agriculture: "शेती काम",
    home: "होम",
    daily_nav: "दैनिक",
    oracle_nav: "ओराकल",
    chat_nav: "चॅट",
    donate_support: "मदत करा",
    next_analysis: "पुढील विश्लेषण निवडा",
    sacred_geometry: "पवित्र भूमिती",
    birth_analysis: "जन्म विश्लेषण",
    my_character: "माझं स्वभाव",
    rasi_kundli: "राशी कुंडली",
    vimshottari: "विंशोत्तरी",
    ashtakavarga: "अष्टकवर्ग",
    planet_sun: "सूर्य",
    planet_moon: "चंद्र",
    planet_mars: "मंगळ",
    planet_mercury: "बुध",
    planet_jupiter: "गुरु",
    planet_venus: "शुक्र",
    planet_saturn: "शनी",
    planet_rahu: "राहू",
    planet_ketu: "केतू",
    planet_lagna: "लग्न",
    planet_mandi: "मांदी",
    rasi_mesha: "मेष",
    rasi_vrishabha: "वृषभ",
    rasi_mithuna: "मिथुन",
    rasi_karka: "कर्क",
    rasi_simha: "सिंह",
    rasi_kanya: "कन्या",
    rasi_tula: "तूळ",
    rasi_vrishchika: "वृश्चिक",
    rasi_dhanu: "धनु",
    rasi_makara: "मकर",
    rasi_kumbha: "कुंभ",
    rasi_meena: "मीन",
    muhurta_analysis: "मुहूर्त विश्लेषण",
    auspicious_time: "शुभ वेळ",
    verdict: "निकाल",
    planetary_positions: "ग्रहांची स्थिती",
    classical_references: "शास्त्रीय आधार",
    panchanga_breakdown: "पंचांग तपशील",
    technical_summary: "तांत्रिक सारांश",
    saved_readings: "आर्काइव्ह",
    no_readings: "आर्काइव्ह रिकामे आहे",
    no_readings_desc: "माहिती जतन करायला सुरुवात करा.",
    clear_history_confirm: "सर्व माहिती काढायची का?",
    vastu_title: "वास्तू शास्त्र",
    vastu_desc: "ऊर्जा आणि वास्तू",
    vastu_analysis: "वास्तू विश्लेषण",
    home_harmony: "घरातील सुख",
    palm_reading_title: "हस्तरेखा शास्त्र",
    palm_reading_desc: "हातावरील रेषांचे भविष्य",
    upload_palm: "हाताचा फोटो अपलोड करा",
    palm_instructions: "हात सपाट पृष्ठभागावर ठेवून फोटो काढा.",
    analyzing_palm: "रेषा तपासत आहे...",
    palm_analysis_res: "हस्तरेखा विश्लेषण",
    camera_access: "कॅमेरा",
    gallery_access: "गॅलरी",
    invalid_palm_error: "फोटो नीट नाही. पुन्हा प्रयत्न करा.",
    classical_source_authority: "शास्त्रीय मूळ",
    welcome_tour: "स्वागत",
    welcome_tour_desc: "ज्योतिष विश्वात आपले स्वागत.",
    seeker_mode_active: "सीकर मार्ग सक्रिय",
    scholar_mode_active: "स्कॉलर मार्ग सक्रिय",
    seeker_tour_desc: "साधा मार्ग",
    scholar_tour_desc: "सखोल ज्ञान",
    sacred_dashboard: "डॅशबोर्ड",
    dashboard_tour_desc: "पंचांग अपडेट",
    guruji_tour: "गुरुजी मार्गदर्शन",
    guruji_tour_desc: "गुरुजी बटन",
    navigation_tour: "वापरण्यास सुलभ",
    nav_tour_desc: "सर्व काही सुटसुटीत आहे.",
    save_profile_error: "नाव लिहा.",
    profile_saved: "प्रोफाइल जतन केले.",
    profile_saved_for: "{name} साठी प्रोफाइल जतन केले.",
    life_partner_analysis: "जीवनसाथी विश्लेषण",
    prashna_analysis: "प्रश्न विश्लेषण",
    stars_silent: "पुन्हा प्रयत्न करा.",
    celestial_connection_failed: "संपर्क झाला नाही.",
    switch_to_dark: "डार्क मोड",
    switch_to_light: "लाईट मोड",
    blog: "ब्लॉग",
    blog_desc: "सिद्धान्त आणि होरा",
    enter_details_warning: "वेळ आणि तारीख लिहा.",
    sending: "पाठवत आहे...",
    offline: "ऑफलाईन",
    csr_tagline: "धर्म आणि सामाजिक सेवा",
    csr_revenue_committed: "उत्पन्न दान",
    csr_souls_nourished: "लाभार्थी",
    csr_verified_integrity: "पारदर्शकता",
    csr_schools_supported: "शाळा मदत",
    csr_kits_distributed: "किट वाटप",
    csr_volunteer_hours: "सेवा वेळ",
    csr_homes_adopted: "दत्तक संस्था",
    csr_elders_assisted: "वृद्धांची सेवा",
    csr_medical_camps: "वैद्यकीय शिबिर",
    csr_special_children_initiative: "विशेष मुलांसाठी उपक्रम",
    csr_elder_care_program: "वृद्धाश्रम सेवा योजना",
    csr_revenue_committed_90: "९०% उत्पन्न समाजसेवेसाठी",
    csr_holistic_care_100: "१००% सेवा",
    seeker_mode_desc_short: "सीकर मोड",
    scholar_mode_desc_short: "स्कॉलर मोड",
    saved_profiles_desc: "अलीकडील कुंडली"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    // Find matching closing brace
    const endMarker = '  },';
    const endIndex = content.indexOf(endMarker, startIndex + startMarker.length);
    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 4);
}

let newContent = content;
newContent = updateLanguage(newContent, 'kn', kn_full);
newContent = updateLanguage(newContent, 'mr', mr_full);

fs.writeFileSync(filePath, newContent);
console.log("Updated Kannada and Marathi translations.");
