import fs from 'fs';

const filePath = './constants.tsx';
const content = fs.readFileSync(filePath, 'utf8');

const hi_full = {
    brand_name: "एस्ट्रो लॉजिक",
    tagline: "प्राचीन ज्ञान और आधुनिक तर्क का संगम",
    begin_journey: "यात्रा शुरू करें",
    choose_path: "अपना मार्ग चुनें",
    disclaimer: "ज्योतिषीय भविष्यवाणियां ग्रहों की गणनाओं पर आधारित होती हैं। यह केवल मार्गदर्शन के लिए है।",
    planetary_transit_in: "में",
    horoscope: "कुंडली",
    matching: "गुण मिलान",
    life_partner: "जीवनसाथी",
    daily: "दैनिक राशिफल",
    muhurta: "मुहूर्त",
    numerology: "अंकशास्त्र",
    chat: "एस्ट्रो चैट",
    prashna: "प्रश्न",
    guruji: "गुरुजी",
    you: "आप",
    guruji_welcome: "अपने जीवन पथ, ग्रह गोचर या आध्यात्मिक मार्गदर्शन के बारे में गुरुजी से पूछें।",
    guruji_thinking: "गुरुजी ग्रहों की गणना कर रहे हैं...",
    error_guruji: "संपर्क टूट गया है। कृपया थोड़ी देर बाद प्रयास करें।",
    ask_guruji_placeholder: "गुरुजी से अपना प्रश्न पूछें...",
    switch_mode: "पद्धति बदलें",
    menu_details: "जन्म विवरण",
    menu_timeline: "जीवन कालक्रम (अतीत, वर्तमान, भविष्य)",
    menu_hora: "शास्त्रीय होरा विश्लेषण",
    menu_sphta: "ग्रह स्पष्टता",
    menu_rasi: "राशि कुंडली",
    menu_navamsha: "नवांश कुंडली",
    menu_bhava: "भाव चलित",
    menu_bhava_analysis: "12 भावों का विश्लेषण",
    menu_sandhi: "संधि विश्लेषण",
    menu_panchangam: "पंचांग",
    menu_dasha: "विंशोत्तरी दशा",
    menu_shadvarga: "षड्वर्ग",
    shadvarga_strengths: "षड्वर्ग बल",
    shadbala_analysis: "षड्बल विश्लेषण",
    energy_strength: "ऊर्जा बल",
    planetary_power: "ग्रह बल",
    menu_yogas: "योग विश्लेषण",
    menu_maitri: "पंचधा ग्रह मैत्री",
    menu_ashtaka: "अष्टकवर्ग",
    menu_trisputa: "त्रिस्फुट विश्लेषण",
    menu_dhumadi: "धूमादि ग्रह",
    menu_basic_details: "मूल जन्म विवरण",
    menu_yoga: "योग",
    menu_career: "करियर और सफलता",
    menu_health: "स्वास्थ्य और ऊर्जा",
    menu_money: "धन और वित्त",
    menu_transit: "ग्रह गोचर",
    menu_dasha_effect: "दशाओं का प्रभाव",
    menu_sade_sati: "साढ़े साती विश्लेषण",
    menu_gemstones: "रत्न और रुद्राक्ष",
    menu_nakshatra: "नक्षत्र रहस्य",
    menu_doshas: "दोष जांच (कालसर्प/पितृ)",
    menu_character: "स्वभाव और व्यक्तित्व",
    menu_numerology: "अंकशास्त्र विश्लेषण",
    back: "पीछे",
    submit: "कुंडली बनाएं",
    quick_profile: "त्वरित प्रोफाइल",
    enter_details_wisdom: "विवरण दर्ज करें",
    save_continue: "सहेजें और आगे बढ़ें",
    continue: "आगे बढ़ें ➔",
    next_choose_analysis: "अगला: विश्लेषण चुनें ➔",
    skip_for_now: "अभी के लिए छोड़ें",
    lang_select: "भाषा",
    loshu_grid: "लोशू ग्रिड",
    full_name: "पूरा नाम",
    classical_predictions: "शास्त्रीय भविष्यवाणियां",
    sacred_guide: "पावन मार्गदर्शक",
    seeker_scholar_desc: "सरल जीवन मार्गदर्शन के लिए 'सीकर' चुनें। गहन ज्योतिषीय विवरणों के लिए 'स्कॉलर' चुनें।",
    save_profile: "प्रोफाइल सहेजें",
    saved_profiles: "हालिया कुंडलियां",
    matching_title: "विवाह मिलान फल",
    conclusion: "निष्कर्ष",
    select_rasi: "राशि चुनें",
    daily_title: "आज का आकाशीय प्रवाह",
    muhurta_title: "शुभ मुहूर्त समय",
    muhurta_select: "प्रयोजन चुनें",
    sacred_intake: "डेटा प्रविष्टि",
    partner_one: "प्रथम साथी",
    partner_two: "द्वितीय साथी",
    birth_location: "जन्म स्थान",
    timeframe: "समय सीमा",
    location: "स्थान",
    quick_search: "त्वरित खोज",
    oracle: "ओराकल",
    name: "नाम",
    date: "तारीख",
    nakshatra: "नक्षत्र",
    ask_guruji: "गुरुजी से पूछें",
    deep_inquiry: "गहन पूछताछ",
    seek_answer: "उत्तर खोजें",
    name_of_soul: "नाम",
    birth_date: "जन्म तिथि",
    birth_time: "जन्म समय",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    search_city_placeholder: "शहर खोजें...",
    muhurta_search_placeholder: "प्रयोजन खोजें...",
    prashna_placeholder: "तारों से आपका क्या प्रश्न है?",
    guruji_listening: "गुरुजी सुन रहे हैं...",
    connection_interrupted: "संपर्क टूट गया है",
    disconnected: "डिस्कनेक्टेड",
    support_guruji: "गुरुजी का समर्थन करें",
    scan_to_support: "समर्थन के लिए स्कैन करें",
    scan_to_donate: "GPay / UPI के माध्यम से दान करने के लिए स्कैन करें",
    support_mission: "हमारे मिशन में साथ दें",
    support_quote: "आपने अभी एक व्यक्तिगत ज्योतिषीय परामर्श प्राप्त किया है। यदि यह आपको अच्छा लगा, तो आप हमें आगे बढ़ने में मदद कर सकते हैं।",
    csr_title: "एस्ट्रो लॉजिक सामाजिक प्रभाव",
    csr_books_title: "विशेष बच्चों के लिए शैक्षिक सहायता",
    csr_books_desc: "एस्ट्रो लॉजिक विशेष बच्चों के सर्वांगीण विकास के लिए प्रतिबद्ध है। हम भारत के विभिन्न स्कूलों में शैक्षिक सामग्री प्रदान करते हैं। हमारी आय का 90% इस नेक कार्य में जाता है।",
    csr_oldage_title: "बुढ़ापे में सम्मान: वृद्धाश्रम सेवा",
    csr_oldage_desc: "असहाय बुजुर्गों को भोजन और आश्रय प्रदान करने का हमारा पवित्र सेवा कार्य।",
    secure: "सुरक्षित",
    spiritual: "आध्यात्मिक",
    support: "समर्थन",
    next_page: "अगला पृष्ठ",
    save_info: "जानकारी सहेजें",
    saved_profiles_title: "सहेजे गए प्रोफाइल",
    celestial_map: "खगोलीय मानचित्र (राशि)",
    stars_obscured: "बादलों की वजह से तारे दिखाई नहीं दे रहे हैं। फिर से प्रयास करें।",
    go_back: "पीछे जाएं",
    dismiss: "खारिज करें",
    select_city_warning: "⚠️ सटीक गणना के लिए सूची से शहर चुनें।",
    search_assistant_placeholder: "उदाहरण: 2024 में मेष राशि पर गुरु का प्रभाव",
    enter_full_name: "पूरा नाम दर्ज करें",
    feedback: "प्रतिपुष्टि और सुझाव",
    feedback_title: "आपकी प्रतिपुष्टि और सुझाव",
    feedback_placeholder: "अपना अनुभव या सुझाव हमारे साथ साझा करें...",
    submit_feedback: "प्रतिपुष्टि भेजें",
    feedback_success: "प्रतिपुष्टि के लिए धन्यवाद!",
    first_name: "प्रथम नाम",
    second_name: "द्वितीय नाम",
    timeframe_placeholder: "उदाहरण: अगले 3 महीने",
    select_seeker: "सीकर चुनें",
    select_scholar: "स्कॉलर चुनें",
    seeker: "सीकर",
    scholar: "स्कॉलर",
    seeker_desc: "आम लोगों के लिए सरल जीवन मार्गदर्शन, करियर और दैनिक ऊर्जा पूर्वानुमान।",
    scholar_desc: "ज्योतिषियों और छात्रों के लिए गहन तकनीकी जानकारी, शास्त्रीय श्लोक और सूक्ष्म गणितीय विश्लेषण।",
    siddhantic_precision: "स्कॉलर विभाग",
    personal_guidance: "सीकर विभाग",
    calculating_heavens: "खगोलीय गणनाएँ चल रही हैं...",
    ask_help_guruji: "मदद के लिए गुरुजी से कहें",
    sacred_conversation: "एक पावन संवाद",
    shastriya: "शास्त्रीय",
    life_path: "जीवन पथ",
    timeline: "समयरेखा",
    siddhantic: "सिद्धांत",
    life_phase: "जीवन का चरण",
    wealth_health: "धन और स्वास्थ्य",
    soul_map: "आत्मा का मानचित्र",
    power_score: "शक्ति संख्या",
    under_construction: "यह मार्ग वर्तमान में निर्माणाधीन है।",
    return_home: "होम पर लौटें",
    get_verdict: "निर्णय प्राप्त करें",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    timezone: "समय क्षेत्र",
    suggestion_title: "सुझाव",
    suggestion_desc: "अनुभव को बेहतर बनाने में गुरुजी की मदद करें",
    suggestion_placeholder: "सुझाव लिखें या समस्या बताएं...",
    suggestion_send: "सुझाव भेजें",
    suggestion_sent: "गुरुजी को भेजा गया",
    panchanga_title: "पंचांग",
    custom_panchanga: "तिथि और स्थान बदलें",
    timeline_title: "जीवनरेखा डैशबोर्ड",
    contact_astrologer_title: "दैवज्ञ को तांबूल अर्पण",
    contact_astrologer_desc: "परामर्श मांगने की एक पावन पद्धति",
    tambula_offering: "तांबूल अर्पण",
    tambula_desc: "वैदिक परंपरा के अनुसार, गुरु को पान, सुपारी और दक्षिणा अर्पित कर मार्गदर्शन प्राप्त करें।",
    problem_label: "अपनी समस्या का वर्णन करें",
    problem_placeholder: "उदाहरण: करियर वृद्धि, स्वास्थ्य समस्या...",
    contact_time_label: "संपर्क करने का पसंदीदा समय",
    contact_time_placeholder: "उदाहरण: कल सुबह 10 बजे",
    submit_problem: "अनुरोध भेजें",
    problem_submitted_msg: "हमारे ज्योतिषी जल्द ही आपसे संपर्क करेंगे।",
    mangala_dosha: "मंगल दोष",
    conclusion_title: "संक्षिप्त निष्कर्ष",
    remedy_options_title: "अपना उपाय मार्ग चुनें",
    tier1_title: "उपाय प्रारंभ",
    tier1_price: "₹99",
    tier1_meaning: "प्रारंभिक उपाय",
    tier2_title: "शुभ मार्ग",
    tier2_price: "₹599",
    tier2_meaning: "भाग्य बदलने वाला रास्ता",
    tier3_title: "सर्व कर्म विश्लेषण",
    tier3_price: "₹999",
    tier3_meaning: "पूर्ण जीवन का विश्लेषण",
    pay_now: "भुगतान करें और आगे बढ़ें",
    appointment_date: "तिथि चुनें",
    appointment_time: "समय चुनें",
    contact_astrologer_remedies: "उपायों के लिए ज्योतिषी से संपर्क करें",
    analysis_tab_title: "विश्लेषण",
    matching_tab_title: "मिलान",
    chat_tab_title: "एस्ट्रो चैट",
    help: "सहायता",
    footer_text: "दैवीय विधान • आकाशीय संरेखण • गहन ज्ञान",
    celestial_insights_title: "वर्तमान खगोलीय अंतर्दृष्टि",
    search_assistant_desc: "ग्रह गोचर या विशिष्ट ज्योतिषीय घटनाओं के बारे में खोजें।",
    searching: "खोज जारी है...",
    ask_stars: "तारों से पूछें",
    sources: "स्रोत",
    invoke_guruji: "गुरुजी का आह्वान करें",
    pranama_end: "प्रणाम (समाप्त)",
    career_guidance: "करियर मार्गदर्शन",
    love_marriage: "प्रेम और विवाह",
    health_energy: "स्वास्थ्य और ऊर्जा",
    spiritual_path: "आध्यात्मिक मार्ग",
    seek_wisdom_message: "ज्ञान खोजें और गुरुजी के माध्यम से तारे उत्तर देंगे।",
    connecting: "कनेक्ट किया जा रहा है...",
    dhanyavaada: "धन्यवाद",
    pranama: "प्रणाम",
    path: "पथ",
    seeker_path: "सीकर पथ",
    you_hint: "मुझे मदद चाहिए ",
    muhurta_vivaha: "विवाह",
    muhurta_grihapravesha: "गृह प्रवेश",
    muhurta_bhoomi_pooja: "भूमि पूजन",
    muhurta_upanayana: "उपनयन",
    muhurta_namakarana: "नामकरण",
    muhurta_annaprashana: "अन्नप्राशन",
    muhurta_aksharabhyasa: "अक्षरारंभ",
    muhurta_vidyarambha: "विद्यारंभ",
    muhurta_karnavedha: "कर्णवेध",
    muhurta_choodakarana: "मुंडन",
    muhurta_seemantham: "सीमांतोन्नयन (गोद भराई)",
    muhurta_vahana: "वाहन खरीद",
    muhurta_vyapaara: "व्यापार प्रारंभ",
    muhurta_shop_opening: "दुकान उद्घाटन",
    muhurta_udyoga: "कार्यभार ग्रहण",
    muhurta_swarna: "स्वर्ण खरीद",
    muhurta_investments: "निवेश",
    muhurta_yaatra: "महत्वपूर्ण यात्रा",
    muhurta_videsha: "विदेश यात्रा",
    muhurta_shastra_kriya: "ऑपरेशन (शल्य चिकित्सा)",
    muhurta_medical_start: "उपचार शुरू करना",
    muhurta_abhijit: "अभिजित मुहूर्त",
    muhurta_brahma: "ब्रह्म मुहूर्त",
    muhurta_shilaanyasa: "नींव पूजन",
    muhurta_renting: "घर परिवर्तन/किराया",
    muhurta_contracts: "अनुबंध हस्ताक्षर",
    muhurta_legal: "कानूनी कार्य",
    muhurta_agriculture: "कृषि कार्य",
    home: "होम",
    daily_nav: "दैनिक",
    oracle_nav: "ओराकल",
    chat_nav: "चैट",
    donate_support: "दान और समर्थन",
    next_analysis: "अगला: विश्लेषण चुनें",
    sacred_geometry: "पवित्र ज्यामिति • प्राचीन तर्क",
    birth_analysis: "जन्म विश्लेषण",
    my_character: "मेरा स्वभाव",
    rasi_kundli: "राशि कुंडली",
    vimshottari: "विंशोत्तरी",
    ashtakavarga: "अष्टकवर्ग",
    planet_sun: "सूर्य",
    planet_moon: "चंद्र",
    planet_mars: "मंगल",
    planet_mercury: "बुध",
    planet_jupiter: "गुरु",
    planet_venus: "शुक्र",
    planet_saturn: "शनि",
    planet_rahu: "राहू",
    planet_ketu: "केतु",
    planet_lagna: "लग्न",
    planet_mandi: "मांदी",
    rasi_mesha: "मेष",
    rasi_vrishabha: "वृषभ",
    rasi_mithuna: "मिथुन",
    rasi_karka: "कर्क",
    rasi_simha: "सिंह",
    rasi_kanya: "कन्या",
    rasi_tula: "तुला",
    rasi_vrishchika: "वृश्चिक",
    rasi_dhanu: "धनु",
    rasi_makara: "मकर",
    rasi_kumbha: "कुंभ",
    rasi_meena: "मीन",
    muhurta_analysis: "सूक्ष्म संयोग",
    auspicious_time: "शुभ समय",
    verdict: "वैदिक निर्णय",
    planetary_positions: "ग्रहों की स्थिति",
    classical_references: "शास्त्रीय प्रमाण",
    panchanga_breakdown: "पंचांग विश्लेषण",
    technical_summary: "तकनीकी सार",
    saved_readings: "पिटारा",
    no_readings: "पिटारा खाली है",
    no_readings_desc: "अपनी जानकारी जानने के लिए कुंडली या प्रश्न शुरू करें।",
    clear_history_confirm: "सभी सहेजी गई जानकारी हटा दें?",
    vastu_title: "वास्तु शास्त्र",
    vastu_desc: "अपने स्थान को दैवीय ऊर्जा से जोड़ें",
    vastu_analysis: "स्थापत्य वेद विश्लेषण",
    home_harmony: "गृह सुख",
    palm_reading_title: "हस्तरेखा विचार",
    palm_reading_desc: "हस्तरेखा शास्त्र का प्राचीन ज्ञान",
    upload_palm: "हथेली का चित्र अपलोड करें",
    palm_instructions: "निर्देश: हथेली को सपाट रखें और सीधे ऊपर से फोटो लें।",
    analyzing_palm: "भाग्य की रेखाएं पढ़ी जा रही हैं...",
    palm_analysis_res: "हस्तरेखा विश्लेषण",
    camera_access: "कैमरा खोलें",
    gallery_access: "गैलरी से चुनें",
    invalid_palm_error: "दैवीय दृष्टि यहां हथेली स्पष्ट नहीं देख पा रही। कृपया साफ चित्र दें।",
    classical_source_authority: "शास्त्रीय स्रोत प्राधिकरण",
    welcome_tour: "एस्ट्रो लॉजिक में स्वागत है",
    welcome_tour_desc: "आइए आपकी खगोलीय यात्रा शुरू करें।",
    seeker_mode_active: "सीकर पथ सक्रिय",
    scholar_mode_active: "स्कॉलर पथ सक्रिय",
    seeker_tour_desc: "आप अभी सीकर मोड में हैं। हम सरल और व्यावहारिक सलाह देंगे।",
    scholar_tour_desc: "आप अभी स्कॉलर मोड में हैं। गहन गणितीय और शास्त्रीय विश्लेषण की अपेक्षा करें।",
    sacred_dashboard: "खगोलीय डैशबोर्ड",
    dashboard_tour_desc: "पंचांग और विभिन्न ज्योतिषीय उपकरणों का आसान माध्यम।",
    guruji_tour: "गुरुजी से परामर्श लें",
    guruji_tour_desc: "नीचे तैरते हुए 'गुरुजी' बटन पर क्लिक करके सीधे प्रश्न पूछें।",
    navigation_tour: "आसान नेविगेशन",
    nav_tour_desc: "विभिन्न मेनू और फीचर के बीच स्विच करने के लिए नीचे दिए गए बार का उपयोग करें।",
    save_profile_error: "सहेजने के लिए नाम दर्ज करें।",
    profile_saved: "प्रोफाइल सहेज लिया गया है।",
    profile_saved_for: "{name} का प्रोफाइल सहेज लिया गया है।",
    life_partner_analysis: "जीवनसाथी विश्लेषण",
    prashna_analysis: "प्रश्न विश्लेषण",
    stars_silent: "तारों से कोई जवाब नहीं मिल रहा। फिर से कोशिश करें।",
    celestial_connection_failed: "दिव्य संपर्क स्थापित नहीं हो सका।",
    switch_to_dark: "डार्क मोड",
    switch_to_light: "लाइट मोड",
    blog: "ब्लॉग",
    blog_desc: "सिद्धांत और होरा",
    enter_details_warning: "सटीక गणना के लिए जन्म तिथि और समय दें।",
    sending: "भेजा जा रहा है...",
    offline: "ऑफलाइन",
    csr_tagline: "धर्म और कर्म",
    csr_revenue_committed: "राजस्व प्रतिबद्धता",
    csr_souls_nourished: "लाभार्थी",
    csr_verified_integrity: "सत्यापित ईमानदारी",
    csr_schools_supported: "समर्थित विद्यालय",
    csr_kits_distributed: "वितरित किट",
    csr_volunteer_hours: "सेवा समय",
    csr_homes_adopted: "गोद लिए आश्रम",
    csr_elders_assisted: "सहायता प्राप्त बुजुर्ग",
    csr_medical_camps: "मेडिकल कैंप",
    csr_special_children_initiative: "विशेष बच्चों की पहल",
    csr_elder_care_program: "वृद्धाश्रम सेवा कार्यक्रम",
    csr_revenue_committed_90: "90% राजस्व प्रतिबद्धता",
    csr_holistic_care_100: "100% समग्र सेवा",
    seeker_mode_desc_short: "सीकर मोड • पावन निर्देश",
    scholar_mode_desc_short: "स्कॉलर मोड • सूक्ष्म विश्लेषण",
    saved_profiles_desc: "हालिया कुंडलियां",
    today_panchanga: "आज का पंचांग"
};

const sa_full = {
    brand_name: "एस्ट्रो लॉजिक",
    tagline: "प्राचीन ज्ञानं आधुनिकतर्कस्य च सङ्गमः",
    begin_journey: "प्रारम्भं कुर्वन्तु",
    choose_path: "स्वमार्गं चिनोतु",
    disclaimer: "ज्योतिषीयभविष्यवाणयः ग्रहगणनाधारिताः सन्ति। एतद् केवलं मार्गदर्शनाय अस्ति।",
    planetary_transit_in: "मध्ये",
    horoscope: "कुण्डली",
    matching: "गुणमेलनम्",
    life_partner: "जीवनसाथी",
    daily: "दैनिकराशिफलम्",
    muhurta: "मुहूर्तः",
    numerology: "अङ्कशास्त्रम्",
    chat: "एस्ट्रो-चैट्",
    prashna: "प्रश्नः",
    guruji: "गुरुजी",
    you: "भवान्/भवती",
    guruji_welcome: "स्वजीवनस्य, ग्रहगोचरस्य वा आध्यात्मिकमार्गदर्शनस्य विषये गुरुजीं पृच्छन्तु।",
    guruji_thinking: "गुरुजी ग्रहाणां गणनां करोति...",
    error_guruji: "सम्पर्कः त्रुटितः अस्ति। कृपया अल्पकालानन्तरं प्रयत्नं कुर्वन्तु।",
    ask_guruji_placeholder: "गुरुजीं स्वप्रश्नं पृच्छन्तु...",
    switch_mode: "पद्धतिं परिवर्तयन्तु",
    menu_details: "जन्मविवरणम्",
    menu_timeline: "जीवनकालक्रमः",
    menu_hora: "शास्त्रीयहोराविश्लेषणम्",
    menu_sphta: "ग्रहस्पष्टता",
    menu_rasi: "राशिकुण्डली",
    menu_navamsha: "नवांशकुण्डली",
    menu_bhava: "भावचलितम्",
    menu_bhava_analysis: "द्वादशभावानां विश्लेषणम्",
    menu_sandhi: "सन्धिविश्लेषणम्",
    menu_panchangam: "पञ्चाङ्गम्",
    menu_dasha: "विंशोत्तरीदशा",
    menu_shadvarga: "षड्वर्गः",
    shadvarga_strengths: "षड्वर्गबलम्",
    shadbala_analysis: "षड्बलविश्लेषणम्",
    energy_strength: "ऊर्जाबलम्",
    planetary_power: "ग्रहबलम्",
    menu_yogas: "योगविश्लेषणम्",
    menu_maitri: "पञ्चधामैत्री",
    menu_ashtaka: "अष्टकवर्गः",
    menu_trisputa: "त्रीस्फुटविश्लेषणम्",
    menu_dhumadi: "धूमादिग्रहाः",
    menu_basic_details: "मूलजन्मविवरणम्",
    menu_yoga: "योगाः",
    menu_career: "करियरं सफ़लता च",
    menu_health: "स्वास्थ्यम् ऊर्जा च",
    menu_money: "धनं वित्तं च",
    menu_transit: "ग्रहगोचरः",
    menu_dasha_effect: "दशानां प्रभावः",
    menu_sade_sati: "साडे-साती विश्लेषणम्",
    menu_gemstones: "रत्नानि रुद्राक्षाणि च",
    menu_nakshatra: "नक्षत्ररहस्याणि",
    menu_doshas: "दोषपरीक्षणम्",
    menu_character: "स्वभावः व्यक्तित्वं च",
    menu_numerology: "अङ्कशास्त्रविश्लेषणम्",
    back: "पृष्ठतः",
    submit: "कुण्डलीं रचयतु",
    quick_profile: "शीघ्रप्रोफ़ाइल",
    enter_details_wisdom: "विवरणं लिखन्तु",
    save_continue: "रक्षतु अग्रे गच्छतु च",
    continue: "अग्रे गच्छतु ➔",
    next_choose_analysis: "अग्रिमम्: विश्लेषणं चिनोतु ➔",
    skip_for_now: "अधुना मास्तु",
    lang_select: "भाषा",
    loshu_grid: "लोशू-ग्रिड्",
    full_name: "पूर्णनाम",
    classical_predictions: "शास्त्रीयभविष्यवाणयः",
    sacred_guide: "पावनमार्गदर्शकः",
    seeker_scholar_desc: "सरलजीवनाय 'सीकर' इति चिनोतु। गूढज्योतिषाय 'स्कॉलर' इति चिनोतु।",
    save_profile: "प्रोफाइलं रक्षतु",
    saved_profiles: "अचिरतनु कुण्डल्यः",
    matching_title: "विवाहमेलनफलम्",
    conclusion: "निष्कर्षः",
    select_rasi: "राशिं चिनोतु",
    daily_title: "अद्यतनं खगोलीयप्रवाहः",
    muhurta_title: "शुभमुहूर्तसमयाः",
    muhurta_select: "प्रयोजनं चिनोतु",
    sacred_intake: "दत्तप्रवेशः",
    partner_one: "प्रथमः साथी",
    partner_two: "द्वितीयः साथी",
    birth_location: "जन्मस्थानम्",
    timeframe: "समयसीमा",
    location: "स्थानम्",
    quick_search: "शीघ्रान्वेषणम्",
    oracle: "ओराकल",
    name: "नाम",
    date: "तिथी",
    nakshatra: "नक्षत्रम्",
    ask_guruji: "गुरुजीं पृच्छन्तु",
    deep_inquiry: "गहनपृच्छा",
    seek_answer: "उत्तरम् अन्विष्यतु",
    name_of_soul: "नाम",
    birth_date: "जन्मतिथिः",
    birth_time: "जन्मसमयः",
    gender: "लिङ्गम्",
    male: "पुरुषः",
    female: "महिला",
    other: "अन्यः",
    search_city_placeholder: "नगरम् अन्विष्यतु...",
    muhurta_search_placeholder: "प्रयोजनम् अन्विष्यतु...",
    prashna_placeholder: "तारेभ्यः भवता प्रश्नः कः?",
    guruji_listening: "गुरुजी शृणोति...",
    connection_interrupted: "सम्पर्कः विच्छिन्नः",
    disconnected: "विच्छिन्नः",
    support_guruji: "गुरुजीं समर्थयन्तु",
    scan_to_support: "समर्थनाय स्कैन् कुर्वन्तु",
    scan_to_donate: "GPay/UPI द्वारा दानाय स्कैन् कुर्वन्तु",
    support_mission: "अस्माकं कार्ये साहाय्यं कुर्वन्तु",
    support_quote: "भवता अधुना व्यक्तिगतं ज्योतिषमार्गदर्शनं प्राप्तम्। यदि एतत् रुचिकरं, तर्हि अस्मान् समर्थयितुं शक्नोति।",
    csr_title: "एस्ट्रो-लॉजिक सामाजिकप्रभावः",
    csr_books_title: "विशेषबालकेभ्यः शैक्षिकसहायता",
    csr_books_desc: "वयं विशेषबालकानां कृते शैक्षिकसामग्रीं प्रदद्मः।",
    csr_oldage_title: "वृद्धावस्थायां सम्मानः",
    csr_oldage_desc: "असहायवृद्धानां कृते भोजनं आवासं च प्रदातुं अस्माकं पावनं सेवाकार्यम्।",
    secure: "सुरक्षितम्",
    spiritual: "आध्यात्मिकम्",
    support: "समर्थनम्",
    next_page: "अग्रिमपृष्ठम्",
    save_info: "विवरणं रक्षतु",
    saved_profiles_title: "रक्षिताः प्रोफाइलाः",
    celestial_map: "खगोलीयमानचित्रम् (राशिः)",
    stars_obscured: "मेघैः ग्रहाः आवृताः सन्ति। पुनः प्रयत्नं कुर्वन्तु।",
    go_back: "पृष्ठतः गच्छतु",
    dismiss: "अपास्तं करोतु",
    select_city_warning: "⚠️ शुद्धगणनाय नगरं चिनोतु।",
    search_assistant_placeholder: "उदा: २०२४ वर्षे मेषराशौ बृहस्पतेः प्रभावः",
    enter_full_name: "पूर्णनाम लिखन्तु",
    feedback: "प्रतिपुष्टिः सूचनं च",
    feedback_title: "भवतः प्रतिपुष्टिः",
    feedback_placeholder: "स्वअनुभवं गुरुजीं प्रति कथयन्तु...",
    submit_feedback: "प्रतिपुष्टिं प्रेषयतु",
    feedback_success: "धन्यवादः!",
    first_name: "प्रथमनाम",
    second_name: "द्वितीयनाम",
    timeframe_placeholder: "उदा: आगामि ३ मासाः",
    select_seeker: "सीकरं चिनोतु",
    select_scholar: "स्कॉलरं चिनोतु",
    seeker: "सीकरः",
    scholar: "स्कॉलरः",
    seeker_desc: "सामान्यानां कृते सरलमार्गदर्शनम्।",
    scholar_desc: "ज्योतिषिणां छात्राणां च कृते गूढज्ञानम् सम्यक् च।",
    siddhantic_precision: "स्कॉलर-विभागः",
    personal_guidance: "सीकर-विभागः",
    calculating_heavens: "खगोलीयगणना प्रचलति...",
    ask_help_guruji: "साहाय्याय गुरुजीं कथयन्तु",
    sacred_conversation: "पावनं सम्भाषणम्",
    shastriya: "शास्त्रीयम्",
    life_path: "जीवनमार्गः",
    timeline: "समयरेखा",
    siddhantic: "सिद्धान्तः",
    life_phase: "जीवनचरणम्",
    wealth_health: "धनं स्वास्थ्यं च",
    soul_map: "आत्ममानचित्रम्",
    power_score: "शक्तिसङ्ख्या",
    under_construction: "एषः मार्गः अधुना निर्माणधीनः अस्ति।",
    return_home: "गृहं प्रति गच्छतु",
    get_verdict: "निर्णयं प्राप्नुवन्तु",
    latitude: "अक्षांशः",
    longitude: "देशान्तरः",
    timezone: "समयक्षेत्रम्",
    suggestion_title: "परामर्शः",
    suggestion_desc: "गुरुजीं साहाय्यं कुर्वन्तु",
    suggestion_placeholder: "परामर्शं लिखन्तु...",
    suggestion_send: "प्रेषयतु",
    suggestion_sent: "गुरुजीं प्राप्तम्",
    panchanga_title: "पञ्चाङ्गम्",
    custom_panchanga: "तिथीं स्थानं च परिवर्तयन्तु",
    timeline_title: "जीवनरेखा डैशबोर्ड्",
    contact_astrologer_title: "दैवज्ञाय ताम्बूलार्पणम्",
    contact_astrologer_desc: "परामर्शाय पावनपद्धतिः",
    tambula_offering: "ताम्बूलार्पणम्",
    tambula_desc: "ताम्बूलं दक्षिणां च दत्त्वा गुरुजीं पृच्छन्तु।",
    problem_label: "स्वसमस्यां वर्णयतु",
    problem_placeholder: "उदा: करियर-वृद्धिः, स्वास्थ्यं...",
    contact_time_label: "सम्पर्कसमयः",
    contact_time_placeholder: "उदा: श्वः प्रातः १० वादने",
    submit_problem: "निवेदनं प्रेषयतु",
    problem_submitted_msg: "अस्माकं ज्योतिषिणः शीघ्रमेव सम्पर्कं करिष्यन्ति।",
    mangala_dosha: "मङ्गलदोषः",
    conclusion_title: "संक्षिप्तं निष्कर्षम्",
    remedy_options_title: "स्वोपायमार्गं चिनोतु",
    tier1_title: "उपायप्रारम्भः",
    tier1_price: "₹९९",
    tier1_meaning: "प्राथमिकोपायाः",
    tier2_title: "शुभमार्गः",
    tier2_price: "₹५९९",
    tier2_meaning: "कल्याणकारी मार्गः",
    tier3_title: "सर्वकर्म-विश्लेषणम्",
    tier3_price: "₹९९९",
    tier3_meaning: "पूर्णजीवनविश्लेषणम्",
    pay_now: "धनं दत्त्वा अग्रे गच्छतु",
    appointment_date: "तिथिं चिनोतु",
    appointment_time: "समयं चिनोतु",
    contact_astrologer_remedies: "उपायेभ्यः ज्योतिषिणा सह वदन्तु",
    analysis_tab_title: "विश्लेषणम्",
    matching_tab_title: "मेलनम्",
    chat_tab_title: "एस्ट्रो-चैट्",
    help: "साहाय्यम्",
    footer_text: "दैवविधानम् • खगोलीयज्ञानम् • गभीरज्ञानम्",
    celestial_insights_title: "अद्यतनखगोलीयस्थितयः",
    search_assistant_desc: "ग्रहगोचरम् अन्विष्यतु।",
    searching: "अन्वेषणं प्रचलति...",
    ask_stars: "तारेभ्यः पृच्छन्तु",
    sources: "स्रोताः",
    invoke_guruji: "गुरुजीम् आह्वयन्तु",
    pranama_end: "प्रणामाः (समाप्तम्)",
    career_guidance: "करियर-मार्गदर्शनम्",
    love_marriage: "प्रेम विवाहं च",
    health_energy: "स्वास्थ्यम् ऊर्जा च",
    spiritual_path: "आध्यात्मिकमार्गः",
    seek_wisdom_message: "ज्ञानं अन्विष्यतु, तारेभ्यः उत्तरं प्राप्नुवन्तु।",
    connecting: "सम्पर्कं कुर्वन् अस्ति...",
    dhanyavaada: "धन्यवादः",
    pranama: "प्रणामः",
    path: "मार्गः",
    seeker_path: "सीकर-मार्गः",
    you_hint: "मम साहाय्यं आवश्यकं ",
    muhurta_vivaha: "विवाहमुहूर्तः",
    muhurta_grihapravesha: "गृहप्रवेशः",
    muhurta_bhoomi_pooja: "भूमिपूजनम्",
    muhurta_upanayana: "उपनयनम्",
    muhurta_namakarana: "नामकरणम्",
    muhurta_annaprashana: "अन्नप्राशनम्",
    muhurta_aksharabhyasa: "अक्षरारम्भः",
    muhurta_vidyarambha: "विद्यारम्भः",
    muhurta_karnavedha: "कर्णवेधः",
    muhurta_choodakarana: "चूडाकरणम् (मुण्डनम्)",
    muhurta_seemantham: "सीमन्तोन्नयनम्",
    muhurta_vahana: "वाहनक्रयः",
    muhurta_vyapaara: "व्यापारप्रारम्भः",
    muhurta_shop_opening: "आपणोद्घाटनम्",
    muhurta_udyoga: "कार्यभारग्रहणम्",
    muhurta_swarna: "स्वर्णक्रयः",
    muhurta_investments: "निवेशः",
    muhurta_yaatra: "महत्त्वपूर्णा यात्रा",
    muhurta_videsha: "विदेशयात्रा",
    muhurta_shastra_kriya: "शल्यचिकित्सा",
    muhurta_medical_start: "चिकित्साप्रारम्भः",
    muhurta_abhijit: "अभिजित् मुहूर्तः",
    muhurta_brahma: "ब्रह्म मुहूर्तः",
    muhurta_shilaanyasa: "शिलाभिन्यासः",
    muhurta_renting: "गृहपरिवर्तनम्",
    muhurta_contracts: "अनुबन्धलेखनम्",
    muhurta_legal: "न्यायालयसम्बन्धिकार्यम्",
    muhurta_agriculture: "कृषिकार्यम्",
    home: "गृहम्",
    daily_nav: "दैनिकम्",
    oracle_nav: "ओराकल",
    chat_nav: "चैट्",
    donate_support: "दानं समर्थनं च",
    next_analysis: "अग्रिमम्: विश्लेषणं चिनोतु",
    sacred_geometry: "पावनज्यामितिः",
    birth_analysis: "जन्मविश्लेषणम्",
    my_character: "मम स्वभावः",
    rasi_kundli: "राशिसम्बन्धि",
    vimshottari: "विंशोत्तरी",
    ashtakavarga: "अष्टकवर्गः",
    planet_sun: "सूर्यः",
    planet_moon: "चन्द्रः",
    planet_mars: "मङ्गलम्",
    planet_mercury: "बुधः",
    planet_jupiter: "गुरुः",
    planet_venus: "शुक्रः",
    planet_saturn: "शनिः",
    planet_rahu: "राहुः",
    planet_ketu: "केतुः",
    planet_lagna: "लग्नम्",
    planet_mandi: "मान्दिः",
    rasi_mesha: "मेषः",
    rasi_vrishabha: "वृषभः",
    rasi_mithuna: "मिथुनम्",
    rasi_karka: "कर्कः",
    rasi_simha: "सिंहः",
    rasi_kanya: "कन्या",
    rasi_tula: "तुला",
    rasi_vrishchika: "वृश्चिकः",
    rasi_dhanu: "धनुः",
    rasi_makara: "मकरः",
    rasi_kumbha: "कुम्भः",
    rasi_meena: "मीनः",
    muhurta_analysis: "सूक्ष्मसंयोगः",
    auspicious_time: "शुभसमयः",
    verdict: "वैदिकनिर्णयः",
    planetary_positions: "ग्रहस्थितयः",
    classical_references: "शास्त्रीयप्रमाणानि",
    panchanga_breakdown: "पञ्चाङ्गविश्लेषणम्",
    technical_summary: "तकनीकीसारः",
    saved_readings: "पिटकम्",
    no_readings: "पिटकं रिक्तम् अस्ति",
    no_readings_desc: "स्वकुण्डलीं पृच्छन्तु।",
    clear_history_confirm: "सर्वाणि विवरणानि निष्कासयितुं इच्छति वा?",
    vastu_title: "वास्तु शास्त्रम्",
    vastu_desc: "दैवीय ऊर्जा",
    vastu_analysis: "वास्तु-विश्लेषणम्",
    home_harmony: "गृहसुखम्",
    palm_reading_title: "हस्तरेखाविज्ञानम्",
    palm_reading_desc: "प्राचीनं हस्तरेखाज्ञानम्",
    upload_palm: "हस्तचित्रं प्रेषयतु",
    palm_instructions: "हस्तचित्रं सम्यक् प्रेषयतु।",
    analyzing_palm: "रेखापरीक्षणं प्रचलति...",
    palm_analysis_res: "हस्तरेखा-विश्लेषणम्",
    camera_access: "कैमरा",
    gallery_access: "गैलरी",
    invalid_palm_error: "चित्रं स्पष्टं नास्ति। पुनः प्रेषयतु।",
    classical_source_authority: "शास्त्रीयमूलम्",
    welcome_tour: "स्वागतम्",
    welcome_tour_desc: "ज्योतिषलोके स्वागतम्।",
    seeker_mode_active: "सीकर-मार्गः",
    scholar_mode_active: "स्कॉलर-मार्गः",
    seeker_tour_desc: "सरलमार्गः",
    scholar_tour_desc: "गभीरज्ञानम्",
    sacred_dashboard: "डैशबोर्ड्",
    dashboard_tour_desc: "पञ्चाङ्गविवरणम्।",
    guruji_tour: "गुरुजी-मार्गदर्शनम्",
    guruji_tour_desc: "गुरुजी-बटन्।",
    navigation_tour: "सरलोपयोगः",
    nav_tour_desc: "उपयोगः सरलः अस्ति।",
    save_profile_error: "नाम लिखन्तु।",
    profile_saved: "रक्षितम्।",
    profile_saved_for: "{name} कृतं रक्षितम्।",
    life_partner_analysis: "जीवनसाथी-विश्लेषणम्",
    prashna_analysis: "प्रश्नविश्लेषणम्",
    stars_silent: "पुनः प्रयत्नं कुर्वन्तु।",
    celestial_connection_failed: "सम्पर्कः न जातः।",
    switch_to_dark: "डार्क-मोड्",
    switch_to_light: "लाइट-मोड्",
    blog: "ब्लॉग्",
    blog_desc: "सिद्धांन्तः होरा च",
    enter_details_warning: "विवरणं लिखन्तु।",
    sending: "प्रेषयन् अस्ति...",
    offline: "ऑफ-लाइन",
    csr_tagline: "धर्मः सेवा च",
    csr_revenue_committed: "राजस्वदानम्",
    csr_souls_nourished: "लाभार्थिनः",
    csr_verified_integrity: "पारदर्शिता",
    csr_schools_supported: "विद्यालयसहायता",
    csr_kits_distributed: "सामग्रीवितरणम्",
    csr_volunteer_hours: "सेवाकालः",
    csr_homes_adopted: "दत्तकसंस्थाः",
    csr_elders_assisted: "वृद्धसेवा",
    csr_medical_camps: "चिकित्साशिविरम्",
    csr_special_children_initiative: "विशेषबालकाः",
    csr_elder_care_program: "वृद्धसेवा-योजना",
    csr_revenue_committed_90: "९०% समाजसेवायै",
    csr_holistic_care_100: "१००% सेवा",
    seeker_mode_desc_short: "सीकर-मोड्",
    scholar_mode_desc_short: "स्कॉलर-मोड्",
    saved_profiles_desc: "अचिरतनु कुण्डल्यः",
    today_panchanga: "अद्यतनं पञ्चाङ्गम्"
};

function updateLanguage(content: string, lang: string, data: Record<string, string>): string {
    const startMarker = `  ${lang}: {`;
    const startIndex = content.indexOf(startMarker);
    if (startIndex === -1) return content;
    
    // Find matching closing brace
    const endMarker = '  },';
    const endIndex = content.indexOf(endMarker, startIndex + startMarker.length);
    if (endIndex === -1) return content;

    let newBlock = `  ${lang}: {\n`;
    Object.entries(data).forEach(([key, value], idx, arr) => {
        const comma = idx === arr.length - 1 ? '' : ',';
        newBlock += `    ${key}: "${value.replace(/"/g, '\\"')}"${comma}\n`;
    });
    newBlock += '  },';

    return content.substring(0, startIndex) + newBlock + content.substring(endIndex + 4);
}

let newContent = content;
newContent = updateLanguage(newContent, 'hi', hi_full);
newContent = updateLanguage(newContent, 'sa', sa_full);

fs.writeFileSync(filePath, newContent);
console.log("Updated Hindi and Sanskrit translations.");
